### ISSUE TITLE
Command palette

### ISSUE THREAD

**Issue by veeral-patel** [tailwindlabs/tailwindui-issues#101]
Similar to:
https://code.visualstudio.com/docs/getstarted/userinterface#_command-palette

**Comment by Wulfheart** [comment]
In the Discord community I saw somebody making one.

**Comment by RobinMalfait** [comment]
It was me!

**Comment by veeral-patel** [comment]
@RobinMalfait Hi! What do you mean you're making one? Thought Tailwind UI is a closed source tool.

**Comment by RobinMalfait** [comment]
@veeral-patel no no, what I meant was in response to @Wulfheart. He mentioned that somebody in the Discord community created a command palette like UI. I created something like that.

**Comment by Christophvh** [comment]
Tailwind UI has one. Press / or CMD+K(mac) cntrl+K (windows) 

You could just look at the code with the inspector. It would be nice as an actual component tho.
![Screenshot 2020-04-09 at 10 26 14](https://user-images.githubusercontent.com/9588070/78874466-b8844200-7a4c-11ea-9140-b3148be5fd30.png)
