### ISSUE TITLE
Full-width flyouts 404 Error for Unsplash Image

### ISSUE THREAD

**Issue by marky291** [tailwindlabs/tailwindui-issues#1015]
Image being used: https://images.unsplash.com/1/apple-gear-looking-pretty.jpg?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2850&q=80

<img width="1336" alt="Screenshot 2021-09-16 at 23 19 18" src="https://user-images.githubusercontent.com/5384515/133693036-df838ae2-0104-4b01-b174-6c1e73ac0e94.png">

**Comment by devnet-io** [comment]
+1 It appears that all sample images are currently broken, or at least all of them within the Application UI component previews.

**Comment by reinink** [comment]
@marky291 Hey thanks for reporting this! It appears that this image is no longer available on Unsplash. We'll get it replaced. 👍 

@devnet-io I just took a quick look at all the Application UI component previews, and all the other images seem to be working for me. Can you give an example of another component that has a broken image link?
