### ISSUE TITLE
Ecommerce, Marketing and Application UI are very good, whats next? social media?

### ISSUE THREAD

**Issue by VerneStudios** [tailwindlabs/tailwindui-issues#1018]
Hey guys, I bought the full package with all the three products. It has been amazing, very professional looking and very well written.

I was wondering if you are going to create new packages? And if you do, what are they going to be about?

I suggest one for social media components, like photos, posts, chat, like buttons etc...

Keep up the good work.

**Comment by reinink** [comment]
Hey there! Thanks so much for buying Tailwind UI and for the kind words — I'm glad to hear you're enjoying it!

As for the next "big thing", that's still a surprise. 😉 That said, we do have a number of exciting component updates planned for the existing bundles.

Thanks for sharing the social media idea — I'm going to move this over to the discussions, which is where we now track feature requests ([see here](https://github.com/tailwindlabs/tailwindui-issues/discussions/1013)).
