### ISSUE TITLE
Broken link on the support page (`Request a component`)

### ISSUE THREAD

**Issue by malobre** [tailwindlabs/tailwindui-issues#1023]
**Describe the bug**
`Request a component` link is broken, `href` is set to `http://tailwindui.com.test/make-a-suggestion`.

**To Reproduce**
1. Go to the [support page](https://tailwindui.com/support).
2. Click on 'Request a component'.
3. See error

**Comment by reinink** [comment]
Hey @malobre, thanks for reporting this. I recently updated that link and left the development address in there like a moron. This has been fixed and is deploying.
