### ISSUE TITLE
<Menu.Item> --> <Link> --> <a> in NextJS doesn't work

### ISSUE THREAD

**Issue by jonkcinema** [tailwindlabs/tailwindui-issues#1025]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/elements/dropdowns
- Component name: Any <Menu.Item> with {({ active })} => (<a href...

**Describe the bug**
I am using NextJS, and we generally use nextjs/Link to wrap <a> tags.  Makes page loads much faster, etc.

When I wrap <a> tags from the TailwindUI templates with <Link> tags under a <Menu.Item>, the active property stops working correctly for mouse hovering.

**To Reproduce**

`<Menu.Item>
  {({ active }) => (
    <Link href="/share">
      <a className={classNames(
          active ? 'bg-gray-100 text-gray-900' : 'text-gray-700',
          'group flex items-center px-4 py-2 text-sm'
        )}>
        Share
      </a>
    </Link>
  )}
</Menu.Item>`

**Expected behavior**
The active argument should get passed properly, even when wrapping <a> with a NextJS <Link> tag.

**Browser/Device (if applicable)**
 - OS: MacOS
 - Browser: Chrome

**Comment by adamwathan** [comment]
Hey! We've actually just published some documentation on this problem, check this out and let me know if it helps:

https://headlessui.dev/react/menu#integrating-with-next-js

**Comment by jonkcinema** [comment]
This is great.  Thank you.  Just wish it were more straightforward...

**Comment by adamwathan** [comment]
Yeah unfortunately Next.js would need to support passing unknown props through to the underlying `a` tag for it to work, nothing we can do about it on our end 😞 If you stick that custom link component in a file somewhere though you can just import that everywhere you need it and not use `next/link` directly other than in that file and you'll be good 👍🏻
