### ISSUE TITLE
Wrong title or classes on container

### ISSUE THREAD

**Issue by adevade** [tailwindlabs/tailwindui-issues#1032]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/layout/containers#component-7359808e2970a406ca075670f344028b
- Component name: Full-width on mobile, constrained to breakpoint with padded content above mobile

**Describe the bug**
The title says full width on mobile, but it's not.

**Expected behavior**
Either the title should change, or the `px-4` class should be removed.

**Screenshots**
![image](https://user-images.githubusercontent.com/1066486/135766371-239bd119-91ff-4b18-83be-62af7f89807e.png)

**Comment by reinink** [comment]
@adevade Hey thanks so much for bringing this to our attention! I've updated this component to remove the padding from the mobile size, and then I also added a new "Constrained to breakpoint with padded content" component, which keeps the mobile padding — the previous behavior 👍
