### ISSUE TITLE
Dropzone

### ISSUE THREAD

**Issue by veeral-patel** [tailwindlabs/tailwindui-issues#104]
Having a styled component to upload files (with drag and drop) would be nice.

See:

https://ant.design/components/upload/

https://www.dropzonejs.com/

**Comment by simonswiss** [comment]
Thanks for the suggestion! 👍

I am porting the component suggestions to an "ideas" column in the Trello roadmap. I'll close this issue, but you can find this request here: https://trello.com/c/hyI8y6D1/66-drop-zone
