### ISSUE TITLE
Select custom component bottom margin

### ISSUE THREAD

**Issue by geodeveloper** [tailwindlabs/tailwindui-issues#1041]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/forms/select-menus
- Component name: Simple custom

**Describe the bug**
The select component is integrated into a page which doesn't have so much height and the component it's rendered near the bottom of the page. When opening the select options,  it shows correctly all the options but the last option or the end part of the component is not completely shown, the bottom border and shadow is not visible. 

**To Reproduce**
1. Add select custom component at the bottom of a page
2. Click on select options
3. Scroll down to the end of list
4. See error (border and shadow not visible)

**Expected behavior**
The select component should be completely visible border and shadow, maybe add some margins at the bottom.

**Screenshots**

See bottom of the image
![image](https://user-images.githubusercontent.com/6689915/137489905-bc963c83-a239-4802-8e4c-983f1aea7556.png)

Expected behaviour image (in order to fix this issue, I had to add some bottom-margin to the page):
![image](https://user-images.githubusercontent.com/6689915/137489996-06e3a0e8-c93c-473f-960f-b6a3e819e256.png)

**Comment by reinink** [comment]
@geodeveloper Awesome, glad I could help! 🙌

**Comment by prestonholt** [comment]
For anyone searching, here is a Listbox example using a portal & Popper in Vue:

https://codesandbox.io/s/tailwind-listbox-select-custom-9xe0c?file=/src/components/SelectSimpleCustom.vue

I was able to get the dropdown to match the width of the trigger button using a Popper modifier.
