### ISSUE TITLE
Multiple h1

### ISSUE THREAD

**Issue by seb-jean** [tailwindlabs/tailwindui-issues#1055]
Hi,

There is multiple `<h1>` in :
- https://tailwindui.com/components/application-ui/page-examples/detail-screens#component-ad515de6435ba177e823a5f823a44ff5

It's not good for SEO

**Comment by reinink** [comment]
Hey, thanks for sharing this feedback.

So yes, generally you do want to avoid having multiple visible `<h1>` elements on any given page. However, if you look at how these headings are built in this component, you'll notice that only one of the two headings is shown at a time. One of them is for the mobile view, and the other for the desktop view. This is generally considered a safe practice, as verified by Google themselves: https://www.youtube.com/watch?v=zyqJJXWk0gk

Further, it's pretty likely that anyone implementing this particular Application UI page example is going to have an authentication layer in place where the user is required to login. Meaning, those pages won't be accessible for indexing by a search engine either way.

That said, if this is a concern for you, there's nothing stopping you from changing one of the `<h1>` elements to something else. That's the great thing about Tailwind UI — it's yours to modify.

Hope that helps! 🤟

**Comment by seb-jean** [comment]
Thanks for answer @reinink 👍🏻
