### ISSUE TITLE
Remove uncompleted class name from component

### ISSUE THREAD

**Issue by bazish** [tailwindlabs/tailwindui-issues#1057]
**What component (if applicable)**
- URL for category: [With avatar and actions](https://tailwindui.com/components/application-ui/forms/textareas)
- Component name: With avatar and actions

**Describe the bug**
missing class value for padding bottom or need to removed pb-

**To Reproduce**
1. Go to 'https://tailwindui.com/components/application-ui/forms/textareas'
2. Click on 'Code'
3. Scroll down to 'div start of the code block'

**Expected behavior**
pb- needs to be removed.

**Screenshots**
![Screenshot 2021-11-10 at 5 23 26 PM](https://user-images.githubusercontent.com/11957812/141113917-86f9bd69-ed8c-4b2c-9ae3-dd9fb5e2fdab.png)

**Comment by reinink** [comment]
@bazish Hey thanks so much for reporting this — this has been corrected 👍
