### ISSUE TITLE
Unable to close shopping cart slide-over by clicking on the overlay on mobile

### ISSUE THREAD

**Issue by kauffmanes** [tailwindlabs/tailwindui-issues#1058]
**What component (if applicable)**
- URL for category:  https://tailwindui.com/components/ecommerce/components/shopping-carts
- Component name:  Slide-over

**Describe the bug**
I am unable to click the gray overlay area outside of the shopping cart slide-over (on mobile) to close it. This works on the slide-overs that are on the left of the screen but not the right.

**To Reproduce**
1. Go to https://tailwindui.com/components/ecommerce/components/shopping-carts#component-ee213165d75da7e921c0bf15f3ab054b
2. Open dev tools and enable mobile view (I did this on Firefox and Chrome)
3. Once in mobile mode, click the gray overlay to the left of the slide-over. 

**Expected behavior**
The modal should close (like it does out of mobile mode on desktop).

**Screenshots**

**Browser/Device (if applicable)**
 - OS: Mac OS X
 - Browser: Chrome, Firefox

**Additional context**

**Comment by aktschge** [comment]
Hi @kauffmanes. I ran into the same issue the other day. 

It seems that the "gray overlay" is just a **left padding of the Slide-Over on mobile devices** (or widths smaller than SM in general). This is the line causing the mentioned behavior: `<div class="fixed inset-y-0 right-0 pl-10 max-w-full flex">`. 

The behavior is forced by `pl-10`. A quick workaround could be adding a clickable div just before the Slide-Over. For example:
```
<div class="fixed inset-y-0 right-0 max-w-full flex">
  <div class="pl-10 bg-red-200" /> <!-- This DIV can listen for a click -->
  <SlideOverContent />
</div>
```

Please note that the `div` in my example has a color of `bg-red-200` for demonstration purposes. 
So feel free to remove it to apply the overlay color.

I hope this helps! :)

**Comment by bradlc** [comment]
Hey @kauffmanes, thanks for reporting – this has now been fixed 👍
