### ISSUE TITLE
No responsive variant for incentive

### ISSUE THREAD

**Issue by adevade** [tailwindlabs/tailwindui-issues#1063]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/ecommerce/components/incentives#component-aeb0ee53368825ebb0be85ae6524cd6c
- Component name: 3-column with icons

**Describe the bug**
Might be on purpose, but this component does not have a layout for smaller screens. Just sideways scrolling.

**Expected behavior**
Initial expectation was that they would stack, but it depends on where they're supposed to be used i guess.

**Screenshots**
![image](https://user-images.githubusercontent.com/1066486/141361993-7935a878-87e0-4841-ba63-91c2e47a80dd.png)

**Browser/Device (if applicable)**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 95

**Comment by bradlc** [comment]
Hey @adevade. This component has been intentionally designed like that. Take a look at [`3-column with icons and supporting text`](https://tailwindui.com/components/ecommerce/components/incentives#component-724313acc0fc44912588500e01b3c900) for an alternative that does stack on mobile 👍
