### ISSUE TITLE
The code for "Light nav on gray background" is correct?

### ISSUE THREAD

**Issue by medialogo** [tailwindlabs/tailwindui-issues#1065]
**What component (if applicable)**
- URL for category: 
- https://tailwindui.com/components/application-ui/application-shells/stacked
- Component name: 
- Light nav on gray background

**Describe the bug**
The code provided for this component,  is it correct? 
I copied it and tried on my browser, but it seems the same as "Light nav with bottom border", not "on gray ground".

**To Reproduce**
Please copied the code and try.

**Comment by aktschge** [comment]
Hi @medialogo. You are basically right: The two components that you've mentioned are the same with the only difference being the background color, which should be `bg-gray-100` in the latter case ("Light nav on gray background").

I copied and tried the example following the notice at the top of the file and achieved the desired result.
Accordingly my best guess would be that you did not update your `html` and `body`? Could you check?

This is the notice I am referring to: 
```
<!--
  This example requires updating your template:

  <html class="h-full bg-gray-100">
  <body class="h-full">
-->
```

I hope this helps! Cheers!

**Comment by reinink** [comment]
Yup, as @aktschge is suggesting, this component requires adding the `bg-gray-100` class to your `<html>` element. Give that a try and let me know if you're still having issues with this 👍
