### ISSUE TITLE
Pricing Feature Grid

### ISSUE THREAD

**Issue by masonhensley** [tailwindlabs/tailwindui-issues#107]
**Additional context**
A pricing / feature grid detail page would be a great compliment to the current pricing sections shown here: https://tailwindui.com/components/marketing/sections/pricing

**Screenshots**
- https://asana.com/pricing
- https://sentry.io/pricing/

![image](https://user-images.githubusercontent.com/534165/77199629-20331700-6ab7-11ea-881c-9956e2137d59.png)

![image](https://user-images.githubusercontent.com/534165/77199315-a307a200-6ab6-11ea-9067-f944792f5626.png)

**Comment by masonhensley** [comment]
Ooops, duplicative? https://trello.com/c/Ewsd8LeD/9-marketing-pricing-page-examples

Should I close this?

**Comment by simonswiss** [comment]
I captured this suggestion in an "idea" card in the roadmap, as this is slightly different. Thanks for suggesting! 🎉

https://trello.com/c/eIr2sPNA/64-features-table
