### ISSUE TITLE
typography configuration not being used.

### ISSUE THREAD

**Issue by Nielssie** [tailwindlabs/tailwindui-issues#1072]
**What component (if applicable)**
    "@tailwindcss/ui": "^0.7.2",
   "tailwindcss": "^2.2.19"

**Describe the bug**
When I use tailwindui the typography configuration is not being used.

**To Reproduce**
1. Add @tailwindcss/typography to the project.
2. Extend the theme in tailwind.config.js:

 `extend: {
        typography: {
            DEFAULT: {
                css: {
                    color: '#333',
                    a: {
                        color: '#468c00',
                        '&:hover': {
                            color: '#2c5282',
                        },
                    },
                },
            },
        },`

3. Change HTML

`<article class="prose lg:prose-xl">
     <a href="">layout</a>`

4. color of the a-tag is changed, the expected behavior.
5. If I remove @tailwindcss/typography and add @tailwindcss/ui
6. I can see the the color of the a-tag has the `.prose a` style from the UI.
7. The typography configuration has no effect...

**Expected behavior**
I would expect that the a-tag would have the color which is specified in de tailwind.config.js when using tailwindcss/ui

**Comment by adamwathan** [comment]
Hey! The `@tailwindcss/ui` package is deprecated and no longer needed as of Tailwind CSS v2, so you just shouldn't use that at all.

You can read more about this in this post from last year when Tailwind CSS v2.0 was released:

https://tailwindui.com/changes-for-v2#whats-changed-in-tailwind-ui

You should be using `@tailwindcss/typography`, not `@tailwindcss/ui`, as like you've discovered the UI plugin will not proxy through customizations to the typography plugin.

Hope that helps!
