### ISSUE TITLE
A guide for making small tweaks to the existing components

### ISSUE THREAD

**Issue by darethas** [tailwindlabs/tailwindui-issues#108]
Hello, this is neither a component request or a bug, but another suggestion that would be very helpful to me and I am sure many others.

I am finding quickly that I lack the skills and expertise in both design and the type of components Adam and Steve have made a living doing (no surprise there). I think a guide on how to perform minor tweaks to the existing components would be wonderful. 

Sometimes one of the components are exactly what we need, in other cases, we need to make small tweaks. Sometimes you want something from one component and another mixed together. 

Here is a specific example: 

I liked the app shell with the sidebar layout, but wanted the profile drop down to be to the right. I did not want the search bar, however. The problem is when you remove the search bar, the profile icons get pushed all the way next to the side bar.

Thank you for all you do.

**Comment by dillingham** [comment]
@darethas what you're requesting exists already.

https://tailwindcss.com/docs/
https://tailwindcss.com/screencasts/
https://flexbox.io/

**Comment by simonswiss** [comment]
For this sort of help, your best bet is to [join the friendly Tailwind UI community on discord](https://tailwindui.com/discord)! 👍
