### ISSUE TITLE
Product overview component does not display all images on mobile

### ISSUE THREAD

**Issue by kmyn** [tailwindlabs/tailwindui-issues#1080]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/ecommerce/components/product-overviews
- Component name: Product Overviews (`With tiered images`, `With image gallery and expandable details`)

**Describe the bug**

In the first two components of `Product Overviews`, the additional images (thumbnails) are not visible on mobile/tablet screens. Only one image is visible.

**To Reproduce**
View either of the components on mobile/tablet screens.

**Expected behavior**
 Need to show product thumbnails/options to view other product images.

**Screenshots**

**Browser/Device (if applicable)**
Mobile & tablet screens

**Additional context**
I'm suspecting this to be a bug. If not, can you please provide me some ideas on how to fix this.

**Comment by bradlc** [comment]
Hey @kmyn. These components have been intentionally designed like that, but if you want to display all of the images on mobile you can remove the display classes. For example for `With tiered images` you would need to remove `hidden` and `lg:block` from the images, and for `With image gallery and expandable details` you can remove `hidden` and `sm:block` from the "Image selector" container. I hope that helps!
