### ISSUE TITLE
Prevent Modal getting closed when esc pressed

### ISSUE THREAD

**Issue by muslemaheshrao** [tailwindlabs/tailwindui-issues#1082]
**Modal**

**BUG**

When we press `esc` the modal gets closed. How to prevent it as no option provided for that.

**Comment by bradlc** [comment]
Hey @muslemaheshrao. It sounds like you are using the React or Vue version of one of the modal components. These components use Headless UI's [Dialog](https://headlessui.dev/react/dialog) component. When pressing the `esc` key the `onClose` function is called, and there is no way to disable this behaviour. However, depending on your use case there's a couple of things you could try:

- If you want to prevent `esc` from closing the modal when you're focused in a form input, you could add a `keydown` event listener on the input and call [`event.stopPropagation()`](https://developer.mozilla.org/en-US/docs/Web/API/Event/stopPropagation) 
- If you want to prevent the modal from closing when there's pending changes, you can check this inside your `onClose` function and decide whether or not the `open` state should be updated, for example:

  ```js
  <Dialog onClose={() => {
    if (!pendingChanges) setOpen(false)
  }}>
  ```

I hope that helps, but if you're still having problems don't hesitate to ask for help [in the Discord](https://tailwindui.com/discord) 👍
