### ISSUE TITLE
Radio group component(s) has incorrect JS

### ISSUE THREAD

**Issue by rgossiaux** [tailwindlabs/tailwindui-issues#1086]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/forms/radio-groups
- Component name: Stacked cards (but this may affect other components on the page, I haven't checked)

**Describe the bug**
On the component page, when you click between the options, the highlight state looks reasonable enough:

https://user-images.githubusercontent.com/3475509/145367847-75ea1f8d-5992-43f2-87c1-d39243e840cb.mov

But if you actually copy the component JS, you get this (rather ugly) behavior instead:

https://user-images.githubusercontent.com/3475509/145367965-4001696b-e2dc-4e8e-b086-206ba760a792.mov

I think the styling for the active state needs to be changed to make this not so painful-looking.

**To Reproduce**
1. Copy/paste the React component code into any React+tailwind application.

**Comment by reinink** [comment]
@rgossiaux Hey thanks so much for reporting this issue. I have corrected this component as well as the [Cards](https://tailwindui.com/components/application-ui/forms/radio-groups#component-45612766894822db447a2837d79355f5) component 👍
