### ISSUE TITLE
UI Error - Page Examples --> Settings Screens --> With breadcrumbs and centered form

### ISSUE THREAD

**Issue by AbdulDotKhan** [tailwindlabs/tailwindui-issues#1091]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/page-examples/settings-screens#component-c29fe3f9f780c97a58f08453fc6bbec8
- Component name: Page Examples --> Settings Screens --> With breadcrumbs and centered form

**Describe the bug**
It looks like the class on the "Project Nero" input form is not correct. 

It is currently:
`"block w-full shadow-sm focus:ring-sky-500 focus:border-sky-500 sm:text-sm border-gray-300 rounded-md"`

However it should be:
`"mt-1 block w-full border border-gray-300 rounded-md shadow-sm py-2 px-3 focus:outline-none focus:ring-sky-500 focus:border-sky-500 sm:text-sm"`

**To Reproduce**
1. Go to the code tab of the component
2. Copy/paste into a Vue or React component
3. Preview in web browser

**Expected behavior**
Would expect the component to look like the preview.

**Screenshots**
![image](https://user-images.githubusercontent.com/10870777/145731194-af137745-246f-40db-9657-03bb2596d2ba.png)

**Additional context**
A small bug in an otherwise wonderful UI package. Keep up the great work :)

** PS - Same also applies to the email address field **

**Comment by bradlc** [comment]
Hey @AbdulDotKhan. It looks like you haven't installed the `@tailwindcss/forms` plugin, it works as expected once you do.

Any time an example from Tailwind UI needs a plugin like that installed it will be mentioned in a big comment at the top of the example:

<img width="828" alt="image" src="https://user-images.githubusercontent.com/4323180/154456762-46871396-151b-45f7-b1d0-35b9cd59e18c.png">

I hope that helps!
