### ISSUE TITLE
Number of total components is different (startpage / pricing)

### ISSUE THREAD

**Issue by ciruz** [tailwindlabs/tailwindui-issues#1092]
It's not really a bug, just a small improvement.

**Describe the bug**
On the startpage you promote over 400+ components, but the pricing page you promote over 500+ components.

I think ~570 is the reality, so why not promote over 500+ on the startpage too.

**Screenshots**
![image](https://user-images.githubusercontent.com/987947/145861178-19064ee7-a2f0-4505-823e-5dd7891c7515.png)

![image](https://user-images.githubusercontent.com/987947/145861218-529d80cd-d044-4e8c-b406-9009f41021b3.png)

**Comment by reinink** [comment]
Hey good catch — updated ❤️
