### ISSUE TITLE
Overlooked static content that should be dynamic

### ISSUE THREAD

**Issue by EdyTheCow** [tailwindlabs/tailwindui-issues#1099]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/marketing/sections/feature-sections
- Component name: Grid with offset icons

**Describe the bug**
The description of the cards is static in Vue and React versions. I am guessing it's meant to be dynamic like the title and icon. 

**Expected behavior**
Description should be dynamic like the title and icon of the card.

**Comment by bradlc** [comment]
Hey @EdyTheCow, thanks for reporting – this has been updated 👍
