### ISSUE TITLE
Component : Profile card

### ISSUE THREAD

**Issue by seb-jean** [tailwindlabs/tailwindui-issues#11]
Hi :)

It would be great to have a "Profile cards" and "Preview cards" component as in Refactoring UI.

**Screenshots**

![Image](https://i.imgur.com/qRQBNfJ.png)
![Image](https://i.imgur.com/Ue9bETF.png)

**Comment by schmidtflo** [comment]
I would also love to have a minimal version, that can be used eg. in the Header of a Blog post.

**Comment by austriker27** [comment]
Really love this idea!

**Comment by simonswiss** [comment]
Nice one! 👍

Capturing this in our "bag of ideas" on the Trello roadmap. If it becomes a popular demand, we'll consider building it! 🎉 https://trello.com/c/9lMYT1eB/95-user-profile-cards
