### ISSUE TITLE
Missing sidebar configuration

### ISSUE THREAD

**Issue by ordago** [tailwindlabs/tailwindui-issues#1106]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/application-shells/sidebar
- Component name: Sidebar Layouts

**Describe the bug**

https://tailwindui.com/v1/documentation#configuring-sidebar-breakpoints

V1 of the docs had a section about configuring breakpoints when using the sidebars. I wasn't able to find the equivalent for V2 in the docs or in the upgrade guide. Sorry if I missed it.

**Comment by adamwathan** [comment]
Hey! For v2 we decided to simplify things and just remove that. All of the templates should just work nicely out of the box as-is, but you might run into situations where wide templates that expect a lot of room need to be tweaked if you have a permanently visible sidebar taking up some of the available space.

In those cases you should just play with the breakpoints on the component and adjust things so they switch to the narrower design earlier — for example if you are using a form layout or something that won't fit in the space you have available on `lg` screens, change the `lg` breakpoint in the layout to `xl` so it stays at the narrower layout for a wider range of viewport sizes.

Hope that helps!
