### ISSUE TITLE
Repeated items should be exactly equal

### ISSUE THREAD

**Issue by rcoelho** [tailwindlabs/tailwindui-issues#111]
**Describe the bug**
Repeated items should be exactly equal, so that when generating the items programatically we don't have to be chasing special cases (or debugging after we miss them).

**What component (if applicable)**
An example:
- URL for category: https://tailwindui.com/components/application-ui/lists/wide
- Component name: Two-column with avatar

**To Reproduce**
The first item is: `<li>`.
Subsequent items are: `<li class="border-t border-gray-200">`.

If I pick the first item as the template, my list will lack borders.
If I pick any other item, the first item will have a border it shouldn't have.

**Expected behavior**

- All items should be the same.
- A markup that would work for all items is for example: `<li class="border-t border-gray-200 first:border-t-0">`.

Thanks!

**Comment by simonswiss** [comment]
A lot of these inconsistencies will go away with the new [spacing](https://tailwindcss.com/docs/space/#add-vertical-space-between-children) and [divide](https://tailwindcss.com/docs/divide-color/#usage) utilities, which we are currently retrofitting through all existing components.

For example, the border between  each `li` can be handled like so:

```html
<ul class="divide-y divide-gray-200">
  <li>...</li>
  <li>...</li>
  <li>...</li>
</ul>
```

This is much cleaner and nicer to maintain than having to handle the border on each individual `li` element! 👍

Closing this issue as we're going to roll out these utilities across all lists of things in all Tailwind UI components.
