### ISSUE TITLE
pages not rendering correctly with tailwind 3

### ISSUE THREAD

**Issue by mooseh** [tailwindlabs/tailwindui-issues#1114]
**Describe the bug**
pages not rendering correctly with tailwind 3.*

**To Reproduce**
1. add tailwind 3.* using yarn / npm
2. run yarn / npm
3. go to your page
4. See page is not rendered correctly with huge images etc

**Expected behavior**
Expecting to see a simple login page

**Screenshots**
With tailwind 3
https://www.awesomescreenshot.com/image/20295920?key=397c699dc16b13ca72756c4f631cffe4
With tailwind 2 (as expected)
https://www.awesomescreenshot.com/image/20296963?key=3c8ad156331bc83e4d7a9ac2a4600add

**Browser/Device (if applicable)**
 - OS: windows
 - Browser chrome
 - Version 97.0.*

**Additional context**
I am using yarn / webpack / vue3

**Comment by reinink** [comment]
@mooseh Hmm, looks to me like no classes are being generated, which suggests to me that you probably don't have your content paths configured. This is a necessary step in Tailwind CSS v3.0 which wasn't required in v2.0. I'd recommend reading through our [upgrade guide](https://tailwindcss.com/docs/upgrade-guide) — in particular the section titled "Configure content sources". Definitely also watch the video on that page, as it explains some of this stuff as well 👍

If that isn't the case, please feel free to share a minimal reproduction of this issue, and I'd be totally happy to have a closer look for you.
