### ISSUE TITLE
E-Commerce Views

### ISSUE THREAD

**Issue by abishekrsrikaanth** [tailwindlabs/tailwindui-issues#112]
It would be good to have different E-Commerce views to build a store.

- HomePage with a slider and product categories list
- Category View with sidebar and filters
- Product View with description, cart, related products
- Cart View
- Checkout View
- Thank you page.

**Comment by simonswiss** [comment]
That's quite a popular request that we're going to work on for sure!

Consolidating this issue with the others at #268 👍
