### ISSUE TITLE
Make changing pricing tier num columns easier

### ISSUE THREAD

**Issue by dctanner** [tailwindlabs/tailwindui-issues#1134]
I got a bit confused adding additional columns to the pricing table: https://tailwindui.com/components/marketing/sections/pricing#component-466fb280c935eaf1bbc06080419b751f

We could use tiers.length to prevent things breaking when the tiers data is changed:

```149c149
<                     className="w-1/4 pb-4 px-6 text-lg leading-6 font-medium text-gray-900 text-left"
---
>                     className={`w-1/${tiers.length + 1} pb-4 px-6 text-lg leading-6 font-medium text-gray-900 text-left`}
185c185
<                       colSpan={4}
---
>                       colSpan={tiers.length + 1}```

**Comment by reinink** [comment]
@dctanner Hey, my apologies on the delay here! So, I totally agree, adding or removing columns from these designs is a bit tricky. However, this solution unfortunately won't completely work either, as Tailwind CSS cannot detect dynamic classes like this:

```jsx
className={`w-1/${tiers.length + 1}
```

We could use a dynamic `colSpan`, as you're suggesting, but that will only work for the React and Vue versions, and isn't a solution for the plain HTML versions of these components.

Given that, I think for now it's probably best to just leave these as they are. I appreciate the feedback either way 👍
