### ISSUE TITLE
Missing height in a component for screens up to lg (Vue)

### ISSUE THREAD

**Issue by guignol1981** [tailwindlabs/tailwindui-issues#1140]
**What component (if applicable)**
- URL for category: 
 https://tailwindui.com/components/ecommerce/components/category-previews
- Component name: 
 [With background image and detail overlay](https://tailwindui.com/components/ecommerce/components/category-previews#component-1f407cdd33b17a2fc24966b27bea7890)

**Describe the bug**

At line 4 the div class value is missing height for screens smaller than lg

`<div class="relative rounded-lg overflow-hidden lg:h-96">
`

**To Reproduce**
1. Implement the code as it is
2. Go into dev console toggle responsive mode
3. Try the component on smaller screen 
4. The component doesn't show up on screen

**Expected behavior**

The component should be visible on smaller screens

**Screenshots**

**Browser/Device (if applicable)**

**Additional context**

**Comment by bradlc** [comment]
Hey @guignol1981. I am unable to reproduce the issue you are describing. For screens up to `lg` the height of the component is dictated by the two divs on lines 8 and 9. If you're still having issues please open a new issue with a full reproduction, for example a GitHub repository or [Tailwind Play](https://play.tailwindcss.com/) link.
