### ISSUE TITLE
Select Menus missing border

### ISSUE THREAD

**Issue by DaZiYuan** [tailwindlabs/tailwindui-issues#1147]
**What component (if applicable)**
- URL for category: 
- Component name: 
https://tailwindui.com/components/application-ui/forms/select-menus

**Describe the bug**

**To Reproduce**
```
<div>
  <label for="location" class="block text-sm font-medium text-gray-700">Location</label>
  <select id="location" name="location" class="mt-1 block w-full pl-3 pr-10 py-2 text-base border-gray-300 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm rounded-md">
    <option>United States</option>
    <option selected>Canada</option>
    <option>Mexico</option>
  </select>
</div>
```
**Expected behavior**
![image](https://user-images.githubusercontent.com/80653/154429037-cad155cb-f2e4-408d-bb0c-909c218a72c0.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/80653/154429127-895ad50a-2923-4324-9abb-7b4704370686.png)

**Browser/Device (if applicable)**

**Additional context**

**Comment by adamwathan** [comment]
Hey! Looks like you haven't installed the `@tailwindcss/forms` plugin, it works as expected once you do:

https://play.tailwindcss.com/1PLWqQOTcy?file=config

Any time an example from Tailwind UI needs a plugin like that installed it will be mentioned in a big comment at the top of the example:

<img width="828" alt="image" src="https://user-images.githubusercontent.com/4323180/154456762-46871396-151b-45f7-b1d0-35b9cd59e18c.png">

**Comment by adamwathan** [comment]
Going to close as resolved but if you are still having problems with this don't hesitate to [join the Discord](https://tailwindui.com/discord) or open another issue.

**Comment by DaZiYuan** [comment]
Sorry, I didn't pay attention to the comments.
