### ISSUE TITLE
{File gallery} screen height issue

### ISSUE THREAD

**Issue by chasak** [tailwindlabs/tailwindui-issues#1148]
[File gallery](https://tailwindui.com/components/application-ui/page-examples/detail-screens#component-0218c9079330128b7d916325b9ad3f38)

**Describe the bug**
At md(IPAD Air) setting, {narrow sidebar} is not at max height 
<img width="1440" alt="Screenshot 2022-02-18 at 12 29 08 AM" src="https://user-images.githubusercontent.com/1892631/154551768-26d5e79e-77eb-492a-af2b-8a22f8fc461a.png">

To Solve the issue change "h-full" for the first div to "h-screen"

**Comment by bradlc** [comment]
Hey @chasak. Some components require you to update your template, and this is indicated by a comment at the top of the component code:

````html
<!--
  This example requires updating your template:

  ```
  <html class="h-full bg-gray-50">
  <body class="h-full overflow-hidden">
  ```
-->
````

If you have extra elements in between `body` and the component code (it looks like you do!) you will need to add `h-full` to those as well, for example:

```html
<body class="h-full overflow-hidden">
  <div id="root" class="h-full">
    <!-- component code -->
  </div>
</body>
```

Unfortunately `height: 100vh` behaves really badly on mobile Safari, so this height drilling approach is the only way to build full height layouts in a cross-browser way.

I hope that helps!

**Comment by chasak** [comment]
Thanks, that helps.
