### ISSUE TITLE
Checkbox lists

### ISSUE THREAD

**Issue by swanson** [tailwindlabs/tailwindui-issues#115]
**Checkbox lists**

Often in data-heavy applications you need to set up associations between data or select many values and a checkbox list can be a good component for that. Often developers will start reaching for UI toolkits at this point, but with basic HTML (and some very minimal Alpine/Stimulus/plain JS) you can get pretty far.

**Screenshots**

![image](https://user-images.githubusercontent.com/56947/77542593-cd71aa80-6e7c-11ea-8d2a-2451192f0ce4.png)
(via https://atlassian.design/guidelines/product/components/checkboxes)

![image](https://user-images.githubusercontent.com/56947/77542698-f5610e00-6e7c-11ea-99e6-501dba21975b.png)
(via https://polaris.shopify.com/components/forms/choice-list#navigation)

![image](https://user-images.githubusercontent.com/56947/77542288-563c1680-6e7c-11ea-85f9-fd58e8e4556b.png)

![image](https://user-images.githubusercontent.com/56947/77542782-175a9080-6e7d-11ea-8d23-0424e6427ee4.png)

![image](https://user-images.githubusercontent.com/56947/77577536-5b658980-6ead-11ea-8043-f33b1a3abd5f.png)

**Additional context**
Optional affordances for select all, select none, showing count/summary of items selected

Would be great to handle nested hierarchies but maybe at that point it's time for a more rich clientside component/library.

**Comment by J05HI** [comment]
Additional examples:

https://element.eleme.io/#/en-US/component/transfer#transfer

![image](https://user-images.githubusercontent.com/16399787/80518360-a714c280-8986-11ea-8c48-949ed3e5e3e9.png)

**Comment by simonswiss** [comment]
Nice examples, thanks for sharing! 

Consolidating this with https://github.com/tailwindlabs/tailwindui-issues/issues/185 👍
