### ISSUE TITLE
Re-opening after typing in `Comboboxes` does not show all results

### ISSUE THREAD

**Issue by adevade** [tailwindlabs/tailwindui-issues#1152]
**What component (if applicable)**
- URL for category: [Comboboxes](https://tailwindui.com/components/application-ui/forms/comboboxes)
- Component name: Any of the Comboboxes

**Describe the bug**
After typing and selecting a name, the dropdown shows only names matching that previous search, until emptied.

**To Reproduce**
1. Go to [any of the Comboboxes](https://tailwindui.com/components/application-ui/forms/comboboxes).
2. Click the button to open the dropdown and select any name.
3. Open the dropdown again, and every name is still visible.
4. Type into the field, ex. **AL**, and select one of the names.
5. Open the dropdown again and see that only the names that matched the previous search is visible.
6. After emptying the text field all names are visible again.

**Expected behavior**
I expected the full list of names to be available every time I opened the dropdown.

**Screenshots**
https://user-images.githubusercontent.com/1066486/155352040-e9afb4d1-a4e4-4fd4-bcc5-a7bc27ff6845.mp4

**Browser/Device**
 - OS: Windows 11
 - Browser: Edge 98

**Additional context**
I guess that this is up to the user to implement how they want, but it felt like unnatural behaviour when I was playing around with the new components.

**Comment by simonswiss** [comment]
Hey! Thanks for reporting this, this is indeed a bug. Going to merge this issue with this other one which contains some screenshots and a video describing the same issue:

https://github.com/tailwindlabs/headlessui/issues/1145
