### ISSUE TITLE
Using keyboard instead of mouse close command palette preview on click

### ISSUE THREAD

**Issue by sergiodxa** [tailwindlabs/tailwindui-issues#1154]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/navigation/command-palettes#component-5e859372042e1b3b308dc51f3ac8bad6
- Component name: Command Palette with preview

**Describe the bug**

If you focus on the input and use the arrow keys to move down to select an option, when you click the button on the preview the preview is closed without clicking the input.

**To Reproduce**
1. Focus on the input
2. Press the arrow down key to select one option
3. Click on the preview (e.g. on the button)
4. The command palette is closed

**Expected behavior**

It should allow me to click on the preview like if I used the mouse to select an option.

**Screenshots**

It's a video, first I show the bug using the keyboard, then I use the mouse to hover one (I click one but then I hover the next one) and clicking doesn't close the preview.

https://user-images.githubusercontent.com/1312018/155580937-0d8ff3bf-f970-498e-9076-b89f5fa82722.mov

**Browser/Device (if applicable)**
 - OS: macOS Monterey
 - Browser Sizzy (Chromium) and Safari
 - Version Safari v15.2, Sizzy v59.0.0

**Additional context**
This may actually be a bug with Combobox from Headless UI.

**Comment by reinink** [comment]
@sergiodxa Hey good catch! This command palette is a little trickier than the others as it has the preview panel, and is borderline abusing the combobox to accomplish this behavior 😅

Nonetheless, I was able to track down the issue here and fixed it. Thanks so much for reporting this bug.
