### ISSUE TITLE
Clipping bottom part of tail letters

### ISSUE THREAD

**Issue by Siemik** [tailwindlabs/tailwindui-issues#1161]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/marketing/page-examples/landing-pages
- Component name: Background image hero with alternating features

**Describe the bug**
Clipping bottom part of the letters tail letters

**To Reproduce**
1. Go to CTA Section (`<!-- CTA Section -->` if you choose HTML code) 
2. Replace _Get in touch or create an account._ with _geography of japan_
3. Look at bottom of _g_, _p_ and _y_ letter 

**Expected behavior**
I expected to see full tail letters.

**Screenshots**
![image](https://user-images.githubusercontent.com/45874801/156889168-d1e427d5-d484-41fd-8997-b960ec0ec19e.png)

**My solution**
I just added `pb-1` to second `<span>`

**Comment by reinink** [comment]
@Siemik Hey thanks for letting us know about this. This text is actually using the default line height set by Tailwind CSS for this font size (40px), and I guess the `bg-clip-text` causes it to just get clipped off. Adding `-mb-1 pb-1` to this element fixes it. You could also just increase the line height, but that changes the design for the worse in my opinion.

Anyway, I've fixed this — thanks again for reporting!! 👍
