### ISSUE TITLE
Border missing on native select

### ISSUE THREAD

**Issue by timonmasberg** [tailwindlabs/tailwindui-issues#1162]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/forms/select-menus#component-79592f355ca6f6e3b081e0158109981c
- Component name: Select Native

**Describe the bug**
Missing `border` class.

![image](https://user-images.githubusercontent.com/13659466/157244733-407e7e8b-a81c-47bc-9332-87c787e9d89b.png)

**Comment by adamwathan** [comment]
Hey! Did you make sure to add the `@tailwindcss/forms` plugin as mentioned in the code snippet?

<img width="1039" alt="image" src="https://user-images.githubusercontent.com/4323180/157260831-e681ca42-0056-4289-8fdc-8c33d6056d85.png">

**Comment by adamwathan** [comment]
Hmm weird! Do you mind creating a GitHub repository that mimics your setup and reproduces this problem?

**Comment by reinink** [comment]
@timonmasberg Hey, I'm going to close this issue because we haven't heard anything back, but absolutely still feel free to share a GitHub repo with a minimal reproduction of this issue and we'll gladly have a look 👍
