### ISSUE TITLE
tailwind-ui.min.css (legacy) & cdn usage for tailwind-ui

### ISSUE THREAD

**Issue by TechAkayy** [tailwindlabs/tailwindui-issues#1168]
Raising this follow-up issue for clarification based on this two year old topic https://github.com/tailwindlabs/tailwindui-issues/issues/84 & Adam's reply to it. 

[cdn.jsdelivr.net/npm/@tailwindcss/ui@latest/dist/tailwind-ui.min.css](https://cdn.jsdelivr.net/npm/@tailwindcss/ui@latest/dist/tailwind-ui.min.css) is around 1.8MB, 

... and Adam responded there that the plan was to migrate most of the extensions into Tailwind itself. 

Did this eventually happen? Is there any reason we should use the above cdn link for tailwind-ui? 

Tailwind-ui documentation also has no information regarding usage via cdn. I couldn't find any info on this anywhere online as well.

Thanks in advance for your clarification on this topic.

**Comment by adamwathan** [comment]
Hey! Yeah that happened back in November 2020 when we released Tailwind v2, the `@tailwindcss/ui` package hasn’t been needed since then 👍🏻
