### ISSUE TITLE
Simple links centered:  resources nav items

### ISSUE THREAD

**Issue by justiny** [tailwindlabs/tailwindui-issues#1171]
**What component (if applicable)**
- URL for category: [Simple links centered](https://tailwindui.com/components/marketing/elements/headers#component-a2aed5adfe85cafed1898b5def5eb40a)
- Component name: Simple Links Centered

**Describe the bug**
When mapping over Resources object, `resources.name` is used, but should be `resource.name`

**To Reproduce**
1. Go to Simple Links Centered component in React version

```{resources.map((resource) => (
    <a
      key={resources.name}
      href={resource.href}
      className="text-base font-medium text-gray-900 hover:text-gray-700"
    >
      {resource.name}
    </a>
```

**Expected behavior**
The a tag key prop is incorrect.

**Screenshots**
None needed.

**Comment by reinink** [comment]
@justiny Hey nice catch! I've just corrected this, and it's deploying to production right now. Thanks! 👍
