### ISSUE TITLE
why are duplication the menu in all code component

### ISSUE THREAD

**Issue by eng-faris** [tailwindlabs/tailwindui-issues#1181]
**What component (if applicable)**
- URL for category: 
- Component name: 

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Browser/Device (if applicable)**

**Additional context**

**Comment by adamwathan** [comment]
Hey! I wrote a bit about this on Twitter a while ago:

https://twitter.com/adamwathan/status/1223707033217720327

Basically in our experience it's just much easier to maintain and gives you much more flexibility. It's easy to change the mobile styles without worrying about how you are screwing up the desktop styles, and you can even do things like swap the mobile menu for a totally different pattern easily (switching from a popover to a slide-over sheet for example).

Hope that's helpful!

**Comment by eng-faris** [comment]
Thanks :)
