### ISSUE TITLE
Cant select other images in product page

### ISSUE THREAD

**Issue by eskiesirius** [tailwindlabs/tailwindui-issues#1183]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/ecommerce/page-examples/product-pages#component-bed7a8c94a54fcd9e9b214b95b71d5d5
- Component name: With expandable product details

**Describe the bug**
When I change the screen to mobile, other images wont display and you cant select other images

**Screenshot**
https://prnt.sc/nHDP4njKxeL6

**Expected behavior**
It should show and select other images

**Comment by eskiesirius** [comment]
also it is possible to make the picture height fixed?

**Comment by reinink** [comment]
Hey!

My apologies on getting back to you on this one.

So this is simply a choice we made for the mobile view of this component — on mobile we hide the additional images to save space to make sure other important things like the price and description don't get pushed down too far.

Of course you're welcome to modify this component however you need to for your own project — that's one of the great things about Tailwind UI — it's really easy to customize! 

For example, you could reintroduce the thumbnails at the mobile size, or alternatively make the main image clickable, which opens an image "lightbox" where users can scroll through all the available images.

In the same way, you're also welcome to change the size (ratio) of the images however you need for your own project.

I hope that helps 👍
