### ISSUE TITLE
User registration components

### ISSUE THREAD

**Issue by bradly** [tailwindlabs/tailwindui-issues#119]
The "Sign-in and Registration" section's components are actually only sign in components. Would be great to have user registration components with different form fields, validation errors, help text, and ToS agreement section.

**Comment by simonswiss** [comment]
Thanks for the suggestion! 👍

I am porting the component suggestions to an "ideas" column in the Trello roadmap. I'll close this issue, but you can find this request here: https://trello.com/c/1OwbBwg1/63-sign-up-registration

**Comment by raci-aivy** [comment]
It would be helpful if in addition to the SignIn, the screens for forgotten password, code verification, change temporary password etc. are also included.
