### ISSUE TITLE
module @tailwindcss/aspect-ratio can't be found

### ISSUE THREAD

**Issue by f2xiao** [tailwindlabs/tailwindui-issues#1196]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/ecommerce/components/store-navigation
- Component name: Store Navigation

**Describe the bug**
Comments in the Vue code instruct to include @tailwindcss/aspect-ratio as a plugin in the config but generate compile error. 
![image](https://user-images.githubusercontent.com/25191617/162582644-ad562350-4c20-4594-8f05-6cc8661ffe45.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/25191617/162582500-3b435556-9113-4346-8e03-d9461384c14f.png)

**Vue and tailwindcss versions**
![image](https://user-images.githubusercontent.com/25191617/162582559-704d199d-de62-4588-80f6-62d2481cdc9c.png)

**Additional context**
Is the comments outdated? After remove the config, the component renders fine with Vue3.

**Comment by adamwathan** [comment]
Hey! You need to actually install the package from npm as well:

`npm install @tailwindcss/aspect-ratio`

That will fix it for you 👍🏻

**Comment by f2xiao** [comment]
> Hey! You need to actually install the package from npm as well:
> 
> `npm install @tailwindcss/aspect-ratio`
> 
> That will fix it for you 👍🏻

i c thx, thought it's included in the core utilities but the component actually uses arbitrary value that's not included. Please close the issue, my problem is solved👌. Have a nice day!
