### ISSUE TITLE
Ecommerce > components > product Features doesn't work in html

### ISSUE THREAD

**Issue by gomguard** [tailwindlabs/tailwindui-issues#1198]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/ecommerce/components/product-features
- Component name: Every Product Features

**Describe the bug**

in html code components doesn't work

**To Reproduce**

**Expected behavior**

**Screenshots**
tailwind.configt.js
![image](https://user-images.githubusercontent.com/34765216/163751727-8c48b3d7-a86e-4fd1-9e69-fdbe4441b2ea.png)

![image](https://user-images.githubusercontent.com/34765216/163751769-7096184b-bc6c-42aa-a9d1-31a3ba6b7851.png)

I copied this code from your site, but it works like this.
![image](https://user-images.githubusercontent.com/34765216/163751858-82254060-84c6-4db2-b381-dd4334442da4.png)

please help me

This component says it doesn't need js file, and I used your html code.

**Browser/Device (if applicable)**
 - OS: [e.g. iOS] windoes

**Additional context**

**Comment by adamwathan** [comment]
Hey! Can you share your project? I just copied the component into Tailwind Play and it worked for me as expected, so must be something specific to how you have your project set up.
