### ISSUE TITLE
Popups

### ISSUE THREAD

**Issue by stevecastaneda** [tailwindlabs/tailwindui-issues#120]
**Screenshots**
![image](https://user-images.githubusercontent.com/171488/77689009-f8d4c200-6f6e-11ea-80fb-72bdf4189356.png)

![image](https://user-images.githubusercontent.com/171488/77689032-068a4780-6f6f-11ea-9fbb-6f4424f20ab2.png)

![image](https://user-images.githubusercontent.com/171488/77689083-1570fa00-6f6f-11ea-9450-42c5cc0475e0.png)

**Additional context**
https://react.semantic-ui.com/modules/popup/

Would be nice to have some pop-ups with pointers.

**Comment by simonswiss** [comment]
Merging this with https://github.com/tailwindlabs/tailwindui-issues/issues/175 - the suggestion has been captured in our Trello roadmap ideas: https://trello.com/c/KVOX3uCK/56-tooltips
