### ISSUE TITLE
Examples are not fully validated proper HTML

### ISSUE THREAD

**Issue by michalzubkowicz** [tailwindlabs/tailwindui-issues#1203]
When I've checked components with w3c validator, many examples like this:
https://tailwindui.com/components/ecommerce/components/product-overviews

has validation errors like:
"Element [p](https://html.spec.whatwg.org/multipage/#the-p-element) not allowed as child of element label in this context. (Suppressing further errors from this subtree.)"

There is a many of them. Built in React validator also show such errors  You should check all the examples with validators and fix those errors.

**Comment by reinink** [comment]
@michalzubkowicz Hey thanks for reaching out about this — you're right, there were some components that were not passing when run through an HTML validation tester. We've reviewed all the components in Tailwind UI and made a few corrections where needed 👍
