### ISSUE TITLE
John/Jane Doe names often used for missing/dead people

### ISSUE THREAD

**Issue by markuswustenberg** [tailwindlabs/tailwindui-issues#1211]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/forms/input-groups
- Component name: [Input with leading icon and trailing button](https://tailwindui.com/components/application-ui/forms/input-groups#component-a8d111fef35bfae4c800af505ea0d276)

**Describe the bug**
Sooo, this is a bit of an odd one. 😅 Not a bug, but I thought I would let you know anyway.

As far as I know, the names John/Jane Doe are often used in law enforcement to refer to missing or dead people. I believe the usual placeholder for generic-sounding English names are John/Jane Smith.

**To Reproduce**
1. See name
2. Think of murdered people

**Expected behavior**
I did not expect to think of murdered people.

**Screenshots**

I don't think a screenshot further clarifies the issue.

**Browser/Device (if applicable)**
 - OS: All
 - Browser: All
 - Version: All

**Additional context**
https://en.wikipedia.org/wiki/John_Doe

**Comment by reinink** [comment]
Hey @markuswustenberg thanks for the heads up on this — we've changed it to "Smith" instead of "Doe" 👍
