### ISSUE TITLE
Sidebar window resizing causes sidebar not to re-appear and no response from click events

### ISSUE THREAD

**Issue by ptimson** [tailwindlabs/tailwindui-issues#1215]
**What component (if applicable)**
- URL for category: [Home Screens](https://tailwindui.com/components/application-ui/page-examples/home-screens)
- Component name: [Full-width with sidebar](https://tailwindui.com/components/application-ui/page-examples/home-screens#component-af4086fe483fb8a418175cf0218dd5c4)

**Describe the bug**
On smaller screen sizes `max-width: 1023px` when the sidebar is hidden, resizing the screen to `min-width: 1024px` and then back to `max-width: 1023px` causes an issue where it seems like the window no longer responds to click events.

_**It works on the component demo screen but does not work when copying the code into our project, so we wonder if the code has not been updated?**_

**To Reproduce**
Steps to reproduce the behaviour:
1. [Bootstrap a NextJS app with tailwindcss](https://tailwindcss.com/docs/guides/nextjs)
2. Copy and save component code to a new page `src/pages/preview.jsx`
3. Visit the page and confirm UI same as component link above
4. Resize window to `max-width: 1023px` to reveal hamburger menu
5. Click on hamburger menu to reveal sidebar
6. Resize window to `min-width: 1024px` to hide hamburger menu
7. Resize window to `max-width: 1023px` to reveal hamburger menu
8. Notice sidebar is hidden
9. Notice other components in window not clickable
10. Notice [7] and [8] does not occur in [component demo page](https://tailwindui.com/components/application-ui/page-examples/home-screens#component-af4086fe483fb8a418175cf0218dd5c4)

**Expected behaviour**
Sidebar should remain visible after steps [4], [5], and [6]

**Screenshots**
Expected
![expected](https://user-images.githubusercontent.com/2879859/170241804-7850006f-b75a-4c9c-9b0e-d40c0240591d.gif)
Actual
![actual](https://user-images.githubusercontent.com/2879859/170241821-3447e146-2787-41b9-85d0-0258386805c9.gif)

**Browser/Device (if applicable)**
 - OS: Windows 10 and MacOS xx
 - Browser: Chrome
 - Version: 101.0.4951.67 (Official Build) (64-bit)

- @headlessui/react: "^1.6.1"

**Additional context**
N/A

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

This is an issue in Headless UI and we just released a fix in [#1500](https://github.com/tailwindlabs/headlessui/pull/1500). It should already be available in the latest `1.6.3` release.

Sorry for the inconvenience
