### ISSUE TITLE
Component - Comboboxes - render error

### ISSUE THREAD

**Issue by JaydenElliott** [tailwindlabs/tailwindui-issues#1228]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/forms/comboboxes
- Component name: Combobox Simple

**Describe the bug**
Just a small, easy to fix bug in the docs. When running the example code, you get the error `Uncaught TypeError: person is undefined` .

**To Reproduce**
1. Copy and paste the code.
2. Render the component.

**Solution**
- The problem is that the state has no default value `const [selectedPerson, setSelectedPerson] = useState();`
- In the headless ui docs (https://headlessui.dev/react/combobox) , the initial state is set to `people[0]` with `const [selectedPerson, setSelectedPerson] = useState(people[0]);` This will fix the issue.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

This should be fixed and will be live very soon!

While your solution works, we made it a bit more robust by making sure that the `displayValue` prop itself doesn't crash. This is going to be useful if you explicitly start with `selectedPerson = null`.

The change looks like this:
```diff
  <Combobox.Input
    className="w-full rounded-md border border-gray-300 bg-white py-2 pl-3 pr-10 shadow-sm focus:border-indigo-500 focus:outline-none focus:ring-1 focus:ring-indigo-500 sm:text-sm"
    onChange={(event) => setQuery(event.target.value)}
-   displayValue={(person) => person.name}
+   displayValue={(person) => person?.name}
  />
```
