### ISSUE TITLE
Full-width secondary column on right sample issue

### ISSUE THREAD

**Issue by ilabsllc** [tailwindlabs/tailwindui-issues#1229]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/application-shells/multi-column#component-65815af4357dfdcf9be55c390221c5fb
- Component name: Full-width secondary column on right sample issue

**Describe the bug**

On your website when I log in and try the sample the behavior is as expected on smaller screen sizes where it only shows the main content area. But when I try the exact same in my local (with brand new next js app ) it hides not only the sidebar and right column but also the main content area. Tried to debug but couldn't figure the reason.

**To Reproduce**
1. Create a simple Next JS app. 
2. Create an index.js under pages.
3. Copy the react code from your sample.
4. Run the app. Resize below 1024 and see the issue.

**Expected behavior**
When resizing below 1024 it shouldn't hide main content area ( the center one ).

**Screenshots**
If applicable, add screenshots to help explain your problem. Not that the top sample SCR displays the border while the local one doesn't

<img width="406" alt="Sample-Scr-Below1024" src="https://user-images.githubusercontent.com/64938082/174212024-fef205d2-cf2f-4dde-a9a3-b68635669b10.png">
![Local-Scr-Below1024](https://user-images.githubusercontent.com/64938082/174212027-13943e37-715b-4d70-a085-9e6f87489a82.png)

**Browser/Device (if applicable)**
 - OS:  Mac Montery 
 - Browser Chrome
 - Version 102.0.5005.115 

**Additional context**

**Comment by adamwathan** [comment]
Hey! If I'm understanding correctly this is working the way you want already — as you resize the secondary column on the right is the one that's hidden, and the main content area in the center is preserved:

https://user-images.githubusercontent.com/4323180/174435157-8c2bccb6-4c5e-41ee-8db7-4a19317a2d46.mov

Can you share a reproduction of the issue you're seeing as a GitHub repo so we can take a look?

**Comment by ilabsllc** [comment]
Here is the repro: https://github.com/ilabsllc/bugreports/tree/main/bug1229

If you just run the above and resize you would find that at a smaller screen size the Main Content is not visible anymore.

I also found the issue. In line 226, if you remove the "absolute" class from the div it works as expected where the Main Content still shows up on a smaller screen.

**Comment by bradlc** [comment]
Hey @ilabsllc. This particular component requires some changes to your template which are outlined on lines 33-40 of the component's React code:

````
{/*
  This example requires updating your template:

  ```
  <html class="h-full bg-white">
  <body class="h-full overflow-hidden">
  ```
*/}
````

Next.js inserts an additional container between `<body>` and your app code, so you will also need to add `height: 100%` to this element. I have opened a [pull request](https://github.com/ilabsllc/bugreports/pull/1) on your repo which makes the necessary changes. I hope that helps!
