### ISSUE TITLE
Process Steps for forms and other UI

### ISSUE THREAD

**Issue by outlawvik** [tailwindlabs/tailwindui-issues#123]
A step shows the completion status of an activity in a series of activities
This feature is something what I feel missing when I create dashboard forms
for reference purpose I have shared the semantic example. 

**Screenshots**
<img width="886" alt="Screenshot 2020-03-27 at 11 24 08 PM" src="https://user-images.githubusercontent.com/44430249/77765771-19417100-7082-11ea-999d-de9146d1464c.png">

**Additional context**
https://semantic-ui.com/elements/step.html

**Comment by J05HI** [comment]
Additional examples:

https://www.leverege.com/solutions-development/overview
![image](https://user-images.githubusercontent.com/16399787/80521275-0ecd0c80-898b-11ea-84d0-d2a63e5be424.png)

https://www.leverege.com/platform/build
![image](https://user-images.githubusercontent.com/16399787/80521321-22787300-898b-11ea-9f37-eea4a4473769.png)

https://dribbble.com/shots/8682801-portfolio-design-webapp
![image](https://cdn.dribbble.com/users/1824846/screenshots/8682801/media/2ed6c97646cc174fd4c332600c51a4e3.png)

**Comment by simonswiss** [comment]
We've been working on a few (7) steps components and they will be shipping very soon! 🎉

Here's an ant-sized sneak peek while you wait! 😅

![image](https://user-images.githubusercontent.com/485747/89975413-033af280-dca9-11ea-81b0-4a6e538daee3.png)
