### ISSUE TITLE
Component: Overlaping images are not displayed

### ISSUE THREAD

**Issue by laurentDellaNegra** [tailwindlabs/tailwindui-issues#1234]
Hello, 

I found a broken component in TailwindUI

**What component**
- URL for category: https://tailwindui.com/components/ecommerce/page-examples/storefront-pages#component-464ebe7691b135031411ad52b3560cc1
- Component name: With overlapping image tiles and perks

**Describe the bug**
The display is broken on desktop size but seems to be ok on small screen.

**To Reproduce**
I've copied paste the HTML code in tailwind play and I have the same issue.
I don't want to paste the code because it's a paid component.

![image](https://user-images.githubusercontent.com/9579159/175139604-246e687d-be9e-44f9-b151-9e0694e93445.png)

**Browser/Device (if applicable)**
 - OS: MacOS
 - Browser:chrome
 - Version 102.0.5005.115 (Official Build) (arm64)

**Additional context**
Reproduced on
- Next.js application
- Storybook
- tailwind play
- No error in console
- I've installed the 2 required plugins:

```
/** @type {import('tailwindcss').Config} */
module.exports = {
  plugins: [require('@tailwindcss/forms'), require('@tailwindcss/aspect-ratio')],
  content: ['./src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        primary: '#579660',
        'primary-light': '#EEF4EF',
        secondary: '#87563B',
        'secondary-light': '#F5DDD2',
      },
    },
  },
  plugins: [],
}
```
I'll keep you posted if I found the issue

Thx for this amazing framework ❤️

**Comment by laurentDellaNegra** [comment]
I've found the issue, the component is still on v2 and aspect ratios values are not updated:

- replace all `aspect-w-1 aspect-h-1` by `aspect-square`
- replace `sm:aspect-w-4 sm:aspect-h-5` by `aspect-square sm:aspect-[4/5]`

did the trick

**Comment by laurentDellaNegra** [comment]
I've jut noticed also another small ui issue with the dropdown on top left, it seems to be in double:

![image](https://user-images.githubusercontent.com/9579159/175232963-fd77b786-9c0b-4186-9dd1-4c1db5d9d116.png)

**Comment by adamwathan** [comment]
Hey! The problem here is you haven't installed the `@tailwindcss/forms` or `@tailwindcss/aspect-ratio` plugins, as mentioned in the instructions at the top of the component snippet:

<img width="1411" alt="image" src="https://user-images.githubusercontent.com/4323180/175285873-81679f1c-2f7b-404c-aecf-b8488a80c653.png">

That will fix the aspect ratio issue and the chevron issue 👍

**Comment by laurentDellaNegra** [comment]
> Hey! The problem here is you haven't installed the `@tailwindcss/forms` or `@tailwindcss/aspect-ratio` plugins, as mentioned in the instructions at the top of the component snippet:
> 
> <img alt="image" width="1411" src="https://user-images.githubusercontent.com/4323180/175285873-81679f1c-2f7b-404c-aecf-b8488a80c653.png">
> 
> That will fix the aspect ratio issue and the chevron issue 👍

It is installed as mentionned in my conf:

```
/** @type {import('tailwindcss').Config} */
module.exports = {
  plugins: [require('@tailwindcss/forms'), require('@tailwindcss/aspect-ratio')], <======== Here
  content: ['./src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        primary: '#579660',
        'primary-light': '#EEF4EF',
        secondary: '#87563B',
        'secondary-light': '#F5DDD2',
      },
    },
  },
  plugins: [],
}
```
