### ISSUE TITLE
Navbar components are not adapted to react-router-dom

### ISSUE THREAD

**Issue by Hernanarica** [tailwindlabs/tailwindui-issues#1244]
**What component (if applicable)**
- URL for category: 
- Component name: 

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Browser/Device (if applicable)**

**Additional context**

**Comment by adamwathan** [comment]
Hey! We can't make any assumptions about what router library or anything people are using, so we just use simple regular link tags. You'd want something different if you are using Next.js for example, so this is the sort of thing you'd just have to adapt a bit when incorporating these snippets into your own codebase 👍 Hope that helps!
