### ISSUE TITLE
Code collapsed variables don't expand

### ISSUE THREAD

**Issue by ChrisGV04** [tailwindlabs/tailwindui-issues#1248]
**What component (if applicable)**
Every component that has a variable with collapsed content. But I'll leave an example.
- URL for category: https://tailwindui.com/components/application-ui/lists/tables
- Component name: Simple

**Describe the bug**
When I view the code of any component and it has a collapsed variable with an arrow to expand the data, if I click the arrow it doesn't do anything, so I can't see how you structured the data on the variables.

**To Reproduce**
1. Go to any component that has an array or collapsed object. I linked an example above.
2. Click on the "Code" view for either React or Vue (Both have the issue)
3. If the code has a variable or piece of state that shows as collapsed, try to click on it to expand but it won't do anything.

**Expected behavior**
When I click the arrow of the collapsed data it should expand and reveal the structure of the data that has been collapsed.

**Screenshots**
![Screen Shot 2022-06-27 at 10 42 41 p m](https://user-images.githubusercontent.com/47041342/176087320-227644da-3e79-4f78-b46e-87854bd3e2d6.png)

**Browser/Device (if applicable)**
 - OS: MacOS
 - Browser: Firefox
 - Version: 101.0.1

**Comment by thecrypticace** [comment]
Wow thanks for reporting this one! It was a bit weird but figured out the issue and the fix has been deployed!

**Comment by ChrisGV04** [comment]
Great! It's working fine again. Thank you very much.

Congrats on the amazing work recently 👍🏼
