### ISSUE TITLE
Syntax template missing env example

### ISSUE THREAD

**Issue by LarryBarker** [tailwindlabs/tailwindui-issues#1260]
**What component (if applicable)**
- URL for category: https://tailwindui.com/templates/syntax
- Component name: Syntax template

**Describe the bug**
May not necessarily be a bug, but the first step in the README for this template says:

```
cp .env.example .env.local
```

This step fails as the `.env.example` file is not included. 

**To Reproduce**
1. Download the syntax template
2. Follow instructions in the README
3. See error copying env example

**Comment by bradlc** [comment]
Thanks for reporting, this has now been resolved 👍
