### ISSUE TITLE
`name` and `id` props typo

### ISSUE THREAD

**Issue by cjavdev** [tailwindlabs/tailwindui-issues#1267]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/ecommerce/components/checkout-forms#component-0cc73c0ab9d4e5c1d34cc5dc1a7ac96a
- Component name: ecommerce

**Describe the bug**
typo should be `region` instead of `regino` 

**To Reproduce**

**Expected behavior**

**Screenshots**

<img width="1445" alt="image" src="https://user-images.githubusercontent.com/3710766/180002832-9edc6382-2f8d-4f56-958a-7f14573d30cf.png">

**Browser/Device (if applicable)**

**Additional context**

**Comment by reinink** [comment]
@cjavdev Hey thanks for reporting this! This has been fixed 💪
