### ISSUE TITLE
Multplie form, only one submit

### ISSUE THREAD

**Issue by mbaroukh** [tailwindlabs/tailwindui-issues#1277]
**What component (if applicable)**

https://tailwindui.com/components/application-ui/forms/form-layouts#component-b5675d2efaa71ec3767969fd53fc3b66

This one:
![image](https://user-images.githubusercontent.com/3954833/180748020-f303fe75-84fd-4aa3-aa7f-bdfbb0730a35.png)

**Describe the bug**

This form layout provides multiple sections with only one submit button at the end.
But the html structure has multiple `<form>` node. 
It must me a copy of the previous one which is "with separate submit actions"

**Expected behavior**

with only one submit button, there should be only one form with the button inside.

**Comment by reinink** [comment]
Hey good catch @mbaroukh, this has been fixed 👍
