### ISSUE TITLE
Syntax Template - width and align can't be set for a markdoc table

### ISSUE THREAD

**Issue by schultzp2020** [tailwindlabs/tailwindui-issues#1278]
**What component (if applicable)**
Syntax Template

**Describe the bug**
Width and align can't be set for a markdoc table.

**To Reproduce**
Create a table using markdoc syntax.

```md
{% table %}
* Key {% width="25%" %}
* Type
* Required
* Description
---
* `name`
* `string`
* yes
* The name of your devfile.
---
* `description`
* `string`
* no
* The description of your starterProject.
---
* `clonePath`
* `string`
* no
* The path relative to the root of your projects. Clone your projects into this path.
{% /table %}
```

**Expected behavior**
Setting width should change the width.

**Screenshots**
Before fix:
![image](https://user-images.githubusercontent.com/52387464/181051500-0845dd3c-e922-455f-83d0-8e56d9110921.png)

After fix:
![image](https://user-images.githubusercontent.com/52387464/181051657-0ae4ec89-80de-4b3e-adf9-235f187c57df.png)

**Browser/Device (if applicable)**
N/A

**Fix**

Add the `align` and `width` attributes to `<th>`.
``` js
const nodes = {
  document: {
    render: undefined,
  },
  th: {
    attributes: {
      scope: {
        type: String,
        default: 'col',
      },
      align: {
        type: String,
      },
      width: {
        type: String,
      },
    },
    render: (props): JSX.Element => <th {...props} />,
  },
  fence: {
    render: Fence,
    attributes: {
      language: {
        type: String,
      },
    },
  },
};
```

**Comment by thecrypticace** [comment]
Hey, thanks for reporting. For the `th` node were were unintentionally overwriting the defaults so we've pulled those back in by referring back to the markdoc package's `nodes` export. This has been updated and you can download the new zip to see the difference (basically an import, `...defaultNodes.th`, and `...defaultNodes.th.attributes`)`

Appreciate it! ✨

**Comment by schultzp2020** [comment]
@thecrypticace you may also want to fix the link to use `next/link` while you're at it as well. 

``` js
import Link from 'next/link';

const nodes = {
  ...
  link: {
    render: Link,
    attributes: {
      href: {
        type: String,
      },
    },
  },
};
```
