### ISSUE TITLE
Unable to download template files

### ISSUE THREAD

**Issue by johnsorianodev** [tailwindlabs/tailwindui-issues#1279]
**What component (if applicable)**
- URL for category: 
- Component name:  Template files

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Browser/Device (if applicable)**

**Additional context**

**Comment by adamwathan** [comment]
Hey! I just double-checked and all of these links work (assuming you are logged in and have a license for each template):

https://tailwindui.com/templates/salient/download
https://tailwindui.com/templates/salient/download
https://tailwindui.com/templates/salient/download
https://tailwindui.com/templates/salient/download

**Comment by johnsorianodev** [comment]
Hi Adam, thanks for pointing that out. btw so basically I need to purchase separate license for templates? I only have Application UI, Markting and eCommerce. So the template is separate

**Comment by adamwathan** [comment]
@johnsorianodev Hey! If you have all three of those then you should automatically have the all-access license now which includes the templates. Shoot us an email at support@tailwindui.com with your account details and I will make sure we sort it out for you!

**Comment by johnsorianodev** [comment]
Thanks @adamwathan , actually here what I see after I click the link you mention above,
![image](https://user-images.githubusercontent.com/17820293/181395735-7425aa29-1be1-448a-a6cc-665c6286c5d2.png)

**Comment by johnsorianodev** [comment]
looks like I always redirected to that link.

**Comment by adamwathan** [comment]
What email address do you use to log in to Tailwind UI?

**Comment by johnsorianodev** [comment]
johnreymsoriano@gmail.com

**Comment by johnsorianodev** [comment]
any luck @adamwathan ? I still not able to download.

**Comment by johnsorianodev** [comment]
https://www.loom.com/share/3f1fdfdd2a3643ff8b7dc5e761ff53cf

**Comment by RobinMalfait** [comment]
Hey!

I also can't reproduce this on your account or in different browsers. Here are a few things I want you to try/check:

1. Can you try in a different browser?
1. Can you try on a different device?
1. Can you try on a different device with a different internet connection (like a smartphone)?
1. Do you have any browser extensions running that could block this? 
1. Do you have any custom Chrome flags enabled that could cause this?
1. Do you have any custom DNS configurations?
1. Do you have a VPN running that could cause this?
1. Do you have antivirus software running that could bock this?
1. Long shot, do you have any overrides in your `/etc/hosts`?

I found this article with a bunch of checks and ways to try and solve the issue. https://www.hostinger.com/tutorials/fix-dns_probe_finished_nxdomain#9_Ways_to_Fix_the_DNS_PROBE_FINISHED_NXDOMAIN_Error
