### ISSUE TITLE
Input field stylings not styled correctly

### ISSUE THREAD

**Issue by gabrielkuik** [tailwindlabs/tailwindui-issues#1280]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/forms/input-groups
- Component name: Input with label

**Describe the bug**
The code with styling given for vue does not correspond to actual example in the browser implementation.

**To Reproduce**
1. Go to https://tailwindui.com/components/application-ui/forms/input-groups
2. Click on "Code"
3. Copy the div with input
5. Paste anywhere and see error

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/87762173/181880023-0b72f96e-f801-4d9e-b44a-4b9d9f73175c.png)
![image](https://user-images.githubusercontent.com/87762173/181880042-e1c4d09f-f788-4cb2-8bcf-91b0a9903811.png)

**Browser/Device (if applicable)**
 - OS: [Windows 10, Linux Ubuntu 18.04]
 - Browser [Brave, Chrome]

**Additional context**

**Comment by adamwathan** [comment]
Hey! This looks to me like you are missing the forms plugin, which is mentioned in the instructions at the top of the code snippet:

![58F0087F-A125-4268-8055-805CA24349EA](https://user-images.githubusercontent.com/4323180/182022840-260d9f8e-4891-4a17-af22-5cb5775d153f.png)

If you install that plugin and add it to your config you should see the styles you expect 👍🏻
