### ISSUE TITLE
Component thumbnails not showing in Safari

### ISSUE THREAD

**Issue by danielfriis** [tailwindlabs/tailwindui-issues#1281]
**Describe the bug**
On your [list of components](https://tailwindui.com/components), images don't show in safari (Version 14.0.3).

**To Reproduce**
1. Go to [list of components](https://tailwindui.com/components)
2. See error

**Expected behavior**
Thumbnail of each component should show.

**Screenshots**
<img width="1470" alt="Skærmbillede 2022-07-30 kl  12 57 22" src="https://user-images.githubusercontent.com/2437484/181907831-3f6c1ea1-6548-4dcd-a714-3fca45acba50.png">

**Browser/Device (if applicable)**
 - OS: macOS Big Sur (11.2.3)
 - Browser: Safari
 - Version: 14.0.3

**Comment by adamwathan** [comment]
Hey! Previously discussed here:

https://github.com/tailwindlabs/tailwindui-issues/issues/1255#issuecomment-1175047429

Basically we are using the `aspect-ratio` CSS property which is supported in Safari 15 but not 14, so in older versions of Safari the page doesn't render properly. Fine with just living with it personally, more fun to just use the new stuff 😊
