### ISSUE TITLE
Navbars to match those in Hero Sections

### ISSUE THREAD

**Issue by ademers** [tailwindlabs/tailwindui-issues#129]
**Screenshots**
Example Hero Section: https://share.getcloudapp.com/o0uDwZ8x

**Additional context**
Scenario: I'm using one of the Hero Sections components on my Homepage and would like to use the same Navbar on my Products page, for example, which includes a simple Page Heading instead of a Hero Section. Extracting just the Navbar from the Hero Section to re-use on other pages, is not that straightforward.

Thanks for you consideration!

**Comment by dakira** [comment]
Ah.. interesting. :) I just reported the same thing as a bug. https://github.com/tailwindui/issues/issues/130

**Comment by simonswiss** [comment]
Consolidating this with https://github.com/tailwindlabs/tailwindui-issues/issues/220 👍
