### ISSUE TITLE
Responsive design does not work for several components

### ISSUE THREAD

**Issue by leonoronhas** [tailwindlabs/tailwindui-issues#1290]
**What component (if applicable)**
- URL for category: https://drive.google.com/file/d/13znpE1VXVaeFNVZ_RBbmvT0LloZ70Uun/view?usp=sharing
- Component name: https://tailwindui.com/components/marketing/sections/heroes#component-a3c09c7a3b8f4bd90d280722eaff9634

**Describe the bug**
Responsive design does not work for mobile. See video attached in first link.

**To Reproduce**
1. Go to inspect page on any browser, then click on the devices and check all device sizes and you see that the design does not apply for mobile. That is true for several components.

**Expected behavior**
Mobile design would work like the drag to the left works.

**Screenshots**
See video in first link

**Additional context**

I was playing with it for a classroom project and created the www.appurus.com website using tailwindui and in there you can see that the design does not work for mobile.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

Which part is not responsive? Do you have an example what you would expect? All the examples you linked to in the Marketing /  Hero Sections are all responsive.

Even if I look at your project it seems perfectly responsive to me:
<img width="686" alt="image" src="https://user-images.githubusercontent.com/1834413/183376982-e144a4a0-a6be-4b8e-8897-192b480fa3b6.png">

Would it be possible to provide a working application or screenshots of parts that you think are not responsive and what you would expect?

**Comment by leonoronhas** [comment]
So if you open in your phone appurus.com you will see that it staya at MD
size. However, if you drag the screen on your computer it resizes correctly

**Comment by RobinMalfait** [comment]
Aha I see, this is not a Tailwind issue but a setup issue. You are missing viewport related meta tags. 

Adding this should fix your problem:
```html
<meta name="viewport" content="width=device-width, initial-scale=1">
```

**Comment by leonoronhas** [comment]
Thank you! I'm sorry for the wrong bug report. You guys are awesome!

**Comment by leonoronhas** [comment]
Here's a screenshot from my phone
