### ISSUE TITLE
Salient template menu doesn't lock scroll

### ISSUE THREAD

**Issue by ChrisGV04** [tailwindlabs/tailwindui-issues#1291]
**What component (if applicable)**
- URL for category: https://tailwindui.com/templates/salient
- Component name: Salient template

**Describe the bug**
I don't think that it's a bug, but I guess it would be a nicer UX if when we open the mobile menu (which is a Popover) the scrolling of the website was locked, since it looks weird that you can scroll down and the white overlay covers the content of the website.

**To Reproduce**
1. Open the salient template on a mobile screen.
2. Click on the menu to open the Popover.
3. Scroll down from outside the popover. You'll see it does allow scrolling.

**Expected behavior**
I believe that if you open the menu, the scrolling should be disabled until the menu is closed. I tried to do this but I wasn't able to do it with the way HeadlessUI's Popover component works, but maybe I just lack the knowledge to do it.

If you agree, I would love to see how you approach this UX situation or if you don't consider it to be an issue at all.

**Screenshots**
Here's a video of the behavior:

https://user-images.githubusercontent.com/47041342/183731230-ec66ed58-9e89-4ee0-9d93-3eb29b0bdd0e.mp4

**Browser/Device (if applicable)**
It happens on every device

**Comment by reinink** [comment]
@ChrisGV04 Hey! So I've chatted with the team, and we generally agree that this isn't an issue. Yes, someone can technically scroll the page when the dropdown is open, but from an accessibility perspective that doesn't create any issues — you can click the backdrop at any time to close the menu and get back to the website.

That said, if you do want the scroll locking behavior, I'd recommend replacing the popover component with the dialog component, as it will prevent page scrolling.

Hope that helps 👍

**Comment by ChrisGV04** [comment]
@reinink Oh I see what you mean. I know it's an edge case or not a very common thing for someone to scroll so much on mobile with a navigation open haha.

Thank you very much for your opinion and for your suggestion on using the Dialog component, really appreciate it. 

Amazing work with all you do at Tailwind Labs btw, big fan!
