### ISSUE TITLE
No Animations in Tabs

### ISSUE THREAD

**Issue by fameoflight** [tailwindlabs/tailwindui-issues#1293]
**What component (if applicable)**
- URL for category:  Tabs
- Component name:  Tabs

**Describe the bug**
There should be a smooth transition in Tabs

**Expected behavior**
Tabs should have animations

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

This isn't really a bug and it works as designed. Maybe we add tabs with animations in the future but can't give you an ETA on that.
