### ISSUE TITLE
tailwindui and tailwindcss should have a different favicon

### ISSUE THREAD

**Issue by slara** [tailwindlabs/tailwindui-issues#1294]
**Describe the bug**
As they are the same, it's super hard to change from tailwindui to the tailwindcss documentation

**To Reproduce**
Open tailwindui and tailwindcss documentation at the same time

**Expected behavior**
Tabs should be recognizable

**Screenshots**

<img width="296" alt="image" src="https://user-images.githubusercontent.com/585824/184003155-f065c8c9-e8b0-460a-9cf2-03bdb5ed9d46.png">

**Browser/Device (if applicable)**
 - OS: all
 - Browser: all
 - Version: all

**Comment by thecrypticace** [comment]
Hey, given that the icon is a key part of both of the Tailwind CSS and Tailwind UI logos, and that Tailwind UI itself is intimately tied to Tailwind CSS, we chose to use the same favicon. This is a suggestion we've heard a few times and it's something we plan to play around with but, at least for now, are not yet going to change. Appreciate you opening the issue. Going to close this to keep these issues focused on bugs in the components themselves. Thanks!
