### ISSUE TITLE
notifications bell icon missing on nearly all mobile navbars

### ISSUE THREAD

**Issue by vesper8** [tailwindlabs/tailwindui-issues#13]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/navigation/navbars
- Component name: most navbars

**Describe the bug**
In nearly all navbar components, the bell icon for notifications disappears completely when mobile view is activated

**To Reproduce**
Drag thingy to trigger mobile view

**Expected behavior**
Notifications are a thing on mobile too

**Comment by davidluhr** [comment]
@vesper8 I know this was filed quite some time ago, but as of the latest Tailwind UI release, we've made sure that any navbar with a notification bell icon button includes this element in the mobile menu, as well. Thanks for pointing this out!
