### ISSUE TITLE
Breaking changes: heroicons updates

### ISSUE THREAD

**Issue by ACPK** [tailwindlabs/tailwindui-issues#1301]
Steps:

1. Downloaded [Tailwind's Salient template](https://tailwindui.com/templates/salient)
2. Create `component/Nav.jsx` using a Navbar from https://tailwindui.com/components/application-ui/navigation/navbars.
3. Call `components/Nav` in `index.jsx`

Issue:

`@heroicons/react 2.0` has breaking changes.

**Before:**
`import { BellIcon, MenuIcon, XIcon } from '@heroicons/react/outline'`
**After:**
`import { BellIcon, Bars3Icon, XMarkIcon } from '@heroicons/react/24/outline'`.

Was there a blog post or Github changelog entry about this that I missed?

**Comment by adamwathan** [comment]
Hey! Right now Tailwind UI is still using Heroicons v1.x, but we're going to get all that updated this week 👍 Bit of a messy transition I admit — hard to co-ordinate a big release like this.

In the mean time, make sure you are installing `@heroicons/react@^1` when using Tailwind UI components.

Will leave this open until we get all of the components migrated to the new version 👍🏻

**Comment by adamwathan** [comment]
Updated the documentation in the mean time 👍

<img width="876" alt="image" src="https://user-images.githubusercontent.com/4323180/186224516-95f33d63-b951-4218-9ab7-2b7d878f17ac.png">

**Comment by ACPK** [comment]
@adamwathan Thank you! Your team has made improvements to Headless's code which the community appreciates (ex: [fixing a close feature](https://github.com/tailwindlabs/headlessui/pull/754)). Has your team published any upgrades to existing TailwindUI code that developers would find helpful? I don't want to miss out on any changes I should make.

**Comment by reinink** [comment]
Hey folks, I just wanted to let you know that all the Tailwind UI components have been upgraded to use Heroicons v2.

If you're looking to upgrade an existing project to use Heroicons v2, I'd recommend checking out the upgrade guide in the v2 release notes, which you can find here: https://github.com/tailwindlabs/heroicons/releases/tag/v2.0.0

**Comment by reinink** [comment]
@ACPK Hey, you can find the Headless UI release notes on GitHub (https://github.com/tailwindlabs/headlessui/releases), which includes all changes we've made to the library.

You can also find a list of updates to Tailwind UI in our changelog here: https://tailwindui.com/changelog

Finally, follow our Tailwind CSS blog (or even join our newsletter) to get periodic updates about what we've been up to: https://tailwindcss.com/blog

Hope that helps 👍

**Comment by ACPK** [comment]
I'm confused about your post as this was about TailwindUI's bug fixes.

**Comment by reinink** [comment]
@ACPK Sorry, didn't totally understand what you were asking for originally, think I have a better understanding now.

We do make bug fixes to Tailwind UI when they are reported. However, it's not practical for us to keep track of these in a way that you can follow and apply yourself on a case by case basis — it would slow our production down to a halt.

Here's what I'd suggest — if you have an issue in your own code, come to the Tailwind UI website and check to see if there are any differences between what we have on Tailwind UI and what you have in your own project, and then just manually apply those changes.

Lots of time our changes are for super minor edge cases that are unlikely to affect your project 👍
