### ISSUE TITLE
Unify spacing methods

### ISSUE THREAD

**Issue by hyunbinseo** [tailwindlabs/tailwindui-issues#1306]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/forms/form-layouts
- Component name: [Application UI / Forms / Labels on left](https://tailwindui.com/components/application-ui/forms/form-layouts#component-cc5bee94bc88387c2511b0e5c3dfffef)

**Describe the bug**

Only the 1st section uses a different spacing method. It uses `.mt-?` in the 2nd child, instead of `.space-y-?` in the parent.

<img width="659" alt="image" src="https://user-images.githubusercontent.com/47051820/187064803-7014bf9b-dffb-42dc-885b-6e0761be49a0.png">

Example fix
<img width="797" alt="image" src="https://user-images.githubusercontent.com/47051820/187064543-ef246b52-9dff-4deb-bb83-2315e285465a.png">

**Comment by hyunbinseo** [comment]
This is minor, but the `.border` in `<textarea>` seems to be unnecessary.

```html
<textarea
  id="about"
  name="about"
  rows="3"
  class="block w-full max-w-lg rounded-md border border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm"
/>

<input
  type="text"
  name="first-name"
  id="first-name"
  autocomplete="given-name"
  class="block w-full max-w-lg rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:max-w-xs sm:text-sm"
/>
```

Classes sorted using [`prettier-plugin-tailwindcss`](https://github.com/tailwindlabs/prettier-plugin-tailwindcss).

**Comment by reinink** [comment]
@hyunbinseo Hey thanks for reporting this! I'm working on a fix and will let you know when that's been merged in 👍

**Comment by reinink** [comment]
@hyunbinseo Hey these improvements have been merged in. Thanks again! 💪
