### ISSUE TITLE
Typo in Salient template

### ISSUE THREAD

**Issue by gimenete** [tailwindlabs/tailwindui-issues#1313]
(Sorry for not using the issue template).

I think this is just a typo. In the [Salient template](https://salient.tailwindui.com/) there's a sentence that says

> It doesn’t matter what size your business is, our software won’t work well for you.

I guess the intention was to say something like:

> It doesn’t matter what size your business is, our software will work well for you.

**Comment by adamwathan** [comment]
Hey! This is actually intentional 😅 If you read the rest of the site you'll see a lot of other similar stuff, it's basically a parody from a content perspective 👍
