### ISSUE TITLE
Overlapping events in Week view Calendar component causes unexpected layout behavior

### ISSUE THREAD

**Issue by ntodd** [tailwindlabs/tailwindui-issues#1315]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/data-display/calendars
- Component name: Week view

**Describe the bug**
Overlapping events causes unpredictable layout behavior. If no events overlap, the layout appears as expected. However, if any events on day 5 overlap, some of the events will appear in a different location on the calendar. This also happens in the single-column day view at the smallest breakpoint.

**To Reproduce**
1. Create multiple events on day 5 with overlapping grid rows.
2. Test large and small single-column layouts

**Expected behavior**
Events should overlap as they do on days 1-4, 6, and 7.

**Screenshots**
Correct behavior with non-overlapping events:

<img width="1239" alt="Screen Shot 2022-09-08 at 2 13 55 PM" src="https://user-images.githubusercontent.com/31457/189196169-f95e8947-cfe1-416e-8659-806dce1e09dc.png">
<img width="497" alt="Screen Shot 2022-09-08 at 2 14 02 PM" src="https://user-images.githubusercontent.com/31457/189196190-8be13b48-c595-4462-a723-57afbedfdef0.png">

Incorrect behavior with overlapping events:

<img width="1241" alt="Screen Shot 2022-09-08 at 2 13 34 PM" src="https://user-images.githubusercontent.com/31457/189196267-ca204041-ed87-412b-919d-52eb65ab3062.png">
<img width="496" alt="Screen Shot 2022-09-08 at 2 13 44 PM" src="https://user-images.githubusercontent.com/31457/189196281-5a86f71b-f711-4bde-9800-e2082cf56858.png">

**Browser/Device (if applicable)**
 - OS: MacOS 12.5.1
 - Browser: Chrome
 - Version: 105

**Additional context**
It might also be nice to have a UI for overlapping events where they can be side-by-side or overlapped. Examples:
<img width="191" alt="Screen Shot 2022-09-08 at 2 23 05 PM" src="https://user-images.githubusercontent.com/31457/189197397-d367e9ff-2bc3-487f-b98b-1d0fe5def103.png">
<img width="188" alt="Screen Shot 2022-09-08 at 2 22 58 PM" src="https://user-images.githubusercontent.com/31457/189197411-1a767163-9d71-4e9a-9318-d8a227f7e1bc.png">

Thank you!

**Comment by ntodd** [comment]
Appreciate you looking at it. I ended up rewriting to handle some other cases and was able to fix it, so it was a bug on my end.

**Comment by vertonghenb** [comment]
Any idea's how we can achieve items next to each other when they overlap?

![Image](https://user-images.githubusercontent.com/31457/189197397-d367e9ff-2bc3-487f-b98b-1d0fe5def103.png)
