### ISSUE TITLE
Unable to see components on Safari

### ISSUE THREAD

**Issue by jdslomka** [tailwindlabs/tailwindui-issues#1316]
**What component (if applicable)**
- URL for category: 
- https://tailwindui.com/components
- Component name: 
- all

**Describe the bug**
The [component page](https://tailwindui.com/components) is missing all previews images

**To Reproduce**
Just went to url

**Expected behavior**
All preview images are missing in cards

**Screenshots**
<img width="1489" alt="Screen Shot 2022-09-10 at 11 09 53 AM" src="https://user-images.githubusercontent.com/25642739/189489539-38fb3475-612f-4312-8538-94e57b0a3320.png">
<img width="1552" alt="Screen Shot 2022-09-10 at 11 10 06 AM" src="https://user-images.githubusercontent.com/25642739/189489550-3eb3a11a-be79-453a-80c9-dcf9da0a01db.png">
<img width="1452" alt="Screen Shot 2022-09-10 at 11 10 17 AM" src="https://user-images.githubusercontent.com/25642739/189489556-eb7b9faa-97b4-425f-b43d-85513e0c03e6.png">

**Browser/Device (if applicable)**
 - OS: MacOs
 - Browser: Safari
 - Version: 14.1.1

**Additional context**

**Comment by adamwathan** [comment]
Hey! This is because we are using the `aspect-ratio` CSS property which isn’t supported in older versions of Safari, but will work if you update to a newer version 👍🏻
