### ISSUE TITLE
Scrollable Slide Over not scrollable on iOS

### ISSUE THREAD

**Issue by ShaunBaker** [tailwindlabs/tailwindui-issues#1317]
**Slide-overs**
- URL for category: https://tailwindui.com/components/application-ui/overlays/slide-overs#component-e925f5b20e7d4110cc16920f1cf1a6fc
- Component name: Contact list example

**Describe the bug**
On iOS 15.5/15.6.1 user is unable to scroll the content in Safari. Tested on Chrome iOS and it does work. Tested in iOS simulator and devices

**To Reproduce**
Minimal repo reproducing issue: https://github.com/ShaunBaker/scroll-test
Clone, install, `npm run dev`, load on iOS and attempt to scroll in Safari and Chrome

**Expected behavior**
List should be scrollable

**Screenshots**

**Browser/Device (if applicable)**
 - OS: iOS
 - Browser Safari
 - Version 15.5/15.6.1

**Additional context**
Appears to impact other Dialog based components with scroll

**Comment by ShaunBaker** [comment]
Appears to be this: https://github.com/tailwindlabs/headlessui/issues/1831

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

This should be fixed in Headless UI v1.7.1.

You can upgrade using `npm install @headlessui/react@latest`.
