### ISSUE TITLE
Add `overflow-anchor: none` to dot pattern in content sections

### ISSUE THREAD

**Issue by ruurtjan** [tailwindlabs/tailwindui-issues#1319]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/marketing/sections/content-sections
- Component name: Multiple

**Describe the bug**
When combining a "content sections" component with [Headless UI's disclosure](https://headlessui.com/vue/disclosure), browsers sometimes anchor the scroll position to the dot pattern, instead of the content itself. This causes unexpected content jumps when opening and closing the disclosures.

This issue can be fixed by adding an `overflow-anchor: none` CSS property, or a `[overflow-anchor:none]` tailwind property to the outer `div` (the one that has the `hidden` class in the component).
Also see [https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-anchor](https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-anchor)

**To Reproduce**
1. Add a Disclosure component near the dot pattern in a content section.
2. Open and close the disclosure

**Expected behavior**
The scroll position is not anchored to the dot pattern, but to the page content.

**Browser/Device (if applicable)**
 - OS: MacOS
 - Browser Chrome

**Additional context**
Took me a while to figure this one out 😅

**Comment by thecrypticace** [comment]
@ruurtjan Could you provide a reproduction showing how you use the Disclosure component with that specific Tailwind UI example? A screen recording could be helpful too — but not necessary. I'm having a bit of a difficult time understanding how to set things up so that they cause strange behavior.

**Comment by ruurtjan** [comment]
Sure, I've published a page that has fixed this issue: [https://www.nslookup.io/learning/dns-record-types/aaaa/](https://www.nslookup.io/learning/dns-record-types/aaaa/)

Scroll to the bottom of the page, then open and close the 'related questions'. It currently works as expected.

To reproduce the issue, remove the `[overflow-anchor:none]` class from a parent div of the dot pattern. Now open and close the related questions again. You'll see that they expand upwards instead of having the question heading at the same scroll position.

Let me know if this helps, or if you'd like me to record my screen.

**Comment by thecrypticace** [comment]
oh that's super helpful — I can reproduce the issue in Chrome on that page. Thanks!

**Comment by thecrypticace** [comment]
Hey, thank you for providing the reproduction. We've updated a couple of the components that we were able to reproduce the issue on by adding the `[overflow-anchor:none]` class on some of the presentational elements.

Thanks! ✨
