### ISSUE TITLE
Heading with banner image broken

### ISSUE THREAD

**Issue by drewtunney** [tailwindlabs/tailwindui-issues#1322]
**What component (if applicable)**
- https://tailwindui.com/components/application-ui/headings/page-headings#component-6fae9e848a855282e0d7fc637cb94791
- Heading with banner image: 

**Describe the bug**
Styling is broken

**To Reproduce**
1. Paste code in browser

**Expected behavior**
See the same styling as the component UI

**Screenshots**
![image](https://user-images.githubusercontent.com/4064746/190173556-b0d1647e-a736-49fb-8c8b-a6c94b8af0bb.png)

expected from website
![image](https://user-images.githubusercontent.com/4064746/190174374-8a6d05bd-ac04-4e6d-a337-a63a1e23b802.png)

**Browser/Device (if applicable)**
 - OS: chrome desktop 

Code from website

```html
<!-- This example requires Tailwind CSS v2.0+ -->
<div>
  <div>
    <img class="h-32 w-full object-cover lg:h-48" src="https://images.unsplash.com/photo-1444628838545-ac4016a5418a?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=1950&q=80" alt="">
  </div>
  <div class="mx-auto max-w-5xl px-4 sm:px-6 lg:px-8">
    <div class="-mt-12 sm:-mt-16 sm:flex sm:items-end sm:space-x-5">
      <div class="flex">
        <img class="h-24 w-24 rounded-full ring-4 ring-white sm:h-32 sm:w-32" src="https://images.unsplash.com/photo-1463453091185-61582044d556?ixlib=rb-=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=8&w=1024&h=1024&q=80" alt="">
      </div>
      <div class="mt-6 sm:flex sm:min-w-0 sm:flex-1 sm:items-center sm:justify-end sm:space-x-6 sm:pb-1">
        <div class="mt-6 min-w-0 flex-1 sm:hidden md:block">
          <h1 class="truncate text-2xl font-bold text-gray-900">Ricardo Cooper</h1>
        </div>
        <div class="justify-stretch mt-6 flex flex-col space-y-3 sm:flex-row sm:space-y-0 sm:space-x-4">
          <button type="button" class="inline-flex justify-center rounded-md border border-gray-300 bg-white px-4 py-2 text-sm font-medium text-gray-700 shadow-sm hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-pink-500 focus:ring-offset-2">
            <!-- Heroicon name: mini/envelope -->
            <svg class="-ml-1 mr-2 h-5 w-5 text-gray-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
              <path d="M3 4a2 2 0 00-2 2v1.161l8.441 4.221a1.25 1.25 0 001.118 0L19 7.162V6a2 2 0 00-2-2H3z" />
              <path d="M19 8.839l-7.77 3.885a2.75 2.75 0 01-2.46 0L1 8.839V14a2 2 0 002 2h14a2 2 0 002-2V8.839z" />
            </svg>
            <span>Message</span>
          </button>
          <button type="button" class="inline-flex justify-center rounded-md border border-gray-300 bg-white px-4 py-2 text-sm font-medium text-gray-700 shadow-sm hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-pink-500 focus:ring-offset-2">
            <!-- Heroicon name: mini/phone -->
            <svg class="-ml-1 mr-2 h-5 w-5 text-gray-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
              <path fill-rule="evenodd" d="M2 3.5A1.5 1.5 0 013.5 2h1.148a1.5 1.5 0 011.465 1.175l.716 3.223a1.5 1.5 0 01-1.052 1.767l-.933.267c-.41.117-.643.555-.48.95a11.542 11.542 0 006.254 6.254c.395.163.833-.07.95-.48l.267-.933a1.5 1.5 0 011.767-1.052l3.223.716A1.5 1.5 0 0118 15.352V16.5a1.5 1.5 0 01-1.5 1.5H15c-1.149 0-2.263-.15-3.326-.43A13.022 13.022 0 012.43 8.326 13.019 13.019 0 012 5V3.5z" clip-rule="evenodd" />
            </svg>
            <span>Call</span>
          </button>
        </div>
      </div>
    </div>
    <div class="mt-6 hidden min-w-0 flex-1 sm:block md:hidden">
      <h1 class="truncate text-2xl font-bold text-gray-900">Ricardo Cooper</h1>
    </div>
  </div>
</div>
```

**Comment by RobinMalfait** [comment]
Hey! Thank you for your PR!
Much appreciated! 🙏

This works fine as-is if you copy/paste it in Tailwind Play (https://play.tailwindcss.com/v7BnXXg10z).
It is likely that your Tailwind isn't properly configured. Make sure to setup your content paths correctly so that the file you are pasting this code in exists in the content array: https://tailwindcss.com/docs/content-configuration

**Comment by drewtunney** [comment]
thanks @RobinMalfait .

Is there something specific with this component that I could be missing in the configuration? As you can see in the code pasted below the [actions with breadcrumbs](https://tailwindui.com/components/application-ui/headings/page-headings#component-8a687a46760e105177d4a4ed39ae6d27) header seems to be loading just fine. Having a really tough time debugging this - any help would be greatly appreciated! Thank you

![image](https://user-images.githubusercontent.com/4064746/191050462-6b1e3936-284e-4958-aee6-e5ed773f8909.png)

**Comment by drewtunney** [comment]
more specifically - `h-32` on the banner image is computer as `height: auto`. `h-24` is computed to `height: 6rem`. How come `h-32` will not compute properly but `h-24` will? I've seen this behavior in other components and am not sure why it's happening. thank you very much
