### ISSUE TITLE
missing close tag for img

### ISSUE THREAD

**Issue by siddharthram** [tailwindlabs/tailwindui-issues#1324]
**What component (if applicable)**
Hero Section Simple Centered
- URL for category: https://tailwindui.com/components/marketing/sections/heroes
- Component name: Hero Section Simple centered

**Describe the bug**
Line 31 img tag is not closed
**To Reproduce**

**Expected behavior**
img tag should be closed
**Screenshots**

**Browser/Device (if applicable)**

**Additional context**

**Comment by thecrypticace** [comment]
Hey! So `img` is a [void element](https://html.spec.whatwg.org/multipage/syntax.html#void-elements) in HTML. This means it does not (and cannot) have any contents / children. Because of this it is self-closing and does not need to be written as `<img src="" />` and `<img src="">` is sufficient.
