### ISSUE TITLE
Syntax Template Theme Selector follows system when should not

### ISSUE THREAD

**Issue by miljan-aleksic** [tailwindlabs/tailwindui-issues#1325]
**Describe the bug**
Syntax Template has a Theme Selector, one of it options is System which follows the system dark/light mode. When dark or light is selected it should not follow the system, but it does, at least in MacOs.

**To Reproduce**
1. Go to https://syntax.tailwindui.com/
2. Choose Light Mode.
3. Without refreshing go to the system Appearance and switch the mode to dark.
4. The template will follow the change without respecting user selection.

**Expected behavior**
The template should respect the user selection despite the system manual or automatic switch.  It does adjust to the user selection if the page is refreshed.

**Browser/Device (if applicable)**
 - OS: MacOS Maverick
 - Browser [e.g. chrome]

**Comment by thecrypticace** [comment]
Hey we've just updated the template to fix this — thanks for the report! ✨ 

If you want to apply these changes to your own project you can download the template again and look at these files:
- `src/components/ThemeSelector.jsx`
- `src/pages/_document.jsx`

**Comment by miljan-aleksic** [comment]
It works perfect now, thank you!
