### ISSUE TITLE
Dropdown in a scrollable list

### ISSUE THREAD

**Issue by akshay-nm** [tailwindlabs/tailwindui-issues#1329]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/elements/dropdowns
- Component name: Dropdown

**Describe the bug**
Dropdowns cause the scrollable to expand. They should pop-out of the scrollable and not in it. This results in the user to scroll down to view all the options in the dropdown.

Here is a list with rows containing dropdowns: 
![db-1](https://user-images.githubusercontent.com/8887163/191471058-9d3ea065-b6d8-415d-9fa9-2b28df94a45a.png)
Here is the dropdown open: 
![db-2](https://user-images.githubusercontent.com/8887163/191471196-5272916d-1cce-4740-9d21-3a96a3d27b47.png)
Dropdown for the 2nd row causing the scrollable to expand:
![db-3](https://user-images.githubusercontent.com/8887163/191471284-b5153690-66fd-4b18-878b-01b1c4647b4a.png)
After scrolling to the bottom: 
![db-4](https://user-images.githubusercontent.com/8887163/191471358-c5993d41-b423-4bc5-a7e6-6a605abb1475.png)

I don't know if that's how the dropdowns are supposed to work. 

**To Reproduce**
1. Create a list with rows containing a dropdown element
2. Fix the height on the list container with 'overflow-auto' making it a scrollable
3. Scroll to the last element in the list
4. Open the dropdown

**Expected behavior**
Dropdowns should not affect the scrollable.

**Comment by reinink** [comment]
Hey @akshay-nm! 👋

In these situations we generally recommend using [Popper](https://popper.js.org/) to properly position the dropdown menus. This is something that the underlying library, [Headless UI](https://headlessui.dev/), supports.

You can find a working example of how to implement Popper with the Headless UI `Menu` (dropdown) component [here](https://github.com/tailwindlabs/headlessui/blob/main/packages/playground-react/pages/menu/menu-with-popper.tsx). You can find a demo of this [here](https://headlessui-react-git-main-tailwindlabs.vercel.app/menu/menu-with-popper).

We also have a example of how to implement Popper with the `Menu` component and a transition. You can find that [here](https://github.com/tailwindlabs/headlessui/blob/main/packages/playground-react/pages/menu/menu-with-transition-and-popper.tsx), and the demo for it [here](https://headlessui-react-git-main-tailwindlabs.vercel.app/menu/menu-with-transition-and-popper).

We considered adding Popper directly to Tailwind UI for situations like this, but we're concerned it's going too far with the implementation. Not everyone needs Popper for their dropdowns, it adds a bunch of extra code, and our focus is really on providing solid design patterns more than specific implementation details, so we've opted to keep things simpler for now and leave it up to the customer to decide if they'd like to implement Popper in their apps. That said, I could see us eventually adding something about Popper in the Tailwind UI documentation.

I hope that all makes sense! 🤟

**Comment by akshay-nm** [comment]
The examples work, but are using a custom implementation for `usePopper`. 
The example's version of `usePopper` can be found in the `utils` folder of the example repo, here is the [link to the hook implementation](https://github.com/tailwindlabs/headlessui/blob/main/packages/playground-react/utils/hooks/use-popper.ts)

The example version works!

This is different from the one exported from `react-popper` (official wrapper by Popper team, [link to the same](https://popper.js.org/react-popper/v2/hook/)). I wasted a couple of minutes on this. Hope this helps anyone else stumbling here.

**Comment by reinink** [comment]
@akshay-nm Glad you got it figured out! 💪
