### ISSUE TITLE
Syntax Template - Horizontal Scrollbar in Navigation (Safari/Firefox)

### ISSUE THREAD

**Issue by StevenBullen** [tailwindlabs/tailwindui-issues#1337]
**What component**
Syntax Template

**Describe the bug**
Horizontal scrollbar displayed when not required. (see screenshot)

**Screenshot**
![Screenshot 2022-09-26 at 22 42 29](https://user-images.githubusercontent.com/239862/192386004-79f1f0a0-88a2-4842-a08d-c63c253762cb.png)

**Browser/Device (if applicable)**
 - Safari (15.6.1)
 - Firefox (105.0.1)

**My Fix**
Added `overflow-x-hidden` to remove scrollbar.

**Comment by bradlc** [comment]
Hey @StevenBullen, thanks for reporting, this is now fixed 👍
