### ISSUE TITLE
Salient carousel seems offset

### ISSUE THREAD

**Issue by corysimmons** [tailwindlabs/tailwindui-issues#1344]
All these screenshots feel like they should be centered.

<img src="https://user-images.githubusercontent.com/224636/193486196-6fa3bc37-0482-4314-8c04-33b30a8dcc6b.png" width="500">

<img src="https://user-images.githubusercontent.com/224636/193486301-8cb0f63d-9deb-4bcf-928d-2007544e744c.png" width="500">

<img src="https://user-images.githubusercontent.com/224636/193486222-b2e882a9-097d-4b3c-b3a6-d57b7a716e79.png" width="500">

**Comment by RobinMalfait** [comment]
Hey! Thank you for your question!
Much appreciated! 🙏

These were designed like this, it also allows you to get a larger preview of the next card in line.
But of course, if you don't like this part you can change it to make it more centered yourself.

If you want the more centered result, then you could apply the following change:
```diff
- <div class="-mx-5 flex">
+ <div class="-mx-5 flex justify-center">
```

Hope this helps!
