### ISSUE TITLE
tailwindui Components are rendered in small size in vue3

### ISSUE THREAD

**Issue by subralog** [tailwindlabs/tailwindui-issues#1353]
i tried to copy paste a application shell component in a vue file, all are rendered fine but the size is small confined to the center of the page. how do i set the size for the application shell?

i found this note in the code sample 
``

but i unable to find the html and body tags in vue3. pls shed light on how to add these classes!

![Screenshot 2022-10-27 at 8 38 26 AM](https://user-images.githubusercontent.com/73687719/198182011-6b9c1d52-8287-40c2-8e7d-72634a50f89e.png)

**Comment by adamwathan** [comment]
Hey! So you will need to add those classes to your `html` and `body` tags but unfortunately I can’t help you do that without seeing the project. We can’t offer this type of technical support I’m afraid but if you ask this question in the Discord server someone with experience using the same tools as you might be able to help 👍🏻
