### ISSUE TITLE
Checkbox labels should be improved to enable more clickable area

### ISSUE THREAD

**Issue by patrickyan** [tailwindlabs/tailwindui-issues#1356]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/forms/sign-in-forms https://tailwindui.com/components/application-ui/forms/checkboxes
- Component name: checkbox

**Describe the bug**
1. On labels, use padding instead of margin (e.g., `pl-2` instead of `ml-2`) to make a continuous clickable area from the checkbox to the label.
2. Do not use margins on checkbox `<input>`s (see "simple list with heading"). Instead use padding on label (see above).
3. Gray subtext/description should be placed in the `<label>` so that it can also be clicked to toggle the checkbox.
4. Labels (and/or their container div) should be `block` and `grow` (when necessary) to make sure the clickable area expands to the entire region that makes sense.

**To Reproduce**
1. Go to a sample page with checkbox.
2. Try to click between the checkbox and label text.
3. Try to click label subtext/description.

**Expected behavior**
Should be able to click within a continuous area around the label text/checkbox to select the checkbox.

**Screenshots**

**Browser/Device (if applicable)**
 - n/a

**Additional context**

**Comment by ngbrown** [comment]
I was about to open an issue on this exact thing. There is a large percentage of the checkbox area on the "List with checkbox on right" that is not clickable, and that makes it difficult to use.

I ended up replacing `<div className="relative flex items-start py-4">` with `<label className="relative flex items-start py-4">`. Then removing the inner nested label. This also removes the need to generate `id` and `htmlFor` values.

Also this was mentioned in #174.

**Comment by reinink** [comment]
Hey! 👋

Thanks for this feedback. I can totally see why you might want the checkboxes to work this way.

The challenge with making the label and description all part of the hit area is that technically you don't want the description in the label from an accessibility perspective. So the workaround is to create an absolutely positioned element within the label that covers the whole desired hit area (label and description). Something like this:

```html
<div class="relative flex items-start">
  <div class="flex h-5 items-center">
    <input id="comments" aria-describedby="comments-description" name="comments" type="checkbox" class="h-4 w-4 rounded border-gray-300 text-indigo-600 focus:ring-indigo-500" />
  </div>
  <div class="relative pl-3 text-sm">
    <label for="comments" class="font-medium text-gray-700"><span class="absolute inset-0"></span>Comments</label>
    <p id="comments-description" class="text-gray-500">Get notified when someones posts a comment on a posting.</p>
  </div>
</div>
```

Here's a working demo: https://play.tailwindcss.com/HkajntKpiu?size=572x720

I think that's a totally valid approach if that's the behavior you want in your app, but I also like that the examples we ship with Tailwind UI are nice and simple, and I don't think they are technically wrong or broken.

At the end of the day if you'd prefer the larger hit areas in your own project you can absolutely modify the components to work that way. Tailwind UI components aren't set in stone, rather they are just recipes that you can change, as desired, in your own stuff.

Hope that helps and makes sense! 🤘

**Comment by patrickyan** [comment]
This only addresses (3) on the list. (1), (2), and (4) are not related to descriptions.
