### ISSUE TITLE
CSS Stylesheets with named classes using @apply

### ISSUE THREAD

**Issue by clockelliptic** [tailwindlabs/tailwindui-issues#137]
I'm loving TailwindUI so far, great stuff!

I've been wishing that the code could also be copied in the form of HTML with named CSS classes and an accompanying Stylesheet.

Why? Because DRY and extracting the style scope away from the markup scope where possible.

**Comment by Christophvh** [comment]
This is the opposite of the core principle of Tailwind. The point is to Extract fully re-usable HTML components including the utility classes inside Vue/React/Blade/.. components.  Tailwind is made to get away from named classes. It is recommended to almost have an empty stylesheet.

https://tailwindcss.com/docs/extracting-components
https://tailwindcss.com/#what-is-tailwind
