### ISSUE TITLE
New Amplify deployment forces new React version that forces new Tailwind version that forces new Postcss version that isnt working at all, im  effed and need to get my blackfriday special live.. please help

### ISSUE THREAD

**Issue by 3lonious** [tailwindlabs/tailwindui-issues#1370]
**What component (if applicable)**
- URL for category: 
- Component name: 

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Browser/Device (if applicable)**

**Additional context**

**Comment by 3lonious** [comment]
![Screen Shot 2022-11-20 at 6 14 19 AM](https://user-images.githubusercontent.com/46793692/202908176-b95f673e-7667-4f96-8551-65f08c9644d3.png)

**Comment by 3lonious** [comment]
![Screen Shot 2022-11-20 at 6 35 29 AM](https://user-images.githubusercontent.com/46793692/202908204-f8cc4abf-dab9-4ac0-9675-9a77c0dfcf49.png)

**Comment by adamwathan** [comment]
Hey! Ugh sorry, these sorts of dependency management problems are frustrating. Unfortunately this isn't the right place to get help with this, this is for reporting specific issues with the templates in Tailwind UI so I'm going to close this issue.

You could asking for help in our [Discord community](https://tailwindcss.com/discord) or in our [discussion forums](https://github.com/tailwindlabs/tailwindcss/discussions) where maybe someone with a similar setup can help you troubleshoot the problem and figure out how to get things configured correctly. Sorry I can't be more help, hope you get it figured out 🤞
