### ISSUE TITLE
Scrollbar - Detail Screen <> Multi-column inbox component

### ISSUE THREAD

**Issue by AmitMirgal** [tailwindlabs/tailwindui-issues#1372]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/page-examples/detail-screens#component-9a82234fc5cbca3875409b92effa3779
- Component name: Detail Screens/**Multi-column inbox**

**Describe the bug**
Not able to see the scrollbar
![Screen Shot 2022-11-21 at 4 09 38 PM](https://user-images.githubusercontent.com/19601060/203158706-3a851b00-21eb-42ae-8060-bbc0bc27a00b.png)

**To Reproduce**
- Copy the code and paste inside one of page that needs to render (for instance `http://localhost:8910/dashboard`)
- navigate to http://localhost:8910/dashboard
- check the inbox and message preview section, we can't see the scrollbar

**Expected behaviour**
Able to see the scrollbar within the Inbox and Message preview column
Here is the expected component suppose to be
[Detailed Screen Component](https://tailwindui.com/components/application-ui/page-examples/detail-screens#component-9a82234fc5cbca3875409b92effa3779)

**Screenshots**
![Screen Shot 2022-11-21 at 4 11 03 PM](https://user-images.githubusercontent.com/19601060/203159076-96c9dfdc-a429-4326-b544-b0a6947ed6c1.png)

As I highlighted in the image, we can't see the scrollbar in the Inbox and Message preview section

**Browser/Device (if applicable)**
 - OS: [e.g. iOS] - MacOS Monterey
 - Browser [e.g. chrome, safari] - Chrome and Brave (Tried on both)
 - Version [e.g. 22] (OS) v12.6.1, [Version 1.45.127 Chromium: 107.0.5304.110]

**Additional context**
**Side note** - Tailwind component is using with RedwoodJS
As per requested from the code I have added the following code in the html and body tag
```
<html class="h-full bg-gray-100">
<body class="h-full overflow-hidden">
     
```
tailwind.config.js
```
module.exports = {
  content: ['src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {},
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/line-clamp'),
  ],
}
```
However other tailwind components working as expected.

**Comment by reinink** [comment]
@AmitMirgal Hey! Happy to help out here.

So you didn't mention it, but I suspect that you're probably using Next.js. Next adds a `<div id="__next">` wrapper around your content which messes with this component.

The simple solution here is to add the following CSS to your project:

```css
#__next {
  @apply flex h-full flex-col;
}
```

This will ensure that this wrapper element takes up the height of the viewport, which in return will make sure the scroll areas within the component work properly.

If you're not using Next.js, let me know what you are using and I can try to help there as well.

Good luck! 💪

**Comment by AmitMirgal** [comment]
@reinink Thanks for looking into it... I am using **RedwoodJS** framework.
If you are not familiar with it here is the https://redwoodjs.com

**Comment by reinink** [comment]
@AmitMirgal Oof, sorry, not sure how I missed that. Let me do some more digging — it's possible the same kind of issue exists.

**Comment by reinink** [comment]
Okay, confirmed — same issue, just the Redwood version of it 😅

Here's how to fix it. Add the following CSS to your project:

```css
#redwood-app {
  @apply flex h-full flex-col;
}
```

That should take care of it 👍

**Comment by AmitMirgal** [comment]
thanks @reinink working as expected... thanks for your time ... I appreciate it 🙏🏽
