### ISSUE TITLE
Can't download Keynote template zip file

### ISSUE THREAD

**Issue by dayvough** [tailwindlabs/tailwindui-issues#1379]
**What component (if applicable)**
- URL for category: https://tailwindui.com/templates/keynote/download
- Component name: Keynote Template

**Describe the bug**
Once I click the download button for the Keynote template, the DigitalOcean link breaks 

<img width="778" alt="CleanShot 2022-12-07 at 10 28 00@2x" src="https://user-images.githubusercontent.com/935170/206072943-023a6d66-5afa-4f96-9081-954b43f6e393.png">

**Comment by reinink** [comment]
@dayvough Hey, sorry you bumped into this! We've actually had a couple other customers report this same issue. They were all on the Globe Telecom ISP — which seems to be blocking Digital Ocean spaces for some reason.

You can get around this by appending `?direct=true` to the template download URLs. Here are links to each of our templates:

https://tailwindui.com/templates/salient/download?direct=true
https://tailwindui.com/templates/spotlight/download?direct=true
https://tailwindui.com/templates/transmit/download?direct=true
https://tailwindui.com/templates/syntax/download?direct=true
https://tailwindui.com/templates/keynote/download?direct=true
https://tailwindui.com/templates/primer/download?direct=true
https://tailwindui.com/templates/pocket/download?direct=true

Admittedly it's kind of an annoying workaround that I hope to eventually fix in a more permanent way.

Hope that helps! 👍
