### ISSUE TITLE
Avatar vertical positioning broken after clicking back from article in Spotlight Template

### ISSUE THREAD

**Issue by rubinovitz** [tailwindlabs/tailwindui-issues#1383]
**What component (if applicable)**
- URL for category: https://tailwindui.com/templates/spotlight
- Component name: Spotlight Template

**Describe the bug**
Avatar overflows onto the site title after clicking back to home from an Article.

**To Reproduce**
This happens when you click on an Article, then click on the avatar in the article to go back home.

**Expected behavior**
The avatar should not be on top of the title, it should be above it.

**Screenshots**

<img width="381" alt="Screen Shot 2022-12-10 at 2 46 11 PM" src="https://user-images.githubusercontent.com/1807895/206878230-00559497-e208-4818-b547-b220466ca211.png">
<img width="392" alt="Screen Shot 2022-12-10 at 2 46 16 PM" src="https://user-images.githubusercontent.com/1807895/206878229-c2cb8447-bb22-4a52-b23d-019d41758b01.png">
<img width="386" alt="Screen Shot 2022-12-10 at 2 46 22 PM" src="https://user-images.githubusercontent.com/1807895/206878228-a551e804-15e2-4ab7-93f4-70bcc2d86b6a.png">

**Browser/Device (if applicable)**
 - OS:  MacOS
 - Browser Chrome
 - Version 108.0.5359.98

**Comment by reinink** [comment]
@rubinovitz Hey! Would you happen to be able to take a screen recording of this happening and post that here? I'm using MacOS and the same version of Chrome and can't reproduce this, but maybe I'm not following the same steps.

**Comment by reinink** [comment]
Hey there! I'm going to close this because I haven't heard back, but again if you want to leave a screen recording of this happening, and ideally a reproduction as a Git repo, I'd be happy to have a closer look 👍

**Comment by rubinovitz** [comment]
Hi I haven’t had time to get you a screen recording yet, should do it at
some point this week

**Comment by reinink** [comment]
@rubinovitz Okay great! Also, if you've made tweaks to the template, please provide a reproduction as a Git repo, otherwise it's really hard for us to help.

**Comment by rubinovitz** [comment]
Will do!

**Comment by rubinovitz** [comment]
Hi! So I figured out this breaks when I attempt to remove the dark mode button (either by removing '<ModeToggle/>' in Header.jsx or removing it and it's two parents.

I can post the code repo but are you sure you want me posting the template publicly?

**Comment by rubinovitz** [comment]
Hi team/ @reinink ,

still having this issue.

you can find it live at rubinovitz.com if you open incognito/first load on mobile browsers
