### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by jalaltek** [tailwindlabs/tailwindui-issues#1393]
Hi. It would be great if you could make your component code and templates available in typescript as well as javascript, that would save us a lot of time.

**Comment by adamwathan** [comment]
Thanks for the suggestion! We use this issue tracker strictly for bug reports so going to close this but appreciate the feedback.

**Comment by MegaMaddin** [comment]
> Thanks for the suggestion! We use this issue tracker strictly for bug reports so going to close this but appreciate the feedback.

@adamwathan Where would I send this as a feature request?

**Comment by adamwathan** [comment]
@MegaMaddin We don't have any real official feature request intake form or public roadmap or anything, best bet is just tweet at us to share the idea 👍

**Comment by MegaMaddin** [comment]
> @MegaMaddin We don't have any real official feature request intake form or public roadmap or anything, best bet is just tweet at us to share the idea 👍

Done 😉
