### ISSUE TITLE
Feature Request: Vertical Divider

### ISSUE THREAD

**Issue by braden-w** [tailwindlabs/tailwindui-issues#1394]
**Vertical Divider**
- [URL for category (Dividers)](https://tailwindui.com/components/application-ui/layout/dividers)

**Describe the feature request**
Have a "vertical divider with label" component that naturally follows the "divider with label component"

**Divider with Label**
```html
<div class="relative">
  <div class="absolute inset-0 flex items-center" aria-hidden="true">
    <div class="w-full border-t border-gray-300"></div>
  </div>
  <div class="relative flex justify-center">
    <span class="bg-white px-2 text-sm text-gray-500">Continue</span>
  </div>
</div>
```

**Vertical divider with Label**
Notice how similar this is to the horizontal one:
```html
<div class="relative flex items-center">
  <div class="absolute inset-0 flex justify-center" aria-hidden="true">
    <div class="h-full border-l border-gray-300" />
  </div>
  <div class="relative">
    <span class="bg-white px-2 text-sm text-gray-500">or</span>
  </div>
</div>
```

**Expected behavior**

**Screenshots**
Horizontal divider:
![CleanShot 2022-12-27 at 00 24 18](https://user-images.githubusercontent.com/13159333/209636417-1cf18239-74d6-4676-846b-09c9dfc3a65a.jpg)

Vertical divider in action:
![CleanShot 2022-12-27 at 00 26 41](https://user-images.githubusercontent.com/13159333/209636757-755c413b-4e5d-405b-ba3b-a32b702c5637.jpg)

**Comment by reinink** [comment]
Thanks for the suggestion! We use this issue tracker strictly for bug reports so going to close this but appreciate the feedback.
