### ISSUE TITLE
Spotlight LinkedIn Icon Missing Aria Attribute

### ISSUE THREAD

**Issue by braden-w** [tailwindlabs/tailwindui-issues#1397]
**What component (if applicable)**
- URL for category: https://tailwindui.com/templates/spotlight
- Component name: Spotlight

**Describe the bug**
LinkedIn Icon seems to be missing Aria Attribute while all other icons have it.

**Screenshots**
![CleanShot 2023-01-02 at 00 18 38](https://user-images.githubusercontent.com/13159333/210207827-4f0d6ddf-fe63-4aea-8aef-cf2c716c9e0b.jpg)

**Browser/Device (if applicable)**
 - OS: MacOS
 - Browser: Brave
 - [Version 1.46.144 Chromium: 108.0.5359.128 (Official Build) (x86_64)](https://brave.com/latest/)

**Additional context**

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

This should be fixed and is live now. If you want to apply this change yourself, then you can apply this diff:

```diff
 export function LinkedInIcon(props) {
   return (
-    <svg viewBox="0 0 24 24" {...props}>
+    <svg viewBox="0 0 24 24" aria-hidden="true" {...props}>
       <path d="M18.335 18.339H15.67v-4.177c0-.996-.02-2.278-1.39-2.278-1.389 0-1.601 1.084-1.601 2.205v4.25h-2.666V9.75h2.56v1.
     </svg>
   )
```
