### ISSUE TITLE
Protocol Template doesn't render table markdown element

### ISSUE THREAD

**Issue by bomshteyn** [tailwindlabs/tailwindui-issues#1398]
**What component (if applicable)**
- URL for category: https://tailwindui.com/templates/protocol
- Component name: Protocol Template

**Describe the bug**
Trying to render a table element written in markdown instead of rendering a html table it just prints it out as text.

**Test Table**:
```markdown
| Name   | Type   | Description          |
|--------|--------|----------------------|
| `name` | string | Name of the resource |
| `path` | string | Path to the resource |
```

**expecting**:
| Name   | Type   | Description          |
|--------|--------|----------------------|
| `name` | string | Name of the resource |
| `path` | string | Path to the resource |

**Screenshot of Actual Result**

![Screen Shot 2023-01-02 at 3 33 18 PM](https://user-images.githubusercontent.com/4259699/210276006-64f8bbce-9ff3-4a4b-bc76-4006bfa420c0.png)

**Comment by reinink** [comment]
Hey! Happy to help out here.

Out of the box MDX supports the standard markdown syntax ([CommonMark](https://spec.commonmark.org/current/)). That means things like tables, autolinking, strikethroughs and other features that you can find in [GitHub flavored markdown](https://github.github.com/gfm/) are not enabled by default.

No worries though, you can enable these for your project using the [remark-gfm](https://github.com/remarkjs/remark-gfm) plugin. Here's how:

First install the `remark-gfm` package:

```sh
npm install remark-gfm
```

Next, add this plugin to the list of remark plugins in the `./mdx/remark.mjs` file:

```diff
  import { mdxAnnotations } from 'mdx-annotations'
+ import remarkGfm from 'remark-gfm'
  
- export const remarkPlugins = [mdxAnnotations.remark]
+ export const remarkPlugins = [mdxAnnotations.remark, remarkGfm]
```

Now if you restart your build you should be able to use tables (and other GFM features) in the Protocol template 👍

<img width="1202" alt="image" src="https://user-images.githubusercontent.com/882133/210277525-71777ac2-83a4-4da3-bd27-d2824572cb63.png">

**Comment by bomshteyn** [comment]
@reinink thank you!

**Comment by reinink** [comment]
Hey just an update here, I've updated the Protocol template to have `remark-gfm` installed by default now.

If you download the latest version of the template from the Tailwind UI website you'll see this 👍
