### ISSUE TITLE
[feature request] multi-select tokens

### ISSUE THREAD

**Issue by dudo** [tailwindlabs/tailwindui-issues#1400]
The discord mentioned that I should send feature requests here. Hopefully this is the right place 😅 

Any plans to provide some multi-select menu templates? Something like
 
![Screenshot 2023-01-03 at 18 17 21](https://user-images.githubusercontent.com/2963800/210472662-d89e3cde-3f65-4071-be6a-2f16b385d7a8.png)

That's from https://github.com/onesine/react-tailwindcss-select, but I'm wondering if you had any thoughts on the matter.

Thanks!

**Comment by reinink** [comment]
Thanks for the suggestion! We use this issue tracker strictly for bug reports so going to close this but appreciate the feedback.

That said, if it helps, we do have an example of how to build a component like this using our Headless UI library, which you find here:

https://headlessui-react-git-main-tailwindlabs.vercel.app/combobox/multi-select

<img width="702" alt="image" src="https://user-images.githubusercontent.com/882133/210585093-87c8e862-478b-45ea-8db1-2e5843e99ea7.png">

You can find the source code for this example component here:

- **Vue:** https://github.com/tailwindlabs/headlessui/blob/main/packages/playground-vue/src/components/combobox/multi-select.vue
- **React:** https://github.com/tailwindlabs/headlessui/blob/main/packages/playground-react/pages/combobox/multi-select.tsx

Hope that helps!

**Comment by dudo** [comment]
Super helpful! Thanks, Jonathan =)

I've paid for access to tailwindUI. Would it be a stretch to add that example to this page https://tailwindui.com/components/application-ui/forms/comboboxes ?

**Comment by TimVervers** [comment]
+1 for adding this to the page that @dudo linked!

**Comment by mattddean** [comment]
> You can find the source code for this example component here:
> 
> * **Vue:** https://github.com/tailwindlabs/headlessui/blob/main/packages/playground-vue/src/components/combobox/multi-select.vue
> * **React:** https://github.com/tailwindlabs/headlessui/blob/main/packages/playground-react/pages/combobox/multi-select.tsx
> 
> Hope that helps!

Looks like these examples have moved:
- Vue: https://github.com/tailwindlabs/headlessui/blob/main/playgrounds/vue/src/components/combobox/multi-select.vue
- React: https://github.com/tailwindlabs/headlessui/blob/main/playgrounds/react/pages/combobox/multi-select.tsx

**Comment by YeyuanNielson1** [comment]
> Thanks for the suggestion! We use this issue tracker strictly for bug reports so going to close this but appreciate the feedback.
> 
> That said, if it helps, we do have an example of how to build a component like this using our Headless UI library, which you find here:
> 
> https://headlessui-react-git-main-tailwindlabs.vercel.app/combobox/multi-select
> 
> <img alt="image" width="702" src="https://user-images.githubusercontent.com/882133/210585093-87c8e862-478b-45ea-8db1-2e5843e99ea7.png">
> 
> You can find the source code for this example component here:
> 
> * **Vue:** https://github.com/tailwindlabs/headlessui/blob/main/packages/playground-vue/src/components/combobox/multi-select.vue
> * **React:** https://github.com/tailwindlabs/headlessui/blob/main/packages/playground-react/pages/combobox/multi-select.tsx
> 
> Hope that helps!

Thank you for the demo and links! https://github.com/tailwindlabs/headlessui/blob/main/playgrounds/react/pages/combobox/multi-select.tsx
I looked into it and wonder if you can make it consistent on removing an item. 
When the listbox is open, if you unselect a selected option from the list, the listbox would stay open; but if you click on the x button of the item while the listbox is open, the listbox would immediately close. 

Could you let me know how you could handle it? I used my own state to track isOpen and when to setIsOpen to true or false for listbox with multiple, but I haven't got that to work with this combobox multiple. Please advise. Thank you!
