### ISSUE TITLE
UI does not look like the one on website

### ISSUE THREAD

**Issue by dlouise** [tailwindlabs/tailwindui-issues#1401]
**What component (if applicable)**
- Application UI
- [Card layout with sidebar](https://tailwindui.com/components/application-ui/page-examples/home-screens#component-d7cea65e442e0c2c85f158472dd2a846)

**Describe the bug**
UI doesn't look the same

**To Reproduce**
Added to my react app, updated ts.config as specified

should look like:

<img width="1370" alt="Screen Shot 2023-01-05 at 10 27 25 PM" src="https://user-images.githubusercontent.com/3881973/210746634-3818e4ac-ed04-476f-9a6f-a86bea12c617.png">

But it looks like this:

<img width="1662" alt="Screen Shot 2023-01-05 at 10 22 57 PM" src="https://user-images.githubusercontent.com/3881973/210746545-5cb1ab94-fa07-4277-bae2-795220dd6f04.png">

Weird content layout.
Links in side nav are underlined etc.
Weird spacing.

**Additional context**
What am I missing

**Comment by reinink** [comment]
@dlouise Glad you got it figured out! 🙌
