### ISSUE TITLE
Protocol template; HTML attributes in JSX format icons

### ISSUE THREAD

**Issue by carlgleisner** [tailwindlabs/tailwindui-issues#1402]
**What component (if applicable)**
- URL for category: https://tailwindui.com/templates/protocol
- Component name: CalendarIcon, FolderIcon, MagnifyingGlassIcon

**Describe the bug**
The SVG:s have HTML attributes despite being in JSX, i.e. should be fixed by `stroke-linecap` -> `strokeLinecap` etc.

I think the above is enough 💪

**Comment by reinink** [comment]
Hey! You're right, this was wrong in the `<CalendarIcon>`, `<FolderIcon>` and `<MagnifyingGlassIcon>` icons.

I just fixed this and published an updated version of the template.

Thanks for the heads up! 💪
