### ISSUE TITLE
Template: Protocol - Support yarn

### ISSUE THREAD

**Issue by cbmono** [tailwindlabs/tailwindui-issues#1403]
**What component**
- URL for category: https://tailwindui.com/templates
- Component name: [Protocol](https://tailwindui.com/templates/protocol)

**Context**
I need to use [Protocol](https://tailwindui.com/templates/protocol) as part of a larger [monorepo](https://turbo.build/repo/docs/getting-started/create-new) project with [yarn workspaces](https://classic.yarnpkg.com/lang/en/docs/workspaces/) and [turborepo](https://turbo.build/repo).

**Describe the bug**
Using `yarn install` instead of `npm install` breaks the app:
1. You get missing **Import** errors for all `/src/pages/*.mdx` files 
     (easy to fix: add `import { <Component> } from '@/components/<Component>';` where required)
2. After fixing error number 1, you get **Hydration** errors for Markdown specific syntax
    (mainly happening for `## headings` and ` ```<language> ...``` ` blocks)

**Steps to reproduce the behavior:**
1. Download the latest version of [Protocol](https://tailwindui.com/templates/protocol)
2. Run `yarn install`
3. Run `cp .env.example .env.local`
4. Run `yarn dev`
5. Open [http://localhost:3000](http://localhost:3000)
6. See _missing import_ errors
7. Edit `/src/pages/index.mdx` and add `import { Button } from '@/components/Button';`
8. See _Hydration_ errors
 
**Expected behavior**
A working app with `yarn`. (the app does work when using `npm`)

**Screenshots**
1. Missing import errors
<img width="600" alt="image" src="https://user-images.githubusercontent.com/352146/212471324-6ad95bac-4dd0-486b-ba6b-fdbd58ceaf1a.png">

2. Hydration errors
<img width="600" alt="image" src="https://user-images.githubusercontent.com/352146/212471423-421dddc5-2a44-4ee4-933e-7b85e68e67aa.png">

**Browser/Device**
 - OS: macOS Ventura (v13.0.1)
 - Browser: Chrome (v108)
 - Node: v19.0.1
 - yarn: 1.22.19
 - npm: 9.2.0

**Comment by bradlc** [comment]
Hey @cbmono. Thanks for reporting this. We have updated the template so that it is compatible with Yarn. For reference the fix was to add `providerImportSource` to the MDX config:

```diff
  const withMDX = nextMDX({
    options: {
      remarkPlugins,
      rehypePlugins,
      recmaPlugins,
+     providerImportSource: '@mdx-js/react',
    },
  })
```

**Comment by cbmono** [comment]
Fantastic. Thanks, @bradlc.

(btw, `package-lock.json` was commited and is now part of the new download file)
