### ISSUE TITLE
E-commerce component with tabs needs js but say so

### ISSUE THREAD

**Issue by HN23** [tailwindlabs/tailwindui-issues#1404]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/ecommerce/components/product-overviews#component-a4287d3928b87e3ac5c04af49bc062a8
- Component name: E-Commerce

**Describe the bug**
The components usually have a 'Requires JS' tag along with information on transisitons/entry/exit if it requires JS, but the above component does not specify any. So when you copy/paste the code, the tabs are just expanded.

**To Reproduce**
1. Copy the code and paste into your project with no further changes
2. Click on any of the tabs (eg. FAQ, or License)

**Expected behavior**
The relevant content is shown and others are hidden

**Browser/Device (if applicable)**
 - OS: Linux (Ubuntu 22.04) 
 - Browser: Chrome
 - Version: Version 108.0.5359.98 (Official Build) (64-bit)

**Comment by bradlc** [comment]
Hey @HN23. You're right, this component should have the "Requires JS" tag 👍 This has now been added, thanks for bringing it to our attention.

Check out the [documentation](https://tailwindui.com/documentation#using-html-and-your-own-js) if you're looking to use the HTML version with your own JavaScript. Alternatively, if you're using [React](https://tailwindui.com/documentation#using-react) or [Vue](https://tailwindui.com/documentation#using-vue) then those versions of the component are already fully interactive and accessible via [Headless UI](https://headlessui.dev).
