### ISSUE TITLE
in remix framework, components are not displaying proper visual behaviour - mostly ecommerce components

### ISSUE THREAD

**Issue by overdrive-dev** [tailwindlabs/tailwindui-issues#1409]
**What component (if applicable)**
- URL for category: 
- Component name: 

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Browser/Device (if applicable)**

**Additional context**

**Comment by overdrive-dev** [comment]
it was my error, a

**Comment by reinink** [comment]
@overdrive-dev Awesome, glad you got it figured out! 💪
