### ISSUE TITLE
SaaS Billing page

### ISSUE THREAD

**Issue by viperfx** [tailwindlabs/tailwindui-issues#141]
**Screenshots**
N/A - Will add as I find good examples.

**Additional context**
- uses the multiple pricing plan UI.
- takes into account how pricing per unit could work. e.g. per seat.
- able to select yearly or monthly plan

**Extension**
Takes into account upgrade. E.g. from 5 units to 10 units.

**Comment by simonswiss** [comment]
We have a lot of requests for e-commerce / billing UI components, and this is something we're planning to work on.

For now, consolidating this request with the other ones at #268, thanks for your suggestion! 👍
