### ISSUE TITLE
Keynote template renders: Unhandled Runtime Error Error: Hydration failed because the initial UI does not match what was rendered on the server.

### ISSUE THREAD

**Issue by mattruby** [tailwindlabs/tailwindui-issues#1410]
**Keynote template**

- URL for category: https://tailwindui.com/templates/keynote
- Component name: Probably `Tab`

**Describe the bug**

The error message window is shown with the hydration error.  And the following is shown in the console:
```
next-dev.js?c188:20 Warning: Prop `aria-selected` did not match. Server: "true" Client: "false"
    at button
    at eval (webpack-internal:///./node_modules/.pnpm/@headlessui+react@1.7.8_biqbaboplfbrettd7655fr4n2y/node_modules/@headlessui/react/dist/components/tabs/tabs.js:20:6088)
    at div
    at div
    at div
    at div
    at eval (webpack-internal:///./node_modules/.pnpm/@headlessui+react@1.7.8_biqbaboplfbrettd7655fr4n2y/node_modules/@headlessui/react/dist/components/tabs/tabs.js:20:5646)
    at div
    at div
    at eval (webpack-internal:///./node_modules/.pnpm/@headlessui+react@1.7.8_biqbaboplfbrettd7655fr4n2y/node_modules/@headlessui/react/dist/components/tabs/tabs.js:20:3131)
    at div
    at Container (webpack-internal:///./src/components/Container.jsx:11:11)
    at section
    at Speakers (webpack-internal:///./src/components/Speakers.jsx:241:58)
    at main
    at Home
    at App (webpack-internal:///./src/pages/_app.jsx:15:11)

```

**To Reproduce**

1. download the keynote template
2. Run `pnpm i' or another package manager
3. Run `pnpm dev'
4. Open: http://localhost:3001/# or http://localhost:3000/#
5. View the error

**Expected behavior**

Not have hydration errors when viewing a fresh template

**Screenshots**

<img width="782" alt="CleanShot 2023-01-30 at 22 37 22@2x" src="https://user-images.githubusercontent.com/142194/215666568-b5335797-3466-4b13-9799-c12589cb4302.png">

<img width="728" alt="CleanShot 2023-01-30 at 22 38 52@2x" src="https://user-images.githubusercontent.com/142194/215666764-bbccdde2-3798-4562-bed7-5272875abe14.png">

![CleanShot 2023-01-30 at 22 39 55@2x](https://user-images.githubusercontent.com/142194/215666915-49021bea-3014-4edf-9177-c7f36b471bb5.png)

**Browser/Device (if applicable)**
 - OS: Mac Ventura
 - Browser Chrome
 - Version 109.0.5414.87 (Official Build) (x86_64)

**Additional context**

Unhandled Runtime Error
Error: Hydration failed because the initial UI does not match what was rendered on the server.

See more info here: https://nextjs.org/docs/messages/react-hydration-error

Call Stack
throwOnHydrationMismatch
node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom.development.js (12507:0)
tryToClaimNextHydratableInstance
node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom.development.js (12535:0)
updateHostComponent
node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom.development.js (19902:0)
beginWork
node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom.development.js (21618:0)
HTMLUnknownElement.callCallback
node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom.development.js (4164:0)
Object.invokeGuardedCallbackDev
node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom.development.js (4213:0)
invokeGuardedCallback
node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom.development.js (4277:0)
beginWork$1
node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom.development.js (27451:0)
performUnitOfWork
node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom.development.js (26557:0)
workLoopSync
node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom.development.js (26466:0)
renderRootSync
node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom.development.js (26434:0)
performConcurrentWorkOnRoot
node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom.development.js (25738:0)
workLoop
node_modules/.pnpm/scheduler@0.23.0/node_modules/scheduler/cjs/scheduler.development.js (266:0)
flushWork
node_modules/.pnpm/scheduler@0.23.0/node_modules/scheduler/cjs/scheduler.development.js (239:0)
MessagePort.performWorkUntilDeadline
node_modules/.pnpm/scheduler@0.23.0/node_modules/scheduler/cjs/scheduler.development.js (533:0)

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

This is an issue in Headless UI that has been fixed. You should be able to run `pnpm add @headlessui/react@latest` to resolve your issue. Also make sure that when you update, that you are on the latest version and that you aren't accidentally stuck on an older version.

I also updated the templates themselves to use the latest version of Headless UI. 

Hope this helps, thanks!
