### ISSUE TITLE
table is not responsive and we need it to be for our company website

### ISSUE THREAD

**Issue by firasmlt** [tailwindlabs/tailwindui-issues#1411]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/lists/tables
- Component name: With avatars and multi-line content

the problem is that this component is not responsive.

**Comment by reinink** [comment]
Hey! Sorry you're having trouble with this component, but it definitely should be responsive. I just tested it out to make sure, and it seems to be working:

https://user-images.githubusercontent.com/882133/215770014-3a5488d4-7801-4d5f-b05d-b2b95ff79d8c.mov

This particular component uses horizontal scrolling on mobile screen sizes, but we also provide a couple alternative approaches for mobile which you might want to check out:

- [With stacked columns on mobile](https://tailwindui.com/components/application-ui/lists/tables#component-e56f750c63d4e53a24f5f0bf9fd7b52a)
- [With hidden columns on mobile](https://tailwindui.com/components/application-ui/lists/tables#component-3b180d3192f5b442c58f58367258c15b)

If you're still having issues, feel free to provide a minimal reproduction as a Git repo, and I'll happily have a closer look.

Good luck! 💪
