### ISSUE TITLE
forms don't support right-to-left 

### ISSUE THREAD

**Issue by firasmlt** [tailwindlabs/tailwindui-issues#1413]
**What component (if applicable)**
- URL for category: 
- https://tailwindui.com/components/application-ui/forms/form-layouts

**Describe the bug**
the form components don't support right-to-left text (text-right)

**Comment by reinink** [comment]
Hey! You're right, Tailwind UI doesn't currently have built-in RTL support. I think that could be a great improvement to the product and something for us to consider in the future.

In the meantime if you'd like to use Tailwind UI components on a RTL-only website, you'll need to tweak the components a little. This will mostly involve adjusting things like margins and paddings.

For example, consider this part of the [Labels on left](https://tailwindui.com/components/application-ui/forms/form-layouts#component-cc5bee94bc88387c2511b0e5c3dfffef) form component:

<img width="659" alt="image" src="https://user-images.githubusercontent.com/882133/219692394-aff91e29-34aa-4d02-a5b0-28fcbd1a587c.png">

Without any RTL changes (other than setting `dir="rtl"`), the button and icon get pushed up against each other:

<img width="662" alt="image" src="https://user-images.githubusercontent.com/882133/219694122-f3c732b8-07f8-45e1-8274-546fbe3dfab9.png">

You can fix this by swapping the `ml-5` class with a `mr-5` class on the button:

```diff
  <div class="sm:grid sm:grid-cols-3 sm:items-center sm:gap-4 sm:border-t sm:border-gray-200 sm:pt-5">
    <label for="photo" class="block text-sm font-medium text-gray-700">Photo</label>
    <div class="mt-1 sm:col-span-2 sm:mt-0">
      <div class="flex items-center">
        <span class="h-12 w-12 overflow-hidden rounded-full bg-gray-100">
          <svg class="h-full w-full text-gray-300" fill="currentColor" viewBox="0 0 24 24">
            <path d="M24 20.993V24H0v-2.996A14.977 14.977 0 0112.004 15c4.904 0 9.26 2.354 11.996 5.993zM16.002 8.999a4 4 0 11-8 0 4 4 0 018 0z"></path>
          </svg>
        </span>
-       <button type="button" class="ml-5 rounded-md border border-gray-300 bg-white py-2 px-3 text-sm font-medium leading-4 text-gray-700 shadow-sm hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2">Change</button>
+       <button type="button" class="mr-5 rounded-md border border-gray-300 bg-white py-2 px-3 text-sm font-medium leading-4 text-gray-700 shadow-sm hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2">Change</button>
      </div>
    </div>
  </div>
```

That will ensure that there is proper margin set between the icon and the "Change" button:

<img width="660" alt="image" src="https://user-images.githubusercontent.com/882133/219693158-00f460c5-b04b-4722-b204-6cee510c0110.png">


If you're working on a site that needs to support *both* LTR and RTL, you can use the the `rtl` and `ltr` modifiers (https://tailwindcss.com/docs/hover-focus-and-other-states#rtl-support) for this.

Using the same example as before, add a `rtl:mr-5` class to the button to add a right-margin in RTL mode:

```diff
  <div class="sm:grid sm:grid-cols-3 sm:items-center sm:gap-4 sm:border-t sm:border-gray-200 sm:pt-5">
    <label for="photo" class="block text-sm font-medium text-gray-700">Photo</label>
    <div class="mt-1 sm:col-span-2 sm:mt-0">
      <div class="flex items-center">
        <span class="h-12 w-12 overflow-hidden rounded-full bg-gray-100">
          <svg class="h-full w-full text-gray-300" fill="currentColor" viewBox="0 0 24 24">
            <path d="M24 20.993V24H0v-2.996A14.977 14.977 0 0112.004 15c4.904 0 9.26 2.354 11.996 5.993zM16.002 8.999a4 4 0 11-8 0 4 4 0 018 0z"></path>
          </svg>
        </span>
-       <button type="button" class="ml-5 rounded-md border border-gray-300 bg-white py-2 px-3 text-sm font-medium leading-4 text-gray-700 shadow-sm hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2">Change</button>
+       <button type="button" class="ml-5 rtl:mr-5 rounded-md border border-gray-300 bg-white py-2 px-3 text-sm font-medium leading-4 text-gray-700 shadow-sm hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2">Change</button>
      </div>
    </div>
  </div>
```

You can find live demos of these examples here: https://play.tailwindcss.com/MjLLjeTMeD

You might need to make some other changes too — I'm not personally super familiar with RTL languages, but hopefully this gives you the right idea either way. And this will actually all become even easier in the next version of Tailwind CSS, which we're planning to add logical property support to.

I hope that helps! 💪
