### ISSUE TITLE
Type error: Type 'ExoticComponent<{ children?: ReactNode; }>' is not assignable to type

### ISSUE THREAD

**Issue by jbpapp** [tailwindlabs/tailwindui-issues#1414]
I'm trying to use a [TailwindUI element](https://tailwindui.com/components/ecommerce/components/store-navigation#component-05d207688239bbe040029b5bfa5ddf92) in a .tsx file. When running the `yarn run dev` command everything's fine, but when I try to run the `yarn run prod` the build is failed with the following error.
Tried to Google it, but couldn't find anything.

Do you have any idea what might be the issue here?

```
Type error: Type 'ExoticComponent<{ children?: ReactNode; }>' is not assignable to type '((string | Element) & ExoticComponent<{ children?: ReactNode; }>) | undefined'.
  Type 'ExoticComponent<{ children?: ReactNode; }>' is not assignable to type 'string & ExoticComponent<{ children?: ReactNode; }>'.
    Type 'ExoticComponent<{ children?: ReactNode; }>' is not assignable to type 'string'.

  32 |     <div className="bg-white">
  33 |       {/* Mobile menu */}
> 34 |       <Transition.Root show={open} as={Fragment}>
     |                                    ^
  35 |         <Dialog as="div" className="relative z-40 lg:hidden" onClose={setOpen}>
  36 |           <Transition.Child
  37 |             as={Fragment}                              ^
```

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

Can you attach a minimal reproduction repo so that we can take a look?

**Comment by jbpapp** [comment]
Hi @RobinMalfait,

Unfortunately, I can't share the repo, but I could show it to you via screen share. I know it is not ideal, but that's all I can do. 😕

**Comment by RobinMalfait** [comment]
@jbpapp I understand that sharing your work repo is not possible. But can you extract the necessary parts to reproduce it in a public repo / CodeSandbox?

Showing the repo via screen share is one thing, but unfortunately not really ideal because then it is way harder to debug / play with solutions. Reproducing it as actual code that I can debug / play with is much better. Hope that makes sense!

**Comment by jbpapp** [comment]
Hey @RobinMalfait
I figured out the issue, we had some misconfiguration in the repo. Thank you for being so helpful! Much appreciated.

**Comment by RobinMalfait** [comment]
Beautiful, glad you figured it out! If there are other issues feel free to open a new issue!
