### ISSUE TITLE
Centered Content sections - even on installing typography not displaying correctly

### ISSUE THREAD

**Issue by vaishkhullar** [tailwindlabs/tailwindui-issues#1416]
**What component (if applicable)**
[- URL for category: ] (https://tailwindui.com/components/marketing/sections/content-sections)
- Component name: centred content sections

**Describe the bug**

Content is not being reproduced in the same way as shown in the code. The prose class doesn't seem to be applying even after installing the tailwind typography plugin.  

**To Reproduce**

**Expected behavior**

**Screenshots**

**Browser/Device (if applicable)**
![Screenshot from 2023-02-12 21-03-30](https://user-images.githubusercontent.com/34738808/218336980-4e121497-89f5-40bb-b245-382ad4b25bc8.png)

**Additional context**

**Comment by adamwathan** [comment]
Hey! Can you provide a reproduction? It seems like the plugin isn’t properly configured based on that screenshot, so would be helpful to be able to see how you’ve got everything set up.

**Comment by vaishkhullar** [comment]
Hey Adam, sure thing. So I copied the code from the component and then I did:

`
 npm install - D 
`

And added this line of code to my config file:
`
    plugins: [
      require("@tailwindcss/forms"),
      require("@tailwindcss/typography"),
    ],
  
`

(Please see attached my screenshot of the full code for the config file). Sorry I'm new to tailwind and coding in general (less than 1 year) so still very much learning. 
![Screenshot from 2023-02-12 22-02-52](https://user-images.githubusercontent.com/34738808/218340006-36cb6fa9-92e4-4831-ab9f-0eb4c8b02174.png)

**Comment by vaishkhullar** [comment]
@adamwathan

**Comment by adamwathan** [comment]
Okay perfect, so the problem is your `plugins` key is in the wrong place. You have it under `theme` but it needs to be top level. Pull that out one level and everything should work 👍🏻

**Comment by vaishkhullar** [comment]
Right - that's perfect, thank you so much for the help. I'm really enjoying using this UI library. Hopefully once I'm better in the future I can contribute to this :) 

Have a good evening! :)
