### ISSUE TITLE
overflow-wrap ignored within CodeGroup component

### ISSUE THREAD

**Issue by wmelton** [tailwindlabs/tailwindui-issues#1418]
**What component (if applicable)**
- URL for category: https://tailwindui.com/templates/protocol
- Component name: <CodeGroup>

**Describe the bug**
The easiest way to see this is within the Protocol template you sell. If you look at any CodeGroup example where you're documenting, for example, an API response that has content wider than the code block, it gets cutoff and a horizontal scrollbar appears.

**Expected behavior**
Ideally, there would be a way to pass a prop to the `<CodeGroup>` component itself, or at worst, a way to get tailwind to respond to a CSS style change (so far it will not respond to any word-break, overflow-wrap, etc. styles) so that code examples could wrap instead of horizontal scroll if a developer wanted it to.

**Screenshots**
:-( 
![image](https://user-images.githubusercontent.com/1544125/219369922-d2657f14-7a18-4ef4-b735-bac897490a6f.png)

**Browser/Device (if applicable)**
 - OS: Mac
 - Browser: Chrome
 - Version: LTS

**Additional context**
Love the product overall. Just looking for a way to fix layout things like this and haven't managed it yet.

**Comment by reinink** [comment]
@wmelton Hey! Yeah, there are way too many ways to control whitespace behavior in CSS 😅 The utility you're looking for is `whitespace-pre-wrap`.

It's pretty easy to update the code blocks in the Protocol template to wrap. You'll need to make a small tweak to line 129 of the `src/components/Code.jsx` file:

```diff
# src/components/Code.jsx
- <pre className="overflow-x-auto p-4 text-xs text-white">{children}</pre>
+ <pre className="overflow-x-auto whitespace-pre-wrap p-4 text-xs text-white">{children}</pre>
```

You could even go a step further and add `break-words` as well, just in case of long words (ie. a url) that you want to forcibly break (wrap):

```diff
# src/components/Code.jsx
- <pre className="overflow-x-auto p-4 text-xs text-white">{children}</pre>
+ <pre className="overflow-x-auto whitespace-pre-wrap break-words p-4 text-xs text-white">{children}</pre>
```

Hope that helps! 💪

**Comment by wmelton** [comment]
@reinink nailed it. Man that was easy lol. Thanks a ton. You guys rock.
