### ISSUE TITLE
Input focus keyboard bug (scroll position) on Application Sidebar layout

### ISSUE THREAD

**Issue by vvo** [tailwindlabs/tailwindui-issues#142]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/application-shells/sidebar
- Component name: Light sidebar with light background

**Describe the bug**
On iOS 13.1 Safari mobile, if you have any input inside the main content, when focused, the iPhone will scroll to show the keyboard. When the keyboard will hide/input blur then the scroll position will not be the initial one.

**To Reproduce**
1. Use the default code of the Light sidebar with light background
2. Add some text to the main content and an input
3. Note the current scroll position (top)
4. Focus the input, keyboard opens (and scroll moves, that's expected)
5. Click on done or any button that will hide the keyboard
5. Note the scroll position (no more top), not expected

**Expected behavior**
The scroll position should go back to the initial (before focus).

**Screenshots**
![RPReplay_Final1586523159](https://user-images.githubusercontent.com/123822/78992717-3b37fa80-7b3c-11ea-8795-dfcbf0d55032.gif)

**Browser/Device (if applicable)**
 - OS: iOS
 - Browser Safari
 - Version 13.1

**Additional context**
The bug is caused by the "h-screen" property here:
![image](https://user-images.githubusercontent.com/123822/78992800-6f132000-7b3c-11ea-9b81-0b07d8e83f66.png)

The behavior should be:
![RPReplay_Final1586523922](https://user-images.githubusercontent.com/123822/78992950-d0d38a00-7b3c-11ea-8661-9ff489113d35.gif)

(I just removed the h-screen class).

Let me know what you think!

PS: I have a live example on CodeSandbox but not sure it's ok to post it here, let me know.

**Comment by vvo** [comment]
better fix: replacing h-screen with max-h-screen fixes all issues and keep the mobile menu always visible (removing h-screen altogether triggers a buggy mobile menu open icon)

**Comment by jasonlbeggs** [comment]
Hey @vvo! Can you DM me a link to the CodeSanbox on Twitter? My username is jasonlbeggs there too. I'll take a look and implement a solution to the issue.
