### ISSUE TITLE
Application Shell component variant has space in CSS transition comment, leading to potential issues

### ISSUE THREAD

**Issue by joelzwarrington** [tailwindlabs/tailwindui-issues#1420]
**What component (if applicable)**
- URL for category: [Application Shells - Multi Column](https://tailwindui.com/components/application-ui/application-shells/multi-column)
- Component name: [Full-width with narrow sidebar](https://tailwindui.com/components/application-ui/application-shells/multi-column#component-6e22fa5715141e2f842a9c887bcfb7a3)

**Describe the bug**

In the comment block for HTML version, there is a space in the CSS:

```diff
 <!--
   Mobile menu, toggle classes based on menu state.

   Entering: "transition ease-out duration-150 sm:ease-in-out sm:duration-300"
     From: "transform opacity-0 scale-110 sm:translate-x-full sm:scale-100 sm:opacity-100"
     To: "transform opacity-100 scale-100  sm:translate-x-0 sm:scale-100 sm:opacity-100"
   Leaving: "transition ease-in duration-150 sm:ease-in-out sm:duration-300"
     From: "transform opacity-100 scale-100 sm:translate-x-0 sm:scale-100 sm:opacity-100"
-   To: "transform opacity-0 scale-110  sm:translate-x-full sm:scale-100 sm:opacity-100"
+   To: "transform opacity-0 scale-110 sm:translate-x-full sm:scale-100 sm:opacity-100"
 -->
```

**To Reproduce**

1. Use the template...
2. In your custom JavaScript use an on click handler which will add tokens: 
```js
element.classList.add(..."transform opacity-0 scale-110  sm:translate-x-full sm:scale-100 sm:opacity-100".split(" "))
```
4. Get error!

> Uncaught (in promise) DOMException: Failed to execute 'add' on 'DOMTokenList': The token provided must not be empty.

**Expected behavior**

That there are no spaces in the HTML comments for the transitions.

One can fix this obviously, but wanted to save others the hassle and fix the component template! Thank you ❤️

**Comment by reinink** [comment]
Hey thanks for reporting this — this has been corrected 👍
