### ISSUE TITLE
Type Error with 'focus' attribute on Dialog.Panel component when pasting React component into .tsx file

### ISSUE THREAD

**Issue by AnonymousSmurf** [tailwindlabs/tailwindui-issues#1421]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/marketing/sections/heroes#component-d63f5b5552a3f3d936c6ab970a47899b
- Component name: Simple centered with background image

**Describe the bug**
When attempting to copy the React code for the component and pasting it into a `.tsx` file, a type error is encountered with respect to the `focus` attribute on the `Dialog.Panel` component. Specifically, the error message states that the `focus` attribute is not recognized, and suggests using `onFocus` instead.

**To Reproduce**
1. Go to [tailwindui](https://tailwindui.com/components/marketing/sections/heroes#component-d63f5b5552a3f3d936c6ab970a47899b).
2. Click on copy icon for the specified component.
3. Paste the component inside of the IDE (vscode in this case).
4. See type error when pasted.

```
Type '{ children: Element[]; focus: string; className: string; }' is not assignable to type 'IntrinsicAttributes & CleanProps<"div", never> & OurProps<"div", PanelRenderPropArg> & { className?: string | ((bag: PanelRenderPropArg) => string) | undefined; } & { ...; }'.
  Property 'focus' does not exist on type 'IntrinsicAttributes & CleanProps<"div", never> & OurProps<"div", PanelRenderPropArg> & { className?: string | ((bag: PanelRenderPropArg) => string) | undefined; } & { ...; }'. Did you mean 'onFocus'?
```
  
**Expected behavior**
When pasting the component inside of vscode, I expect it to work without any errors.

**Screenshots**
![image](https://user-images.githubusercontent.com/45464235/221395941-24f929ce-4aae-473e-9101-495191b38a40.png)

**Browser/Device**
 - vscode: 1.75.1 (Universal)

**Additional context**
My guess is that it is just a missed or badly typed property. I read that tailwindUI is still working on fully supporting Typescript so I thought I open an issue for this.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

This was a mistake that has been fixed, a new version is deploying as we speak.

To fix it for you, you can safely drop the `focus="true"` from the `Dialog.Panel`. This prop doesn't exist (hence why you get TypeScript issues). This prop _does_ exist on the `Popover.Panel` (https://headlessui.com/react/popover#popover-panel).

```diff
- <Dialog.Panel focus="true" className="fixed inset-0 z-10 overflow-y-auto bg-gray-900 px-6 py-6 lg:hidden">
+ <Dialog.Panel className="fixed inset-0 z-10 overflow-y-auto bg-gray-900 px-6 py-6 lg:hidden">
```

Hope this helps!
