### ISSUE TITLE
Feature section overlaps hero section dropdown on a small screen 

### ISSUE THREAD

**Issue by seporaitis** [tailwindlabs/tailwindui-issues#1425]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/marketing/sections/heroes and https://tailwindui.com/components/marketing/sections/feature-sections
- Component name: Simple centered (hero section) and With product screenshot panel (feature section), but as far as I can tell this happens with most feature (and FAQ) sections.

**Describe the bug**
On a small screen, when the hero section menu is expanded, if the user scrolls down - the feature section can be seen through underneath. As far as I can tell it has something to do with the feature elements being `relative/absolute`. I searched around and adding `z-10` to various elements did not work. I am not enough expert in CSS to understand why.

**To Reproduce**
1. Create a tailwind-ready page with empty `<body>`.
2. Paste [Simple centered](https://tailwindui.com/components/marketing/sections/heroes#component-b9bcab4538776a17fff93d18f82a8272) component.
3. Paste [With product screenshot panel](https://tailwindui.com/components/marketing/sections/feature-sections#component-af398a1e42b35d28ba7204314a10db6e) component (FAQ components also have this problem)
4. Narrow down browser window
5. Scroll the page down - you should see the feature elements poke through

**Expected behavior**
The elements should either not be see through or the menu should not be pinned at the top so it scrolls away (similar to what navbar elements do)

**Screenshots**
A screenshot (open in a new tab for full size):

<img width="300" alt="SCR-20230305-b9p" src="https://user-images.githubusercontent.com/141768/222949474-7116f8d7-8ba3-40a6-830c-74da347cb868.png">

**Browser/Device (if applicable)**
 - OS: macOs
 - Browser: Safari
 - Version: 16.3

Although same happens with an up to date Chrome too.

**Additional context**

I use the plain HTML component code (not React or Vue), but I don't think it makes a difference.
If it's expected behaviour - any advice on how this could be overcome would be very welcome. Thanks!

**Comment by bradlc** [comment]
Hey @seporaitis. The hero component that you're using has an [`isolate`](https://tailwindcss.com/docs/isolation) class on the root element, which creates a new [stacking context](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning/Understanding_z_index/The_stacking_context) and is likely preventing the `z-index` classes on the mobile navigation from being effective. After reviewing the hero section markup we have made some changes to make it easier to use them alongside other components. You will notice that in the updated code the `<header>` element is completely separate from the hero content, and now has a `z-50` class. This will ensure that the header (and the mobile navigation) appears on top of other components that you are using.

I hope that helps!

**Comment by seporaitis** [comment]
It works! Thank you, it would have taken me ages to work this out. :)
