### ISSUE TITLE
Sign in split screen form does not take up full height of the screen

### ISSUE THREAD

**Issue by peciulevicius** [tailwindlabs/tailwindui-issues#1429]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/forms/sign-in-forms
- Component name: Split screen ([link](https://tailwindui.com/components/application-ui/forms/sign-in-forms#component-fef1d7e9849359af76d4d6ead796938b))

**Describe the bug**
Currently this is how the login page looks when implemented with code snippet provided. It doesn't take up full height of the screen:

![image](https://user-images.githubusercontent.com/43075730/225119470-b499e451-fa97-49ea-9a9b-60ab68860af8.png)

```tsx
export default function Example() {
  return (
    <>
      <div className="flex min-h-full">
          ....
      </div>
    </>
  )
}

```

What fixes the issue is replacing above code into this:
```tsx
export default function Example() {
  return (
    <>
      <div className="flex h-screen">
          ....
      </div>
    </>
  )
}

```

**To Reproduce**
I provided an example NextJS project to reproduce [here](https://github.com/peciulevicius/twui-signin-forms-issue). Old and "broken" login page is loaded on `/` and the new, expected behaviour can be found on `/newsignin`

**Browser/Device (if applicable)**
 - OS: [macOS]
 - Browser [chrome, brave, firefox]

**Comment by adamwathan** [comment]
Hey! So Next.js adds an extra `div` in the tree that you need to add `h-full` to to make sure the full-height stuff properly drills down all the way from the `html` element.

Opened a PR against your repo that makes it all work for you!

https://github.com/peciulevicius/twui-signin-forms-issue/pull/1

**Comment by peciulevicius** [comment]
I see. Thank you for the clarification. :)
