### ISSUE TITLE
Components using old version of @heroicons

### ISSUE THREAD

**Issue by matthewPrimitive** [tailwindlabs/tailwindui-issues#1430]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/marketing/sections/heroes
- Component name: Simple Centered

**Describe the bug**
Uses version 1 of @hericons/vue/outline.
When using newer components that utilize the latest version of hero icons it creates a build error.

**To Reproduce**
1. Copy and paste the "Simple Centered" hero component
2. Copy and paste the "Simple centered with background image" hero component
3. run the site locally

**Expected behavior**
Display the component with no build errors

**Screenshots**

**Browser/Device (if applicable)**

**Additional context**
Changing the icons to the newer versions fixes the problem
EX: 
Change "import { MenuIcon, XIcon } from '@heroicons/vue/outline'"
to "import { Bars3Icon, XMarkIcon } from '@heroicons/vue/24/outline'"

**Comment by adamwathan** [comment]
Hey! When I look at that component I see the right imports here:

<img width="689" alt="image" src="https://user-images.githubusercontent.com/4323180/225404116-e7c9686b-f01f-41c9-8490-406cbd3420c0.png">

Any other information you can provide that might explain the difference?

**Comment by matthewPrimitive** [comment]
@adamwathan 
Looks like it is correct. Not sure why it gave me the bug at first. Just checked the copy and paste and it seems to be working. I'll close this down.
