### ISSUE TITLE
Tailwind UI Keynote Has a Hydration Error on First Run

### ISSUE THREAD

**Issue by 1Ghasthunter1** [tailwindlabs/tailwindui-issues#1436]
**What component (if applicable)**
Tailwind UI Keynote Template (https://tailwindui.com/templates/keynote)

**Describe the bug**
Upon the first run of Keynote, NextJS displays three errors all related to mismatches between the initial UI and content generated on the server. 

`Error: Hydration failed because the initial UI does not match what was rendered on the server.
`

**To Reproduce**
1. Download the Keynote folder from Tailwind UI
2. Paste the contents into a new folder
3. Run `npm install`
4. Run `npm run dev` to start the server
5. Navigate to `http://localhost:3000` and NextJS should throw errors immediately.

**Expected behavior**
The initial UI and server generated content should match and no error should be thrown, especially as the steps in the `readme.md `file were followed as listed.

**Screenshots**
[Screenshots Here
](https://gyazo.com/collections/98d596cbb1aedf2d47b81d84b0052b3c)

**Browser/Device (if applicable)**
 - OS: Windows 11 Version 22H2 64 bit with Ubuntu 22,04 WSL
 - Browser Chrome
 - Version 111.0.5563.65

**Additional context**
Running the Next server from the ubuntu WSL environment.

**Comment by 1Ghasthunter1** [comment]
Update on this: The issues are completely within the `Speakers` and `Schedule` components. For clarification, if the `Speakers` component is removed from `index.jsx` and the corresponding `import { Speakers } from '@/components/Speakers'` import is removed, most of the original error stack trace remains.

However, if the `Schedule` component and it's corresponding import are removed from `index.jsx`, then Next only throws an error in console (not on the UI anymore) that reads as follows: `Warning: Prop `aria-selected` did not match. Server: "true" Client: "false`.

If both `Speakers` and `Schedule` components are removed along with their corresponding imports, the errors go away completely.

**Comment by bradlc** [comment]
Hey @1Ghasthunter1, thanks for reporting this! The issue is resolved by upgrading `@headlessui/react` to its latest version (`v1.7.13`). You can either re-download the template or run `npm install @headlessui/react@latest` to upgrade your existing project. Thanks again!
