### ISSUE TITLE
Styling is not used

### ISSUE THREAD

**Issue by regrub** [tailwindlabs/tailwindui-issues#1437]
No styling is perfomed other than colors when copying the code from the ui site into my source except for some forms.
I have followed instructions to "install" to the letter. 

Using Laravel 10, Jetstream & Livewire, Alpine. 

For example field with hidden label shows label, tables don't use class"min-w-full".
Looks like some of the required css is not present? 

Please help.

Browsers: Chrome, Safari

<img width="1318" alt="Scherm­afbeelding 2023-03-24 om 20 27 55" src="https://user-images.githubusercontent.com/49644016/227621825-e169b016-a720-4933-9189-6b39a65525b5.png">

**Comment by reinink** [comment]
Hey! So it's really hard to help in these situations without actually seeing your code.

One cause could be an incorrectly configured `content` key in your `tailwind.config.js` file. Be sure to include all of your templates in this option. You can read more about this on the Tailwind CSS website here: https://tailwindcss.com/docs/content-configuration

Another possible problem is that you've maybe forgotten to re-run your Tailwind build process after adding these components.

But again, without seeing the actual code it's difficult to help. Are you able to provide a minimal reproduction?

**Comment by reinink** [comment]
Hey! Going to close this one for now since we haven't heard back. Feel free to still share a minimal reproduction and I'd be happy to have a closer look 👍

**Comment by regrub** [comment]
Hello Jonathan,

Sorry was very busy. Here is some code. If you need some more please let me know?
**welcome.blade.php**
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>Evenda</title>

        
        <link rel="preconnect" href="https://fonts.bunny.net">
        <link href="https://fonts.bunny.net/css?family=figtree:400,600&display=swap" rel="stylesheet" />
        <link rel="stylesheet" href="https://rsms.me/inter/inter.css">
        
        @vite(['resources/css/app.css', 'resources/js/app.js'])
        @livewireStyles

    </head>
    <body class="antialiased">

        <div class="px-4 sm:px-6 lg:px-8">
            <div class="sm:flex sm:items-center">
              <div class="sm:flex-auto">
                <h1 class="text-base font-semibold leading-6 text-gray-900">Users</h1>
                <p class="mt-2 text-sm text-gray-700">A list of all the users in your account including their name, title, email and role.</p>
              </div>
              <div class="mt-4 sm:mt-0 sm:ml-16 sm:flex-none">
                <button type="button" class="block rounded-md bg-indigo-600 py-2 px-3 text-center text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">Add user</button>
              </div>
            </div>
            <div class="mt-8 flow-root">
              <div class="-my-2 -mx-4 overflow-x-auto sm:-mx-6 lg:-mx-8">
                <div class="inline-block min-w-full py-2 align-middle sm:px-6 lg:px-8">
                  <table class="min-w-full divide-y divide-gray-300">
                    <thead>
                      <tr>
                        <th scope="col" class="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-0">Name</th>
                        <th scope="col" class="py-3.5 px-3 text-left text-sm font-semibold text-gray-900">Title</th>
                        <th scope="col" class="py-3.5 px-3 text-left text-sm font-semibold text-gray-900">Email</th>
                        <th scope="col" class="py-3.5 px-3 text-left text-sm font-semibold text-gray-900">Role</th>
                        <th scope="col" class="relative py-3.5 pl-3 pr-4 sm:pr-0">
                          <span class="sr-only">Edit</span>
                        </th>
                      </tr>
                    </thead>
                    <tbody class="divide-y divide-gray-200">
                      <tr>
                        <td class="whitespace-nowrap py-4 pl-4 pr-3 text-sm font-medium text-gray-900 sm:pl-0">Lindsay Walton</td>
                        <td class="whitespace-nowrap py-4 px-3 text-sm text-gray-500">Front-end Developer</td>
                        <td class="whitespace-nowrap py-4 px-3 text-sm text-gray-500">lindsay.walton@example.com</td>
                        <td class="whitespace-nowrap py-4 px-3 text-sm text-gray-500">Member</td>
                        <td class="relative whitespace-nowrap py-4 pl-3 pr-4 text-right text-sm font-medium sm:pr-0">
                          <a href="#" class="text-indigo-600 hover:text-indigo-900">Edit<span class="sr-only">, Lindsay Walton</span></a>
                        </td>
                      </tr>
          
                      
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          </div>
          
        @livewireScripts
    </body>
</html>

**tailwind.config.js**
const defaultTheme = require('tailwindcss/defaultTheme');

/** @type {import('tailwindcss').Config} */
module.exports = {
    content: [
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './vendor/laravel/jetstream/**/*.blade.php',
        './storage/framework/views/*.php',
        './resources/views/**/*.blade.php',
    ],

    theme: {
        extend: {
            fontFamily: {
                sans: ['Inter var', ...defaultTheme.fontFamily.sans],
            },
        },
    },

    plugins: [require('@tailwindcss/forms'), require('@tailwindcss/typography')],
};

Output
<img width="1506" alt="Scherm­afbeelding 2023-04-06 om 13 47 03" src="https://user-images.githubusercontent.com/49644016/230367676-1b5ea49a-10b5-4083-9bdf-b64b250acdfc.png">

If you need some more please let me know.

Regards,
Rutger
