### ISSUE TITLE
Idea: Add amount / number of products to ecommerce -> product overviews

### ISSUE THREAD

**Issue by black-forest-digital** [tailwindlabs/tailwindui-issues#1441]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/ecommerce/components/product-overviews
- Component name: any

**Describe the bug**
To put more than 1 item in the card, I would expect a "number of items" field with +/- buttons in the product overview.
This is not contained in any of the product overview components.

**Expected behavior**
Have a counter field which has buttons to increase / decrease the amount of products I want to put into the cart. Also editable as number input.

**Comment by reinink** [comment]
@black-forest-digital Hey! Thanks for sharing this feedback. That's not a bad idea, and we'll take that into consideration if we're ever making updates to the ecommerce components 👍
