### ISSUE TITLE
Incorrect screen reader (sr-only) text

### ISSUE THREAD

**Issue by kreierson** [tailwindlabs/tailwindui-issues#1443]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/marketing/sections/contact-sections
- Component name: Split with pattern

**Describe the bug**
Contact Section - Split with pattern email screen reader span says Telephone for the email and address sections

**To Reproduce**
1. Go to https://tailwindui.com/components/marketing/sections/contact-sections
2. Scroll down to Split with pattern component
3. Click the Code button
4. Scroll down to the email contact information

**Expected behavior**
For the email address, the sr-only for the email should not be Telephone, probably something like Email.

**Screenshots**
![image](https://user-images.githubusercontent.com/11322709/231515218-17a4a081-a273-4859-ae97-386195c31f8d.png)

**Comment by reinink** [comment]
@kreierson Hey thanks for pointing this out! I've just corrected this 🤙
