### ISSUE TITLE
HTML <ul> using aria list role

### ISSUE THREAD

**Issue by mirhamasala** [tailwindlabs/tailwindui-issues#1444]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/lists/stacked-lists
- Component name: Stacked Lists

**Describe the bug**
The components use HTML`<ul>` and `role="list"`

**To Reproduce**
1. Go to https://tailwindui.com/components/application-ui/lists/stacked-lists
2. Click on the `code` tab for any stacked list component
3. Find `<ul>`
4. See `role="list"`

**Expected behavior**
`role="list"` shouldn't be necessary when using `<ul>`

**Screenshots**
<img width="840" alt="Screenshot 2023-04-13 at 14 16 55" src="https://user-images.githubusercontent.com/26620750/231771956-953c0d91-44df-479e-a87c-8d19ed0063fd.png">

**Additional context**
https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/list_role

**Comment by adamwathan** [comment]
Hey! So `role=“list”` is necessary when setting `list-style-type: none` otherwise certain screen readers won’t treat the element like a list:

https://www.scottohara.me/blog/2019/01/12/lists-and-safari.html

Hope that helps!
