### ISSUE TITLE
Archived examples link is missing in Page examples

### ISSUE THREAD

**Issue by Shajansheriff** [tailwindlabs/tailwindui-issues#1446]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/page-examples/home-screens
- Component name: 

**Describe the bug**
Recently the components got updated, and there is a link to see the archived examples. Still, that link is unavailable inside Application UI Page examples like the Home screen, Detail Screen & Settings screen. 

**To Reproduce**
1. Go to https://tailwindui.com/components/application-ui/page-examples/home-screens
2. Scroll down to bottom of the page
4. See there is no link for archived examples

**Expected behavior**
Need this link 
<img width="882" alt="Screenshot 2023-04-20 at 1 05 15 PM" src="https://user-images.githubusercontent.com/5535530/233293953-8a27dc9c-f8bf-4b97-8f12-3ad165b30472.png">

**Screenshots**
<img width="1291" alt="Screenshot 2023-04-20 at 1 06 24 PM" src="https://user-images.githubusercontent.com/5535530/233294208-1efa098f-8f6d-486c-8e14-9a89b7cf98ef.png">

**Browser/Device (if applicable)**

**Additional context**
FYI, I have an All-access package
<img width="669" alt="Screenshot 2023-04-20 at 1 07 04 PM" src="https://user-images.githubusercontent.com/5535530/233294412-4749719e-17ae-45dd-b7ee-f23868f36a25.png">

**Comment by RobinMalfait** [comment]
Hey, thank you for this bug report! 🙏

There was a small issue with the dates between the archival of components and the date you bought your license. You should be able to see the link for the archived components now.

Hope this helps!
