### ISSUE TITLE
"Stacked on Dark" Form Component dropdown issues on Windows

### ISSUE THREAD

**Issue by sbmsr** [tailwindlabs/tailwindui-issues#1447]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/forms/form-layouts#component-00915bfd3ee87bc28e2c0c6dc6c3c8ca
- Component name: Stacked on Dark

**Describe the bug**

Some of my users are reporting that on Windows, the dropdown options are invisible unless hovered on. This is happening on both Firefox and Chrome.  

**To Reproduce**
1. Using a windows PC, go to the ["Stacked on Dark" component](https://tailwindui.com/components/application-ui/forms/form-layouts#component-00915bfd3ee87bc28e2c0c6dc6c3c8ca)
2. Scroll down to the Country drop down
3. Click it
4. See that all options are invisible, except for the first.

**Expected behavior**

At step 4, i'd expect all options to be visible.

**Screenshots**

Chrome: ![IMG_2231](https://user-images.githubusercontent.com/2349518/233397780-6a633496-d68c-4e36-b618-57cabc21196e.jpeg)

Firefox: ![IMG_2230](https://user-images.githubusercontent.com/2349518/233397804-4a213053-378f-4f0f-be9b-6040cc83f4a3.jpeg)

**Browser/Device (if applicable)**
 - OS: Windows 11 Pro, Version 22H2, OS Build 22621.1631, Windows Feature Experience Pack 1000.22641.1000.0
 - Browser: 
   - firefox: 112.0.1 (64 bit)
   - chrome: 112.0.5615.138 (64 bit)
 - Version 
   - firefox: 112.0.1 (64 bit)
   - chrome: 112.0.5615.138 (64 bit)

**Additional context**

I've identified the issue - the font is set to be white. Since the dropdown box has a white background, the text appears invisible unless hovered (white on blue background is visible). 

For now I've removed the font color + dropdown background color, and it's working as expected.

**Comment by reinink** [comment]
@sbmsr Hey thanks so much for bringing this to our attention! I'm really surprised that this even happens — I would have expected the dropdown content styles to all be set by the native operating system level styles.

Either way, I just pushed up a fix for this, where I add a `[&_*]:text-black` class to the `<select>` elements in the dark components. Here's a diff if you'd like to make the same change in your project:


```diff
- <select id="country" name="country" autocomplete="country-name" class="block w-full rounded-md border-0 bg-white/5 py-1.5 text-white shadow-sm ring-1 ring-inset ring-white/10 focus:ring-2 focus:ring-inset focus:ring-indigo-500 sm:text-sm sm:leading-6">
+ <select id="country" name="country" autocomplete="country-name" class="block w-full rounded-md border-0 bg-white/5 py-1.5 text-white shadow-sm ring-1 ring-inset ring-white/10 focus:ring-2 focus:ring-inset focus:ring-indigo-500 sm:text-sm sm:leading-6 [&_*]:text-black">
```

Let me know if you run into any other issues here 👍
