### ISSUE TITLE
Pages and components not displaying as it should in react app.

### ISSUE THREAD

**Issue by udaya-reddy** [tailwindlabs/tailwindui-issues#1448]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/application-shells/sidebar
- Component name: Side layout anyone. Tried with 1st one.

**Describe the bug**

All the components and pages are getting distorted badly... including icons without width and height.

**To Reproduce**
1. Go to '...' set up a vite tailwindcss react project.  https://github.com/udaya-reddy/testtwuireact. This is empty shell.
2. Click on '....'  copy paste the component code into App.tsx  
3. Scroll down to '....'  yarn dev and go to the url where the app is hosted

**Expected behavior**
Expected the component/page to be rendered as depicted in website.

**Screenshots**
![image](https://user-images.githubusercontent.com/67152550/234277170-426a0593-15fc-4885-8ab2-62b812d8199b.png)

**Browser/Device (if applicable)**
 - OS: [e.g. iOS] windows
 - Browser [e.g. chrome, safari] chrome

**Additional context**

**Comment by adamwathan** [comment]
Hey! Make sure to update your `tailwind.config.js` file to look for `tsx` files, right now it's only looking for `html` and `js` extensions:

https://github.com/udaya-reddy/testtwuireact/blob/master/tailwind.config.js#L3

**Comment by udaya-reddy** [comment]
added. didnt fix.  the repo is also updated with the same.
/** @type {import('tailwindcss').Config} */
module.exports = {
	content: ['./**/*.{html,js,tsx,ts}'],
	theme: {
		extend: {},
	},
	plugins: [require('@tailwindcss/forms'), require('@tailwindcss/typography'), require('@tailwindcss/aspect-ratio')],
}

**Comment by udaya-reddy** [comment]
import '../main.css'
was missing.....
Thank you @adamwathan  closing the ticket.
