### ISSUE TITLE
doc website not showing any data

### ISSUE THREAD

**Issue by wozhendeaa** [tailwindlabs/tailwindui-issues#1449]
**stacked list**
- [URL for category: ](https://tailwindui.com/components/application-ui/application-shells/stacked)
- Component name:  stacked list doc

**Comment by RobinMalfait** [comment]
Hey, thank you for this bug report! 🙏

Can you elaborate what you mean exactly?

The linked list for `Stacked Layouts` (https://tailwindui.com/components/application-ui/application-shells/stacked) seems to work as expected.
The mentioned `Stacked List` (https://tailwindui.com/components/application-ui/lists/stacked-lists) seem to include data in both the React and Vue version. The HTML version is expanded with example data.

Going to close this issue for now. But if you can elaborate what you see / expect then I'm happy to help you out!
