### ISSUE TITLE
Cookie Consent 

### ISSUE THREAD

**Issue by taftse** [tailwindlabs/tailwindui-issues#145]
**Screenshots**
https://elfsight.com/wp-content/uploads/2019/04/cookie-consent-hero-image-1.png
https://i0.wp.com/byteplate.com/wp-content/uploads/s/silktide-notice.png?resize=862%2C265&ssl=1

**Additional context**
I would like to see a few different examples how you would deal with the EU Cookie consent dialog's/banners

**Comment by JeanPaulvB** [comment]
I'd love this too!

**Comment by JonasEriksson** [comment]
Probably not much work for anyone to adjust what https://www.osano.com/cookieconsent outputs with a few tailwind bits though? I mean we already have cards and notifications in TailwindUI.

Best regards / Med vänliga hälsningar
Jonas Eriksson
INNOMEGA AB
________________________________

**Comment by simonswiss** [comment]
Thanks for the suggestion! 👍

I am porting the component suggestions to an "ideas" column in the Trello roadmap. I'll close this issue, but you can find this request here: https://trello.com/c/rrvHvsYh/62-cookie-consent
