### ISSUE TITLE
Boxes become bigger and bigger when resizing window.

### ISSUE THREAD

**Issue by arduino-man** [tailwindlabs/tailwindui-issues#1450]
**What component (if applicable)**
https://preview.cruip.com/mosaic/

**Describe the bug**
Boxes become bigger and bigger when resizing window. Boxes do not go back to their original size.

**To Reproduce**
Open the URL mentioned above in Firefox with your screen maximized. Then grab the right side of the browser window and drag it with your mouse to make the window smaller until you reach phone size, then make it big again, then small again. Repeat this a couple more times and you will see how the boxes that say "Acme Plus", "Acme Advanced" and "Acme Professional" get bigger and bigger until the layout becomes messed up.

**Expected behavior**
Boxes should be responsive but always go back to their original size.

**Screenshots**
Normally looks like:
![Screenshot 2023-05-02 at 4 18 23 PM](https://user-images.githubusercontent.com/5546597/235798001-66a28f01-4bbf-40d2-932a-7594ecec1e6d.png)

After a few window resizes, looks like:
![Screenshot 2023-05-02 at 4 13 39 PM](https://user-images.githubusercontent.com/5546597/235797267-35bd6a85-7e42-4717-ac4f-930cdc46416e.png)

**Browser/Device (if applicable)**
 - Mac OS 13.3.1
 - Firefox 112.0.2

**Comment by adamwathan** [comment]
Hey! This isn't our product, you'll want to report this issue to whoever runs https://cruip.com/ 👍

This issue tracker is for [Tailwind UI](https://tailwindui.com). Sorry can't be more help here — at a quick glance it looks like something to do with whatever JS they are using to resize the charts as the viewport size changes.
