### ISSUE TITLE
Missing striped class on table HTML example

### ISSUE THREAD

**Issue by hodeinavarro** [tailwindlabs/tailwindui-issues#1455]
**What component**
- URL for category: https://tailwindui.com/components/application-ui/lists/tables#component-b9407334ee0ee7eacb27cfbb5c08bb46
- Component name: With striped rows

**Describe the bug**
The example provides a table with greyed out rows. This is achieved in React/Vue with a gray row on a white base.
HTML example sets the body to `bg-white` but doesn't apply the expected `odd:bg-gray-50` or a simple `bg-gray-50` to the row.

**Expected behavior**
Given example row to have `odd:bg-gray-50` class.

**Screenshots**
HTML (bug)
<img width="271" alt="image" src="https://github.com/tailwindlabs/tailwindui-issues/assets/73967816/d95c5e2d-139b-4e11-8d04-382ecdccc5e8">
React (OK)
<img width="777" alt="image" src="https://github.com/tailwindlabs/tailwindui-issues/assets/73967816/fc0a0c8f-7a69-472e-a902-bdbe4c37be3f">
Vue (OK)
<img width="1074" alt="image" src="https://github.com/tailwindlabs/tailwindui-issues/assets/73967816/fb4831fc-b7df-4c39-9c59-cc7634918179">

**Browser/Device**
 - OS: macOS
 - Browser: Safari
 - Version: 16.4 (18615.1.26.110.1)

**Additional context**
Did not check for other similar components or browsers.

**Comment by adamwathan** [comment]
Thanks, just pushed a fix!
