### ISSUE TITLE
Primer Template Smooth Scroll Does Not Work with NextJS Link

### ISSUE THREAD

**Issue by MarioGiancini** [tailwindlabs/tailwindui-issues#1456]
**What component (if applicable)**
- URL for category: https://tailwindui.com/templates/primer
- Component name: **Primer**

**Describe the bug**
Smooth scrolling is enabled for the tailwind portion of the project, but using the React version with NextJS `<Link>` components does not allow for smooth scrolling anchors.

**To Reproduce**
1. Init a repo with the Primer template
2. `npm run dev`
3. Scroll down until the navigation bar appears
4. Click any section nav link
5. Observe no smooth scroll, just an anchor jump

**Expected behavior**
Smooth scrolling on all anchor links and navigation

**Screenshots**
n/a

**Browser/Device (if applicable)**
 - OS: `Mac OS 12.6.2`
 - Browser: `Chrome`
 - Version: `112.0.5615.137 (Official Build) (arm64)`

**Additional context**
This is also broken on the demo here: https://primer.tailwindui.com/

**Comment by MarioGiancini** [comment]
### How To Fix

When using NextJS [`<Link>` components](https://nextjs.org/docs/pages/api-reference/components/link#scroll), the prop `scroll` needs to be set to false. 

This prevents the override of NextJS trying to scroll to top when visiting a new URL. This doesn't seem to play nicely with anchor tags.

**Comment by reinink** [comment]
@MarioGiancini Hey thanks so much for reporting this and sharing the `scroll={false}` suggestion. That works perfect! I've just updated the Primer template to correct this 👍

https://primer.tailwindui.com/

**Comment by MarioGiancini** [comment]
@reinink awesome! Happy to help. 🤝 

I have it working on my latest site as well: https://self.engineer

**Comment by ttiras** [comment]
i am on next.js 13.4.10 and `scroll={false} `was breaking the functionality. I removed the line from Link and now it is working as expected.
