### ISSUE TITLE
How about a chat window or message feed?

### ISSUE THREAD

**Issue by smorris1709** [tailwindlabs/tailwindui-issues#146]
**Screenshots**
Provide a screenshot of your existing solution or of examples you've seen elsewhere that you think would be helpful inspiration.

**Additional context**
Add any important details you think we need to know to make sure we build something that matches what you need.

**Comment by simonswiss** [comment]
Consolidating this with https://github.com/tailwindlabs/tailwindui-issues/issues/249 - thanks for the suggestion! 👍
