### ISSUE TITLE
Missing padding classes on input components

### ISSUE THREAD

**Issue by larslommen** [tailwindlabs/tailwindui-issues#1460]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/forms/input-groups 
- Component name: Input with label
**Describe the bug**
It seems that a horizontal padding class is missing from the input components code. It appears that this is the case with all the examples on that page. I'm not sure if this is the case with the input components on the other pages.

**Comment by reinink** [comment]
Hey! It sounds like you probably don't have the Tailwind CSS [forms plugin](https://github.com/tailwindlabs/tailwindcss-forms) installed. There's a comment about this in the component code:

```html
<!--
  This example requires some changes to your config:
  
  // tailwind.config.js
  module.exports = {
    // ...
    plugins: [
      // ...
      require('@tailwindcss/forms'),
    ],
  }
-->
```

Try installing `@tailwindcss/forms` via npm, then adding `require('@tailwindcss/forms')` to your `plugins` array in your `tailwind.config.js`, and this issue should be fixed 👍
