### ISSUE TITLE
Side-overs are not compatible with notifications

### ISSUE THREAD

**Issue by jeanmatthieud** [tailwindlabs/tailwindui-issues#1465]
**What component (if applicable)**
- Component name: Right [Slide-overs](https://tailwindui.com/components/application-ui/overlays/slide-overs), [Notifications](https://tailwindui.com/components/application-ui/overlays/notifications)

**Describe the bug**
The notification is shown below the Slide-Overs :
- I changed the z-index of the slide-over and the notification
- The notification is now over the slide-over
- However, the close button of the notification and the notification button bar cannot be clicked. 
The text of the notification cannot be selected.
- If I close the slide-over, the notification button are behaving as expected.

**Browser/Device (if applicable)**
 - OS: Windows
 - Browser Chrome
 - Version last release

**Comment by RobinMalfait** [comment]
Hey, thank you for this bug report! 🙏

Are you using this with `@headlessui/react` or `@headlessui/vue`?

For some context: the slide overs are built using the `Dialog` component from Headless UI. This does a few things for you:
1. Renders the `Dialog` in a `Portal` (which means that it is rendered at the end of the document)
2. It sets up a bunch of mouse/keyboard listeners for outside click, escape to close and other behaviour.

It looks like you are running into those issues:
1. To ensure that the notifications are rendered on top, ideally you stick them in a `Portal` component as well. Both `@headlessui/react` and `@headlessui/vue` expose a `Portal` component that you can use for this.
2. Once you use the `Portal` component, the `Dialog` should be smart enough to allow clicks inside these elements and _not_ close the `Dialog` and therefore not close the slide over.

```js
import { Portal } from '@headlessui/react'

function Notifications({ children }) {
  return (
    <Portal>
      <div
        aria-live="assertive"
        className="pointer-events-none fixed inset-0 flex items-end px-4 py-6 sm:items-start sm:p-6"
      >
        {children}
      </div>
    </Portal>
  )
}
```

I made a CodeSandbox example to showcase this behaviour: https://codesandbox.io/p/sandbox/github/tailwindlabs/reproduction-headlessui-react/tree/main

Hope this helps!
