### ISSUE TITLE
HeroIcons Copy JSX issue

### ISSUE THREAD

**Issue by aorborc** [tailwindlabs/tailwindui-issues#1466]
**What component (if applicable)**
- URL for category: https://heroicons.com/
- Component name: HeroIcons

**Describe the bug**

**To Reproduce**
1. Go to ['heroicons page'](https://heroicons.com/)
2. Hover on Any Icon
3. Click on Copy JSX (or SVG)
4. You will see that it copies SVG.

**Comment by adamwathan** [comment]
Hey! It does copy JSX I just don't think it's what you were expecting (but is what we intend) — see previous issue here 👍 

https://github.com/tailwindlabs/heroicons/issues/888
