### ISSUE TITLE
Radio Group Small Cards not working

### ISSUE THREAD

**Issue by danielniccoli** [tailwindlabs/tailwindui-issues#1468]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/forms/radio-groups#component-245cb777f4a9823e97d8b1c2dfb87e0c
- Component name: Small Cards

**Describe the bug**
The static HTML code shows that the radio group is created with `input` elements.

![image](https://github.com/tailwindlabs/tailwindui-issues/assets/2971735/851a58ac-901b-4652-a3cf-a3ea693517c9)

The code does not produce the expected output (in Firefox). The specific styles for checked and unchecked variants are not applied correctly, after adding them manually to the static HTML.

![image](https://github.com/tailwindlabs/tailwindui-issues/assets/2971735/8809b4af-64b7-4c1f-bb95-56eccf4a13b2)

Going back to the example on your website, I can see that your sample is not created with `input` elements, as opposed to the static HTML sample.

![image](https://github.com/tailwindlabs/tailwindui-issues/assets/2971735/53655566-74b7-4574-b96c-c99f1a0bbadd)

**Comment by thecrypticace** [comment]
Hey! The `<input>` element is hidden using `sr-only` which only makes it visible to screen readers. You should, instead, place all the classes for active, stocked, not stocked, checked, and not checked on the `<label>` element.

**Comment by danielniccoli** [comment]
🤦 Duh. Thank you!
