### ISSUE TITLE
Possibly typo in TailwindUI-webstei

### ISSUE THREAD

**Issue by deviationist** [tailwindlabs/tailwindui-issues#1469]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/overlays/notifications#component-7d20f80f5b5fc2a13c14034d3d60115e
- Component name: Notification (With split buttons)

**Describe the bug**
The buttons say "Reply" and "Don't allow", but it only makes sense with "Allow" and "Don't Allow". It seems like the "Reply"-text comes from the component above (With avatar).

**To Reproduce**
1. Go to https://tailwindui.com/components/application-ui/overlays/notifications#component-7d20f80f5b5fc2a13c14034d3d60115e
2. See the buttons to the left, "Reply" and "Don't Allow".
4. See that "Allow" seems like a more fitting term for the example.

**Expected behavior**
I would expect the button to display "Allow" instead of "Reply".

**Screenshots**
[![Screenshot-2023-06-30-at-12-01-21.png](https://i.postimg.cc/Z54jwhD8/Screenshot-2023-06-30-at-12-01-21.png)](https://postimg.cc/PPVmq0HJ)

**Browser/Device (if applicable)**
 - OS: macOS Ventura 13.3.1 (a)
 - Browser: Brave
 - Version: 1.52.126 Chromium: 114.0.5735.133 (Official Build) (arm64)

**Additional context**
None.

**Comment by reinink** [comment]
Hey! Thanks for this feedback, but these are really just placeholders and don't necessarily reflect real-world applications — feel free to update the component with whatever actions make sense for your particular project 👍
