### ISSUE TITLE
Visual glitches in Safari for the search component of the Syntax template 

### ISSUE THREAD

**Issue by pfandrade** [tailwindlabs/tailwindui-issues#1470]
**What component (if applicable)**
- [Syntax template ](https://syntax.tailwindui.com)
- Search component

**Describe the bug**
Searching in Safari produces various visual glitches.

**To Reproduce**
1. Open the  [Syntax](https://syntax.tailwindui.com) template
2. Click on the search field
3. Type "ba"
4. Notice the visual glitches

**Expected behavior**
No visual glitches, like in other browsers.

**Screenshots**
<img width="1437" alt="Screenshot 2023-07-04 at 09 51 19" src="https://github.com/tailwindlabs/tailwindui-issues/assets/867472/3773f949-fd77-407d-8ac6-a2402a8b352f">

**Browser/Device (if applicable)**
 - OS: macOS
 - Browser: safari
 - Version 16.5.1

**Additional context**
Manually resizing the window forces a redraw and everything looks nice again.

**Comment by thecrypticace** [comment]
Hey — this is definitely a Safari bug and it looks to be a recent one at that. I tested on Safari 16.3 and it looks fine there. I did some additional testing using Safari Tech Preview Release 174 — which roughly corresponds to Safari 17 — and it appears they've fixed it. This means hopefully this bug won't last more than a 2ish months at most (but hopefully less).

For now though, to work around the bug, you can add `transform-gpu` to the `<Dialog.Panel>` that contains the search input and results:

```jsx
<Dialog.Panel className="mx-auto transform-gpu …">
  {/* … */}
</Dialog.Panel>
```

We've updated the Protocol and Syntax templates to use this workaround and updated the live previews and downloads on Tailwind UI.

Thanks for reporting this! ✨
