### ISSUE TITLE
can't compile when setting prefix field in config

### ISSUE THREAD

**Issue by hp8wvvvgnj6asjm7** [tailwindlabs/tailwindui-issues#1471]
![Screenshot 2023-07-06 at 18-27-32 Praivit Ltd](https://github.com/tailwindlabs/tailwindui-issues/assets/45887282/02c88e31-0f7c-4556-a220-5ad34fccf539)

```js
/** @type {import('tailwindcss').Config} */
module.exports = {
  
  prefix: 'pv-',
  
  content: [
    "./app/**/*.{tsx,mdx,ts}",
    "./components/**/*.{tsx,mdx,ts}",
    "./src/**/*.{tsx,mdx,ts}",
  ],
  theme: {
    extend: {
      
      fontFamily: { sans: ['var(--font-riviera-nights)'] },

      colors: {
        'gold': '#8e7d4b',
        'gold-dark': '#e3dbc4',
      },
    
    },
    container: { center: true },
  },
  plugins: [],
}
```

**Comment by reinink** [comment]
Hey! Happy to help out here.

When using a prefix, that prefix must also be included in the classes when using `@apply`:

```css
.test {
  @apply pv-tracking-wider;
}
```

Here's a Tailwind Play that illustrates this:

https://play.tailwindcss.com/jbiw3WrNQi?file=css

Hope that helps! 🤙
