### ISSUE TITLE
Constant checked is declared and assigned a value but never used

### ISSUE THREAD

**Issue by OmarBouziane** [tailwindlabs/tailwindui-issues#1474]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/lists/tables
- Component name: With checkboxes

**Describe the bug**
The constant checked is declared and assigned a value, but it's not used anywhere in the code.

```
<script setup>
import { ref } from 'vue'
const checked = ref(false)
</script>
```

**Comment by thecrypticace** [comment]
Thanks for catching this! I've updated the component to remove it. It was a carry over from the React version where it's necessary.

Appreciate it! ✨
