### ISSUE TITLE
Amounts alignments in table with summary rows

### ISSUE THREAD

**Issue by bnzo** [tailwindlabs/tailwindui-issues#1476]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/lists/tables
- Component name: [With summary rows](https://tailwindui.com/#component-78248cc564cd1fd14d6ff65b461cbab1)

**Describe the bug**
Subtotal and Tax amounts not aligned properly on small viewport

**To Reproduce**
1. Go to [With summary rows](https://tailwindui.com/#component-78248cc564cd1fd14d6ff65b461cbab1)
2. Reduce the viewport
3. Have a look at the Subtotal and Tax amounts not aligned properly

**Expected behavior**
subtotal and tax should be aligned with prices and total amounts. This can be fixed by reducing the right padding from `pr-6` to `pr-4`

**Screens
<img width="501" alt="Screenshot 2023-07-17 at 16 05 33" src="https://github.com/tailwindlabs/tailwindui-issues/assets/17174973/8f895925-9337-445c-90bd-b43e66839df6">
hots**

**Comment by bradlc** [comment]
Hey @bnzo, thanks for reporting this. The alignment has now been fixed 👍
