### ISSUE TITLE
Toggle disappears on the right of the screen

### ISSUE THREAD

**Issue by seb-jean** [tailwindlabs/tailwindui-issues#1477]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/page-examples/settings-screens#component-caa8ef7bf6e8809077b5f2d91a57dabb
- Component name: Settings Screens

**Describe the bug**
The toggle disappears on the right of the screen.

**To Reproduce**
1. Go to https://play.tailwindcss.com/oYKEKwduxz on mobile
2 The toggle (label: Automatic timezone) disappears on the right of the screen

**Expected behavior**

**Screenshots**
![Capture](https://github.com/tailwindlabs/tailwindui-issues/assets/12116264/ac6e8bf8-505d-4ad4-9b39-88aaec70390b)

**Browser/Device**
 - Mobile

**Comment by bradlc** [comment]
Hey @seb-jean, thanks for reporting this. The component has been updated to fix the overflow issue 👍

**Comment by seb-jean** [comment]
Thanks @bradlc
