### ISSUE TITLE
Contact list slide-over overflow issue.

### ISSUE THREAD

**Issue by iamcarlos94** [tailwindlabs/tailwindui-issues#1479]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/overlays/slide-overs
- Component name: [Contact list example](https://tailwindui.com/components/application-ui/overlays/slide-overs#component-e925f5b20e7d4110cc16920f1cf1a6fc)

**Describe the bug**
When there is only one person in the team, the MenuItems are cut off from view and require scrolling.

Also, this one I'm not sure but when using the Vue component, there is an attribute `x-descriptions` which I believe is for React? <`nav class="-mb-px flex space-x-6" x-descriptions="Tab component">`

**Screenshots**
![image](https://github.com/tailwindlabs/tailwindui-issues/assets/62184065/ab4a3eea-4169-4228-bd41-fd0720a8b747)

**Comment by RobinMalfait** [comment]
Hey @iamcarlos94! 👋

In these situations we generally recommend using [Floating UI](https://floating-ui.com) to properly position the dropdown menus. This is something that the underlying library, [Headless UI](https://headlessui.dev/), supports.

You can find a working example of how to implement Floating UI with the Headless UI `Menu` (dropdown) component here:

- A [React](https://github.com/tailwindlabs/headlessui/blob/main/packages/playground-react/pages/menu/menu-with-floating-ui.tsx) implementation, and a demo can be found [here](https://headlessui-react-git-main-tailwindlabs.vercel.app/menu/menu-with-popper).
- A [Vue](https://github.com/tailwindlabs/headlessui/blob/main/packages/playground-vue/src/components/menu/menu-with-floating-ui.vue) implementation, and a demo can be found [here](https://headlessui-vue-git-main-tailwindlabs.vercel.app/menu/menu-with-popper).

We considered adding Floating UI directly to Tailwind UI for situations like this, but we're concerned it's going too far with the implementation. Not everyone needs Floating UI for their dropdowns, it adds a bunch of extra code, and our focus is really on providing solid design patterns more than specific implementation details, so we've opted to keep things simpler for now and leave it up to the customer to decide if they'd like to implement Floating UI in their apps. That said, I could see us eventually adding something about Floating UI in the Tailwind UI documentation.

I hope that all makes sense! 🤟
