### ISSUE TITLE
Image Gallery Grid

### ISSUE THREAD

**Issue by stefanstifter** [tailwindlabs/tailwindui-issues#148]
First of all, awesome Tailwind components. Love them!  
Only thing I'm missing for the Marketing components: Better support for dealing with images.  
It would be cool to have some kind of basic Image Gallery component. This could either be a simple even grid (all images as Thumbnails with the same dimensions), or something more fancy like for example airbnb is using it (image Thumbnails have different dimensions, see second screenshot).  

Requirements for Image Gallery Grid:
- Display an arbitrary number of image thumbnails in a grid  
- Images can have different dimensions and aspect ratio (landscape format, portrait format)
- Gallery is fully responsive 

Also it would be a nice "nice-to-have" if there could be some form of simple Lightbox solution included. Clicking on the Image Thumbnail opens the Lightbox Gallery and the image can be viewed with the original aspect ratio..

**Screenshots**
![gallery-grid-2](https://user-images.githubusercontent.com/56681488/79245635-a48b7680-7e78-11ea-9e90-6d07a0edda2d.png)   
![gallery-grid-1](https://user-images.githubusercontent.com/56681488/79245652-aa815780-7e78-11ea-9d2b-3cf6f39fa47c.png)

**Comment by mjatharvest** [comment]
This would be handy for marketing sites!

**Comment by simonswiss** [comment]
Thanks for the suggestion! 👍

I am porting the component suggestions to an "ideas" column in the Trello roadmap. I'll close this issue, but you can find this request here: https://trello.com/c/PsNKad1C/61-image-galleries-grids
