### ISSUE TITLE
Tailwind logo redirects to main site within preview of Tailwind UI.

### ISSUE THREAD

**Issue by ThijmenGThN** [tailwindlabs/tailwindui-issues#1480]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/marketing/feedback/404-pages
- Component name: Split with image

**Describe the bug**
The logo of Tailwind has "/" as href but should be "#".

**To Reproduce**
1. Navigate to the component preview on TailwindUI.com.
2. Click the logo.

**Expected behavior**
It shouldn't do anything at all.

**Screenshots**
![image](https://github.com/tailwindlabs/tailwindui-issues/assets/54316157/5e0a1a2e-3911-4ef6-962a-7cec3734a0b9)
![image](https://github.com/tailwindlabs/tailwindui-issues/assets/54316157/73d6059d-32d6-4e83-ab71-4043732b735f)
![image](https://github.com/tailwindlabs/tailwindui-issues/assets/54316157/9fa82903-042c-451b-804e-267df2f99000)

**Browser/Device (if applicable)**
 - OS: Windows 11
 - Browser Opera GX
 - Version LVL5 (core: 100.0.4815.82)

**Comment by RobinMalfait** [comment]
Hey, thank you for this bug report! 🙏

This has been fixed, and will be available shortly!
