### ISSUE TITLE
TailwindUI does not load.

### ISSUE THREAD

**Issue by yuvrajmidha** [tailwindlabs/tailwindui-issues#1482]
I am Yuvraj Midha, a developer from India.
I am facing an issue using TailwindUI.
tailwindui.com does not load properly on my system. It takes around 2-3 minutes to load the website.

I bought TailwindUI recently to speed up my work but it seems all my time is wasted in loading the components,

**Comment by reinink** [comment]
Hey sorry to hear that! I just checked the site and it's loading fine for me, and haven't had any reports from other customers, so I'm worried this might be a localized issue.

Do you potentially have a different Internet connection that you could test the website on? Maybe it's some kind of issue with your particular ISP.

Really sorry I can't be more helpful than that. If the issue persists and the site is simply not useable for you, feel free to reach out to support@tailwindui.com and we'll happily issue a refund.

Thanks 🙏
