### ISSUE TITLE
Colors in TailwindUI

### ISSUE THREAD

**Issue by samzuercher** [tailwindlabs/tailwindui-issues#1483]
Visiting https://tailwindui.com/ and also the FAQ-Sections when buying a template i could not find information on how the templates and components are colored / styled. Do you use general color-aliases e.g. 'primary' or do you apply colors on all elements individually?

I would add this at least to the FAQ-Section.

Greetings,
Sam

**Comment by RobinMalfait** [comment]
Hey, thank you for your question! 🙏

We just use the default Tailwind CSS classes. In some components we have a comment at the top if a change to your `tailwind.config.js` file is required. An example of that can be found here: https://tailwindui.com/components/application-ui/forms/form-layouts#component-1c3f9860d66ce5cd9fb35ba7fde6721a

More information on the requirements can be found here: https://tailwindui.com/documentation#getting-set-up

Hope this helps!

**Comment by samzuercher** [comment]
Ok i see. To customize tailwindui-templates it might be much easier to use aliases for colors.

thanks anyway.
