### ISSUE TITLE
TailwindUI Studio Template Nextjs 13 API route 404 bug

### ISSUE THREAD

**Issue by keir-whitehead** [tailwindlabs/tailwindui-issues#1484]
**What component (if applicable)**
- URL for category: 
- Component name: TailwindUI Studio Template

**Describe the bug**

I am getting a 404 error every time I try to create an API route with this template. I am just creating an api folder in the /app directory with a nested folder e.g. /contact with a route.js file inside. When I try to access the API route through the browser or a fetch request I am getting a 404 error. The page will keep trying to reach the endpoint with a 404 error every 1-2 seconds. Within all my other next.js 13 projects this works perfectly fine. I have tried updating the all dependencies but still having no luck, but I could be missing something here.

**To Reproduce**
1. Download TailwindUI Studio Template and run NPM install
2. Create an /api folder in the /app directory, then either create a route.js file in this folder, or create a nested folder e.g. /contact to put the route.js in.
3. I am trying a simple GET request that should return a message:

import { NextResponse } from "next/server";

export async function GET() {
    return NextResponse.json({
        message: "Hello",
    });
}

4. Instead of displaying the json message response, the page redirects to the 404 template page.

**Expected behavior**
Expected to see the json response from the api endpoint.

Screenshots:
Error:

![CleanShot 2023-07-31 at 21 10 45](https://github.com/tailwindlabs/tailwindui-issues/assets/101802778/3b7e92ac-a0a9-48b4-b1da-84a983de851e)**Screenshots**

Working Test Project:
![CleanShot 2023-07-31 at 21 14 11](https://github.com/tailwindlabs/tailwindui-issues/assets/101802778/8f604ee1-2d6a-4f76-87a6-333a7aed32a9)

**Browser/Device (if applicable)**
 - OS: iOS
 - Browser Chrome

**Additional context**

**Comment by bradlc** [comment]
Hey @keir-whitehead, this is happening because of the [`pageExtensions` config](https://nextjs.org/docs/app/api-reference/next-config-js/pageExtensions) in `next.config.mjs`. By default this includes `js` but we used a custom value in this template so that we could include `mdx`. You can fix the issue by adding `js` to the array, which will :

```diff
  const nextConfig = {
-   pageExtensions: ['jsx', 'mdx'],
+   pageExtensions: ['js', 'jsx', 'mdx'],
  }
```

We've now updated the template to include `js` so that others don't run in to the same issue. I hope that helps!
