### ISSUE TITLE
`truncate` class not works

### ISSUE THREAD

**Issue by seb-jean** [tailwindlabs/tailwindui-issues#1485]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/lists/stacked-lists#component-ddd6f8c57e5a07ac015b69ee0a71b0d4
- Component name: Full width with links

**Describe the bug**
`truncate` class are not taken into account on the various components of the `Stacked Lists` page

**To Reproduce**
1. Go to [https://play.tailwindcss.com/tlGwq0tbNq](https://play.tailwindcss.com/tlGwq0tbNq)
2. See error

**Comment by RobinMalfait** [comment]
Hey, thank you for this bug report! 🙏

That's a very good catch, we've updated the components and the fix should now be live. You can apply the following changes:
```diff
  <li class="relative flex justify-between gap-x-6 px-4 py-5 hover:bg-gray-50 sm:px-6 lg:px-8">
-   <div class="flex gap-x-4">
+   <div class="flex min-w-0 gap-x-4">
      <img class="h-12 w-12 flex-none rounded-full bg-gray-50" src="https://images.unsplash.com/photo-1494790108377-be9c29b29330?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80" alt="">
      <div class="min-w-0 flex-auto">
        <p class="text-sm font-semibold leading-6 text-gray-900">
          <a href="#">
            <span class="absolute inset-x-0 -top-px bottom-0"></span>
             Leslie Alexander 
          </a>
        </p>
        <p class="mt-1 flex text-xs leading-5 text-gray-500">
          <a href="mailto:leslie.alexander@example.com" class="relative truncate hover:underline">leslie.alexander@example.comleslie.alexander@example.comleslie.alexander@example.comleslie.alexander@example.comleslie.alexander@example.comleslie.alexander@example.com</a>
        </p>
      </div>
    </div>
-   <div class="flex items-center gap-x-4">
+   <div class="flex shrink-0 items-center gap-x-4">
      <div class="hidden sm:flex sm:flex-col sm:items-end">
        <p class="text-sm leading-6 text-gray-900">Co-Founder / CEO</p>
        <p class="mt-1 text-xs leading-5 text-gray-500">Last seen <time datetime="2023-01-23T13:23Z">3h ago</time></p>
      </div>
      <svg class="h-5 w-5 flex-none text-gray-400" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
        <path fill-rule="evenodd" d="M7.21 14.77a.75.75 0 01.02-1.06L11.168 10 7.23 6.29a.75.75 0 111.04-1.08l4.5 4.25a.75.75 0 010 1.08l-4.5 4.25a.75.75 0 01-1.06-.02z" clip-rule="evenodd" />
      </svg>
    </div>
  </li>
```

The first `min-w-0` ensures that the truncation actually takes place. But this on its own is not enough yet. The "role" and the "last seen" on the right would be pushed and squished. To solve this part, we apply the second diff (add `shrink-0`) to make sure that this part doesn't shrink.

This now results in the following:
<img width="755" alt="image" src="https://github.com/tailwindlabs/tailwindui-issues/assets/1834413/8821316f-afd5-48bc-93a4-123da9986c7a">


Hope this helps!
