### ISSUE TITLE
ul missing

### ISSUE THREAD

**Issue by Temepest74** [tailwindlabs/tailwindui-issues#1487]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/navigation/sidebar-navigation#component-34180dd5b86e303286a8aa59b2ca9c34

![image](https://github.com/tailwindlabs/tailwindui-issues/assets/28103890/7cdef300-a988-4680-a49e-22eb09d83a98)
While displaying the child items, you missed to add another ul element

**Comment by RobinMalfait** [comment]
Hey, thank you for your question! 🙏

The `ul` is handled by the `DisclosurePanel`, this has a prop with `as="ul"` which will render a `ul` in the DOM.

Hope this helps!

**Comment by Temepest74** [comment]
> Hey, thank you for your question! 🙏
> 
> The `ul` is handled by the `DisclosurePanel`, this has a prop with `as="ul"` which will render a `ul` in the DOM. The `DisclosurePanel` is a component coming from our Headless UI package, and it renders _some_ element by default. With the `as` prop you can override that behaviour.
> 
> Hope this helps!

Oh, I understand. I was thinking this was the case, because Volar (vscode Vue 3 formatter) didn't format the file correctly
