### ISSUE TITLE
Image Carousel

### ISSUE THREAD

**Issue by stefanstifter** [tailwindlabs/tailwindui-issues#149]
Similar to #148  
It would be awesome to have a simple Image Carousel component solution.
(I know that's also not a pure css requirement, it probably gonna need some kind of javascript, but it would be really helpful to have a simple solution for this on marketing pages).

Requirements for Image Carousel:
- Display an arbitrary number of images in a carousel
- Images can have different dimensions and aspect ratio (landscape format, portrait format)
- Carousel is fully responsive

Again, doesn't need to be something super fancy, but a simple, reliable, responsive solution in form of a tailwind component would be super helpful.

[Bootstrap 4 Carousel](https://getbootstrap.com/docs/4.0/components/carousel/)

**Screenshots**
![carousel-1](https://user-images.githubusercontent.com/56681488/79247406-c5ed6200-7e7a-11ea-849b-a6e2b0b30e4a.png)

**Comment by J05HI** [comment]
Not only images. It should support text too.

https://codepen.io/adamwathan/pen/QWLEJGr
![image](https://user-images.githubusercontent.com/16399787/80520972-86e70280-898a-11ea-8035-bcc3eb51498a.png)

**Comment by simonswiss** [comment]
Thanks for the suggestion! 👍

I am porting the component suggestions to an "ideas" column in the Trello roadmap. I'll close this issue, but you can find this request here: https://trello.com/c/E2A3rBEz/60-carousels
