### ISSUE TITLE
Missing folders on new studio template 

### ISSUE THREAD

**Issue by codeibrahima** [tailwindlabs/tailwindui-issues#1497]
**What template (if applicable)**
- URL for category: https://tailwindcss.com/blog/2023-08-07-meet-studio-our-new-agency-template
- Component name: Studio

**Describe the bug**
File in the zip file are incomplete. Precisely, the component folder is missing. Here is a screenshot of the folder structure I got:  
![Screenshot 2023-09-01 at 20 30 55](https://github.com/tailwindlabs/tailwindui-issues/assets/59965615/3a2fc63f-8a80-4537-8ad1-e1949066fd7a)

**To Reproduce**
1. Go to ['...'](https://tailwindcss.com/blog/2023-08-07-meet-studio-our-new-agency-template)
2. Click on download
3. npm install 
4. Npm run dev and see the error 
5. `![Screenshot 2023-09-01 at 20 33 30](https://github.com/tailwindlabs/tailwindui-issues/assets/59965615/a8a82006-438d-46ad-9775-0814a0a3e7a5)

**Expected behavior**
Should start without error

**Comment by thecrypticace** [comment]
What version of macOS are you running and did you use a different app to extract the zip or the normal one ("Archive Utility")? I just downloaded the zip and it has the correct files:

<img width="600" alt="Screenshot 2023-09-01 at 19 00 12" src="https://github.com/tailwindlabs/tailwindui-issues/assets/614993/718505cb-ba33-4238-b65f-c9f4895aa356">

I also see that the tailwind config file is missing in your archive. It's almost like it stopped extracting part of the way through the archive. You might want to try re-downloading it and extracting it again.

**Comment by codeibrahima** [comment]
> What version of macOS are you running and did you use a different app to extract the zip or the normal one ("Archive Utility")? I just downloaded the zip and it has the correct files:
> 
> <img alt="Screenshot 2023-09-01 at 19 00 12" width="600" src="https://user-images.githubusercontent.com/614993/265140043-718505cb-ba33-4238-b65f-c9f4895aa356.png">
> I also see that the tailwind config file is missing in your archive. It almost stopped extracting part of the way through the archive. You might want to try re-downloading it and extracting it again.

I have a MacOS Ventura 13.1. 
When I use the Archive Utility, I get the "Enable to expand studio.zip" error,
So, I've used The Unarchiver app downloaded from the app store. 
I do not have a ts file on the unzipped file either. 
It's weird. 
I'll try it on a PC and let you know.

**Comment by codeibrahima** [comment]
Worked on another laptop. Thanks for the support
