### ISSUE TITLE
Home Screens and Detail Screens display almost the same content

### ISSUE THREAD

**Issue by GitHubish** [tailwindlabs/tailwindui-issues#1498]
The pages displaying the "Home Screens" and "Detail Screens" examples are almost identical, and it seems to me that this wasn't the case before. Hasn't something been reversed? I'm not sure, but it seems to me that the examples on the "Detail Screens" page weren't like that.

Detail Screens : [page](https://tailwindui.com/components/application-ui/page-examples/detail-screens)
Home Screens : [page](https://tailwindui.com/components/application-ui/page-examples/home-screens)

Thanks

**Comment by adamwathan** [comment]
Hey! So the home screens are meant to be dashboard/overview views, like the sort of thing you'd see as soon as you log into an app. The detail screens are for showing details about an individual resource in your project, like one invoice, one project, one customer, etc.

Think of home screens like the `/` URL, and detail screens like the `/{resource}/:id` URL.

The overall application shell and navigation and stuff is the same just like it would be in an app.

If you want to view the old/archived examples, they are still available here:

https://tailwindui.com/components/application-ui/page-examples/home-screens?include=archived
https://tailwindui.com/components/application-ui/page-examples/detail-screens?include=archived

There's a "Show archived" link at the bottom of any category that has archived examples 👍
