### ISSUE TITLE
Protocol template doesn't render sub sections on sidebar when deployed to Vercel

### ISSUE THREAD

**Issue by rexwangcc** [tailwindlabs/tailwindui-issues#1500]
**What component (if applicable)**
- URL for category: https://tailwindui.com/templates/protocol
- Component name: The protocol template

**Describe the bug**

When we deployed a slightly modified version of the Protocol template, the sections, are not shown on the Vercel-deployed version, however, they look normal on the local dev server page. 

![image](https://github.com/tailwindlabs/tailwindui-issues/assets/14366016/2d2b52fd-04e8-4790-bc8d-891d71953057)

We have a theory that this is due to the fact that the template has hard-coded `const pages = await glob("**/*.mdx", { cwd: "src/app" });` in `src/utils/generateSections.mjs`, while the MDX files are locate-able locally, they are not included in the Vercel runtime.

The theory can be semi-proved by renaming some of the directories that have MDX file (under `src/app/`) **after** a `yarn build` compilation I guess?

Right now we wrote a custom MDX parser to generate the sections at build time to hack around this but would appreciate an official fix, we also wonder the deployment option the official template preview chose (it seems the preview site does NOT have this issue 🤔 ) Thanks!

**Expected behavior**

The deployed version and local version should both have the sub-sections in sidebar.

**Comment by reinink** [comment]
Hey! Happy to try and help out here.

So our demo of this template (https://protocol.tailwindui.com/) is actually hosted on Vercel, and it's working fine there.

The thing that's throwing me off right now is that this template does not include a `src/utils/generateSections.mjs` file, and as far as I can tell, never has. Is it possible that this is a file you created in your modified version of this template?

**Comment by reinink** [comment]
Hey, just another update here, I've just downloaded both the JavaScript and TypeScript versions of the Protocol template and deployed them both to Vercel, and both worked without any issues.

Could you please provide a minimal reproduction of this issue as a Git repo so that we can reproduce this issue on our end?

**Comment by rexwangcc** [comment]
Hey reinink, thanks for the prompt reply! The fact that the official template worked fine with Vercel vanilla deployments made me think if there are something wrong during our process of adapting the template to our use case, lemme double check the diff set and get back to you later!

**Comment by rexwangcc** [comment]
I want to give an update that we have found the root cause:

- in order to add some client-side components in the `components/mdx.tsx` we marked it as `"use client"` at its top, which made the site a SSR one (which is completely different from the official template site, which is an ISR/SSG one, latter we assume has some pre-generated stuff that helps Vercel find the MDX sections structure)

We managed to revert the mdx.tsx to a non-client component, and it seems to solve the issue. Thanks for the help!

**Comment by reinink** [comment]
@rexwangcc Glad you got it figured out 🤙

**Comment by ynnelson** [comment]
@reinink something must have change because I am getting the same problem and when I go to the one hosted on tailwindUI the subsections don't show for me. See the screenshot below taken directly from the tailwindUI preview.

![image](https://github.com/user-attachments/assets/f00796c1-295f-4515-ade5-b0ffad32dc3a)
