### ISSUE TITLE
Primer Anchor Links not working

### ISSUE THREAD

**Issue by AlessandroVol23** [tailwindlabs/tailwindui-issues#1501]
**What component (if applicable)**
- URL for category: https://tailwindui.com/templates/primer (In the TS Version)
- Component name: Navbar

**Describe the bug**
The anchor links are not working. E.g. I click on 2 Screencasts or 5 Author and it isn't jumping to the page. It doesn't work on the template and also not on the live demo.

**To Reproduce**
1. Download the template
2. Install dependencies
3. Run repository
4. Click on "2 Screencasts" 
5. URL changes but the page is not jumping down

**Same in mobile view

Video:
https://www.loom.com/share/287e3cbc221f4f71b26968e4543ba883

**Expected behavior**

**Screenshots**

Video: https://www.loom.com/share/287e3cbc221f4f71b26968e4543ba883

**Browser/Device (if applicable)**
 - OS: Mac OS
 - Browser Arc / Chrome

**Comment by bradlc** [comment]
Hey @AlessandroVol23, thanks for reporting this. The issue can be resolved by replacing the `Link` component with `a` instead, in `src/components/NavBar.tsx`:

```diff
  <Popover.Button
-   as={Link}
+   as="a"
    key={section.id}
    href={`#${section.id}`}
-   scroll={false}
    className="flex items-center px-4 py-1.5"
  >
```

```diff
- <Link
+ <a
    href={`#${section.id}`}
-   scroll={false}
```

The template has now been updated with these changes 👍
