### ISSUE TITLE
Button component on Salient react template has a typescript issue

### ISSUE THREAD

**Issue by alanhett** [tailwindlabs/tailwindui-issues#1503]
**What component (if applicable)**
- URL for category: https://tailwindui.com/templates/salient
- Component name: Button

**Describe the bug**
First, thank you for this great template and hilarious placeholder content. Something is wrong with the typescript that is causing this block of code to throw a TypeScript error:

```
  className = clsx(
    baseStyles[variant],
    variantStyles[variant][color],  // this is the problematic line
    className,
  )
```

The error states:
`Argument of type '{ solid: { slate: string; blue: string; white: string; }; outline: { slate: string; white: string; }; }[Variant][Color]' is not assignable to parameter of type 'ClassValue'.`

**To Reproduce**
1. Open the file in the context of a project with React and TypeScript installed
2. The TypeScript error should appear if linting is turned on.

**Expected behavior**
The types should not throw an error.

**Screenshots**
<img width="635" alt="image" src="https://github.com/tailwindlabs/tailwindui-issues/assets/20879700/f01ef582-4c2f-433d-832b-cdbd2b3fb976">

**Browser/Device (if applicable)**
 - OS: macOS
 - Browser n/a (using VS Code)
 - Version (Typescript version 5.2.2)

**Additional context**
Thank you!

**Comment by thecrypticace** [comment]
Hey! So I haven't looked into this too deeply yet (doing that later today) but wanted to let you know that — for whatever reason — this error only appears in TypeScript 5.2. My preliminary look into this made it look like TypeScript 5.2 isn't collapsing the type of `variantStyles[variant]` and `variantStyles[variant][color]` like we'd expect it to which is maybe why this error is happening.

In the short term you can use TS v5.1 and the error will go away — TS v5.1 is also the version that the template is currently pinned to.

I'll follow up with more details when I know more!

**Comment by paulgould** [comment]
We also ran into the same issue today, we're running 5.2.2, will try using 5.1 instead.

**Comment by reinink** [comment]
@paulgould Hey, apologies on the delay here, this turned out to be a really tricky problem to solve, which we're pretty sure is ultimately a regression in newer versions of TypeScript. Nonetheless, we were able to figure out a workaround for this, and we've published an updated version of the Salient template to tailwindui.com — feel free to download it from there, or you can simply update the `Button.tsx` file in your project to the following:

```tsx
import Link from 'next/link'
import clsx from 'clsx'

const baseStyles = {
  solid:
    'group inline-flex items-center justify-center rounded-full py-2 px-4 text-sm font-semibold focus:outline-none focus-visible:outline-2 focus-visible:outline-offset-2',
  outline:
    'group inline-flex ring-1 items-center justify-center rounded-full py-2 px-4 text-sm focus:outline-none',
}

const variantStyles = {
  solid: {
    slate:
      'bg-slate-900 text-white hover:bg-slate-700 hover:text-slate-100 active:bg-slate-800 active:text-slate-300 focus-visible:outline-slate-900',
    blue: 'bg-blue-600 text-white hover:text-slate-100 hover:bg-blue-500 active:bg-blue-800 active:text-blue-100 focus-visible:outline-blue-600',
    white:
      'bg-white text-slate-900 hover:bg-blue-50 active:bg-blue-200 active:text-slate-600 focus-visible:outline-white',
  },
  outline: {
    slate:
      'ring-slate-200 text-slate-700 hover:text-slate-900 hover:ring-slate-300 active:bg-slate-100 active:text-slate-600 focus-visible:outline-blue-600 focus-visible:ring-slate-300',
    white:
      'ring-slate-700 text-white hover:ring-slate-500 active:ring-slate-700 active:text-slate-400 focus-visible:outline-white',
  },
}

type ButtonProps = (
  | {
      variant?: 'solid'
      color?: keyof typeof variantStyles.solid
    }
  | {
      variant: 'outline'
      color?: keyof typeof variantStyles.outline
    }
) &
  (
    | Omit<React.ComponentPropsWithoutRef<typeof Link>, 'color'>
    | (Omit<React.ComponentPropsWithoutRef<'button'>, 'color'> & {
        href?: undefined
      })
  )

export function Button({ className, ...props }: ButtonProps) {
  props.variant ??= 'solid'
  props.color ??= 'slate'

  className = clsx(
    baseStyles[props.variant],
    props.variant === 'outline'
      ? variantStyles.outline[props.color]
      : props.variant === 'solid'
      ? variantStyles.solid[props.color]
      : undefined,
    className,
  )

  return typeof props.href === 'undefined' ? (
    <button className={className} {...props} />
  ) : (
    <Link className={className} {...props} />
  )
}
```

Hopefully that solves this issue for you — thanks so much for letting us know 👍
