### ISSUE TITLE
Invalid `condition` attribute

### ISSUE THREAD

**Issue by devtvd** [tailwindlabs/tailwindui-issues#1504]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/navigation/steps#component-9a29a1d37a37b90f0b926478e8706004
- Component name: Steps: Circles

**Describe the bug**
There seem to be a `condition` attribute, which looks like was added by mistake:

```
<template v-else-if="step.status === 'current'" condition="step.status === 'current'">
```

**Screenshots**
![Screenshot 2023-09-13 at 11 04 04](https://github.com/tailwindlabs/tailwindui-issues/assets/110223958/d7b5f676-169f-4e7d-8f2d-4482d3dad0f0)

**Comment by RobinMalfait** [comment]
Hey!

Thanks for flagging this. This should be updated on Tailwind UI itself. You can safely drop the `condition` from the `<template>`.

Thanks!
