### ISSUE TITLE
`<h1>` missing on Settings Screens

### ISSUE THREAD

**Issue by seb-jean** [tailwindlabs/tailwindui-issues#1505]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/page-examples/settings-screens
- Component name: Stacked

**Describe the bug**
`<h1>` are missing on for Settings screens example pages.
In the example that [James proposed](https://twitter.com/jamesm/status/1622950229409497099/photo/4), there was a `<h1>`.

**To Reproduce**
1. Go to https://tailwindui.com/components/application-ui/page-examples/settings-screens
2. Scroll down to 'Stacked'
3. `<h1>` is missing

**Screenshots**

On [Tailwind UI](https://tailwindui.com/):

![Capture](https://github.com/tailwindlabs/tailwindui-issues/assets/12116264/fef65167-4cfe-429f-96c2-e582fe1535c4)

On [Tweet](https://twitter.com/jamesm/status/1622950229409497099/photo/4):

![FoXgoVnX0AAcvNk](https://github.com/tailwindlabs/tailwindui-issues/assets/12116264/63bc11c2-5caf-4b84-bada-3b2438b9e0d4)

What do you think ? 😄

**Comment by ACPK** [comment]
@seb-jean, considering the original GitHub issue you reported regarding the missing <h1> tags in the "Stacked" component of the Settings screens example pages at https://tailwindui.com/components/application-ui/page-examples/settings-screens, it's important to discuss the impact on SEO and ADA/accessibility.

I observed an interesting pattern during a Google search for related terms (e.g., importance of h1 tag): Facebook's setting page doesn't appear, while LinkedIn's does. This emphasizes the potential importance of including <h1> tags for better search engine visibility.

Additionally, when testing with a screen reader on the TailwindUI's setting layout, I found that the presence of the <h1> tag significantly contributed to accessibility. Given this context, it would be valuable to address the missing <h1> tags in the "Stacked" component to align with best practices for both SEO and ADA considerations. I'm happy to discuss how I have dealt with pages with sub-menus.

**Comment by ACPK** [comment]
@seb-jean, considering the original GitHub issue you reported regarding the missing <h1> tags in the "Stacked" component of the Settings screens example pages at [tailwindui.com/components/application-ui/page-examples/settings-screens](https://tailwindui.com/components/application-ui/page-examples/settings-screens), it's important to discuss the impact on SEO and ADA/accessibility.

I observed an interesting pattern during a Google search for related terms (e.g., importance of h1 tag): Facebook's setting page doesn't appear, while LinkedIn's does. This emphasizes the potential importance of including <h1> tags for better search engine visibility. 

When testing with a screen reader on the TailwindUI's setting layout, I found that the presence of the <h1> tag significantly contributed to accessibility. Given this context, it would be valuable to address the missing <h1> tags in the "Stacked" component to align with best practices for both SEO and ADA considerations. I'm happy to discuss how I have dealt with pages with sub-menus.

**Comment by zulkufdemirhan** [comment]
If you have concerns about SEO and search results and simultaneously don't want to disrupt the existing design, 
you can customize your 'font-size' as outlined in the documentation at [Tailwindcss](https://tailwindcss.com/docs/font-size).

Alternatively, you can create a custom class such as **'font-size-h2'** as shown below to address this issue without compromising the current design. In this way, by preserving the appearance, you create an SEO compatible element.

`<h1 class="font-size-h2 font-semibold leading-7 text-gray-900">Profile</h1>`
