### ISSUE TITLE
Featured testimonial from Grid testimonial component is invisible on mobile

### ISSUE THREAD

**Issue by emilthemaker** [tailwindlabs/tailwindui-issues#1506]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/marketing/sections/testimonials
- Component name: Grid

**Describe the bug**
The featured testimonial on the Grid testimonial component is invisible on mobile.

**To Reproduce**
1. Go to 'https://tailwindui.com/components/marketing/sections/testimonials' and scroll to the grid component
2. Drag the component to be smaller until the testimonial disappears
4. Observe

**Expected behavior**
Featured testimonial stays visible

**Video**
https://share.cleanshot.com/vKt57dG2

**Comment by thecrypticace** [comment]
Hey! Thanks for bringing this one up. I've updated the component to address this. On the updated component you can look at the classes on the `figure`, `blockquote`, and `figcaption` elements for the featured testimonial for comparison.
