### ISSUE TITLE
Lagging

### ISSUE THREAD

**Issue by paanblogger** [tailwindlabs/tailwindui-issues#1508]
**What component (if applicable)**
- URL for category: 
- Component name: https://tailwindui.com/components/marketing/page-examples/landing-pages

**Describe the bug**
The landing page template , is very-very lagging

**Comment by reinink** [comment]
Hey! Are you having an issue with this page on the Tailwind UI website, or are you having an issue with a specific component? Can you expand on what you mean by "very laggy"? Ideally could you provide a video illustrating the issue? Thanks!

**Comment by reinink** [comment]
Hey! Going to close this issue since we haven't heard back and I can't reproduce this problem, but if you're able to share more information I'd be more than happy to dig into this deeper 👍
