### ISSUE TITLE
Responsive table (transforms to cards or transposed view when narrow)

### ISSUE THREAD

**Issue by jacobq** [tailwindlabs/tailwindui-issues#151]
It's hard to make a good UI for tabular data on narrow viewports, in my opinion. Simply adding a scrollbar, or shrinking padding, or hiding some less critical columns usually isn't enough. 

**Example**
I know I've seen some cool solutions to this problem before, but I can't seem to find them now. 
I'd like to have the behavior described [here](https://css-tricks.com/accessible-simple-responsive-tables/#article-header-id-2) as "collapse rows"
Here's something sort-of close:
https://codepen.io/team/css-tricks/pen/wXgJww?editors=1100
And another example, though I don't like how this one is "uncollated"
https://react.semantic-ui.com/collections/table/#types-structured

**Comment by simonswiss** [comment]
We have some basic examples of that pattern in the new [Application Home Screen Examples](https://tailwindui.com/components/application-ui/page-examples/home-screens), but I have captured this request in our Trello roadmap here: https://trello.com/c/2JwXAYR4/59-responsive-table-card-on-small-screens 

Thanks for suggesting! 👍
