### ISSUE TITLE
Cannot scroll through the tailwindui.com/components or the documentation due to some bug

### ISSUE THREAD

**Issue by akashroy1** [tailwindlabs/tailwindui-issues#1511]
**version - v3.3.3**

**Browser - Google Chrome**

**OS: Windows**

**Reproduction URL - https://tailwindui.com/components?ref=sidebar**

**Description**

When I am going to the documentation of component pages I can see the page but cannot scroll down through the page.

**Comment by adamwathan** [comment]
Going to close this for now since we haven't heard anything back for a week now and no one has been able to reproduce it. If it's still an issue for you feel free to reach out again 👍
