### ISSUE TITLE
E-Commerce Components

### ISSUE THREAD

**Issue by ChuckHeintzelman** [tailwindlabs/tailwindui-issues#152]
First of all ... you're building a great set of beautifully designed components. Well worth the money. I think with popularity of e-commerce today what would be really helpful would be a series of e-commerce related components.

For example:
- Product pages
- Shopping Cart pages
- Checkout pages
- Product listings
- Order history / detail pages

And so forth. I know I'd find these type of components extremely useful and I think many people would purchase Tailwindcss UI just for e-commerce components.

Thank you.

**Comment by simonswiss** [comment]
Popular request - this is definitely something we're thinking about! 👍

I'm going to consolidate this issue with the others in https://github.com/tailwindlabs/tailwindui-issues/issues/268
