### ISSUE TITLE
Some components are not rendered as expected

### ISSUE THREAD

**Issue by brusacco** [tailwindlabs/tailwindui-issues#1520]
- URL for category: https://tailwindui.com/components/application-ui/navigation/breadcrumbs
- Component name:  [Full-width bar](https://tailwindui.com/components/application-ui/navigation/breadcrumbs#component-09fbe246cb968a4ab03a97c5da4947ee)

**Describe the bug**
After adding the sample HTML to a web page, it does not render as expected.

**To Reproduce**
1. Go to https://www.influencers.com.py/profile/3984

See the breadcrumbs on the header.

**Expected behavior**
I expect the breadcrumbs to be rendered as the example page.

**Additional context**
Using the HTML version on a Rails 7 application.

**Comment by adamwathan** [comment]
Hey! You've got some extra custom CSS in your project that is messing things up:

<img width="297" alt="image" src="https://github.com/tailwindlabs/tailwindui-issues/assets/4323180/e2917f38-c549-4390-aa82-5798bb4a35c7">

Adding the `mb-0` class to the `ol` element will fix it specifically for your project though by overriding your other custom styles you're applying to all of your lists 👍

**Comment by brusacco** [comment]
Hello, thanks!

After checking this and for anyone that has this issue in the future,
ActiveAdmin styles create conflicts with the components library, so you should only load the admin styles for the admin sections.

**Comment by brusacco** [comment]
This is the solution I used, in Rails 7:

This post is pretty old, so I figured including my recent findings with an updated version of Rails (6.1.4) was worth it.

Moving active_admin.css.scss from app/assets/stylesheets/ to vendor/assets/stylesheets/ worked for me too.

Using Rails 6.1.4
