### ISSUE TITLE
Simple Toggle input when name provided

### ISSUE THREAD

**Issue by SaizDev** [tailwindlabs/tailwindui-issues#1521]
**What component (if applicable)**
- URL for category:  https://tailwindui.com/components/application-ui/forms/toggles
- Component name: Simple Toggle

**Describe the bug**
When provided the switch component with a prop name, an input type hidden should appear. It only appears if the toggle is switched to on. The input dissappear when the toggle is off.
https://headlessui.com/react/switch#using-with-html-forms

**Expected behavior**
The input related to the toggle does not disappear when the toggle is off

**Screenshots**
<img width="1065" alt="image" src="https://github.com/tailwindlabs/tailwindui-issues/assets/24271943/25b379a0-502f-4548-b1a1-266949436fd2">
<img width="1080" alt="image" src="https://github.com/tailwindlabs/tailwindui-issues/assets/24271943/a995c5ee-4c32-4598-9936-2a6851797e9d">

**Browser/Device (if applicable)**
 - MacOS
 - Chrome

**Comment by adamwathan** [comment]
Hey! This is by design at the moment — it works like an HTML checkbox which works the same way, the only time a value is included in the form data and sent to the server is when the checkbox is checked, otherwise it is omitted 👍 

What's the actual problem you're running into as a result? Open to making changes here for sure if there's a good reason to do so.

**Comment by SaizDev** [comment]
Hey!
Thanks for such quick answer!

The problem comes when I want to retrieve the value of the input. I retrieve the value of the input automatically based on a config array previously generated. If the input does not appear, it throws an error. I found a workaround, but makes the code ugly and less reusable.

![image](https://github.com/tailwindlabs/tailwindui-issues/assets/24271943/e012141f-fb14-4946-9376-d7ccd680ce55)

What would you suggest?
