### ISSUE TITLE
All the code I copy/paste from your landing page sections seems way oversized, everything looks completely broken when I try to use it.

### ISSUE THREAD

**Issue by stefanlenoach** [tailwindlabs/tailwindui-issues#1527]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/marketing/page-examples/landing-pages
- Component name: Landing Page 1

**Describe the bug**
Visually the code does not seem to scale correctly.

**To Reproduce**
Copy/paste the HTML or React code into a new Astro project and view it

**Expected behavior**
Properly scaled landing page elements

**Screenshots**
<img width="1386" alt="Screenshot 2023-11-30 at 2 27 01 PM" src="https://github.com/tailwindlabs/tailwindui-issues/assets/17815103/afb8ee6a-a38f-4a47-9869-936b9f79e9ef">

**Browser/Device (if applicable)**
 - Safari

**Additional context**

**Comment by adamwathan** [comment]
Hey! It looks to me like none of your CSS is actually compiling, which makes me think Tailwind CSS hasn't been installed and set up correctly. Make sure you are following the instructions for setting up Tailwind CSS here and see where that gets you:

https://tailwindcss.com/docs/installation

**Comment by adamwathan** [comment]
Going to close this one as I don't believe this to be a bug in Tailwind UI, but hope my previous comment helps and if you need more help I'd encourage you to join our Discord server where there are lots of folks who are happy to help you figure out what's configured incorrectly 👍
