### ISSUE TITLE
Header is cut off on salient.tailwindui.com/register

### ISSUE THREAD

**Issue by ACPK** [tailwindlabs/tailwindui-issues#1528]
The logo is being cut off on the webpage [salient.tailwindui.com/register](https://salient.tailwindui.com/register), as illustrated in the screenshot provided below.

**Bonus:** I can create a separate issue for this, if applicable (let me know). When accessing the website on a mobile device with a resolution of 400x584 using Chrome, an unexpected visual artifact is observed. Specifically, there is a gray line followed by shading behind the "Password" label and field, as illustrated in the screenshot provided below.

**To Reproduce**

1. Open the webpage [salient.tailwindui.com/register](https://salient.tailwindui.com/register) using both Chrome and Safari browsers.
2. Ensure that the zoom level is set to 100%.
3. Set the screen resolution to 1352x878.
4. Observe the issue. Note that it works correctly on a device with a resolution of 1512x982.

**Expected behavior**

The logo should be displayed with sufficient space above it, resembling its appearance when the screen resolution is set to 1512x982.

**Screenshots**

<img width="1352" alt="Screenshot 2023-12-06 at 5 19 26 PM" src="https://github.com/tailwindlabs/tailwindui-issues/assets/2019893/686394f4-d573-4242-8fd9-290a58f6ea3f">

<img width="333" alt="Screenshot 2023-12-06 at 5 33 22 PM" src="https://github.com/tailwindlabs/tailwindui-issues/assets/2019893/38fd3064-4711-4c14-b76a-49fe09470c96">

<img width="580" alt="Screenshot 2023-12-06 at 5 38 34 PM" src="https://github.com/tailwindlabs/tailwindui-issues/assets/2019893/87746139-ba4f-43f0-b135-0f7345065cfe">

**Browser/Device (if applicable)**

- Operating System: OSX 14.1.2
- Browsers: Latest Chrome (Version 119.0.6045.199) and Safari (Version 17.1.2)

**Comment by adamwathan** [comment]
Woof thanks for catching, not sure how we missed that one! Just pushed a fix, here's the diff:

```diff
---
 templates/salient/src/components/SlimLayout.tsx | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/templates/salient/src/components/SlimLayout.tsx b/templates/salient/src/components/SlimLayout.tsx
index 8cb72829..2fef6729 100644
--- a/templates/salient/src/components/SlimLayout.tsx
+++ b/templates/salient/src/components/SlimLayout.tsx
@@ -5,7 +5,7 @@ import backgroundImage from '@/images/background-auth.jpg'
 export function SlimLayout({ children }: { children: React.ReactNode }) {
   return (
     <>
-      <div className="relative flex min-h-full justify-center md:px-12 lg:px-0">
+      <div className="relative flex min-h-full shrink-0 justify-center md:px-12 lg:px-0">
         <div className="relative z-10 flex flex-1 flex-col bg-white px-4 py-10 shadow-2xl sm:justify-center md:flex-none md:px-28">
           <main className="mx-auto w-full max-w-md sm:px-4 md:w-96 md:max-w-sm md:px-0">
             {children}
```
