### ISSUE TITLE
Social icon update: Twitter -> X

### ISSUE THREAD

**Issue by jarimustonen** [tailwindlabs/tailwindui-issues#1529]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/marketing/sections/footers

**Describe the bug**

The components refer to Twitter both in name and in logos. These are not usable anymore because Twitter needs to be updated to X. This makes components harder to use as there is not a easy to access svg path for X available.

**Comment by reinink** [comment]
Hey thanks for the reminder to do this!

I've just updated all the components in Tailwind UI to use the new X name and logo. For example:

<img width="443" alt="image" src="https://github.com/tailwindlabs/tailwindui-issues/assets/882133/474419f8-d961-4025-817b-4b8e32a54160">
