### ISSUE TITLE
[Catalyst] Select component dropdown ignoring background in Chrome/Edge

### ISSUE THREAD

**Issue by joshmeney** [tailwindlabs/tailwindui-issues#1533]
**What component (if applicable)**
- URL for category: [https://catalyst.tailwindui.com/docs/select](https://catalyst.tailwindui.com/docs/select)
- Component name: Select

**Describe the bug**
When viewing the demo of a Select component, the background of the dropdown is a solid white when using Chrome/Edge. Works fine with Firefox. 

**To Reproduce**
1. Go to [https://catalyst.tailwindui.com/docs/select](https://catalyst.tailwindui.com/docs/select)
2. Click on the Select element

**Screenshots**
![image](https://github.com/tailwindlabs/tailwindui-issues/assets/16173540/41851431-d066-4b76-859d-f50e1d700abd)
![image](https://github.com/tailwindlabs/tailwindui-issues/assets/16173540/b7a39ef6-2a94-4502-9871-403ef9d38d02)

**Browser/Device (if applicable)**
 - OS: Windows 11
 - Browser/Version: Chrome (120.0.6099.129) / Edge (120.0.2210.77)

**Comment by reinink** [comment]
Hey thanks for reporting this! This has been fixed:

<img width="633" alt="image" src="https://github.com/tailwindlabs/tailwindui-issues/assets/882133/b1877c2e-0c54-4d6e-91ce-2b07d6e52f4c">

To update it in your own project (assuming you even have one with Catalyst already 😅) you can either download Catalyst again and grab the `select.tsx` file out of it, or you can update this file yourself like this:

```diff
          // Typography
-         'text-base/6 text-zinc-950 placeholder:text-zinc-500 sm:text-sm/6 dark:text-white',
+         'text-base/6 text-zinc-950 placeholder:text-zinc-500 sm:text-sm/6 dark:text-white dark:*:text-white',

          // Border
          'border border-zinc-950/10 data-[hover]:border-zinc-950/20 dark:border-white/10 dark:data-[hover]:border-white/20',

          // Background color
-         'bg-transparent dark:bg-white/5',
+         'bg-transparent dark:bg-white/5 dark:*:bg-zinc-800',
```
