### ISSUE TITLE
Header public site styling issue

### ISSUE THREAD

**Issue by pieterjanscheir** [tailwindlabs/tailwindui-issues#1535]
![image](https://github.com/tailwindlabs/tailwindui-issues/assets/56866152/bb48a927-0623-40b7-99ba-9699e6611917)

**Comment by reinink** [comment]
Yikes — thanks for the heads up on this @pieterjanscheir. We only tested this while logged into the website, but there's less space when logged out. This has been fixed now — really appreciate you letting us know! 🙏
