### ISSUE TITLE
404 background image doesn't cover full viewport

### ISSUE THREAD

**Issue by dimerman** [tailwindlabs/tailwindui-issues#1537]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/marketing/feedback/404-pages
- Component name: simple, with background image

**Describe the bug**

**To Reproduce**
- Created a 404.js page in Gatsby
- added the <html class="h-full"> and <body class="h-full"> tags via Head API (confirmed on browser)

**Expected behavior**
the background image covers full screen

**Screenshots**
![image](https://github.com/tailwindlabs/tailwindui-issues/assets/633961/eb6841da-5a30-4ca6-afd4-d0ab03accbad)

**Browser/Device (if applicable)**
 - OS: macOS
 - Browser chrome
 - Version 120.0.6099.109

**Additional context**

**Comment by adamwathan** [comment]
Hey! See answer here: https://github.com/tailwindlabs/tailwindui-issues/issues/1536#issuecomment-1870716028
