### ISSUE TITLE
FEATURE Request Tailwindui Website

### ISSUE THREAD

**Issue by roarkmccolgan** [tailwindlabs/tailwindui-issues#154]
On the components page of the tailwindui website 
At a glance it's difficult to see what is currently available and what is coming soon.

I would like to suggest adding a touch of color to the icons for the groups that are available.
The dotted outline can be seen but is a bit too subtle.

![image](https://user-images.githubusercontent.com/1567162/79428842-078b2380-7fc7-11ea-98dd-67e13f508e6d.png)

**Comment by J05HI** [comment]
Would be great!

**Comment by simonswiss** [comment]
Valid point! 

While we probably won't implement this in the near future, I have added this tour our list of improvements. If there is a growing demand that justifies us putting other projects on hold to implement this, we will definitely consider doing it.

It's not a big task, but there are so many exciting things we're working on for the next few months, and we need to "aggressively prioritize" what we want to ship.

Thank you for raising this!

**Comment by roarkmccolgan** [comment]
You are all legends!!
I think the updates look amazing

![image](https://user-images.githubusercontent.com/1567162/114838757-508dd780-9dd5-11eb-8df0-71aa9da9e952.png)
