### ISSUE TITLE
Card headings are disabled

### ISSUE THREAD

**Issue by ferrucc-io** [tailwindlabs/tailwindui-issues#1544]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/headings/card-headings
- Component name: 

<img width="1455" alt="Screenshot 2024-01-05 at 11 29 02" src="https://github.com/tailwindlabs/tailwindui-issues/assets/8315559/d7cbaa10-6166-43e6-847d-af1bc80389fc">

All sections are disabled for some reason

**Comment by thecrypticace** [comment]
Hey, so the disabled areas are placeholders for the previews to better showcase how the headings are intended to look in context — inside a card-like element. The card is not part of the component which is why it looks disabled and also why it's not present in any of the code samples.
