### ISSUE TITLE
"With search in column layout" shows nav items when minimized.

### ISSUE THREAD

**Issue by thomaswitt** [tailwindlabs/tailwindui-issues#1545]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/navigation/navbars
- Component name: With search in column layout

**Describe the bug**
The navbar is without any navigation but when you resize it a burger menu appears which suddently shows navigations items like "Dashboard", "Calendar" and Teams and not just the profile related links like "Your Profile"

**To Reproduce**
1. Go to ['...'](https://tailwindui.com/components/application-ui/navigation/navbars#component-ac4ed72c2e03976dc5415ce711fe2f78)
2. Resize the Browser

**Expected behavior**
Only profile related menu items appear

**Browser/Device (if applicable)**
 - OS: macOS
 - Browser Firefox

**Comment by adamwathan** [comment]
Hey! See my response to your other issue here: https://github.com/tailwindlabs/tailwindui-issues/issues/1546#issuecomment-1880331020
