### ISSUE TITLE
Module not found: Can't resolve 'flexsearch' within the Syntax template

### ISSUE THREAD

**Issue by Emily-Nilsen** [tailwindlabs/tailwindui-issues#1547]
**What component (if applicable)**
- URL for category: https://tailwindui.com/templates/syntax
- Component name: FlexSearch within the Syntax template

**Describe the bug**
Module not found: Can't resolve 'flexsearch'

**To Reproduce**
1. Download the Syntax template
2. Install node modules
3. Cannot run on Next.js
4. See error:
```
- error ./src/markdoc/search.mjs:2:14
Module not found: Can't resolve 'flexsearch'
  1 | 
> 2 |               import FlexSearch from 'flexsearch'
    |              ^
  3 | 
  4 |               let sectionIndex = new FlexSearch.Document({
  5 |                 tokenize: 'full',

https://nextjs.org/docs/messages/module-not-found

Import trace for requested module:
./src/components/Search.jsx
./src/components/Layout.jsx
```

**Expected behavior**
I expected to run the Syntax template in my local browser.

**Screenshots**
![Screenshot 2024-01-10 at 08 18 26](https://github.com/tailwindlabs/tailwindui-issues/assets/67239572/16f39606-2eea-40eb-9ae8-e4e4c82187d6)

**Browser/Device (if applicable)**

**Additional context**
I have used this template previously without any issues. I'm now encountering the same problem on that project.

**Comment by adamwathan** [comment]
Hey! The [flexsearch](https://www.npmjs.com/package/flexsearch) package is a dependency and listed in the `package.json` file — can you try deleting `node_modules` and running `npm install`?

It was added a few months after the initial release when we switched form Algolia Docsearch to built-in search — any chance downloaded a fresh copy of the template but replaced the `package.json` file with the old `package.json` from your old project or similar?

**Comment by Emily-Nilsen** [comment]
Hi Adam,

I downloaded a fresh copy of the Syntax template directly from the Tailwind website yesterday, installed the node modules using npm install and received the error message when I attempted to run the new Syntax-template project on VS Code. I assumed that a fresh copy of the template would run without errors. The error I received trying to run yesterday's fresh copy is identical to the error I’m receiving when I try to run my earlier Syntax-template project (I received the error even after I deleted the node modules and ran the npm install command). 

Do you have any advice on how to resolve the error?

Here is the screenshot error I received attempting to run the fresh Syntax template I downloaded yesterday:
￼

I really appreciate any help you can provide.

Emily

**Comment by Emily-Nilsen** [comment]
Hi Adam,

Please ignore the last email. I deleted and reinstalled the node_modules again, and now both projects are running as expected. Thanks again for getting back to me so quickly. 

Emily

**Comment by adamwathan** [comment]
Ah great glad to hear it, thanks for following up!
