### ISSUE TITLE
Hey there, I've noticed you have made some changes to the site and now I am unable to scroll on desktop to look at the components. Basically what is happeining is I click on a component and I am unable to scroll to look att he others. 

### ISSUE THREAD

**Issue by La-la-Lupo** [tailwindlabs/tailwindui-issues#1552]
**What component (if applicable)**
- URL for category: 
- Component name: 

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Browser/Device (if applicable)**

**Additional context**

**Comment by reinink** [comment]
Hey! Can you let me know what browser you're using, including the version? Also, how are you trying to scroll? With the keyboard, or with the mouse? Does this happen with all our components, or a specific component? I am trying to reproduce this and I'm unable to do so.

The only thing I can think is that this has something to do with the fact that we show our components in an iframe, and when the iframe is focused and you press the space bar the page doesn't scroll, but if you're focused outside of an iframe it does. Either way though scrolling with the mouse works.

Any extra information you can provide would be helpful here. Thanks!

**Comment by La-la-Lupo** [comment]
Hi there, I have recorded a video to show you the problem. Here is the link. 
https://share.vidyard.com/watch/o3hhDqqtBPTHjVsMPmhrtN?

**Comment by reinink** [comment]
Hey! Thanks for sharing that video — it helped me figure out what's going on here.

The [Web Paint Tool - draw online](https://chromewebstore.google.com/detail/web-paint-tool-draw-onlin/iklgljbighkgbjoecoddejooldolenbj) browser plugin that you have installed is causing this. I was able to reproduce this issue by simply installing it.

Disable that plugin and you should be back to normal 👍
