### ISSUE TITLE
Catalyst's Button cannot be focused on Safari

### ISSUE THREAD

**Issue by silvenon** [tailwindlabs/tailwindui-issues#1555]
**What component (if applicable)**
- URL for category: https://catalyst.tailwindui.com/docs/button
- Component name: Button

**Describe the bug**
Safari skips buttons when tabbing through Catalyst components, I assume due to a bug in Headless UI.

**To Reproduce**
1. Open Safari on macOS
2. Go to [Catalyst's home page](https://catalyst.tailwindui.com/)
3. Tab through the components
4. Notice that it's skipping button components

**Expected behavior**
Use keyboard to tab to the button and hit Enter, but not only do I not see the focused state, focusing seems to be skipped altogether.

**Browser/Device**
 - OS: macOS 14.3.1
 - Browser Safari
 - Version 17.3.1

**Additional context**
Initially I thought that Button hover wasn't working either, and neither was toggling Checkboxes, then I realized that my client-side JS crashed on Safari for a different reason, which caused interactivity to stop working as well. It took me a while to realize that it depends entirely on JS. 

I hope Catalyst will eventually be progressively enhanced 🤞

**Comment by adamwathan** [comment]
Hey! I can't seem to reproduce this 🤔

https://github.com/tailwindlabs/tailwindui-issues/assets/4323180/c8733bc6-23cb-413c-a897-5a3482adcd1f

I'm on Safari 17.0 though not 17.3, so will try to get this tested on Monday on the exact same version to be sure.

**Comment by silvenon** [comment]
You're right, I didn't realize that by default Safari only focuses text fields and menus, I needed to enable tabbing through all focusable elements in settings.

<img width="450" alt="Screenshot 2024-02-18 at 20 51 51" src="https://github.com/tailwindlabs/tailwindui-issues/assets/471278/6b5178ce-59f4-40c3-a7cb-35c7e4e100fc">

**Comment by silvenon** [comment]
Ugh, sorry for the resolution mess, I couldn't make up my mind.

**Comment by adamwathan** [comment]
Ah okay gotcha! Yeah that is a weird default in Safari for sure, never understood that decision 🤔
