### ISSUE TITLE
custom tailwind prefix 

### ISSUE THREAD

**Issue by tomsour1s** [tailwindlabs/tailwindui-issues#1556]
**Describe the feature-request**
It would be great, if i can set a custom prefix like `tw-`.

**Expected behavior**
Rerender the `code` component with updated tailwind-classes containing the prefix

**Comment by reinink** [comment]
Hey! Thanks for this suggestion. We've had some discussion about this previously (see #480), but it's not something that we've been able to prioritize adding to Tailwind UI to date. I'd recommend looking at some of the suggestions in that issue, as there are some third-party workarounds available 👍
