### ISSUE TITLE
Scroll is broken in register page for the Pocket template

### ISSUE THREAD

**Issue by federicoaldunate** [tailwindlabs/tailwindui-issues#1563]
**What component (if applicable)**
- URL for category: 
- Component name:  Pocket template

**Describe the bug**

**To Reproduce**
1. Go to https://pocket.tailwindui.com/register
2. See error, the screen doesn't have a scroll, inability to see the whole screen.

**Expected behavior**
The screen doesn't have a scroll and users might not see the whole screen.

**Screenshots**
<img width="1376" alt="Screenshot 2024-03-26 at 23 24 26" src="https://github.com/tailwindlabs/tailwindui-issues/assets/39736940/03d6283a-5672-4bc8-b3d7-60e920613712">

**Browser/Device (if applicable)**
 - Browser Chrome, Desktop

**Comment by reinink** [comment]
Hey! Thanks so much for letting us know about this. I was able to reproduce this issue and also fix it: https://pocket.tailwindui.com/register

To fix this in your app, you can download the updated template from the Tailwind UI website and grab the updated `src/app/layout.tsx` file, or you can make the following change yourself:

```diff
  return (
-   <html
-     lang="en"
-     className={clsx('h-full bg-gray-50 antialiased', inter.variable)}
-   >
-     <body className="flex h-full flex-col">
-       <div className="flex min-h-full flex-col">{children}</div>
-     </body>
+   <html lang="en" className={clsx('bg-gray-50 antialiased', inter.variable)}>
+     <body>{children}</body>
+   </html>
  )
```

Thanks again! 🤙
