### ISSUE TITLE
Studio Template studio-js does not work.

### ISSUE THREAD

**Issue by LexiphanicStroon** [tailwindlabs/tailwindui-issues#1564]
**Tailwind Studio Template**

I have tried numerous times to download the zip of studio, unzip, npm install in the relevant folder (studio-js) and npm run dev. My terminal currently looks like this.

![image](https://github.com/tailwindlabs/tailwindui-issues/assets/80656460/a9eb80cd-4062-430c-9afa-8549286ee3fc)

I have done this around 6 times now. The exact steps I follow are: 
Download the studio zip. 
Extract the zip.
 Open studio-js in vscode, 
run npm install, run npm run dev and I consistently receive errors. 
One time when it did run, I was receiving two errors before changing anything. Keep in mind, on subsequent attempts, I have not changed a single character, just tried to run it and view it in browser, and I get runtime errors appearing. 

**To Reproduce**
1. Go to ['...'](https://tailwindui.com/templates/studio)
2. Click on download studio
3. Extract Studio zip file.
4. Open studio-js
5. Run npm install in terminal
6. run npm run dev
7. Errors appear

**Screenshots**
![image](https://github.com/tailwindlabs/tailwindui-issues/assets/80656460/5df576d3-48f6-44d4-8cbf-811ef4db8090)

**Browser/Device (if applicable)**
 - OS: Windows 10 
 - Browser Chrome
 - 
**Additional context**
Have attempted running it from WSL, and Windows file system.

**Comment by LexiphanicStroon** [comment]
![image](https://github.com/tailwindlabs/tailwindui-issues/assets/80656460/e863e580-5e8e-4ab0-abb2-077b7660473a)
After a fresh download of the zip, you can get it to run once with errors appearing in browser before it errors out. I spotted that the next.js version was out of date so I updated that, still receiving runtime errors right out of the box:

![image](https://github.com/tailwindlabs/tailwindui-issues/assets/80656460/b5ab3831-6906-413f-9c93-afe7b0ff609b)

**Comment by adamwathan** [comment]
Hey! I just downloaded it myself and ran `npm install` then `npm run dev` and can't seem to reproduce — what version of Node are you using?

https://github.com/tailwindlabs/tailwindui-issues/assets/4323180/7d09cda8-2c83-4cc1-89ac-66d9e9c2b961

**Comment by LexiphanicStroon** [comment]
Hey Adam, thanks for the reply. I tested it using node v20.11.1 and also node v21.6.2

**Comment by LexiphanicStroon** [comment]
@adamwathan , I also notice you're using the spotlight template. This issue is with the studio template

**Comment by LexiphanicStroon** [comment]
https://github.com/tailwindlabs/tailwindui-issues/assets/80656460/d0bf5e4e-0f5b-4d0c-bd1c-7d3b271da1f3

**Comment by adamwathan** [comment]
Ugh sorry about checking the wrong template — weekend dad brain in action 🤦🏻‍♂️ Tried the Studio template and couldn't reproduce locally either so trying to think what it could be 🤔

Any chance you have a browser extension installed or anything that might be interfering with hydration? I don't have a Windows machine to test on but can get someone on our team who does to test on Monday.

**Comment by LexiphanicStroon** [comment]
Hey man, that's ok. I'm going to dig around more myself to see if I can get it working. I did the same thing in a windows VM I quickly spun up and I got it to happen again. I'm assuming it's my machine. I uninstalled Node and NPM and am reinstalling them all to see if the issue could be with my machine. I opened the project in an incognito tab to see if it could be an extension, unfortunately still had the same issue. I appreciate you following up.

**Comment by LexiphanicStroon** [comment]
After trying many, many things, it seems this just does not play nice with Ubuntu. I was using WSL to run this template locally. Moving it to a windows terminal and filesystem just seems to work much better for some reason. I'll consider this resolved
