### ISSUE TITLE
Two errors in  template pocket-js 

### ISSUE THREAD

**Issue by irisolafsdottir** [tailwindlabs/tailwindui-issues#1572]
When running the template pocket-js, it has two errors.

**Comment by reinink** [comment]
Hey! I just downloaded this template and ran both the development and production builds for both the TypeScript and JavaScript versions, and I don't see any errors.

Can you please share the errors you're bumping into?

**Comment by reinink** [comment]
Hey going to close this one for now since we haven't heard back, but feel free to still share the errors you ran into if you want and I'd be happy to help out 👍
