### ISSUE TITLE
Deprecated HeadlessUI components used in TailwindUI components

### ISSUE THREAD

**Issue by liams000** [tailwindlabs/tailwindui-issues#1573]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/forms/comboboxes
- Component name: Simple

**Describe the bug**
The components used, for example `Combobox.Input` is marked as depreceated in the HeadlessUI package and should instead be `ComboboxInput`. This can also be found in other UI components in TailwindUI that use the HeadlessUI package.

**To Reproduce**
View the source code, it's non-breaking but the components are deprecated.

**Screenshots**
![image](https://github.com/tailwindlabs/tailwindui-issues/assets/94682429/a2ef0bfd-ea6b-467c-ad9c-4af89c04a5b1)

**Comment by RobinMalfait** [comment]
Hey!

Thanks for the bug report, we've updated the Tailwind UI examples and we removed the deprecated components and use the new non-deprecated components instead!

If you want to apply the same changes locally, you can essentially drop the `.` in `Combobox.Input` -> `ComboboxInput` and make sure to update the imports.

Hope this helps!
