### ISSUE TITLE
React code example for Dropdowns: `Menu.{SubComponent}` deprecated; use`Menu{SubComponent}` instead

### ISSUE THREAD

**Issue by clintharris** [tailwindlabs/tailwindui-issues#1577]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/elements/dropdowns
- Component name: Dropdowns

**Describe the bug**

Request doc example update.

The React code example shows use of `Menu.Button`, `Menu.Items`, and `Menu.Item`. These are deprecated in the current version of `@headlessui/react` and should be replaced with `MenuButton`, `MenuItems`, and `MenuItem`.

**Comment by RobinMalfait** [comment]
Hey!

Thanks for the bug report, we've updated the Tailwind UI examples and we removed the deprecated components and use the new non-deprecated components instead!

This has already been deployed.

If you want to apply the same changes locally, you can essentially drop the `.` in `Menu.Button` -> `MenuButton` and make sure to update the imports.

Hope this helps!
