### ISSUE TITLE
DialogPanel in component

### ISSUE THREAD

**Issue by kldeb** [tailwindlabs/tailwindui-issues#1578]
**What component (if applicable)**
- URL for category:  https://tailwindui.com/components/marketing/sections/heroes
- Component name: [Simple centered](https://tailwindui.com/components/marketing/sections/heroes#component-b9bcab4538776a17fff93d18f82a8272)

**Describe the bug**
DialogPanel is no longer in headlessui, should be updated to Dialog.Panel

**To Reproduce**

**Expected behavior**

**Screenshots**

**Browser/Device (if applicable)**

**Additional context**

**Comment by reinink** [comment]
Hey! I think I know what you're bumping into here.

We recently updated all the React components in Tailwind UI to use Headless UI v2.0 — the latest version of our headless UI library.

In v2.0 we deprecated the "dot notation" for all our components (things like `Dialog.Panel` and `Menu.Button`), as doing this causes issues with React Server Components and bundler tree-shaking. Meaning all our components now have explicit exports, like `DialogPanel` and `MenuButton`.

I'd highly recommend upgrading to the latest version of Headless UI:

```sh
npm install @headlessui/react@latest
```

You can find a detailed upgrade guide here:

https://github.com/tailwindlabs/headlessui/releases/tag/%40headlessui%2Freact%40v2.0.0

It looks long, but honestly it's really not that bad of an upgrade — there's a bunch of deprecations and only a few actual breaking changes.

Totally get how this is kind of annoying if you have an existing project based on Tailwind UI components, but we've always felt that it's important for Tailwind UI to use the latest version of our open source libraries.

Hope that makes sense! Let me know if you bump into any other issues 👍
