### ISSUE TITLE
Design for graphs/charts

### ISSUE THREAD

**Issue by BoyeMagnus** [tailwindlabs/tailwindui-issues#158]
Many SAAS services make use of graphs, such as donut, pie and line charts. It would be a very welcoming addition to the components :-)

**Screenshots**
https://dribbble.com/shots/10762151-Chattermill-Dashboard-in-Motion
https://dribbble.com/shots/6994258/attachments/8282?mode=media

**Additional context**
IMO the graph design could include both design with and without title axis/grid and such. (See second screenshot. It includes both of them :))

**Comment by simonswiss** [comment]
Thanks for the suggestion! 👍

I am porting the component suggestions to an "ideas" column in the Trello roadmap. I'll close this issue, but you can find this request here: https://trello.com/c/9JVOI65l/58-charts-graphs
