### ISSUE TITLE
Catalyst: Make live demo site available to access

### ISSUE THREAD

**Issue by dokkodo101** [tailwindlabs/tailwindui-issues#1580]
Thanks for the release of catalyst. Been waiting on it for some time.

Catalyst demo site looks really good.

Wish I could access the live demo site source code as a standalone project to see how all the pieces come together.

Thanks!

**Comment by reinink** [comment]
Hey, thanks for this suggestion!

It took us a few days to put together, but the demo is now included in the `catalyst-ui-kit.zip` file that you download from the Tailwind UI website.

Like our other templates this demo is built using Next.js and is available in both TypeScript and JavaScript versions.

Enjoy! 🤙

<img width="1139" alt="image" src="https://github.com/tailwindlabs/tailwindui-issues/assets/882133/8cc9c914-53af-4e0d-a4f7-04ec5b67cf5d">
