### ISSUE TITLE
Catalyst: Text inside TableCell isn't affected by the dark/light mode feature

### ISSUE THREAD

**Issue by FoksVHox** [tailwindlabs/tailwindui-issues#1581]
**What component (if applicable)**
- URL for category: https://catalyst.tailwindui.com/docs/table
- Component name: TableCell

**Describe the bug**
When you use `media` in your `tailwind.config.js` as the method for dark mode, you will see that everything except the text in `TableCells` is affected. Hence you'll have a dark mode, with black/gray text which makes it very hard to read.  

**To Reproduce**
Steps to reproduce the behaviour:
1. Start with a blank project which already has Catalyst set up (preferably with Laravel & Inertia)
2. Add the example table from the docs, as well as some data to display
3. Make sure you use `media` as the method for dark mode in your `tailwind.config.js`
4. Switch from light to dark.
5. You should now see a dark table with black text in the cells.

**Expected behaviour**
For the text to be affected by the dark mode. 

**Screenshots**
![image](https://github.com/tailwindlabs/tailwindui-issues/assets/37844753/9c124ef5-0a85-4796-8a47-b57dd1411a6d)

**Browser/Device (if applicable)**
 - OS: Windows 11
 - Browser: Chrome
 - Version: 125.0.6422.113

**Additional context**
I've found that adding `style="color-scheme: dark;"` fixes the text, however, the text will then appear white when you use light mode. This is used in the demo, but it isn't mentioned anywhere in the docs. Also, this isn't a viable solution when you're using the `media`-method instead of the `selector`-method.

I've used Laravel & Inertia for this, instead of Next.js. However, I do believe the same would happen on Next.js.

**Comment by dokkodo101** [comment]
Wrap it around a <Text /> component. should get it fixed.

**Comment by FoksVHox** [comment]
> Wrap it around a `<Text />` component. should get it fixed.

While it solves some of the issue, it doesn't solve it 100%. 

The example table doesn't wrap the text in a `<Text />`, but rather it just has the text as it's children.

![image](https://github.com/tailwindlabs/tailwindui-issues/assets/37844753/bee761eb-3215-47fb-baed-1c5e103ad05a)
The above image is produced with the following code
```jsx
    <Table>
      <TableHead>
        <TableRow>
          <TableHeader>Name</TableHeader>
          <TableHeader>Email</TableHeader>
          <TableHeader>Role</TableHeader>
        </TableRow>
      </TableHead>
      <TableBody>
        {users.map((user) => (
          <TableRow key={user.handle}>
            <TableCell className="font-medium">{user.name}</TableCell>
            <TableCell>{user.email}</TableCell>
            <TableCell className="text-zinc-500">{user.access}</TableCell>
          </TableRow>
        ))}
      </TableBody>
    </Table>
```

And as you can see, the text with the `user.name` and `user.email` isn't gray, which it will become when you `<Text />`. 

I do belive that it's a bug, that should be addressed.

**Comment by reinink** [comment]
Hey! So the reason this is happening is because the `Table` component doesn't have a default text color applied to it, so it's falling back to the document's default text color.

It's probably a good idea to give your app a default text color, something like this:

```html
<body class="text-zinc-950 dark:text-white">
```

However, I think it's also a good idea for the `Table` component to have a default color, so I've gone ahead and fixed that. You can either re-download Catalyst from the Tailwind UI website to get this change, or you can update your `Table.tsx` with this change:

```diff
- <table className="min-w-full text-left text-sm/6">{children}</table>
+ <table className="min-w-full text-left text-sm/6 text-zinc-950 dark:text-white">{children}</table>
```

Hope that helps! 👍
