### ISSUE TITLE
Catalyst: Wishlist

### ISSUE THREAD

**Issue by psztoch** [tailwindlabs/tailwindui-issues#1586]
1. Sidebar - in docs example add badge with number of item (like in email applications)
1. Lack of 3 states control: checkbox or switch (yes/no/unknown)
2. Table - example with column sorting icon (asc/desc) selector/indicator.
3. Heading - add sample: heading with small image (like avatar)
5. Input - add password example
6. Lack of tabs and filepicker.

**Comment by FoksVHox** [comment]
Some of the examples request I'd say are very specific in it use case, and such I wouldn't say it's something that should be added, as the examples are there for showing how you use it, and not how to combine different elements.
1. Can be solved by combining the documentation for [the sidebar](https://catalyst.tailwindui.com/docs/sidebar) and [the badges](https://catalyst.tailwindui.com/docs/badge).
2. Not sure what you mean by this.
3. The can be achieved by simply adding icons to the table header.
4. Should be possible by combining an [avatar element](https://catalyst.tailwindui.com/docs/avatar) and the [heading element](https://catalyst.tailwindui.com/docs/heading)
5. Can be solved by looking the docs. [Link to how to set the type of the input](https://catalyst.tailwindui.com/docs/input#setting-the-type)
6. I'd love to see this added, as well as a combobox.

**Comment by psztoch** [comment]
Ad. 2. Example: https://dequeuniversity.com/library/aria/checkbox-tri

**Comment by adamwathan** [comment]
Hey thanks for the suggestions! We do have a checkbox with indeterminate state already here that is a bit easy to miss:

https://catalyst.tailwindui.com/docs/checkbox#indeterminate-state

But the other stuff are all good ideas 👍 I'm going to close this because we use this space exclusively for bug requests but appreciate putting these ideas on our radar.

**Comment by abielan** [comment]
More examples work as better test case sheet.
Every reader of the documentation is immediately a tester.

**Comment by abielan** [comment]
> But the other stuff are all good ideas 👍 I'm going to close this because we use this space exclusively for bug requests but appreciate putting these ideas on our radar.

Studio SocialMediaProfiles should be with youtube and linkedin icons.
It is popular and should be included.
