### ISSUE TITLE
Component or page with map and address

### ISSUE THREAD

**Issue by abielan** [tailwindlabs/tailwindui-issues#1587]
No template now has an address presentation linked to the map.

**Comment by RobinMalfait** [comment]
Hey, thanks so much for this suggestion! 🙏

We'll keep it in mind when we are designing our next batch of components. I can't promise we will build it and if we do when that will be. I appreciate the suggestion!

Going to close this issue so that we can use this place for bug reports.

**Comment by abielan** [comment]
Then where is place for wishes proposal? :-)
