### ISSUE TITLE
AvatarButton not displaying text content correctly

### ISSUE THREAD

**Issue by roomman** [tailwindlabs/tailwindui-issues#1588]
**What component (if applicable)**
- URL for category: https://catalyst.tailwindui.com/docs/avatar
- Component name: AvatarButton

**Describe the bug**
Rendering an Avatar and AvatarButton side-by-side as follows:
```
<AvatarButton className="size-12 bg-white text-black" initials="SZ" />
<Avatar className="size-12 bg-white text-black" initials="SZ" />
```

In the case of AvatarButton, the text element that contains `initials` is positioned outside of the containing element, and not visible.

**Screenshots**
![image](https://github.com/tailwindlabs/tailwindui-issues/assets/10168451/31dc9cb9-edb3-4768-9498-0ee86ed37d52)

**Comment by reinink** [comment]
Hey good catch! Thanks for letting us know, this has been fixed.

To get the updated version you can simply download Catalyst again from the Tailwind UI website, or you can make the following changes to your `avatar.tsx` file:

First add the `size-full` class to the `Avatar` svg:

```diff
  <svg
-   className="select-none fill-current text-[48px] font-medium uppercase"
+   className="size-full select-none fill-current text-[48px] font-medium uppercase"
    viewBox="0 0 100 100"
    aria-hidden={alt ? undefined : 'true'}
  >
```

Next, add the `size-full` class to the `Avatar` image:

```diff
- {src && <img src={src} alt={alt} />}
+ {src && <img className="size-full" src={src} alt={alt} />}
```

Finally, add the `inline-grid` class to the `AvatarButton`:

```diff
  let classes = clsx(
    className,
    square ? 'rounded-[20%]' : 'rounded-full',
-   'relative focus:outline-none data-[focus]:outline data-[focus]:outline-2 data-[focus]:outline-offset-2 data-[focus]:outline-blue-500'
+   'relative inline-grid focus:outline-none data-[focus]:outline data-[focus]:outline-2 data-[focus]:outline-offset-2 data-[focus]:outline-blue-500'
  )
```

Thanks again! 👍

**Comment by roomman** [comment]
@reinink, this is amazing, thanks for documenting those changes. 🥳

On a related note, if you drop "MW" in as initials, the text goes edge to edge in the container:
![Screenshot 2024-05-30 at 16 39 44](https://github.com/tailwindlabs/tailwindui-issues/assets/10168451/38264ffa-b655-4fce-b81a-43e9c0dcfc3b)

I added 'p-1' to to the className it looks better for `<Avatar>`
![Screenshot 2024-05-30 at 16 53 46](https://github.com/tailwindlabs/tailwindui-issues/assets/10168451/a7d89944-2214-482c-b871-7ecbf27a99f1)

The same isn't true for `<AvatarButton>` because it the outline 
![Screenshot 2024-05-30 at 17 10 58](https://github.com/tailwindlabs/tailwindui-issues/assets/10168451/762a6239-6960-4801-b3b8-85caf3ae8bea)

Can you recommend a solution to this one? 🙏🏼

**Comment by roomman** [comment]
For now, I've just added `p-1` to the `Avatar` svg. Do let me know if you think there's a better solution.

```diff
  <svg
-   className="select-none fill-current text-[48px] font-medium uppercase"
+   className="size-full select-none fill-current p-1 text-[48px] font-medium uppercase"
    viewBox="0 0 100 100"
    aria-hidden={alt ? undefined : 'true'}
  >
```
Thanks again 👌🏼

**Comment by adamwathan** [comment]
Going to reopen this so we don’t forget about the other issue you raised, definitely want the initials to be rendered the same for regular avatars and button avatars 👍🏻

**Comment by reinink** [comment]
Hello again @roomman 👋

So from what I can tell the `Avatar` and `AvatarButton` components render exactly the same when using the `initials` prop. That said I agree that a little padding would be helpful to keep the text from bumping up against the edge.

To fix this I actually used a percentage based padding (`p-[5%]`), since this scales up automatically for large avatars. Here's how it looks:

<kbd><img width="691" alt="image" src="https://github.com/tailwindlabs/tailwindui-issues/assets/882133/b56d1de5-2303-4423-a607-9171bee8df59"></kbd>

Here's the source code for this demo:

```jsx
<Avatar initials="MW" className="size-6 bg-zinc-500 text-white" />
<AvatarButton initials="MW" className="size-6 bg-zinc-500 text-white" />
<Avatar initials="MW" className="size-8 bg-zinc-500 text-white" />
<AvatarButton initials="MW" className="size-8 bg-zinc-500 text-white" />
<Avatar initials="MW" className="size-10 bg-zinc-500 text-white" />
<AvatarButton initials="MW" className="size-10 bg-zinc-500 text-white" />
```

Note how both the `Avatar` and `AvatarButton` look identical — not sure why you were seeing a difference there. Maybe try download Catalyst from the Tailwind UI website again and grab a fresh copy of the `avatar.tsx` file?

Hope that helps! 🤙
