### ISSUE TITLE
Ordering in the Catalyst docs 

### ISSUE THREAD

**Issue by roomman** [tailwindlabs/tailwindui-issues#1590]
Sorry for being a complete pedant, but Divider and Dialog are in the wrong order (alphabetically) in the Catalyst docs, components side bar. Sorry, I am really not "that guy". 🤦🏻‍♂️

**Comment by reinink** [comment]
Hey! I for one appreciate making sure things are sorted corrected alphabetically, so don't apologize! 😊

That said, I am not sure where you're seeing this, as the items appear to be ordered correctly in the sidebar:

<img width="269" alt="image" src="https://github.com/tailwindlabs/tailwindui-issues/assets/882133/2b148471-0ea5-43c1-af5e-fec8f8670a33">

Are you referring to something in the code maybe? Like maybe some imports or something?

Let me know and I'll get it fixed up 👍

**Comment by roomman** [comment]
My mind is blown (or has blown up!) I was adding a few examples into our Storybook and was sure I'd seen Divider first. Sorry to have wasted your time. 🤣

Happy weekend!

**Comment by reinink** [comment]
Haha all good — have a nice weekend 🤙
