### ISSUE TITLE
Feature request: Secondary navigation components

### ISSUE THREAD

**Issue by poisa** [tailwindlabs/tailwindui-issues#1597]
Would be nice to have designs with secondary navigation in mind. Like https://tailwindui.com/components/application-ui/navigation/navbars but with another line below denoting the secondary nav. When showing this on mobile, secondary nav items could be indented somehow.

I find myself needing this quite often for stuff like CMS navigation bars. I just model them based on the primary nav linked above but my designs are never as good as what I could get from you folks 🙂.

**Comment by reinink** [comment]
Hey thanks for the suggestion! We use this issue tracker strictly for bug reports so going to close this but appreciate the feedback either way! 🤙
