### ISSUE TITLE
Wrong image for modal components 

### ISSUE THREAD

**Issue by florianbouvot** [tailwindlabs/tailwindui-issues#1598]
Modal Dialogs card in Components / Application UI / Overlays display the wrong image:

<img width="416" alt="Capture d’écran 2024-06-12 à 22 05 26" src="https://github.com/tailwindlabs/tailwindui-issues/assets/2061540/8b901abd-01a8-45e5-92da-e4dbcd76c9e0">

;)

**Comment by adamwathan** [comment]
FIXED 😄 Thanks!
