### ISSUE TITLE
Catalyst <Input /> component `onChange` handler is passed full event, not just the value as the docs show

### ISSUE THREAD

**Issue by torra** [tailwindlabs/tailwindui-issues#1600]
**What component (if applicable)**
Catalyst Input component
- URL for category: https://catalyst.tailwindui.com/docs/input#controlled-component
- Component name: Input

**Describe the bug**
When using the Catalyst <Input /> component, if I copy the the example from the documentation, the rendered input component does not correctly update with the value the user types. Instead, it updates with `[Object object]`, as it is casting a javascript Event object to a string.

**To Reproduce**
1. Copy and paste the example usage of an <Input /> component from: https://catalyst.tailwindui.com/docs/input#controlled-component
2. Start typing in the input box
3. Note that the component renders `[object Object]` rather than the string value you entered
4. Update the `onChange` handler to a function for debugging, like: 
```
const handleChange = (e) => {
  console.log(e);
};
```
5. Set a breakpoint in the new `handleChange` function, and note that the value passed into the event handler is an Event object, not the string value as expected based on the documentation.

**Expected behavior**
As the documentation shows, the expected behavior would be for the event handler to be passed the string value of `event.target.value`.

**Screenshots**
Visual example of the problem:
<img width="1184" alt="Screenshot 2024-06-17 at 12 46 44 PM" src="https://github.com/tailwindlabs/tailwindui-issues/assets/3345347/ec1e70cc-09fd-41e3-9adc-ef5f9d6df12e">

**Browser/Device (if applicable)**
 - OS: MacOS
 - Browser Chrome
 - Version 125.0.6422.76 (Official Build) (arm64)

**Additional context**
I also have the same problem with the Textarea component (https://catalyst.tailwindui.com/docs/textarea#controlled-component), but other components, like Listbox and Switch, seem to work as expected from the docs.

**Comment by thecrypticace** [comment]
Ah whoops. Good catch. The `Input`, `Select`, and `Textarea`  components use the event in their `onChange` handler rather than just the value so it's the docs that are incorrect here. I've corrected the examples in the docs. 

Thanks for pointing this out! ✨

**Comment by torra** [comment]
Thanks! Appreciate the quick turnaround.
