### ISSUE TITLE
Need TailwindUI older version that works with older version of HeadlessUI

### ISSUE THREAD

**Issue by naishe** [tailwindlabs/tailwindui-issues#1601]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/marketing/elements/flyout-menus
- Component name: Flyout menu

**Describe the bug**
I need the older version of user interface which does not depend on the latest headless UI. For example, I am currently on `"@headlessui/react": "^1.7.17",` and there's no way that I can get Flyout component from the website because it depends on the latest one.

**To Reproduce**
1. Use an older version of HeadlessUI, e.g. `"@headlessui/react": "^1.7.17",`
2. try to import `PopoverButton, PopoverPanel`

**Expected behavior**
We are a small team and we haven't been able to get a chance to upgrade to the latest HeadlessUI as I have seen there are some changes that require us to change old code and then it ensues testing before releasing. It would be great if I could access the older version of the website which relied on an older version of HeadlessUI. It used to be my central location to quickly copy the components and use in our app.

**Screenshots**
N/A

**Browser/Device (if applicable)**
 N/A

**Additional context**
N/A

**Comment by TarikFojnica** [comment]
From their documentation:

_First and foremost, we understand that not everyone is in a position to drop what they are working on and upgrade to Tailwind CSS v2.0 right away._

_If you purchased a Tailwind UI license before Tailwind CSS v2.0 was released, you will always be able to access the previous version here:_
https://tailwindui.com/v1/components

However, the link is not working. We need all those v1 examples.

**Comment by reinink** [comment]
@naishe Hey! I'm really sorry, but unfortunately there isn't an easy way for us to make all the old components that were based on the previous version of Headless UI available.

I know it's a pain, but if at all possible I'd recommend trying to upgrade to the latest version of Headless UI. You can find a detailed upgrade guide here:

https://github.com/tailwindlabs/headlessui/releases/tag/%40headlessui%2Freact%40v2.0.0

It looks long, but honestly it's really not that bad of an upgrade — there's a bunch of deprecations and only a few actual breaking changes.

I totally get how this is annoying if you have an existing project that uses Headless UI v1.x, but we've always felt that it's important for Tailwind UI to use the latest version of our open source libraries.

That all said, if you have one or two specific components in mind, we might be able to dig those out of version control for you as a one-off. If you'd like us to do that, please fire us an email at support@tailwindui.com and reference this GitHub issue, plus the components you're looking for, and we'll do our best to help you.

Hope that all makes sense, and sorry again for the annoyance ❤️
