### ISSUE TITLE
[Typo] Inconsistent "dark" naming for Footer components

### ISSUE THREAD

**Issue by hyphenzero** [tailwindlabs/tailwindui-issues#1608]
**What component (if applicable)**

* URL for category: [Marketing / Page Sections / Footers](https://tailwindui.com/components/marketing/sections/footers)
* Component name: ["4-column simple dark"](https://tailwindui.com/components/marketing/sections/footers#component-b93739e879ce134b20f93fc9a68df0e1) and every "dark" component below it

**Describe the bug**

The specified components’ names are affixed with "dark" (as in "4-column simple dark")

**To Reproduce**

–

**Expected behavior**

Component names are affixed with "**_on_** dark" (as in "4-column simple on dark"), which is the naming convention that all other "dark" components follow

**Screenshots**

–

**Browser/Device (if applicable)**

–

**Additional context**

–

**Comment by reinink** [comment]
Hey thanks for point this out, I've corrected this 👍
