### ISSUE TITLE
Paid account is not recognized

### ISSUE THREAD

**Issue by pvangundy** [tailwindlabs/tailwindui-issues#1611]
https://tailwindui.com/login

**Describe the bug**
Our paid account is not available anynore.  Email is not recognized.

**To Reproduce**
Tried to login with formerly working password.  No go.  Tried resetting password.  Email not recognized.

**Expected behavior**
Expected to be able to login to TailwindUI website with email associated with paid account.

I could not find a private way to submit a help ticket.

**Comment by reinink** [comment]
Hey! Do you mind reaching out to us at support@tailwindui.com? Happy to help you out there 👍
