### ISSUE TITLE
ts-protocol Template isn't showing the sub-section

### ISSUE THREAD

**Issue by ynnelson** [tailwindlabs/tailwindui-issues#1614]
**Describe the bug**
When I use the protocol template locally the subsection load up just fine but when deploying it to Vercel they stopped working.
This bug also seems to be present in the live preview of Protocol (see the screenshot below). I read issue #1500 but unfortunately it seems to be a different problem. 

**Expected behavior**
I would expect the sub section to show just as they do locally.

**Screenshots**
![image](https://github.com/user-attachments/assets/c0ea4699-3cb0-4a8b-a80f-054fddf318bf)
![image](https://github.com/user-attachments/assets/c75553a9-f28f-47e5-9767-8540f21cc802)

**Comment by ynnelson** [comment]
The issue is the code that generates the section metadata, when deployed to Vercel `allSections` is empty, I wonder if it's because Vercel only has access to the .mdx files at build time and not at Runtime. Thought about using `GetStaticProps` but you can't use that function in the RootLayout only in a page. So alternative would be a prebuild script that generates the data perhaps but that feels like a messy solution.

Any ideas? 

![image](https://github.com/user-attachments/assets/6764c37f-e900-4e20-825b-c7132c0f0021)

**Comment by reinink** [comment]
Hey folks! This is definitely a strange one. This seems to happen randomly, and redeploying seems to fix it. For example:

https://tailwindui-template-protocol-git-protocol-test-tailwindlabs.vercel.app/

Compared that to the production build:

https://protocol.tailwindui.com/

Here's a screenshot, just in case these builds change:

<img width="1938" alt="Screen Shot 2024-08-07 at 3 40 19 PM" src="https://github.com/user-attachments/assets/03b7c622-b53a-442d-b7f1-33f368bf085d">


Not sure exactly what's up here, but I've reached out to our contacts at Vercel to see if they have any suggestions. I'll report back when I know more 👍

**Comment by ynnelson** [comment]
Thank you so much for looking into this!! Super helpful!
