### ISSUE TITLE
Update Tailwind UI Documentation to Use InterVariable Font Family Instead of Legacy Inter var

### ISSUE THREAD

**Issue by nishad** [tailwindlabs/tailwindui-issues#1619]
**What component (if applicable)**
- URL for category: 
- Component name: 

**Describe the bug**

The documentation for [optionally adding the Inter font family](https://tailwindui.com/documentation#optional-add-the-inter-font-family) uses `Inter var` as the font family. However, as per the [official Inter font CSS file](https://rsms.me/inter/inter.css), it was changed to `InterVariable`, and `Inter var` became legacy from October 2023.

**To Reproduce**

**Expected behavior**

The Tailwind UI documentation should reference the updated font family name `InterVariable` instead of the legacy `Inter var`. 

**Screenshots**

<img width="842" alt="image" src="https://github.com/user-attachments/assets/efd5a5ee-8b8f-4538-9b1f-f17bdf2fa304">

**Browser/Device (if applicable)**

**Additional context**

**Comment by adamwathan** [comment]
Thanks, deploying update now 👍
