### ISSUE TITLE
Catalyst: Add Sign-in / Auth Forms to Demo

### ISSUE THREAD

**Issue by gkor** [tailwindlabs/tailwindui-issues#1623]
Really great work guys, thanks so much for releasing Catalyst!

One minor request, would it be possible to add sign in / sign up blocks to the Catalyst demo pages similar to how it is on [catalyst.tailwindui.com](catalyst.tailwindui.com) main page? Obviously understand the issue with state but it would be nice to have them included (maybe off the sign-out link? 🤔) It just looks so good!

Thanks again!

<img width="322" alt="Screenshot 2024-08-25 at 7 17 58 PM" src="https://github.com/user-attachments/assets/42372c6a-786b-4157-8521-53e97397e460">

**Comment by reinink** [comment]
Hey @gkor! I completely agree, it would be awesome if Catalyst shipped with a login page. Honestly kind of surprised we overlooked this 😅

I've made a note of this feature request, and we'll definitely consider it for a future improvement to Catalyst. But given that it's not actually a bug I am going to close this issue, hope that makes sense.

Thanks so much for the kind words as well, glad you're enjoying Catalyst!

**Comment by ramilexe** [comment]
Hi @reinink 
Any updates on it? 
If is still not include into demo but this issue is closed. Why is that?

**Comment by reinink** [comment]
@ramilexe Hey!

> If is still not include into demo but this issue is closed. Why is that?

Just because we use this issue tracker for bugs, not feature requests. This is on our radar though and we hope to get this added to Catalyst in the nearer future 👍
