### ISSUE TITLE
Select Component shows default chevron

### ISSUE THREAD

**Issue by AliMejbar** [tailwindlabs/tailwindui-issues#1624]
**What component (if applicable)**
- URL for category: https://catalyst.tailwindui.com/docs/select
- Component name: Select

**Describe the bug**
Browser default select chevron shows on top of the component's.

**To Reproduce**
- Copy the Select's component code.
- Use it.

**Expected behavior**
For only the component's chevron to show.

**Screenshots**
<img width="196" alt="image" src="https://github.com/user-attachments/assets/12b45add-bcbf-400d-a7c4-407584e324b6">

**Browser/Device (if applicable)**
 - OS: macOS Sequoia beta 15.0 (24A5327a)
 - Browser : Arc Version 1.57.1 (52939) Chromium Engine Version 128.0.6613.85 / Safari Version 18.0 (20619.1.26.31.6) (Both show the bug)
 
 "@headlessui/react": "^2.1.3",
 "@headlessui/tailwindcss": "^0.2.1"
"tailwindcss": "^3.4.10"

**Additional context**
I am using Next.js 15 RC, could have something to do with the problem.

**Comment by mkurtay** [comment]
I am seeing the same issue as well.
![CleanShot 2024-08-31 at 11 04 01@2x](https://github.com/user-attachments/assets/2628bb1e-3f15-409d-b131-52be38291606)

**Comment by ben519** [comment]
You need to remove the Tailwind Forms plugin. See [here](https://github.com/tailwindlabs/tailwindcss-forms/issues/160)

This is also discussed in the Tailwind UI discord [here](https://discord.com/channels/674983035946663957/1270132447396233266)

(Given how many people have been bitten by this, I think Tailwind should do something to address the problem. Perhaps just a note in the catalyst docs.)

**Comment by adamwathan** [comment]
Hey! As @ben519 mentioned it looks like you have `@tailwindcss/forms` installed which conflicts with Catalyst — Catalyst already has all of the form styles necessary for each component applied directly in the component markup. Either remove the plugin, or switch to the `class` strategy so you can opt-in to it as needed for things that aren't using Catalyst 👍

**Comment by AliMejbar** [comment]
Thank's to the both of you @ben519 @adamwathan !
