### ISSUE TITLE
Error in Global Search Functionality

### ISSUE THREAD

**Issue by shyam0118** [tailwindlabs/tailwindui-issues#1628]
I encountered an issue with the global search box on the [tailwindui.com](https://tailwindui.com/) website. When searching for content and then clearing the search input, an error is thrown in the browser console.

**To Reproduce**
1. Go to [tailwindui.com](https://tailwindui.com/).
2. Type any search term in the global search box.
3. Clear the search input field (delete all text).
4. Open the browser console (F12 or right-click and "Inspect").
5. You will see the following error message:

"TypeError: Cannot read properties of null (reading 'url')"

**Expected behavior**
No error should be thrown when clearing the search box after performing a search.

**Browser/Device (if applicable)**
 - OS: [e.g. linux]
 - Browser [e.g. chrome]

**Additional context**
Please let me know if any additional information is needed to assist with troubleshooting. Thank you!

**Comment by reinink** [comment]
Hey, thanks for letting us know, this has been fixed! 🙏
