### ISSUE TITLE
Broken images when clicking to home page from a blog post in Radiant template

### ISSUE THREAD

**Issue by okleahcim** [tailwindlabs/tailwindui-issues#1631]
**Describe the bug**
When you navigate from a blog post directly back to the home page. A lot of the images on the main site are suddenly broken. It fixes if you refresh the page. 

**To Reproduce**
1. Go to https://radiant.tailwindui.com/blog/radiant-raises-100m-series-a-from-tailwind-ventures 
2. Click on the radiant logo icon in top left
3. Scroll down and see all the images broken

**Expected behavior**

**Screenshots**

**Browser/Device (if applicable)**
- MacOS latest version
- Safari latest version

**Additional context**
This is also broken on my site using the template as well.

**Comment by reinink** [comment]
Hello again @okleahcim! 👋

This is a strange one — this only happens (at least for me) in Safari and not in Chrome. There is something funky going on here with Next.js and relative image paths. The solution here is to just use absolute paths for all images — we probably should have just done this from the beginning.

Again, I've published an updated version of Radiant, but if you want to fix this yourself you can simply look for all images that use a relative path and update them to absolute paths by removing the leading period.

For example, in the `/src/components/testimonials.tsx` file:

```diff
  const testimonials = [
    {
-     img: './testimonials/tina-yards.jpg',
+     img: '/testimonials/tina-yards.jpg',
      name: 'Tina Yards',
      title: 'VP of Sales, Protocol',
      quote:
        'Thanks to Radiant, we’re finding new leads that we never would have found with legal methods.',
    },
```

Thanks again! 🙏
