### ISSUE TITLE
Incorrect date within blog post in Radiant Template

### ISSUE THREAD

**Issue by okleahcim** [tailwindlabs/tailwindui-issues#1632]
**What component (if applicable)**
- URL for category: https://radiant.tailwindui.com/blog/radiant-raises-100m-series-a-from-tailwind-ventures
- Component name:  Sanity blog post

**Describe the bug**
Date within blog post does not match dates within sanity or on the blog list page

**To Reproduce**
1. Go to https://radiant.tailwindui.com/blog and see the date on any blog post
2. Click into that blog post and see that the date does not match

**Expected behavior**
I expected the dates to match.

**Screenshots**
See screenshots below.
![right date](https://github.com/user-attachments/assets/c8a780a6-bdff-4321-a2b1-42905d40331a)
![wrong date](https://github.com/user-attachments/assets/18690cae-9279-4973-9440-a049b9060679)

**Browser/Device (if applicable)**
 - MacOS latest version
 - Safari latest version

**Additional context**
Radiant template.

**Comment by reinink** [comment]
Nice catch! Looks like we somehow had the wrong date format on the blog post page.

I've just published an updated version of Radiant that includes a fix for this, but if you'd like you can fix this in your project by updating the `/src/app/blog/[slug]/page.tsx` file:

```diff
- {dayjs(post.publishedAt).format('dddd, MMMM M, YYYY')}
+ {dayjs(post.publishedAt).format('dddd, MMMM D, YYYY')}
```

Thanks for making us aware of this! 💪
