### ISSUE TITLE
Input Group borders are not visible in Windows high contrast themes

### ISSUE THREAD

**Issue by bsully75** [tailwindlabs/tailwindui-issues#1635]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/forms/input-groups
- Component name: Input groups

**Describe the bug**
The Input Group borders are not visible in Windows high contrast themes.

**To Reproduce**
1. Go to https://tailwindui.com/components/application-ui/forms/input-groups
2. Open Windows Settings > Accessibility > Contrast themes
3. Select any contrast theme
4. Select the Apply button
5. Return to the browser
6. See error

**Expected behavior**
The Input Group borders should be visible in Windows high contrast themes.

**Screenshots**
Screenshot of Input Group showing the borders are visible:

![Screenshot of Input Group showing the borders are visible](https://github.com/user-attachments/assets/7d235eed-9045-45f8-8e21-344ddb799f8d)

Screenshot of Input Group in Windows high contrast theme showing the borders are not visible:

![Screenshot of Input Group in Windows high contrast theme showing the borders are not visible](https://github.com/user-attachments/assets/a06aa558-c28b-46b5-869d-c19df504b3c0)

**Browser/Device (if applicable)**
 - OS: Windows 11
 - Browser: Chrome 130.0.6723.59 and Firefox 131.0.3

**Additional context**
You can try using the `contrast-more` modifier to add a 1px outline only in high contrast mode. Below is an example. I haven't tried this on input groups that use add-ons or icons. This was just something off the top of my head.

`contrast-more:outline contrast-more:outline-1 contrast-more:outline-gray-300 contrast-more:focus:outline-offset-0`

You can see an example of this in Tailwind Play: https://play.tailwindcss.com/lGoBBcbOF9

**Comment by reinink** [comment]
Hey thanks for bringing this to our attention! We're actually already working on a more significant update to modernize the inputs and other form elements in Tailwind UI, and part of this will include insuring they work well in forced-colors mode. I'll report back here when that work has been completed 👍

**Comment by reinink** [comment]
Hey thanks again for reporting this issue! We just pushed a significant update to Tailwind UI that updates all inputs, selects and textareas to use outlines instead of rings (shadows), which works much nicer in forced-colors mode. Give that a try and let me know if you run into any issues! 👍
