### ISSUE TITLE
Catalyst Fieldset API documentation needs correcting

### ISSUE THREAD

**Issue by roomman** [tailwindlabs/tailwindui-issues#1638]
**What component (if applicable)**
- URL for category: https://catalyst.tailwindui.com/docs/fieldset#component-api
- Component name: Fieldset

**Describe the bug**
The documentation states that the component API allows for a `layout` prop that is not accounted for in the implementation.

**To Reproduce**
1. Render <Fieldset layout={false}> 

**Expected behavior**
Prevent styles being applied to children.

**Comment by reinink** [comment]
Hey good catch @roomman!

We had experimented with the `layout` prop while building Catalyst but ultimately decided that just using components directly from `@headlessui/react` to implement custom layouts made more sense!

I've corrected the docs — thanks! 🙏
