### ISSUE TITLE
Catalyst `DropdownItem` not disabled.

### ISSUE THREAD

**Issue by onehorsetown** [tailwindlabs/tailwindui-issues#1640]
**What component (if applicable)**
Catalyst
- URL for category:  https://catalyst.tailwindui.com/docs/dropdown#with-disabled-items
- Component name: DropdownItem

**Describe the bug**
DropdownItem is not disabled as one would expect. 

**To Reproduce**
1. Go to '...'   https://catalyst.tailwindui.com/docs/dropdown#with-disabled-items
2. Click on '....'  Options
4. See error: `Rename` menu item is not disabled.

**Expected behavior**
`Rename` menu item in example should be disabled.

**Screenshots**
<img width="601" alt="Dropdown Example" src="https://github.com/user-attachments/assets/3b13034b-9085-4c38-85a2-eaaa16b5fcca">

**Browser/Device (if applicable)**

**Additional context**
To fix this, I had the `DropdownItem` pick off the `disabled` property and pass it to the `Headless.MenuItem` as in:

```
export function DropdownItem({
  className,
  disabled,
  ...props
}: ... )) {
...
  return (
    <Headless.MenuItem disabled={disabled}>...
}
```

**Comment by reinink** [comment]
Hey! Thanks so much for bringing this to our attention. It appears that we broke this prop while trying to fix some type issues.

I've just published an updated version of Catalyst, which you can download from the Tailwind UI website, or you can keep the fix that you've already made (which totally works!), or if you want you can apply the changes we've made to the `DropdownItem` component:

First, update the types:

```diff
    }: { className?: string } & (
-     | Omit<React.ComponentPropsWithoutRef<'button'>, 'as' | 'className'>
-     | Omit<React.ComponentPropsWithoutRef<typeof Link>, 'className'>
+     | Omit<Headless.MenuItemProps<'button'>, 'as' | 'className'>
+     | Omit<Headless.MenuItemProps<typeof Link>, 'as' | 'className'>
    )) {
```

Next, update the return statement:

```diff
-   return (
-     <Headless.MenuItem>
-       {'href' in props ? (
-         <Link {...props} className={classes} />
-       ) : (
-         <button type="button" {...props} className={classes} />
-       )}
-     </Headless.MenuItem>
-   )
+   return 'href' in props ? (
+     <Headless.MenuItem as={Link} {...props} className={classes} />
+   ) : (
+     <Headless.MenuItem as="button" type="button" {...props} className={classes} />
+   )
```

I hope that helps, and thanks again! 🙏
