### ISSUE TITLE
Border of collapsed table rows combine in color

### ISSUE THREAD

**Issue by ben519** [tailwindlabs/tailwindui-issues#1644]
Observe this example of a basic [`Table`](https://catalyst.tailwindui.com/docs/table).

```js
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/table'

<Table>
  <TableHead>
    <TableRow>
      <TableHeader>Foo</TableHeader>
      <TableHeader>Bar</TableHeader>
    </TableRow>
  </TableHead>
  <TableBody>
    <TableRow>
      <TableCell>foo 1</TableCell>
      <TableCell>bar bar 1</TableCell>
    </TableRow>
    <TableRow>
      <TableCell>foo 2</TableCell>
      <TableCell>bar bar bar bar bar 2</TableCell>
    </TableRow>
    <TableRow>
      <TableCell>foo foo foo 3</TableCell>
      <TableCell>bar 3</TableCell>
    </TableRow>
  </TableBody>
</Table>
```

<img width="578" alt="Screenshot 2024-11-07 at 10 45 03 AM" src="https://github.com/user-attachments/assets/99578307-963d-408c-bc89-9ce4f68afceb">

In my app, the table rows are filterable. (E.g. via a search term). To displayed filtered rows, I hide various rows using the [`collapse`](https://tailwindcss.com/docs/visibility#collapsing-elements) class.

```js
<Table>
  <TableHead>
    <TableRow>
      <TableHeader>Foo</TableHeader>
      <TableHeader>Bar</TableHeader>
    </TableRow>
  </TableHead>
  <TableBody>
    <TableRow className="collapse">
      <TableCell>foo 1</TableCell>
      <TableCell>bar bar 1</TableCell>
    </TableRow>
    <TableRow className="collapse">
      <TableCell>foo 2</TableCell>
      <TableCell>bar bar bar bar bar 2</TableCell>
    </TableRow>
    <TableRow>
      <TableCell>foo foo foo 3</TableCell>
      <TableCell>bar 3</TableCell>
    </TableRow>
  </TableBody>
</Table>
```

<img width="597" alt="Screenshot 2024-11-07 at 10 45 41 AM" src="https://github.com/user-attachments/assets/71aa75b3-dc27-40ec-963b-7d8b34ae455a">

As you can see in the image above, this creates the undesired affect of stacking the row borders on top of one another to produce a weird, very dark border. When you have a table with hundreds of rows and various, random rows are collapsed, it looks extra weird.

Perhaps this is not a "bug", I would call it an "issue". And I can't figure out a simple CSS patch to fix it.

**Comment by reinink** [comment]
Hey! Thanks for reporting this. That's a weird rendering anomaly that I wouldn't have expected considering that the cells within that row are supposed to be hidden.

Either way, the trick to fixing this is to just hide the borders on cells that exist in a collapsed row. You can do this with an arbitrary modifier:

```html
<TableRow className="collapse [&>*]:border-b-0">
```

This has me thinking that it might be nice to add an `collapsed` prop on the `TableRow` component that does this automatically. If we end up implementing that I'll be sure to report back here.

Hope that helps! 👍

**Comment by reinink** [comment]
Hey just a follow up on this — you may not want to use `collapse` at all. Unfortunately, support for `visibility: collapse` isn't great in Safari — it hides the content, but keeps the space it contained, so you end up with weird gaps. Probably better to just use `display: none` or conditionally render this content.

**Comment by ben519** [comment]
Hmm, interesting..

I used to render the data dynamically instead of hiding rows with CSS but then the table column widths recalculate which is _really_ annoying. (See [here](https://stackoverflow.com/questions/25807564/hiding-a-tr-while-still-involving-it-in-width-calculations))

Thanks for the heads up.

**Comment by reinink** [comment]
Totally, it's a really nice CSS feature in principle for that exact reason, unfortunately Safari just does a terrible job with it 😕

**Comment by ben519** [comment]
Note:

Someone suggested using `line-height: 0` but I just realized that Tailwind doesn't have a class for that. I find that really strange. In fact, it seems `leading-none` resolves to `line-height: 1`, according to the [docs](https://tailwindcss.com/docs/line-height). Weird.
