### ISSUE TITLE
Landing Page footer link is not clickable

### ISSUE THREAD

**Issue by ravibpatel** [tailwindlabs/tailwindui-issues#1645]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/marketing/page-examples/landing-pages
- Component name: [With large screenshot and testimonial](https://tailwindui.com/components/marketing/page-examples/landing-pages#component-09a9f8bd8b212b82cada14de363e1c02)

**Describe the bug**
The first link on the right side of the footer is not clickable. 

**To Reproduce**
1. Go to Footer
2. Click on first link on right side

**Expected behavior**
The link should be clickable.

**Browser/Device (if applicable)**
 - OS: Windows 11 24H2
 - Browser Firefox
 - Version 132.0.2

**Additional context**
It is happening cause the following element is overlapping the right side of the footer.

```html
<div aria-hidden="true"
     class="absolute left-1/2 right-0 top-full -z-10 hidden -translate-y-1/2 transform-gpu overflow-hidden blur-3xl sm:block">
    <div class="aspect-[1155/678] w-[72.1875rem] bg-gradient-to-tr from-[#ff80b5] to-[#9089fc] opacity-30" style="clip-path: polygon(74.1% 44.1%, 100% 61.6%, 97.5% 26.9%, 85.5% 0.1%, 80.7% 2%, 72.5% 32.5%, 60.2% 62.4%, 52.4% 68.1%, 47.5% 58.3%, 45.2% 34.5%, 27.5% 76.7%, 0.1% 64.9%, 17.9% 100%, 27.6% 76.8%, 76.1% 97.7%, 74.1% 44.1%)" />
</div>
```

**Comment by reinink** [comment]
Hey, thanks for reporting this bug! I've just pushed up a fix for this, but if you'd like to fix this in your app directly simply add the "relative" class to the footer:

```diff
    <!-- Footer -->
-   <footer class="mx-auto mt-32 max-w-7xl px-6 lg:px-8">
+   <footer class="relative mx-auto mt-32 max-w-7xl px-6 lg:px-8">
      <div class="border-t border-gray-900/10 py-16 sm:py-24 lg:py-32">
```

Hope that helps! 🤙
