### ISSUE TITLE
Syntax template - Unable to build

### ISSUE THREAD

**Issue by Fyroeo** [tailwindlabs/tailwindui-issues#1646]
**What component (if applicable)**
- URL for category: https://tailwindui.com/templates/syntax/
- Component name: Syntax template

**Describe the bug**
It is currently impossible to build the Syntax template using the downloaded sources. The build fails with the following error :

```
Failed to compile.

./src/components/Layout.tsx + 10 modules
Unexpected end of JSON input

./node_modules/@headlessui/react/dist/components/listbox/listbox.js + 34 modules
Unexpected end of JSON input

./src/markdoc/search.mjs + 1 modules
Unexpected end of JSON input


> Build failed because of webpack errors
```

But, the project works in the dev environment (npm run dev/yarn dev)

**To Reproduce**
1. Download the template
2. Install the dependencies (npm install / yarn install)
3. Try to make a build (npm run build / yarn build)

The build will fail.

**Expected behavior**
The project should be built.

**Screenshots**

**Browser/Device (if applicable)**
 - OS: macOS Sequoia 15.1
 - Browser: Safari
 - Version: 18.1

**Additional context**

**Comment by Fyroeo** [comment]
Hey!
The node version was indeed the culprit; I didn't think about this before making the issue. I was using the current version instead of the LTS. My bad!
Therefore, it works on the 22 LTS but not on 23.2.0 (current).

Sorry for wasting your time 🙁

**Comment by reinink** [comment]
@Fyroeo all good! Glad we got it figured out 👍
