### ISSUE TITLE
SVG issues with Hero component with image tiles

### ISSUE THREAD

**Issue by akoutmos** [tailwindlabs/tailwindui-issues#1648]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/marketing/sections/heroes?include=archived#component-a4b2f622985371f413e0d6c13309d389
- Component name: Heros with image tiles

**Describe the bug**
When the SVG tiling background is rendered, there are a few tiles where the fill color is black.

**To Reproduce**
1. Go to the component linked above
2. Click on the copy to clipboard button
3. Paste the code into my project
4. See error when the SVG background is rendered.

**Expected behavior**
Expect the copy and pasted template to look like it does in the preview section.

**Screenshots**
<img width="1400" alt="image" src="https://github.com/user-attachments/assets/d68923a4-f4dc-4c7b-9dfe-8b308ecffba4">

**Browser/Device (if applicable)**
 - OS: MacOs
 - Browser Brave & Safari
 - Version Brave 1.67.115, Safari 17.5

**Comment by reinink** [comment]
Hey! So it looks like you maybe don't have `gray-50` in your theme. When I remove the `fill-gray-50` from this component, I get the same results. Is it possible that you've customized your color scheme and removed this color?

<kbd><img width="1261" alt="image" src="https://github.com/user-attachments/assets/3f8bca7a-3331-49d5-a266-e6ccfd274d06"></kbd>

**Comment by akoutmos** [comment]
Thank you so much Jonathan!!! Looks like gray was indeed missing from the tailwind.config.js fill section. User error 😆.

**Comment by reinink** [comment]
Awesome, glad we got it figured out quickly! 🤙
