### ISSUE TITLE
Input fields have thicker corners and dropdowns have 2 arrows.

### ISSUE THREAD

**Issue by divpala1** [tailwindlabs/tailwindui-issues#1650]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/forms/form-layouts
- Component name: All forms (basically any input field)

**Describe the bug**
So I am using the tailwind forms. I have used it for my earlier projects also. I recently made a new project, setup tailwind and got the forms HTML from the URL above. But this time the corners of all the input fields appeared thicker. Also, they had a rectangle box behind the input field. It was visible since the corners of the input behind were not rounded. At first I believed the issue was with my process of setting up the Tailwind. So I cloned my earlier project and tried the form in that. And so it turns out that the forms I used in that are working properly. But if I copy-pasted the code from the URL above into it, then the input fields' CSS was all messed up along with the dropdowns. They have got two down arrows.

**To Reproduce**
1. Go to 'https://tailwindui.com/components/application-ui/forms/form-layouts' > any form.
2. Copy-paste the form code.
3. See the input field and dropdowns messed up.

**Expected behavior**
The form to be visible as they are on the URL.

**Screenshots**
![image](https://github.com/user-attachments/assets/b7c8a644-6d5b-42a5-b763-736f891f9fd5)
![image](https://github.com/user-attachments/assets/2e9191fd-d264-4020-bfcd-777a57402e79)

**Browser/Device (if applicable)**

**Additional context**

**Comment by reinink** [comment]
Hey there! Happy to help out here.

So the simple fix is to remove the Tailwind CSS forms plugin (`@tailwindcss/forms`) from your project.

We recently updated all the inputs, textareas, select menus, checkboxes, and radio groups in Tailwind UI to no longer depend on this plugin. While the forms plugin has been helpful, modern browser CSS capabilities have reduced our reliance on it. For example:

- **Accent color support** now allows tweaking the colors of checkboxes and radio groups directly.
- **Outline utilities** can replace rings (shadows) for focus styles, as Safari now supports outlines with border radiuses.

Looking ahead—especially with the upcoming release of Tailwind CSS v4—we decided to move away from the forms plugin and include the necessary form styles directly with the components in Tailwind UI. This approach has several benefits:

- **More explicit styling**: No more hidden styles from the plugin; everything is directly in your markup.
- **Easier customization**: You can edit the form control HTML directly.
- **Simpler setup**: No need to install or configure an additional plugin.

We recognize this might be inconvenient if you're adding new form controls from Tailwind UI to an existing project that still uses the forms plugin. In such cases, you can configure the forms plugin to use the `class` strategy and apply its styles only where needed. Here's how:

```js
// tailwind.config.js
plugins: [
  require("@tailwindcss/forms")({
    strategy: 'class', // only generate classes
  }),
],
```

Then, update your existing form inputs to include the appropriate class:

```diff
- <input class="...">
+ <input class="form-input ...">
```

You can find a list of all the available classes in the forms plugin documentation here:

https://github.com/tailwindlabs/tailwindcss-forms?tab=readme-ov-file#using-classes-to-style

I totally understand this might be a bit of a hassle, we just feel like it's important that Tailwind UI always reflects the best way we know how to do things, so this felt like a necessary change.

Hopefully, this helps! 👍

**Comment by lancechentw** [comment]
Hey @reinink, thanks for the thorough explanation of the causes and fixes. I wonder if there will be any sort of official announcement or a alert or comments besides the affected components addressing this issue? That will surely save people hours from digging their code bases and questioning themselves what have they changed that could possibly break the styling and sneak under git's mighty monitoring. :p

**Comment by jason-beach** [comment]
@reinink , thanks for the explanation on this. I have an app which is huge with tons of forms so this is quite cumbersome. I've transitioned to TWv4 and removed the forms plugin and all the new inputs look good but the others are showing a blue border on focus. I'm assuming your fix for the tailwind.config.js will resolve that, however, since TWv4 doesn't require a tailwind.config.js how would I achieve this in the app.css file? Or is it not possible and I need to bring back the tailwind.config.js? Appreciate your suggestion on how to handle that.

```
plugins: [
  require("@tailwindcss/forms")({
    strategy: 'class', // only generate classes
  }),
],
```

**Comment by reinink** [comment]
@jason-beach Good question! Here's how:

```css
@plugin "@tailwindcss/forms" {
  strategy: 'class';
}
```

Cheers 🤙

**Comment by jason-beach** [comment]
@reinink , thanks for the fast response. I found the solution in another issue and came back here to delete my comment but you responded as I deleted. Thanks!
