### ISSUE TITLE
Official TailwindUI component for billing / payments / checkout forms

### ISSUE THREAD

**Issue by connecteev** [tailwindlabs/tailwindui-issues#166]
Official TailwindUI component for checkout forms (credit cards, subscriptions)

**Screenshots**

- If using Stripe, it would be nice to have the interactivity like 
https://c45nv.sse.codesandbox.io/ (note this example does not use an iframe)
https://stripe.dev/elements-examples/

- If not using Stripe, it could be like https://tailwindcomponents.com/component/checkout-form
(but this example is clunky at best)

**Comment by Christophvh** [comment]
Input-groups + the form-layouts handle all these use-cases?

**Comment by connecteev** [comment]
You find payments and subscriptions in a lot of apps. it would be very useful to have these in tailwindui and not start from scratch.

**Comment by simonswiss** [comment]
Consolidating with https://github.com/tailwindlabs/tailwindui-issues/issues/268 - ecommerce components is definitely something we're thinking about! 👍
