### ISSUE TITLE
Square Image Button Toggle

### ISSUE THREAD

**Issue by pdevito3** [tailwindlabs/tailwindui-issues#167]
Hey Adam, might be cool to add in the special toggle with images that you made in the kanban board video. In this case, it was toggling between a list view and a board view, but it could use any two svgs.

**Screenshots**
For reference to the control I mentioned, see [here](https://youtu.be/_H38A6E8Nsg?t=2910)

**Additional context**
Hopefully this would be quick since it's mostly built already? If not, this is what I put together:
```html
<span class="p-3px inline-flex bg-gray-200 border rounded-md">
            <button 
              @click="ingredientView = ListView" 
              class="px-2 py-1 rounded focus:outline-none"
              :class="ingredientView == ListView ? 'bg-white shadow' : ''">
              <svg class="w-5 h-5 text-gray-600" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24"><path d="M4 6h16M4 10h16M4 14h16M4 18h16"></path></svg>
            </button>
            
            <button 
              @click="ingredientView = BatchView" 
              class="px-2 py-1 rounded focus:outline-none"
              :class="ingredientView == BatchView ? 'bg-white shadow' : ''">
              <svg class="w-5 h-5 text-gray-600" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24"><path d="M7 21h10a2 2 0 002-2V9.414a1 1 0 00-.293-.707l-5.414-5.414A1 1 0 0012.586 3H7a2 2 0 00-2 2v14a2 2 0 002 2z"></path></svg>
            </button>
</span>
```

**Comment by simonswiss** [comment]
Hello! 👋

Would the "Icon Only" button group example be doing what you're looking for?

https://tailwindui.com/components/application-ui/elements/button-groups#component-0d33369a2dac81cc4ed2f8b1e997a9cb

**Comment by pdevito3** [comment]
Hey Simon, it's similar, but has state change depending on which button is active and which isn't. That would obviously require JS to some degree, but for the TUI side, there isn't a component that describes what an active/inactive state might look like for these.

Here's a timestamp of his build: https://youtu.be/_H38A6E8Nsg?t=2883

**Comment by simonswiss** [comment]
Right, I see what you mean!

![image](https://user-images.githubusercontent.com/485747/90355545-014da680-e090-11ea-8346-f28b1b24228e.png)

I have captured this suggestion in our Trello roadmap in the new "ideas" column. What's in there is not guaranteed to be built, but it allows people to upvote what they'd like to see implemented in the future.

You can find this suggestion here: https://trello.com/c/faS9fvtD/98-square-icon-button-toggle-switch

Thanks again - will close this issue now, but please go upvote that suggestion in Trello! 👍
