### ISSUE TITLE
Wizard - Form Layout

### ISSUE THREAD

**Issue by DanHarrin** [tailwindlabs/tailwindui-issues#17]
**Screenshots**
![Wireframe](https://miro.medium.com/max/4176/1*qZF8hLpB3eaIo4LSYleR-A.jpeg)
![Implemented examples](https://miro.medium.com/max/3584/1*NS93dbpEd1dtPzVsRj170g.png)

**Additional context**
The existing form layouts we have are good, but it would be nice if we also had a basic form wizard layout as well. It would be especially useful for dividing up long forms into less intimidating sections, whilst supporting new users by guiding them through a process step by step.

My ideal implementation of this would be a wrapper around the existing form layouts that shows the progress of the user through the wizard, and next / previous buttons.

**Comment by mgibas** [comment]
This would be awesome!

**Comment by DanHarrin** [comment]
I've made a [quick prototype](https://codepen.io/danharrin/full/gOpRBZj) of how it could look - still needs a bit of fine tuning though.

![Screenshot 2020-03-02 at 10 41 09](https://user-images.githubusercontent.com/41773797/75669119-5b89b500-5c72-11ea-8466-cc205cda24f3.png)

**Comment by mgibas** [comment]
There is already planed component like that: Application UI => Navigation => Steps

**Comment by DanHarrin** [comment]
Nice, didn't notice that one! My [prototype](https://codepen.io/danharrin/full/gOpRBZj) has next / previous buttons too.

**Comment by dillingham** [comment]
@DanHarrin probably shouldnt publish snippets that contain so much paid content

**Comment by simonswiss** [comment]
Captured this suggestion in our "bag of ideas" on the roadmap.

https://trello.com/c/SQfKHM4g/94-multi-step-forms

We're about to shit steps components, but they are not including examples with forms in each steps! 😅
