### ISSUE TITLE
Visual states

### ISSUE THREAD

**Issue by kotfire** [tailwindlabs/tailwindui-issues#171]
Would be great to have examples of visual states (disabled, active, focus) for every component.

There are some existing requests but they are specific to some states for a component:
Disabled button states #109
Pagination suggestion: disabled/active #4

**Comment by simonswiss** [comment]
Thanks for suggesting this!

I have captured it internally. It's not something we're going to build _right now_ due to the various other projects we're currently pushing forward, but if the demands keeps coming, we'll consider implementing more "stateful" examples for our existing components. 👍
