### ISSUE TITLE
Missing input groups (Checkboxes / Radio-buttons )

### ISSUE THREAD

**Issue by Christophvh** [tailwindlabs/tailwindui-issues#172]
Hi, currently radio-buttons and checkboxes are available on the Form layouts or Sign-in layouts.

When you need a single checkbox they are not that easy to port-over. It would be nice to add them to the Input groups section.

![Screenshot 2020-04-23 at 11 21 09](https://user-images.githubusercontent.com/9588070/80082458-b514ae80-8554-11ea-95a6-743633a90cad.png)

Example:
![Screenshot 2020-04-23 at 11 24 47](https://user-images.githubusercontent.com/9588070/80082742-12a8fb00-8555-11ea-89a6-b00567c22439.png)

**Comment by simonswiss** [comment]
Thanks for the suggestion! 👍

I am porting the component suggestions to an "ideas" column in the Trello roadmap. I'll close this issue, but you can find this request here: https://trello.com/c/gTNr7K7h/57-checkbox-radio-in-input-groups-section
