### ISSUE TITLE
wrapper for <input type="file">

### ISSUE THREAD

**Issue by jhancock** [tailwindlabs/tailwindui-issues#176]
I'd like a button for selecting a file

**Comment by J05HI** [comment]
Definitly!

**Comment by nassan** [comment]
Voting for this.

**Comment by labnol** [comment]
+1

**Comment by simonswiss** [comment]
I like that suggestion!

I am porting the component suggestions to an "ideas" column in the Trello roadmap. I'll close this issue, but you can find this request here: https://trello.com/c/WdDvvJGC/55-file-upload-input
