### ISSUE TITLE
Compact Version of Controls & Layouts

### ISSUE THREAD

**Issue by vangundy** [tailwindlabs/tailwindui-issues#179]
Many users find ‘compact’ themes very useful when generating a highly dense, data-intensive UI.
Please provide a ‘compact’ theme for the controls and layouts.
## Compact
![image](https://user-images.githubusercontent.com/1762926/80416662-59666000-8889-11ea-8d05-b9681e396272.png)

## Vs. Regular (for comparison)
![image](https://user-images.githubusercontent.com/1762926/80416992-ddb8e300-8889-11ea-8490-da179551151f.png)

**Comment by simonswiss** [comment]
Thanks for the suggestion! 

Porting the component suggestions to an "ideas" column in the Trello roadmap. I'll close this but you can find this request in the roadmap here: https://trello.com/c/nlKiYuxt/54-smaller-form-controls-variant
