### ISSUE TITLE
Date Selector Styling - "date" input type

### ISSUE THREAD

**Issue by niravmehta** [tailwindlabs/tailwindui-issues#18]
HTML5 date selector (input type="date") looks terrible as it is. Would love to get Tailwind styling for it!

**Screenshots**
<img width="101" alt="date-selector" src="https://user-images.githubusercontent.com/822681/75659637-50458200-5c90-11ea-91b1-5e10a6bf9c0f.png">

That's how it looks currently.

**Additional context**
Mainly the width, and styling for steppers as well as "chevron" / triangle that opens the date calendar.

**Comment by DanHarrin** [comment]
Note: `<input type="date">` is not supported by Safari, so I'm not sure if it's worth supporting or not?

A better solution could be customising a third party date picker to follow Tailwind UI design standards.

**Comment by DanHarrin** [comment]
Related to #54

**Comment by simonswiss** [comment]
Thanks for suggesting this! 👍

I have captured this separately from #54, since date pickers and native date input are two different things.

https://trello.com/c/II0Uy1Rb/93-pretty-native-date-input
