### ISSUE TITLE
Color picker

### ISSUE THREAD

**Issue by J05HI** [tailwindlabs/tailwindui-issues#181]
It would be amazing to have a color picker.

https://element.eleme.io/#/en-US/component/color-picker

![image](https://user-images.githubusercontent.com/16399787/80518948-7da86680-8987-11ea-8971-4d7004b18101.png)

https://dribbble.com/shots/7917603-Color-Picker-DailyUI-day060

![image](https://cdn.dribbble.com/users/1231641/screenshots/7917603/media/eb2dbd3bae888436eb92b4f59423a025.png)

**Comment by atomgiant** [comment]
Here is the one I built in case you find it useful:
![flair-tailwind-colorpicker](https://user-images.githubusercontent.com/21659/82897928-6b89fb80-9f26-11ea-910a-271a52c6242e.gif)

It uses the full Tailwind color palette as the defaults, and is a heavily modified version of: https://github.com/Simonwep/pickr

**Comment by J05HI** [comment]
Hello @atomgiant 
Your color picker looks awesome! Would you mind sharing your modified version?
Thank you!

**Comment by atomgiant** [comment]
@J05HI I don't have this in a sharable form at the moment.  I am basically just hiding all the built-in pickr controls and drawing the color palette and shades myself.  If I whip this up as a workable example I'll update this thread.

**Comment by J05HI** [comment]
Okay thanks!

**Comment by simonswiss** [comment]
Thanks for the suggestion! 

Porting the component suggestions to an "ideas" column in the Trello roadmap. I'll close this but you can find this request in the roadmap here: https://trello.com/c/RfX6W4m5/53-color-picker
