### ISSUE TITLE
Tree view

### ISSUE THREAD

**Issue by J05HI** [tailwindlabs/tailwindui-issues#182]
It would be amazing to have a tree view.

https://element.eleme.io/#/en-US/component/tree

![image](https://user-images.githubusercontent.com/16399787/80519465-51d9b080-8988-11ea-9fc9-8c6ef461bbbc.png)
---
![image](https://user-images.githubusercontent.com/16399787/80519496-5f8f3600-8988-11ea-8e80-97bcba728203.png)

**Comment by simonswiss** [comment]
Thanks for the suggestion! 

Porting the component suggestions to an "ideas" column in the Trello roadmap. I'll close this but you can find this request in the roadmap here: https://trello.com/c/oupB2Ges/52-tree-view
