### ISSUE TITLE
Divide and space update to components

### ISSUE THREAD

**Issue by rsm23** [tailwindlabs/tailwindui-issues#184]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/lists/wide
- Component name: Wide Lists

**Describe the bug**
This is not a bug but more like a feature request, when will the transition to "space" and "divide" be done?
Just to get rid of "`if i > 0` add this class"

**Comment by herpaderpaldent** [comment]
just came here to state the same. It would probably also help simplify other components where margin left or right was needed, could be replaced with `space-x-{}`

**Comment by simonswiss** [comment]
Just wanted to let you know this is something we're definitely thinking of implementing. 

All the new components are using these spacing/divide utilities, and we ideally want to update all instance of "internal spacing" to use these parent level utilities too!

I'll close this issue, but rest assured this is in our radar. 👍
