### ISSUE TITLE
Beautiful hover style for checkboxes and checkbox sections

### ISSUE THREAD

**Issue by connecteev** [tailwindlabs/tailwindui-issues#185]
Love this hover style for checkboxes and checkbox sections. It would be great to add this to tailwindUI!
https://twitter.com/_philippkuehn/status/1255089435953242113?s=12

**Comment by J05HI** [comment]
I like them too!
Please add them.

**Comment by LouisCuvelier** [comment]
This is so neat 😍

**Comment by simonswiss** [comment]
These look great! 😻

Porting the component suggestions to an "ideas" column in the Trello roadmap. I'll close this but you can find this request in the roadmap here: https://trello.com/c/yZbLi53C/51-checkbox-groups 👍
