### ISSUE TITLE
Spinner :)

### ISSUE THREAD

**Issue by andriy-andriyuk** [tailwindlabs/tailwindui-issues#187]
It would be really nice to have something like a spinner component, please :)

**Comment by J05HI** [comment]
@andriy-andriyuk something like this?
![Screenshot_20200503-141056](https://user-images.githubusercontent.com/16399787/80913866-2ec44d80-8d48-11ea-8d71-4db38d24b6a8.jpg)

**Comment by sw-yx** [comment]
thats a stepper not a spinner.

in case it helps here are some spinners i collected https://github.com/sw-yx/spark-joy/blob/master/README.md#user-content-spinners

**Comment by J05HI** [comment]
Okay, loading spinner ;)

**Comment by nassan** [comment]
Voting for this

**Comment by rgdelato** [comment]
A loading spinner was also the first component that felt obviously missing to me when building a demo app with Tailwind UI, but I don't know if it really makes sense to add in considering that normal Tailwind CSS doesn't seem to have classes for things like infinite rotation/pulsing keyframes.

**Comment by simonswiss** [comment]
Might add some "loading" component examples at some point, but for now, Tailwind (since v1.6.0) has neat [animation utilities](https://tailwindcss.com/docs/animation/#spin) that you can use to implement your own loading spinners! 👍

**Comment by simonswiss** [comment]
Porting the component suggestions to an "ideas" column in the Trello roadmap. I'll close this but you can find this request in the roadmap here: https://trello.com/c/whj4CPQS/48-loading-spinners-skeletons 🎉
