### ISSUE TITLE
Product gallery and product item

### ISSUE THREAD

**Issue by AdamJSoftware** [tailwindlabs/tailwindui-issues#188]
Hey tailwind team, love the stuff that you guys do, on my end, I am not the most creative type of person so your components do help give my projects a nice touch. However, I recently started building ecommerce sites and I have noticed that you guys don't have any components based on products. I will submit a few screenshots of what I think would be a great add to the tailwind component list.

Thank you for all your work!

**Screenshots**
Provide a screenshot of your existing solution or of examples you've seen elsewhere that you think would be helpful inspiration.
![image](https://user-images.githubusercontent.com/42972871/81081066-75888380-8ebf-11ea-9e61-26fbf493e258.png)
![image](https://user-images.githubusercontent.com/42972871/81081248-ac5e9980-8ebf-11ea-9fc6-d2d9f6629782.png)

**Additional context**
Add any important details you think we need to know to make sure we build something that matches what you need.

**Comment by simonswiss** [comment]
Nice suggestion! This is definitely something we're  thinking about implementing. 

Consolidating this with https://github.com/tailwindlabs/tailwindui-issues/issues/268
