### ISSUE TITLE
Search page example

### ISSUE THREAD

**Issue by torepettersen** [tailwindlabs/tailwindui-issues#198]
Most websites need some kind of search functionality. So a simple search page with the listed results with title and description would be nice to have.

**Screenshots**
Provide a screenshot of your existing solution or of examples you've seen elsewhere that you think would be helpful inspiration.

Most well known is google:
![Screenshot from 2020-05-15 23-19-07](https://user-images.githubusercontent.com/17319716/82097480-41a12f80-9703-11ea-9d5d-6a8dd0c53128.png)

Another example could be [crates.io](https://crates.io/search?q=tokio) where you also can sort by relevance, popularity, and so on.  
![Screenshot from 2020-05-15 23-19-51](https://user-images.githubusercontent.com/17319716/82097470-3ea63f00-9703-11ea-88a7-445c8ed1fa2b.png)

**Comment by simonswiss** [comment]
Thanks for the suggestion! Porting the component suggestions to an "ideas" column in the Trello roadmap. I'll close this but you can find this request in the roadmap here: https://trello.com/c/bm9JXw8v/49-search-search-results
