### ISSUE TITLE
Grids (Layouts) & Stats (Data Display)

### ISSUE THREAD

**Issue by richardorsey** [tailwindlabs/tailwindui-issues#20]
Adam & Steve,

First, love the product!

Second, looking forward to the release of Grids and Stats. Hoping these are coming soon! Keep up the good work!

- Richard

**Comment by DanHarrin** [comment]
Adam released a [public Trello board](https://trello.com/b/tkcuwST3/itinify) that details all of the components currently in the pipeline.

Voting is enabled on this board, so you can help him prioritize what to work on next by clicking "Vote" in the actions sidebar of any individual card:

![Voting for a component](https://user-images.githubusercontent.com/41773797/76107290-42fdff80-5fd0-11ea-8af6-777acef10c47.png)

I think that this issue can be safely closed now, thank you.

**Comment by DanHarrin** [comment]
Adam released a [public Trello board](https://trello.com/b/Nh6e9w8Q/tailwind-ui-roadmap) that details all of the components currently in the pipeline.

Voting is enabled on this board, so you can help him prioritize what to work on next by clicking "Vote" in the actions sidebar of any individual card:

![Voting for a component](https://user-images.githubusercontent.com/41773797/76107290-42fdff80-5fd0-11ea-8af6-777acef10c47.png)

I think that this issue can be safely closed now, thank you.
