### ISSUE TITLE
Mock-ups for 'coming soon' components 

### ISSUE THREAD

**Issue by ilyahq** [tailwindlabs/tailwindui-issues#201]
Hi,

Recently purchased the product and lovin' it. 
One small thing though. I could use some of the upcoming components in my projects and I was wondering if it'd be a good idea to at least upload the mockups (assuming they're done) purely for reference until the real thing comes in? That would help save a ton of time in case I decide to go with my own implementation for the time being.

Good job so far, anyways!

**Comment by pqt** [comment]
Hey @ilyahq instead of doing that you could fashion your own components for the time being but build them in such a way that you can swap in the Tailwind UI components when the time comes?

**Comment by ilyahq** [comment]
@pqt I could, but why? That means I would have to go through multiple design iterations of my own before getting a decent thing, consistent with the rest of the UI. And I do not considering myself to be a great UI/UX designer, so that would add up considerably in term of time-to-market. Speed of development is one of the main selling points for such products, I would say. So to me it makes perfect sense to share the mock-ups if they're finalized.

Appreciate your suggestion though :)

**Comment by ilyahq** [comment]
By the way, not saying they should be up on the main website or something (though they could). Maybe the Figma boards shared privately amongst the paying users would suffice (e.g. the discord channel).

**Comment by pqt** [comment]
Totally agree and understand, I don't think the mock ups are finalized, just the little snapshots for sections. For a Figma file I know it's a hot topic so I can only assume that one will be made available eventually.

The reason I don't think that all of the mockups are done is because the trello board has a `designing` column so I think it's a collaborative effort still for new components having to be accepted (upvoted to priority), designed, then developed and eventually published on the site.

See: https://trello.com/b/Nh6e9w8Q/tailwind-ui-roadmap

**Comment by ilyahq** [comment]
@pqt Ah, I see. Thanks for sharing the trello board. Makes more sense now.

Well then, still could be a good idea in case the design progress speeds up at some point :)

**Comment by simonswiss** [comment]
The best way to have early previews of components is to follow Steve Schoger on Twitter! 😅 That's where you'll get screenshots of what's in the "designing" column of the Trello roadmap.

There are not many things kept "secret" around Tailwind Labs, we tend to work in public a whole lot, so.. if something is being designed, there is a good chance that you can have a look at it soon after, as soon as it's deemed "good enough to show"! 👍

Also, yes: Figma files **are** coming! 🎉
