### ISSUE TITLE
Adding @tailwindcss/ui plugin causes extreme memory usage during build

### ISSUE THREAD

**Issue by johncantrell97** [tailwindlabs/tailwindui-issues#203]
**Describe the bug**
When I add the @tailwindcss/ui plugin to my tailwind.config.js it causes my build machine to run out of memory.  

**To Reproduce**
1. Add @tailwindcss/ui plugin to your tailwind.config.js
2. Build project using postcss 
3. See all the memory go away

**Expected behavior**
Would be nice to figure out what is causing this massive spike in memory usage from including some css.  I assume it's triggering some kind of memory leak in postcss.

**Screenshots**
![Screen Shot 2020-05-20 at 2 00 58 PM](https://user-images.githubusercontent.com/41305919/82480848-6cdca380-9aa2-11ea-8f67-482d3807e5ec.png)

**Browser/Device (if applicable)**
Deploying on render.com

**Additional context**

**Comment by guillaumebriday** [comment]
Maybe it's related: https://github.com/tailwindui/issues/issues/157

**Comment by hc-codersatlas** [comment]
As a workaround you can increase the memory allocated to the nodejs process via `--max-old-space-size`

**Comment by davidluhr** [comment]
As of the latest Tailwind UI release, there is no longer a dedicated UI plugin, and various other build improvements with Tailwind CSS 2.0. We've also reduced the number of additional classes to generate for Tailwind UI.

Are you experiencing these issues still with the latest versions?

**Comment by davidluhr** [comment]
Closing this issue for now, per the above reasons. If there are issues specific to the latest Tailwind UI, please feel free to re-open.m

**Comment by waynelinks** [comment]
Whenever I edit tailwind.config memory usage spike during recompiling
