### ISSUE TITLE
Button Loading Animations `is-loading`.

### ISSUE THREAD

**Issue by mikeburrelljr** [tailwindlabs/tailwindui-issues#204]
**Screenshots**
![Button loading animation example 1](https://media.giphy.com/media/Vg0HR0izzFBHAt8QbA/giphy.gif)

![Button loading animation example 2](https://media.giphy.com/media/ZeLcDzaR72sHQk9RGJ/giphy.gif)

**Additional context**
Button loading animations, similar to those found in [Bulma](https://bulma.io/documentation/elements/button/#states).

**Comment by rgdelato** [comment]
Linking this issue since it's probably the same underlying thing being asked for:
https://github.com/tailwindui/issues/issues/187

**Comment by simonswiss** [comment]
Consolidating this with https://github.com/tailwindlabs/tailwindui-issues/issues/187 👍
