### ISSUE TITLE
VanillaJS Documentation Example

### ISSUE THREAD

**Issue by williammincy** [tailwindlabs/tailwindui-issues#205]
**Documentation**
- https://tailwindui.com/documentation 

**Documentation Improvement**
The current documentation gives examples of how to incorporate Tailwind UI into a number of JavaScript frameworks, but there isn't a section explaining how to use the UI framework outside of a JavaScript framework torecreate the great examples that require JavaScript to implement. I think it would be a good first portion in the documentation where introducing interactions to have a VanillaJS example of how to toggle classes. 

Not sure how many people come to the docs and get a bit confused at how to recreate the examples without a framework, so this may not be a large concern. But adding a portion in the docs that covers VanillaJS would broaden the use cases the docs cover.

**Comment by simonswiss** [comment]
Thank you for the suggestion!

We have no concrete plans to do this right now, but would definitely consider it if there is significant enough demand. 👍

Have captured your suggestion internally and will close this.
