### ISSUE TITLE
Date Picker!

### ISSUE THREAD

**Issue by abunsen** [tailwindlabs/tailwindui-issues#215]
**Screenshots**
<img width="308" alt="Screen Shot 2020-05-31 at 1 46 06 PM" src="https://user-images.githubusercontent.com/93429/83358975-1cd4cb00-a345-11ea-92b3-f4122e8ead15.png">

**Additional context**
It would be awesome to have a date picker component and perhaps even a time picker.

**Comment by brandoncordell** [comment]
Would love if this included the ability to pick a range (preferably from side by side calendars)!

**Comment by abishekrsrikaanth** [comment]
I don't see any purpose in re-inventing the whole wheel. We can select a good date picker component that includes a time picker as well and find a way to just have a theme built for it through tailwind UI. Say [flatpickr](https://flatpickr.js.org/)

**Comment by inopinatus** [comment]
duplicate of #54 ?

**Comment by simonswiss** [comment]
Consolidating this with https://github.com/tailwindlabs/tailwindui-issues/issues/54 👍
