### ISSUE TITLE
Include heroicon name in HTML

### ISSUE THREAD

**Issue by sugendran** [tailwindlabs/tailwindui-issues#217]
**Describe the bug**
For the component HTML can you please include the name of the heroicon being used in a comment. When I convert to react I want to use the react heroicon wrapper so that the code is easier to read. Would be helpful to have the name of the icon somewhere so that I can replace the SVG in the code.

**Comment by simonswiss** [comment]
This is a fantastic suggestion @sugendran - have just implemented that functionality 👍

It might not show up immediately, but will when we do our next build. Here's a preview of what it will look like:

![image](https://user-images.githubusercontent.com/485747/91034424-549f9600-e648-11ea-9fe0-341acbd55926.png)

Thanks again for the idea, which I think is a good user experience improvement!
