### ISSUE TITLE
Provide a way to get code with other primary color

### ISSUE THREAD

**Issue by RolandStuder** [tailwindlabs/tailwindui-issues#22]
The tailwind components are currently using indigo as a primary color. While it is fairly easy to do a search and replace, it would be nice to have a quicker way to adapt the components to your needs. There are several ways you could do that:

**Actually use `text-primary-500` instead of `text-indigo-500`**

This way, we could just adjust our configuration in the tailwind config. However it also means, that you would have to add a primary color definition in the `@tailwindcss/ui` as a default.

**Give user a possibility to set a preference for primary color, so the text in the code example gets adjusted**

![image](https://user-images.githubusercontent.com/194364/75768883-7d07a100-5d45-11ea-820d-a55ef1c7de01.png)

So like some color switcher, with a custom option. On the custom option, I should be able to set any string. But the preview should keep the the teal color. Or If you have time to waste, make a colorpicker, that calculates the other shades automatically ;-)

**Comment by dillingham** [comment]
Ive been search and replacing `-indigo-` with -red-` for example.
Avoids needing `primary` because it catches all the variations.
Maybe the component does the same search and replace

**Comment by LarBearrr** [comment]
Stumbled across this Tailwind CSS implementation today. They do a nice job of handling color preferences: https://www.creative-tim.com/learning-lab/tailwind-starter-kit/#/documentation/alerts

**Comment by jreviews** [comment]
I needed something similar so I made this https://prefixer-tailwindui.netlify.com/ Allows you to change primary color and add a prefix.

**Comment by simonswiss** [comment]
That's a very interesting suggestion. Thanks for sharing this! 👍

No concrete plans to build this right now, but we have captured the request internally. If there is enough demand for it to warrant pausing some work on other projects, we'll consider implementing it!
