### ISSUE TITLE
Enhancement Request: JSX Compatible Code

### ISSUE THREAD

**Issue by udf2457** [tailwindlabs/tailwindui-issues#224]
You know what would be really, really, really useful ?

If you template code (https://tailwindui.com/components) gave the option to output JSX compatible code (https://tailwindui.com/documentation#js-react)

At the moment you have to go through it all manually and switch `class` to `className` etc.

Surely you could come up with a more classy way to do it (e.g. drop-down to choose beween HTML or JSX).

**Comment by IL4Miy** [comment]
@udf2457 I think they are planning this feature.
For the time in between there is a cool utility from a community member:
https://gist.github.com/RobinMalfait/a90e8651196c273dfa51eec0f43e1676
Adam uses this as well

**Comment by simonswiss** [comment]
We're working on React and Vue code snippets in complement to the HTML code snippets. Going to close this issue but rest assured it's coming in the future! 🎉

Also, happy to report (as you may have heard) that Robin Malfait mentioned above joined the Tailwind Labs team and will be working on React & Vue headless UI libraries for Tailwind! 👍👍
