### ISSUE TITLE
Preview, Code AND Both

### ISSUE THREAD

**Issue by wesort** [tailwindlabs/tailwindui-issues#225]
On tailwindui.com it would be nice if there was the option to view the rendered component AND the code at the same time. 

I sometimes find myself flipping back and forth a lot or opening dev tools. Or even getting confused about which exact component I'm looking at the code for. 

NB: _I appreciate that the rendered preview isn't exactly aligned with the code (especially JS heavy components). Here's a rough idea of what I had in mind._ 

![both-preview-and-code](https://user-images.githubusercontent.com/3920126/84281739-dba49e00-ab30-11ea-9800-3a9dd83f9e01.jpg)

**Comment by simonswiss** [comment]
I've capture this idea in our internal "bag of ideas" we could look at implementing one day if the demand is high enough to justify de-prioritizing other projects.

No concrete plans to build this right now, but thanks for the suggestion, we've taken note! 👍
