### ISSUE TITLE
More Components without JavaScript (especially headers)

### ISSUE THREAD

**Issue by denten** [tailwindlabs/tailwindui-issues#226]
According to the docs:
 
> To make Tailwind UI as universal as possible, we've built all the components using HTML only. The vast majority of components don't need JavaScript at all and are completely ready to go out of the box.

Yet, there are no headers without JavaScript and it seems that almost half of other components are JavaScript only. The integration with JavaScript is not trivial, introducing a significant external dependency that is not covered well in the docs. More resources should go to pure HTML components, before introducing ones with JavaScript.

**Comment by PolMrt** [comment]
Some components can't be done in pure HTML. If you want, you can use header in pure HTML but you won't be able to make it responsive with a burger menu.

**Comment by Apostolique** [comment]
Actually that's not entirely true, yesterday I reimplemented the sidebar in pure Tailwind CSS, no JavaScript was needed.
![2020-06-24_12-32-31](https://user-images.githubusercontent.com/2766423/85595519-ee31d380-b616-11ea-9b1e-12479b0ac687.gif)

**Comment by ordago** [comment]
@Apostolique How did you make the sidebar open and close without javascript?

**Comment by Apostolique** [comment]
You can see the page here: <https://apostolique.github.io/GitHubActionsFun/>. The trick was to use a checkbox to toggle it.

**Comment by simonswiss** [comment]
Hey, thanks for the suggestion! 👍

We try to keep the use of JS to a minimum, like here to control the show/hide of the mobile menu. It's pretty tricky to build responsive navigation menus without a little bit of JS. 

Using a checkbox for this works visually, but comes with some accessibility concerns which would require some JS to cover.

As a general rule, we use as little JS as required to provide user interactions (toggles, modals etc).
