### ISSUE TITLE
Darkmode

### ISSUE THREAD

**Issue by Bowriverstudio** [tailwindlabs/tailwindui-issues#227]
For the component - https://tailwindui.com/components/marketing/elements/headers

Do you have a suggestion for some default configuration for dark mode?

Thank you for the library btw it is amazing.

**Comment by simonswiss** [comment]
Porting the component suggestions to an "ideas" column in the Trello roadmap. I'll close this but you can find this request in the roadmap here: https://trello.com/c/7IJuekaq/46-dark-headers-for-marketing
