### ISSUE TITLE
Hero for mobile Apps

### ISSUE THREAD

**Issue by ThomasKientz** [tailwindlabs/tailwindui-issues#228]
**Screenshots**
Provide a screenshot of your existing solution or of examples you've seen elsewhere that you think would be helpful inspiration.

![boomerang-app io_](https://user-images.githubusercontent.com/10157845/84655257-ed12ef00-af10-11ea-9208-49b4e4e40151.png)

https://boomerang-app.io/

**Additional context**
Add any important details you think we need to know to make sure we build something that matches what you need.

Basic text + image presentation on a single row.

**Comment by IL4Miy** [comment]
@ThomasKientz They already added a few new hero sections 🎉:
https://tailwindui.com/components/marketing/sections/heroes

**Comment by simonswiss** [comment]
Porting the component suggestions to an "ideas" column in the Trello roadmap. I'll close this but you can find this request in the roadmap here: https://trello.com/c/XixReuYs/45-app-landing-page-hero-example
