### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by RolandStuder** [tailwindlabs/tailwindui-issues#23]
![image](https://user-images.githubusercontent.com/194364/75794992-eef5df80-5d71-11ea-8163-dcef10a41256.png)

Would be great to have some comment component. I don't think we need something threaded but just some nice comments we can have after a content area.

**Comment by DanHarrin** [comment]
I think you're looking for...
![Screenshot 2020-03-03 at 20 14 29](https://user-images.githubusercontent.com/41773797/75815584-97fd0400-5d8b-11ea-93b4-3bd6add4bedc.png)

**Comment by bkilshaw** [comment]
Came here to make the same request 👍

**Comment by simonswiss** [comment]
There are a few of these requests - consolidating there at #249 🎉
