### ISSUE TITLE
Suggestion: expanding details accordion for table/item list

### ISSUE THREAD

**Issue by inopinatus** [tailwindlabs/tailwindui-issues#234]
I've always liked the UX of clicking a table row or list item, to open an accordion containing further details or even editing of the item.  I've also noted criticism recently of modals (and their cousins e.g. slide-overs) that at least partially resonates with my experience. Detail accordions may be a satisfying device for some situations.

**Example**

Not by me, but https://codepen.io/jopico/pen/EGpim has a clear example of what I mean. This one uses alternating table rows, which is quite nice, although there are other ways to build them.

I've even used HTML-native `<details>` when IE wasn't a factor, and I think even Edge supports it now. Unsure of animation opportunities however.

**Comment by simonswiss** [comment]
Porting the component suggestions to an "ideas" column in the Trello roadmap. I'll close this but you can find this request in the roadmap here: https://trello.com/c/i4qvoJvM/43-expanding-detail-table-rows 🎉
