### ISSUE TITLE
White buttons have another focus color

### ISSUE THREAD

**Issue by Jubeki** [tailwindlabs/tailwindui-issues#235]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/elements/buttons#component-109c4104d58d9fedfa8650dbe24c1ae8
- Component name: White buttons

**Describe the bug**
All buttons use `focus:border-indigo-x00` and `focus:shadow-outline-indigo` except white buttons here is `focus:border-blue-300` and `focus:shadow-outline-blue` used

**Expected behavior**
All buttons have the same border and outline color on focus (this is also better for replacing indigo to another color)

**Comment by simonswiss** [comment]
Similarly to https://github.com/tailwindlabs/tailwindui-issues/issues/238#issuecomment-671673684, this is actually a design decision to keep the default blue border and `shadow-outline` on form elements and white buttons throughout Tailwind UI.

It looks great with the "brand" color applied to them too, but as an overall decision, white buttons will always have the default blue focus styles throughout all examples. 

You can see this in the new [app home screen examples](https://tailwindui.com/components/application-ui/page-examples/home-screens) - the "primary" button will have the brand color, while the white button retains the default blue.

![image](https://user-images.githubusercontent.com/485747/89848454-8d138e80-dbc9-11ea-9a28-aad78426e90b.png)
