### ISSUE TITLE
Tables for white background

### ISSUE THREAD

**Issue by pikant** [tailwindlabs/tailwindui-issues#241]
Currently, the "Application UI" set contains components designed for use on a white background as well as components designed for use on a colored (e.g. gray) background. Example:
https://tailwindui.com/components/application-ui/forms/form-layouts

For the tables (for me one of the most essential components) there are only components for use on a colored background:
https://tailwindui.com/components/application-ui/lists/tables

It would be nice if you could add tables that look good on a white background.

Thanks a lot for your effort!

Translated with www.DeepL.com/Translator (free version)

**Comment by simonswiss** [comment]
Porting the component suggestions to an "ideas" column in the Trello roadmap. I'll close this but you can find this request in the roadmap here: https://trello.com/c/3p5ltxsw/44-table-examples-for-white-backgrounds 🎉
