### ISSUE TITLE
Extract tailwind ui constants so they may be used directly in code

### ISSUE THREAD

**Issue by CTOJoe** [tailwindlabs/tailwindui-issues#246]
Would it be possible to extract tailwind ui specific constants such as **spacing** and **boxShadow** much like **colors** already is? This would allow importing wherever needed or the ability to cherry pick and manually extend only what is required in the tailwind config.

`const colors = require("@tailwindcss/ui/colors");`

**Comment by simonswiss** [comment]
Hey!

Instead of importing the "tokens" directly, you can use the `resolveConfig` function that will give you access to **all** your theme properties! 👍

https://tailwindcss.com/docs/configuration#referencing-in-java-script
