### ISSUE TITLE
Support for <select> multiple selection

### ISSUE THREAD

**Issue by SandroMaglione** [tailwindlabs/tailwindui-issues#247]
**Screenshots**
![Example1](https://raw.githubusercontent.com/harshzalavadiya/react-multi-select-component/HEAD/preview.gif)
![Example2](https://raw.githubusercontent.com/srigar/multiselect-react-dropdown/HEAD/images/dd.png)
![Example3](https://i.pinimg.com/originals/d1/b4/d0/d1b4d0e8c357f6fdab68369138e85679.png)

**Additional context**
When building an online form, a multi selectable <select> element allows the user to easily choose multiple options using only the keyboard (go up and down and choose an option with the arrow keys, and select a new choice using tab, no need to use the mouse or select multiple checkboxes).

This element can greatly improve the user experience and the time it takes for a user to fill a form, making the website faster and easier to use.

**Links to some examples**
[Vue multiselect](https://vue-multiselect.js.org/) - https://vue-multiselect.js.org/
[react-multi-select-component](https://www.npmjs.com/package/react-multi-select-component) - https://www.npmjs.com/package/react-multi-select-component
[multiselect-react-dropdown](https://www.npmjs.com/package/multiselect-react-dropdown) - https://www.npmjs.com/package/multiselect-react-dropdown

**Comment by simonswiss** [comment]
Consolidating this popular request with the others at https://github.com/tailwindlabs/tailwindui-issues/issues/61 👍
