### ISSUE TITLE
Add the ability to mark components as favourites (improvement)

### ISSUE THREAD

**Issue by johanrosenson** [tailwindlabs/tailwindui-issues#248]
When browsing the components it would be great to be able to add components as favourites (or similar functionality), to easier remember and find them.

**Comment by simonswiss** [comment]
Hey, thanks for the suggestion! 

I think this is an interesting idea and we've captured it internally as something to think about exploring in the future. We have no concrete plans to build this right now, but if there is an overwhelming demand for it we can definitely consider de-prioritizing some other projects to give this idea some attention. 👍
