### ISSUE TITLE
Activity Feeds

### ISSUE THREAD

**Issue by pascalschwientek** [tailwindlabs/tailwindui-issues#249]
Taken from: https://getstream.io/based-feed-ui-kit-sketch/

**Screenshots**

![](https://getstream.imgix.net/images/based/gallery-m.png)
---
![](https://getstream.imgix.net/images/based/gallery-i.png)
---
![](https://getstream.imgix.net/images/based/gallery-d.png)
---

**Additional context**
These are great to include in Dashboards or roll-ups that display information about recent activity. Following the history of an object or user can provide great context into the activity of your app and allows you to quickly catch up on what has happened since you last logged in.

**Comment by simonswiss** [comment]
Porting the component suggestions to an "ideas" column in the Trello roadmap. I'll close this but you can find this request in the roadmap here: https://trello.com/c/ZGJMqc4F/42-activity-feeds 🎉
