### ISSUE TITLE
Sidebar Layouts with Sub Menu

### ISSUE THREAD

**Issue by youyi1314** [tailwindlabs/tailwindui-issues#250]
If your tailwindui sidebar layouts with sub-menu like: https://tailwindcomponents.com/component/app-sidebar-with-sub-navigation
will be better =)

**Comment by IL4Miy** [comment]
@youyi1314 They added https://tailwindui.com/components/application-ui/navigation/sidebar-navigation 🎉

**Comment by simonswiss** [comment]
Yep, the examples with "expandable sections" are doing what you need 👍
