### ISSUE TITLE
Testimonial needs a name/face check

### ISSUE THREAD

**Issue by brandonpittman** [tailwindlabs/tailwindui-issues#253]
![image](https://user-images.githubusercontent.com/967145/88004588-4be80b80-cb42-11ea-9def-a97ebc9c1886.png)

Testimonial needs a name/face check. Dude doesn't look like a Judith. Maybe his name actually is Judith, but probably not.

**Comment by Apostolique** [comment]
He / She also speaks a weird latin.

**Comment by simonswiss** [comment]
Thanks for pointing that out! 👍

Will update the name + company, but they will continue to speak a weird latin! 😅

**Comment by simonswiss** [comment]
This now fixed - closing this issue!

![image](https://user-images.githubusercontent.com/485747/89618053-b6cd6c80-d8ce-11ea-87f8-704585a48758.png)
