### ISSUE TITLE
Navbar Layouts with Sub Menu

### ISSUE THREAD

**Issue by edvinaskrucas** [tailwindlabs/tailwindui-issues#256]
It would be good to see navbar layouts with submenu items.

**Comment by simonswiss** [comment]
We currently have sidebar examples with submenus: https://tailwindui.com/components/application-ui/navigation/sidebar-navigation

If you need the main top nav menu items to have submenus, you can currently achieve this with a [Flyout Menu](https://tailwindui.com/components/marketing/elements/flyout-menus) or a [Dropdown](https://tailwindui.com/components/application-ui/elements/dropdowns)

While it's not in the pipeline for now, I have captured the request for sub navigation in the navbar.
