### ISSUE TITLE
Single price with details uses flex-shrink-1

### ISSUE THREAD

**Issue by davecardwell** [tailwindlabs/tailwindui-issues#257]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/marketing/sections/pricing
- Component name: Single price with details

**Describe the bug**
Around line 19 of the component code it uses the class `lg:flex-shrink-1` which doesn’t seem to exist. Should it be `lg:flex-shrink` which sets `flex-shrink: 1`, or possibly `lg:flex-shrink-0` which sets `flex-shrink: 0`?

**Comment by simonswiss** [comment]
Thanks for raising this up - the `flex-shrink-1` class definitely does nothing here.

Will fix (remove the class entirely), thank you! 👍

**Comment by simonswiss** [comment]
This has now been fixed and merged go master, the code example will update on next release!
