### ISSUE TITLE
Remove headers from all content sections (Hero, Application Shells, etc.)

### ISSUE THREAD

**Issue by kcsf** [tailwindlabs/tailwindui-issues#258]
Currently, the code in several content components includes a "header/menu".  This isn't necessary, as headers are a separate component.  It would save a lot of time (and make the components more usable in tailwind.build) if you removed the headers from all non-header components.

Example:
![image](https://user-images.githubusercontent.com/17506215/88214663-6340fa80-cc0f-11ea-9972-2bab1227ac4b.png)

*the top header/menu is redundant.  we constantly have to manually remove this when using these components.

**Comment by adamwathan** [comment]
Interesting suggestion — for the application shells it seems weird to me that it would be beneficial to delete part of the shell? What you'd be left with would be sort of weird. Can you explain what you'd actually like the application shells to look like?

**Comment by simonswiss** [comment]
We captured the desire to have more "granular" components, this is certainly a good idea. Closing this issue though, as Adam says, the "stacked layout" examples without a navigation would be just a heading.
