### ISSUE TITLE
Component name should say "right" not "left"

### ISSUE THREAD

**Issue by StevenTCramer** [tailwindlabs/tailwindui-issues#259]
**What component (if applicable)**
- URL for category: https://tailwindui.com/preview#component-70a9bdf83ef2c8568c5cddf6c39c2331
- Component name:  "Simple dark with menu button on left"

**Describe the bug**

**Expected behavior**
Should read "Simple dark with menu button on right"

**Screenshots**
![image](https://user-images.githubusercontent.com/357219/88461710-0de74080-ced0-11ea-93e1-78950198b6e9.png)

**Comment by adamwathan** [comment]
Hey thanks for the report! It's correct actually — it's referring to the menu button on mobile which is on the left 👍 

![image](https://user-images.githubusercontent.com/4323180/88463328-d650a800-ce7f-11ea-8050-321a01b4d8ee.png)

**Comment by StevenTCramer** [comment]
@adamwathan  Thanks ... was trying to help.  I see what you were going for now.
