### ISSUE TITLE
Copy component with custom prefix

### ISSUE THREAD

**Issue by jreviews** [tailwindlabs/tailwindui-issues#26]
Would be great if an option could be added eventually to the component "copy" function to automatically add a given prefix to all the CSS classes so it can be plug-n-play in cases where the Tailwind configuration includes a prefix.

Could also be a separate page where you paste the chosen component, and are then allowed to quickly change the prefix and copy it again.

**Comment by mike-seekwell** [comment]
rough pass at this


```
var twPrefix = 'tw'
    var h = `<div>
      <label for="email" class="block text-sm font-medium leading-5 text-gray-700">Email</label>
      <div class="mt-1 relative rounded-md shadow-sm">
        <div class="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
          <svg class="h-5 w-5 text-gray-400" fill="currentColor" viewBox="0 0 20 20">
            <path fill-rule="evenodd" d="M2.003 5.884L10 9.882l7.997-3.998A2 2 0 0016 4H4a2 2 0 00-1.997 1.884zM18 8.118l-8 4-8-4V14a2 2 0 002 2h12a2 2 0 002-2V8.118z" clip-rule="evenodd"/>
          </svg>
        </div>
        <input id="email" class="form-input block w-full pl-10 sm:text-sm sm:leading-5" placeholder="you@example.com" />
      </div>
    </div>`
    
    function createElementFromHTML(htmlString) {
      var div = document.createElement('div');
      div.innerHTML = htmlString.trim();
      return div.firstChild; 
    }
    var el = createElementFromHTML(h)
    var els = el.querySelectorAll('*')
    for (let index1 = 0; index1 < els.length; index1++) {
    		let node = els[index1]
    		let newClasses = []
    		for (let index = 0; index < node.classList.length; index++) {
    				newClasses.push(`${twPrefix}-${node.classList[index]}`)
    		}
    		node.className = newClasses.join(' ')
    }
```

**Comment by mike-seekwell** [comment]
@jreviews doesn't work for `sm:text-sm` for example, but gets everything else

**Comment by jreviews** [comment]
@mike-seekwell Great! I put this together using AlpineJS and made it work with pseudo-class variants

https://github.com/clickfwd/css-prefixer-tailwindui/

https://prefixer-tailwindui.netlify.com/

**Comment by simonswiss** [comment]
This is a nice suggestion! 

Have captured it internally. No plans to built it as of now, but if there is growing demand for it and we can justify de-prioritizing some other work to implement it, we'll definitely have a look! 👍
