### ISSUE TITLE
SVG and image Jank

### ISSUE THREAD

**Issue by imacrayon** [tailwindlabs/tailwindui-issues#261]
None of the images and SVG have a set `width` or `height` attribute, instead they rely on the tailwind width/height classes for sizing. This causes a lot of "jank" in the flash of unstyled content before the CSS is loaded.

Have you considered adding size attributes to SVGs and images? There's an [MDN article](https://developer.mozilla.org/en-US/docs/Web/Media/images/aspect_ratio_mapping) recommending `width` and `height` attributes to prevent Jank in this way.

**Comment by simonswiss** [comment]
Hey thanks for the suggestion! 

This would be a nice improvement for sure and I've captured it internally as something for us to explore when we have some time. Thankfully in the mean time it is a quick change for the end-user if they want to avoid any layout jank before the images are fully loaded.
