### ISSUE TITLE
Comment location update or possible documentation update

### ISSUE THREAD

**Issue by P-James** [tailwindlabs/tailwindui-issues#262]
I think either the docs or the transition comments may need updating for the [sidebar component](https://tailwindui.com/components/application-ui/application-shells/sidebar). 

Reason being, the docs state that the comments are directly above the dynamic element, but in this case the first comment is below the element that needs to get wrapped/ dynamically updated in Vue.

I'm not familiar enough with React/ other frameworks to know if this differs per framework.

![https://cdn.discordapp.com/attachments/682241106733301913/736327133697278042/unknown.png](https://cdn.discordapp.com/attachments/682241106733301913/736327133697278042/unknown.png)

**Comment by simonswiss** [comment]
The element which takes the show/transition attributes is actually the one below the comment, as per the documentation.

These comments get automatically generated form our build process, and in the source component code (using Alpine JS), the attributes are placed on the div below that big first comment.

![image](https://user-images.githubusercontent.com/485747/89846167-cfd26800-dbc3-11ea-9bf7-160eb22dce2f.png)

**Comment by P-James** [comment]
@simonswiss 
Sorry I should've been more clear about the detail of the bug.
The problem is, if you implement the transition as documented, on screen sizes < md, the overlay hides any clickable functionality.

I have made a codepen here showing the issue: https://codepen.io/p-james/pen/GRZpqXJ

Please let me know  if you need this pen to be deleted
