### ISSUE TITLE
z-index needed for Application > Navbars > Profile dropdown

### ISSUE THREAD

**Issue by shanerobinson** [tailwindlabs/tailwindui-issues#264]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/navigation/navbars
- Component name: Navbars

**Describe the bug**
Related to #25  
While z-index can be context specific as discussed in #25 , the **Profile dropdowns** in the Navbars will always require a z-index as they hover off the Navbar and over the following component.

**Comment by simonswiss** [comment]
You can often resolve stacking issues by giving the element that needs to be "on top" a class of `relative`, which will create a new [stacking context](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning/Understanding_z_index/The_stacking_context).

Do you have a concrete example (in CodePen or a repo) that shows a situation where a z-index is absolutely required?

**Comment by shanerobinson** [comment]
`relative` did the trick. Thanks!
