### ISSUE TITLE
Content sections look different when pasting them on nuxt/tailwind project

### ISSUE THREAD

**Issue by lmuzquiz** [tailwindlabs/tailwindui-issues#265]
https://tailwindui.com/components/marketing/sections/content-sections
Component name: Mostly all of them in this category 

**Describe the bug**
The components don't look the same. When pasting it on my project,. 

Im using @tailwindcss/ui": "^0.4.0", and "@nuxtjs/tailwindcss": "^2.1.1",

![Screen Shot 2020-07-30 at 14 36 13](https://user-images.githubusercontent.com/11865448/88966590-28c00900-d272-11ea-8308-63f0c0e2e1a1.png)
![Screen Shot 2020-07-30 at 14 38 08](https://user-images.githubusercontent.com/11865448/88966720-6329a600-d272-11ea-9323-4f97172de626.png)
![Screen Shot 2020-07-30 at 14 38 41](https://user-images.githubusercontent.com/11865448/88966727-66249680-d272-11ea-8f5f-17601c19f651.png)

**Comment by lmuzquiz** [comment]
On the Two columns with testimonial component you specify the size font on the "What makes us different" title:

![Screen Shot 2020-07-30 at 14 42 40](https://user-images.githubusercontent.com/11865448/88967492-84d75d00-d273-11ea-95e6-e2b4a17e6b9f.png)


`<h1
            class="mt-2 mb-8 text-3xl leading-8 font-extrabold tracking-tight text-gray-900 sm:text-4xl sm:leading-10"
          >
            What makes us different
          </h1>`

But then on the Split with image component on the how we're different title you don't specify anything, no spaces, no font size no nothing: 

` <p>
                Rhoncus nisl, libero egestas diam fermentum dui. At quis
                tincidunt vel ultricies. Vulputate aliquet velit faucibus
                semper. Pellentesque in venenatis vestibulum consectetur nibh
                id. In id ut tempus egestas. Enim sit aliquam nec, a. Morbi enim
                fermentum lacus in. Viverra.
              </p>
              <h2>How we’re different</h2>
              <p>
                Tincidunt integer commodo, cursus etiam aliquam neque, et.
                Consectetur pretium in volutpat, diam. Montes, magna cursus
                nulla feugiat dignissim id lobortis amet. Laoreet sem est
                phasellus eu proin massa, lectus. Diam rutrum posuere donec
                ultricies non morbi. Mi a platea auctor mi.
              </p>`

**Comment by lmuzquiz** [comment]
O forget it, it was fixed after doing a npm run dev after the upgrade to TailwindUI 0.4.0

**Comment by IL4Miy** [comment]
@lmuzquiz Could you close the issue then, please? :)

**Comment by simonswiss** [comment]
Yep, these are styled with the `prose` classes from the new [typography plugin](https://tailwindcss.com/docs/typography-plugin/) 👍 

Marking this as closed.
