### ISSUE TITLE
Allow editing in the Component page view code section

### ISSUE THREAD

**Issue by AlainPilon** [tailwindlabs/tailwindui-issues#266]
As a user of the components page, whenever I click to view the code, I would like to be able to edit it before cut&pasting it in my software. This would allow me to remove extra lines, edit the content to replace the generic text with placeholders, etc...

**Comment by simonswiss** [comment]
Interesting idea that we've been talking about internally, as something to explore in the future. 

We have no concrete plans to build this right now, but if there is an overwhelming demand for it we can definitely consider pausing some other projects to give this idea some attention. 👍
