### ISSUE TITLE
Item in Select Menu does not have corrent classes

### ISSUE THREAD

**Issue by jansedlon** [tailwindlabs/tailwindui-issues#267]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/forms/select-menus
- Component name: Custom with status indicator

**Describe the bug**
In preview Tom Cook has bold text and check mark. This is not present in code section

**Screenshots**
![obrazek](https://user-images.githubusercontent.com/13948180/89214495-31dd0d00-d5c7-11ea-9e0d-5ca246e7297e.png)
![obrazek](https://user-images.githubusercontent.com/13948180/89214526-415c5600-d5c7-11ea-8289-89612d2c6f03.png)

**Comment by adamwathan** [comment]
Just deployed a fix, had a small mistake in our templating code 🙈  Thank you!
