### ISSUE TITLE
Implement more ecommerce layouts/components.

### ISSUE THREAD

**Issue by erier** [tailwindlabs/tailwindui-issues#268]
**Suggestion**
There's really not much yet in terms of ecommerce ... ie: product pages/listing/etc. That would be a great addition. Hope you can make it happen.

**Comment by IL4Miy** [comment]
I think Steve posted on Twitter that they are thinking about a separate e-commerce package. Would be great! :)

**Comment by simonswiss** [comment]
I don't have a time frame on this, but I can tell you that we're definitely talking/thinking about this within the team. 👍

Will keep this issue open, and consolidate with eventual others that are similar.

**Comment by simonswiss** [comment]
Porting the component suggestions to an "ideas" column in the Trello roadmap. I'll close this but you can find this request in the roadmap here: https://trello.com/c/JSmk7d31/41-e-commerce-ui-components 🎉

**Comment by erier** [comment]
y'all rock. Keep crushing it.

**Comment by simonswiss** [comment]
Consolidating with https://github.com/tailwindlabs/tailwindui-issues/issues/268 - e-commerce components is definitely something we're thinking about! 👍

**Comment by connecteev** [comment]
Adding comment from #166 

Love to see official TailwindUI components for checkout forms (credit cards, subscriptions)

Screenshots
If using Stripe, it would be nice to have the interactivity like
https://c45nv.sse.codesandbox.io/ (note this example does not use an iframe)
https://stripe.dev/elements-examples/

If not using Stripe, it could be like https://tailwindcomponents.com/component/checkout-form
(but this example is clunky at best)
