### ISSUE TITLE
@tailwindcss/ui unavailable on npm

### ISSUE THREAD

**Issue by tomwassing** [tailwindlabs/tailwindui-issues#270]
**Describe the bug**
It seems that the dependency is no longer available on npm. When installing I get the following error:

`@tailwindcss/ui@0.5.0' is not in the npm registry.`

**To Reproduce**
Steps to reproduce the behaviour:
1. Remove node_modules
2. npm install

**Comment by tomwassing** [comment]
Whoops, seems happing because of issue at npm: https://twitter.com/npmstatus?lang=nl

**Comment by sajeezy** [comment]
Having this same issue actually. Thanks for the heads up @tomwassing

**Comment by sajeezy** [comment]
UPDATE: It just worked for me. I guess NPM has resolved its issue. Cheers

**Comment by simonswiss** [comment]
Looks like it's sorted, marking this as closed 👍
