### ISSUE TITLE
Svelte integration

### ISSUE THREAD

**Issue by codemodify** [tailwindlabs/tailwindui-issues#271]
Is there Svelte integration ?

**Comment by simonswiss** [comment]
We're currently working on React and Vue variants of the UI components. 

Svelte is not in the immediate pipeline, but we've captured this request internally. If this is a popular request, we'll consider wether it's worth de-prioritising other stuff to make a Svelte integration, or at least write documentation/guides on how to integrate Tailwind UI with Svelte.

**Comment by codemodify** [comment]
Do you accept contributions ?
I'm working on a project that uses Svelte + Tailwind, built a manual integration for now

**Comment by cedricmay** [comment]
Svelte components would be awesome! ❤️
