### ISSUE TITLE
tailwindui does not purge

### ISSUE THREAD

**Issue by hc-codersatlas** [tailwindlabs/tailwindui-issues#272]
Coming from a tailwindcss setup and adding the @tailwindcss/ui plugin adds ~80KB to a blank project. 

Looking at the generated classes, a lot of it is from tailwind typography even though none of it has been used. This is using the built-in purgecss functionality with no additional config. C an also see classes from custom forms.

Can't find anything about it in the documentation.

Can this be fixed so that purgecss strips out the unused classes? Thanks.

**Comment by adamwathan** [comment]
You can strip out those classes by switching the purge mode from `conservative` to `all`:

```js
module.exports = {
  purge: {
    mode: 'all',
    content: [...]
  }
}
```

We will be updating this default in the future but can't currently as it is a breaking change.

**Comment by simonswiss** [comment]
Closing this issue, assuming Adam's comment resolves it.
