### ISSUE TITLE
Autocomplete widget

### ISSUE THREAD

**Issue by matthewpull** [tailwindlabs/tailwindui-issues#275]
**Introduction**
Firstly, I'd like to say that the existing components are really awesome - I've build a few projects with Tailwind now and while it does take slightly longer than just importing Bootstrap / Bulma, the result looks amazing.

Also, I understand that you planned this library as simply a collection of HTML / CSS examples; the whole point was not to have a set of inflexible premade interactive widgets.

However, with the recent shift to include JS in some cases, might I suggest adding an autocomplete element?

**Example**
I won't include a screenshot, as this is by definition an interactive components, but you can see examples of how this would look and behave here:
[https://buefy.org/documentation/autocomplete/](https://buefy.org/documentation/autocomplete/)

**Additional context**
From a design point of view, I think that this would be fairly similar to the dropdown, just with the initial element being a text field rather than a button.

An autocomplete widget is helpful in all manner of situations, from simply filtering a really long dropdown (e.g. a country select field) to pulling data from a backend (e.g. the search box right here on GitHub), so I think this would make a great addition to the library.

Once again, thank you for such a great product!

**Comment by simonswiss** [comment]
Hey Matthew, 

Thanks for the suggestion! 👍 I've captured this in our "bag of ideas" in the Trello Roadmap: https://trello.com/c/oxsLcXMi/96-autocomplete-widget

We can't guarantee that we will be building this, but if the request becomes popular enough (you can upvote it), we'll consider it! 🎉

**Comment by matthewpull** [comment]
Thanks!
