### ISSUE TITLE
Overflow scrolling on table not working correctly in Firebox

### ISSUE THREAD

**Issue by weavdale** [tailwindlabs/tailwindui-issues#276]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/lists/tables
- Component name: Simple Striped

**Describe the bug**
overflow-x-auto isn't working correctly in Firefox. When you scroll right on the table, the right padding is missing.

**To Reproduce**
1. shrink browser window till table overflow activates
2. scroll table horizontally till you can see right side.
3. table is flush against right side of browser instead of having padding like the left side.

**Browser/Device (if applicable)**
 - OS: macOS
 - Browser Firebox
 - Version 80

**Screenshot**
![Screen Shot 2020-08-12 at 1 12 06 PM](https://user-images.githubusercontent.com/68517144/90046456-7ee37200-dc9e-11ea-914e-b9252595e698.jpg)

**Comment by simonswiss** [comment]
Yep, I am able to reproduce this bug - thanks for sharing! 👍 Working on it.
