### ISSUE TITLE
Chat / Comment Interface

### ISSUE THREAD

**Issue by duttonkj** [tailwindlabs/tailwindui-issues#278]
It would be great to have a couple of components for Slack style chatting or blog style commenting.  Real world examples:

- Slack
- Git PR comments
- Basecamp DM's and comments on TODO's

![image](https://user-images.githubusercontent.com/833755/90129485-bf8eca00-dd36-11ea-9c7c-7f62cbb25c46.png)
![image](https://user-images.githubusercontent.com/833755/90129625-f7960d00-dd36-11ea-8597-94b88eb08d10.png)

I was able to get something working by hacking/frankensteining  the `Grid Lists -> Contact Cards with small portraits` but having guidance on spacing, separators, and details like timestamps would be huge.:

![image](https://user-images.githubusercontent.com/833755/90129749-362bc780-dd37-11ea-9762-1e3ad9ab7ccb.png)

Thanks!

**Comment by simonswiss** [comment]
Hey, thanks for the suggestion and screenshots! 🎉

That's something that has been suggested a couple of times - will consolidate this with #249. This has been captured in our "bag of ideas" for components to consider building if there is enough demand!
