### ISSUE TITLE
form-input class is mentioned in input name

### ISSUE THREAD

**Issue by PhiloNL** [tailwindlabs/tailwindui-issues#279]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/forms/form-layouts
- Component name: Simple stacked

**Describe the bug**
The class name 'form-input' is listed inside field name attribute.

**To Reproduce**
```html
<input id="push_everything" name="form-input push_notifications" type="radio" class="form-radio h-4 w-4 text-indigo-600 transition duration-150 ease-in-out">
```

**Expected behavior**
```html
<input id="push_everything" name="push_notifications" type="radio" class="form-radio h-4 w-4 text-indigo-600 transition duration-150 ease-in-out">
```

**Comment by simonswiss** [comment]
Thanks for pointing that out - I have now fixed it. Component examples will be updated on next release! 👍
