### ISSUE TITLE
Section separators / dividers

### ISSUE THREAD

**Issue by dillingham** [tailwindlabs/tailwindui-issues#28]
Some svg section separators would be cool for the marketing kit

**Screenshots**
![CSS-divider-6](https://user-images.githubusercontent.com/29180903/75897453-945a9300-5e06-11ea-9793-f1360ebba7e9.jpg)

**Additional context**

- https://getwaves.io/
- https://tympanus.net/Development/SectionSeparators/
- https://iheartpagelines.com/section-separators/

**Comment by simonswiss** [comment]
Great suggestion! 👍

Have captured this in our bag of ideas on the roadmap here: https://trello.com/c/aVBI31X2/92-dividers-separators
