### ISSUE TITLE
List of blog posts

### ISSUE THREAD

**Issue by gustojs** [tailwindlabs/tailwindui-issues#280]
We've got some real cool components to create a blog for our company but we're missing some options for a traditional list of blog posts. 

The ones we have are more fitting for a landing page section or "read more articles about/from" section under an article.

In mobile version they're fine though.

**Screenshots**
Looks familiar, doesn't it? ;)
![blog posts list](https://i.imgur.com/OcDG4b2.png)

**Comment by simonswiss** [comment]
Haha, yep, looks familiar. There is even my name on the last post example! 🤣

Are you suggesting to expand on the list of available blog post listings from https://tailwindui.com/components/marketing/sections/blog-sections ?

**Comment by simonswiss** [comment]
I'll close this for now, but if you have something different in mind, feel free to re-open.

Worth noting that we now have ported the new component suggestions to an "ideas" column in our Trello roadmap, so people can upvote what they'd like to see us consider for implementation.

What's in this column is not guaranteed to be ever built, but it's guaranteed to be "in the mix" when we choose what to add to our backlog. 👍
