### ISSUE TITLE
Tree Widget

### ISSUE THREAD

**Issue by clarkevans** [tailwindlabs/tailwindui-issues#281]
In my application have to represent hierarchies that can be expanded/collapsed like a traditional file folder browser.  I don't have any particular visual aesthetic in mind, only that I could show a hierarchy in one pane and then display detail about a selected item in another, and that I could navigate via keyboard.  Key functionality is being able to open/close folders. Then, we need an ability to indicate which branch/leaf has current keyboard focus. Orthogonal to keyboard focus is the current selection (with detail shown in another window pane).  Hence, there are style permutations of keyboard focus vs current selection vs open/closed.  Thank you for your consideration.

**Comment by simonswiss** [comment]
Hi, 

Thanks for the suggestion! Consolidating this with https://github.com/tailwindlabs/tailwindui-issues/issues/182 👍

You can go upvote this idea on our Trello roadmap bag of suggestions: https://trello.com/c/oupB2Ges/52-tree-view
