### ISSUE TITLE
components have wrong class names or classes that make sense

### ISSUE THREAD

**Issue by eli007s** [tailwindlabs/tailwindui-issues#282]
in some of the components, like the `nabvar` there are instances where `bg-gray-50` is used.. did you mean `bg-gray-500`? also in other components there is `-mr-2` did you mean `mr-2`?

too lazy to look thru all the components, but do a search and find to locate those instances =)

**Comment by gustojs** [comment]
These are not mistakes though.

From the docs:

> It also includes a new "50" shade, so there are now 10 shades per color instead of 9.

> Control the negative margin of an element using the -m{side?}-{size} utilities.

**Comment by simonswiss** [comment]
Yep, these are correct and existing classnames!

![image](https://user-images.githubusercontent.com/485747/90347452-f08f3780-e073-11ea-841f-12c4791e8b8a.png)

![image](https://user-images.githubusercontent.com/485747/90347475-0a307f00-e074-11ea-8cdd-4ce844dec679.png)
