### ISSUE TITLE
Toggle desktop/mobile versions of all components on the page

### ISSUE THREAD

**Issue by gustojs** [tailwindlabs/tailwindui-issues#283]
We can see how every component behaves on small and big screens using a slider but we need to do it separately for each of them.

I'd love a way to automatically show all components as narrow or wide, using a toggle or a button.

**Comment by simonswiss** [comment]
Hey!

Thanks for your suggestion. I have captured this idea internally. If there's enough demand for it and we can justify de-prioritizing other projects to implement this, we'll consider it!

In the mean time, you can resize the window for the Tailwind UI app and see what all the components look like at a given viewport width. 😅

![image](https://user-images.githubusercontent.com/485747/90347407-a312ca80-e073-11ea-9013-d40b6549ec3d.png)
