### ISSUE TITLE
Escape characters for elements to enable easier copying into React

### ISSUE THREAD

**Issue by Spasmochi** [tailwindlabs/tailwindui-issues#284]
Most of the components are written without escape characters (inputs etc.). This causes no issues with standard html, however, React requires escape character to close the tag. I.e.:

```
<input id="email" class="someclasses">

vs 

<input id="email" class="someclasses"/>
```

Adding escape characters to close tags such as input tags would not detrimentally impact users looking to include these components in standard html pages, and it would make them easier to intergrate into React.

Here is a list of tags that are not closed by default:
input
img

Love the work, Tailwind UI is well worth every penny.

**Comment by simonswiss** [comment]
Hello!

Thanks for the kind words on Tailwind UI and for the suggestion for improvement! ❤️

I have made a note of this internally. No guarantee we'll implement that, but if this become a popular request, we'll see if it makes sense de-prioritizing otther projects to take care of that.

That said - we're planning to bring React version of the components to Tailwind UI in the future! 👍

Also - have you looked at [this bookmarklet by Robin Malfait](https://gist.github.com/RobinMalfait/a90e8651196c273dfa51eec0f43e1676)? Perhaps it could be useful to you.

**Comment by Spasmochi** [comment]
@simonswiss 

Anytime, I love Tailwind and have learnt so much from the Tailwind UI components. 

I've been working on a TSX functional component conversion of the components for React (in a private repo since I want people to go to Tailwind UI and pay for the originals like I did) and have found it reasonably straight forward to convert thanks to how well structured the components are.

Thanks for sending that link, I hadn't seen it before, much appreciated!
