### ISSUE TITLE
Book an appointment

### ISSUE THREAD

**Issue by seb-jean** [tailwindlabs/tailwindui-issues#285]
Hello,

it would be great to have a booking widget.

For example for this site: https://www.zocdoc.com/doctor/risa-cole-aprn-293360

**Screenshots**
![Image](https://i.imgur.com/Nkhpp5D.png)

Thanks :)

**Comment by simonswiss** [comment]
Hey, thanks for this suggestion! 👍

I have added it in the "ideas" column of the trello roadmap. It doesn't mean that it will be built, but if enough people upvote this suggestion, we'll consider it as an addition to our backlog! 

You can find it here: https://trello.com/c/vUOwnYZ4/99-booking-widget
