### ISSUE TITLE
Component for "Add new Collection" / "Add item to Collection" modal

### ISSUE THREAD

**Issue by connecteev** [tailwindlabs/tailwindui-issues#287]
Love this "Add new Collection" / "Add item to Collection" modal. It would be great to add this to tailwindUI!

https://twitter.com/jamesm/status/1295310797875417088?s=12

**Comment by simonswiss** [comment]
Thanks for the suggestion!

I have captured this in our Trello roadmap under the "ideas" column, which doesn't mean it's going to be built, but makes this suggestion available for community upvotes and "in the mix" for things we will consider adding to our backlog. 👍

Here it is: https://trello.com/c/zBuxRZXk/100-add-to-collection
