### ISSUE TITLE
Possible error in comments on Step Components

### ISSUE THREAD

**Issue by kendalled** [tailwindlabs/tailwindui-issues#288]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/navigation/steps
- Component name: Bullets (Example), but applies to rest

**Describe the bug**
The comments above each step all say `<!-- Completed step -->`, when the latter two should say `<!-- Incomplete step -->` for clarity, and maybe `<!-- Current step -->` for the highlighted one. 

**To Reproduce**
1. Go to 'steps'
2. Click on 'code'
3. Scroll down to '`<li>`'

**Expected behavior**
Comments that correctly label each dot

**Browser/Device (if applicable)**
 - OS: MacOS Catalina
 - Browser: All
 - Version: All

**Additional context**
Sorry if this is nit-picky, but the comments should help newcomers! I think this was a small oversight but wanted to mention.

**Comment by viloskovic** [comment]
Hi.

It's not only for the bullets. After a quick lookup I see that it is in fact for every component in that category.
For me this is just a trivial issue with the documentation, but for newcomers it can be indeed confusing.

**Comment by simonswiss** [comment]
Thanks for pointing that out! 

This is definitely something we need to fix. Speaking of which, I just did right now and will merge 👍

**Comment by simonswiss** [comment]
This is how the comments will look on next release: 

![image](https://user-images.githubusercontent.com/485747/90708265-b5dc0800-e2dc-11ea-97a7-29d8d0f090a3.png)

Thanks again for flagging it! 👍

**Comment by kendalled** [comment]
No prob, happy to help in any way I can.
