### ISSUE TITLE
Labels on left form layout with validation errors

### ISSUE THREAD

**Issue by Ramblurr** [tailwindlabs/tailwindui-issues#289]
There exists the [Labels on left](https://tailwindui.com/components/application-ui/forms/form-layouts#component-cc5bee94bc88387c2511b0e5c3dfffef) form layout.

There also exists the [Input with validation error](https://tailwindui.com/components/application-ui/forms/input-groups#component-7a5297f99a5ed22df80939dd1986de5f) that shows a field-level validation error on an input.

However these two do not combine well..

An example of validation errors on a "labels on left" form layout is sorely needed. 

Thanks!

**Comment by simonswiss** [comment]
Thank you for your suggestion!

I captured this in our roadmap "ideas" column with a link back to this issue: https://trello.com/c/UbR0ObD9/101-left-label-form-with-validation-example

Will close this, but you can  go upvote your suggestion in Trello! :)
