### ISSUE TITLE
Event Calendar: Month, week, day, and list views 

### ISSUE THREAD

**Issue by ademers** [tailwindlabs/tailwindui-issues#29]
**Screenshots**
From [FullCalendar](https://fullcalendar.io) website:
- Month: https://share.getcloudapp.com/z8uX4BWo
- Week: https://share.getcloudapp.com/WnuNlXv5
- Day: https://share.getcloudapp.com/nOuNDJ0B
- List: https://share.getcloudapp.com/6quBxXyW

**Additional context**
Would be super useful and a huge time saver for websites featuring event calendars.

Thanks for your consideration!

**Comment by simonswiss** [comment]
Thanks for this suggestion! Captured this in our "bag of ideas" in our trello roadmap: https://trello.com/c/tc5JwcIn/91-calendar-view 👍

Make sure you go upvote it there :)

**Comment by ademers** [comment]
Excellent. Thank you!
