### ISSUE TITLE
TailwindUI components site improvements

### ISSUE THREAD

**Issue by robdekort** [tailwindlabs/tailwindui-issues#292]
Not sure if this belongs here and if it's appreciated but I'll give it a shot anyway. Feel free to delete this.

Of course I can manage, but I find it a little difficult to browse the TailwindUI components page.  All the dressed down component graphics are in grey tones and it is column based. This makes it difficult for me to discern the different categories and find what I need. Instead of browsing and taking it in I usually go to `cmd+f` and try some search terms to find what I need

It might be nice to separate stuff on different pages as well: marketing and application UI.

Keep up the awesome work folks!

**Comment by adamwathan** [comment]
Hey thanks @robdekort! Agree this is something we can improve. There is a "secret" search option right now you might find helpful, available via `cmd+k`:

![image](https://user-images.githubusercontent.com/4323180/91198656-d33d1780-e6ca-11ea-8531-c976a92476a6.png)

Need to surface that in the UI properly at some point!

**Comment by robdekort** [comment]
Oh that's great, didn't knew that :-). Thanks @adamwathan. If you need input at any time. Feel free to reach out.

**Comment by simonswiss** [comment]
Closing this issue for now 👍
