### ISSUE TITLE
Missing transitions

### ISSUE THREAD

**Issue by MrJmpl3** [tailwindlabs/tailwindui-issues#293]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/forms/select-menus
- Component name: Simple custom

**Describe the bug**
If you use devtools can see the transitions, but in code sample section are missing.

**Comment by simonswiss** [comment]
Yep, I see what you mean and can confirm there is a bug here - the code snippet should display a list of transition classes to add.

Thanks for reporting - will provide a fix soon! 👍
