### ISSUE TITLE
Incorrect class

### ISSUE THREAD

**Issue by MrJmpl3** [tailwindlabs/tailwindui-issues#294]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/marketing/sections/heroes
- Component name: With sign-in form

**Describe the bug**
The overflow-hidden is in the line 1, but in the visual example with devtools is in line 2.

**Comment by simonswiss** [comment]
Hi @MrJmpl3 👋

Thanks for reaching out!

I don't think this is a bug - this happens in every component example. We have some sort of `layout` wrapper for each component that is not part of the code snippets. 

We use this to provide some padding, background color, etc to "embellish" the presentation of certain components in the preview.

In this specific component, the first `div` of the UI component is the one highlighted in blue:

![image](https://user-images.githubusercontent.com/485747/91385836-19ce7580-e875-11ea-9b75-36e0bf1e7343.png)

Does this make sense?

**Comment by MrJmpl3** [comment]
Oh, ok. A question, in this component, the icon pattern is broken when add more section to the default hero sections. ¿Maybe need wrap the background svg pattern to the section instead the section and navbar?

**Comment by simonswiss** [comment]
Yes, depending on how you're trying to modify that hero section, you may need to move the SVG pattern higher up in the component tree.

We're actually planning to do some work to make the hero / navigation components more "composable" and easier to separate, this is captured in https://github.com/tailwindlabs/tailwindui-issues/issues/220 and will probably lead to some refactoring around these anyway! 👍
