### ISSUE TITLE
shadow-outline not generated for extended color palette

### ISSUE THREAD

**Issue by goellner** [tailwindlabs/tailwindui-issues#296]
**What component (if applicable)**
Input & Select

**Describe the bug**
Trying to use `shadow-outline-primary` in my project, but it doesn't work. Seems the 

**To Reproduce**
Steps to reproduce the behaviour:
1. Extend the default color palette with a new color (with shades)
2. Try to set `shadow-outline-primary` on an element
3. Not working

**Expected behaviour**
The shadow-outline should get extended and work with a single extended color and a color palette.

**Comment by RobinMalfait** [comment]
I don't think it is an actual bug since we hardcoded it in the Tailwind UI config (https://unpkg.com/browse/@tailwindcss/ui@0.5.0/index.js#L81). I would suggest to add it in the extend section of your config. https://tailwindcss.com/docs/box-shadow#customizing
