### ISSUE TITLE
Code formatted for react

### ISSUE THREAD

**Issue by goellner** [tailwindlabs/tailwindui-issues#297]
It would be great to have the code available for React. It doesn‘t need all the transition stuff, it would be so much quicker to copy/paste stuff.

And a second improvement I would suggest is to highlight open/closing elements, when clicking on them. Most of the time I copy the whole html in my editor to find the closing tag.

**Comment by itzshahay** [comment]
Don't you just have to edit the `class=*` to `className=*` and then it's usable in React?

**Comment by goellner** [comment]
Every image needs to have a closing `/>` and I haven't found a solution for searching & replacing those. I think it is the same for input elements. Also the attributes on SVGs have to be changed manually.

**Comment by RobinMalfait** [comment]
You can use this bookmark in the mean time: https://gist.github.com/RobinMalfait/a90e8651196c273dfa51eec0f43e1676

**Comment by goellner** [comment]
> You can use this bookmark in the mean time: https://gist.github.com/RobinMalfait/a90e8651196c273dfa51eec0f43e1676

This is absolutely great! Thank you, this will do the job perfectly for now

**Comment by itzshahay** [comment]
I'm not against it, I'm simply wondering, and also I was unaware of the closing tag being forced. Doesn't it seem overkill to have different code versions when it takes less than a minute to convert it anyway?

**Comment by simonswiss** [comment]
Hey 👋

The React (and Vue) version of Tailwind UI components is a frequently asked feature 👍

As you may have heard, we're currently building a library called Headless UI, which will come in both React & Vue flavours. This library will be used to power Tailwind UI components and allow users to select between HTML, React or Vue versions of the components.

Like Robin said, using [this tool](https://gist.github.com/RobinMalfait/a90e8651196c273dfa51eec0f43e1676) in the meantime is probably the easiest path to converting Tailwind UI components to React.

Going to close this issue now. You can [follow the evolution of Headless UI's React version on GitHub](https://github.com/tailwindlabs/headlessui/tree/develop/packages/%40headlessui-react) 🎉
