### ISSUE TITLE
All Steps are annotated as “Complete Step”

### ISSUE THREAD

**Issue by inopinatus** [tailwindlabs/tailwindui-issues#298]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/navigation/steps
- Component name: Steps

**Describe the bug**

All of the sample code is commented as “Complete Step”, including samples that are clearly not for completed steps. 

**To Reproduce**

1. Go to Steps page
2. Click on Code for any of the components
3. Read the comments 

**Expected behavior**

Not sure of precise intention but I was looking for comments to correctly pick out the “Current Step” and “Incomplete Step” components.

**Additional context**

I was also hoping for some UX clarification around correct presentation if a user goes back to an earlier step I.e. the currently displayed step is in the middle of a sequence of otherwise completed steps (which might occur if this is used to help break up a form).

**Comment by simonswiss** [comment]
Hey 👋

There was a similar bug with the comments when we initially released the steps components, but I fixed it the day after the release.

I just checked all the steps components, and they all seem to have the correct comment (completed, current, upcoming).

Maybe something happened in the 18 days (sorry for the delay 😅) between your message and mine?

Could you please check again?

Re: going back to previous steps - we haven't considered this scenario, but my immediate thinking is I would style the step they went back to as "current step" and any steps already completed _after_ that as "completed step", and the rest "upcoming".

This might need a bit more thinking than that though - we'll keep this scenario in mind, thanks for the suggestion! 👍

**Comment by inopinatus** [comment]
@simonswiss yep, looks good now. Thanks!
