### ISSUE TITLE
Use absolute paths for example images

### ISSUE THREAD

**Issue by adamwathan** [tailwindlabs/tailwindui-issues#3]
Right now example images like the "Workflow" logo use site-relative paths like `/img/logos/workflow.svg` in the component HTML. This means when someone copies it into their project the image is broken. The image is meant to be replaced of course anyways so it's not an enormous issue, but it would certainly be nicer if the example looked identical when they pasted it in.

**Comment by simonswiss** [comment]
Closing this as there are no more relative path for images in the examples 👍
