### ISSUE TITLE
Search capability

### ISSUE THREAD

**Issue by LarryBarker** [tailwindlabs/tailwindui-issues#30]
This is not a component request, but more a feature request, so my apologies if this is not the best place for my idea. Anyhow, it would be extremely helpful if we could search components, or have a menu of some kind to narrow down what we are looking for.

Currently, if I am looking for a specific component, I have to think about which section it lives in (Marketing vs. Application), and then I have to scroll through to find the appropriate section. Finally, I may be looking for a specific component out of many, and if I don't know where it lives, it can be difficult to find.

**Comment by dillingham** [comment]
Would love `CMD` + `/` to search from list or single component.

**Comment by vvo** [comment]
I wonder if [DocSearch](https://docsearch.algolia.com/) could help here, @s-pace? The only challenge might be that some parts of Tailwind UI are public and some are not.

DocSearch powers most of the developer's documentations nowadays, see it in action here: https://reactjs.org/. They do require a logo in the search results for the owning company (Algolia).

Thoughts?

**Comment by LarBearrr** [comment]
@vvo I would think the tailwind team could differentiate or identify which components should be publicly searchable and use a different index for each? Or only offer search to paid subscribers?

**Comment by vesper8** [comment]
Am really missing the ability to quickly search for anything. The search works so well on tailwindcss.com, I'd love something just like it on tailwindui.com

**Comment by s-pace** [comment]
Happy to help, [just apply and we will quickly solved this](https://docsearch.algolia.com/apply/)

**Comment by Christophvh** [comment]
This has been implemented. Press '/' or CMD+K

**Comment by vvo** [comment]
Nice, I see it was implemented client side (no Algolia), what's the module you're using to do that? Thanks!

**Comment by adamwathan** [comment]
We just have a big array of all the component categories that we pull out of our database and send that to the front-end as a static list, then use [Fuse.js](https://fusejs.io/) to fuzzy search the list based on user input 👍

**Comment by MrSunshyne** [comment]
@adamwathan Pressing "/" in Firefox also opens the browser "find on page" box and grabs the cursor. 

Browser: Firefox 75.0
OS: KDE Neon

CTRL + K works fine though. 

![Screenshot_20200411_220717](https://user-images.githubusercontent.com/1721611/79051386-0cf01300-7c41-11ea-8ce9-63e189d6f7e6.png)

**Comment by davidluhr** [comment]
As of 2020-11-23, this issue seems to be fully addressed by past work in April and August. Closing this now.
