### ISSUE TITLE
sidebar code w-14

### ISSUE THREAD

**Issue by chucklin72** [tailwindlabs/tailwindui-issues#300]
<div class="flex-shrink-0 w-14">
        
      </div>

Tailwind v1.7.5 does not have a w-14

**Comment by chucklin72** [comment]
also in a related issue the close button class has mr-14 which also does not exist.

**Comment by RobinMalfait** [comment]
You have to add the `@tailwindcss/ui` package, this contains the `w-14` and `mr-14` classes. See: https://tailwindui.com/documentation
