### ISSUE TITLE
Review star component

### ISSUE THREAD

**Issue by seb-jean** [tailwindlabs/tailwindui-issues#301]
Hi :smile: 
It would be great to have a review star component.

For example:

![Image](https://i.imgur.com/jsWqOjm.png)

Or:

![Image](https://i.imgur.com/IQHDz3U.png)

Thanks

**Comment by simonswiss** [comment]
Awesome suggestion! ⭐️

I have captured this in the "bag of ideas" column our Trello roadmap, where the community can upvote it.

https://trello.com/c/Xt8pehsw/105-star-review

If it gets enough demand, we'll consider adding it to the backlog of things we plan to build 👍

Thanks again for the suggestion - closing this for now, but please go and upvote this request in Trello!
