### ISSUE TITLE
Card Heading Button c

### ISSUE THREAD

**Issue by meanspa** [tailwindlabs/tailwindui-issues#302]
Apologies! Somehow accidentally submitted this prematurely, ignore/delete this issue.

**Comment by RobinMalfait** [comment]
(Fyi: You can also edit issues, so there is no need to close and open a new one)

**Comment by meanspa** [comment]
Thanks again! I actually didn't realize this issue was created until _after_ I created and submitted the second one, still not sure how it happened to be honest.
