### ISSUE TITLE
Hierarchical comments

### ISSUE THREAD

**Issue by andrew-snek** [tailwindlabs/tailwindui-issues#306]
Would be very cool to see hierarchical comments from you. This is what Reddit has, for example:
<img width="863" alt="Screenshot 2020-09-02 at 12 18 57" src="https://user-images.githubusercontent.com/45121397/91963572-af0ab780-ed16-11ea-89aa-1fb700f81d6f.png">

**Comment by simonswiss** [comment]
Thanks for the suggestion!

Going to move this to our "bag of ideas" in the Trello roadmap, where people can upvote it. If it gets enough traction, it might be moved into the backlog of things we're building for Tailwind UI! 👍

Here's the link to it: https://trello.com/c/6cHXXtwe/106-nested-comments

Will close this now, but go and upvote your suggestion in Trello 🎉
