### ISSUE TITLE
Figma / Sketch Library

### ISSUE THREAD

**Issue by chrispadfield** [tailwindlabs/tailwindui-issues#307]
There was some discussion on twitter about a Figma / Sketch component library being created. I hope it's ok to create this issue so there is something to subscribe to regarding a release for this; but also any updates on progress or alpha/beta we could experiment with would be really helpful.

**Comment by vvo** [comment]
@chrispadfield Are you on the discord channel? There's indeed a Figma file available at the moment, in beta. Read the tailwindui documentation and join the discord channel #figma-kits

And if this works for you, close this issue!

**Comment by chrispadfield** [comment]
Great thanks!
