### ISSUE TITLE
Suggestion for component markup refactoring, using grid on one column

### ISSUE THREAD

**Issue by kyotoprotokollet** [tailwindlabs/tailwindui-issues#308]
Not sure on how to suggest this (ticket-wise), but I have a suggestion:

Some components use a pattern where they start out in one column and expand to multiple columns on wider viewports, for example the "Meet our leadership" component on the [team section page](https://tailwindui.com/components/marketing/sections/team-sections).

Most of these components seem to use a pattern where _space-y_  is used and then canceled out when the multi column grid which uses gap comes inte play. I don't see the use for this since we can just use grid and gap directly while on one column.

The example "Meet our leadership" contains the following classes for the list:

`space-y-12 sm:grid sm:grid-cols-2 sm:gap-12 sm:space-y-0 lg:col-gap-8`

but could just aswell be written as 

`grid gap-12 sm:grid-cols-2  lg:col-gap-8 `

which reads a lot nicer I think.

**Comment by simonswiss** [comment]
We've started doing this on new components, and I think this is a valuable suggestion, as it definitely makes the code easier to read/understand 👍

We have a few things we want to refactor (using new spacing utilities for example), and I'll add this to the list of improvement we want to bring to the component markup when we go through some refactoring.

I have captured this internally, so I'll close this issue now, but thank you so much for sharing this! 🙏

**Comment by kyotoprotokollet** [comment]
Great to hear!
