### ISSUE TITLE
Changing select menu icon color changes the icon

### ISSUE THREAD

**Issue by damienbuckley** [tailwindlabs/tailwindui-issues#310]
Not sure if I'm doing this wrong or if it's a bug. I'm trying to change the color of the icon in UI select fields. The only way I can find to do this is making the adjustments for customForms - bundled with UI; When I try this however, the icon also changes to the single arrow as per the customForms plugin and not the double up/down arrows in the UI library.

`customForms: theme => ({
      default: {
        select: {
          iconColor: theme('colors.indigo.700'),
        },
        checkbox: {
          iconColor: theme('colors.indigo.700'),
        },
        radio: {
          iconColor: theme('colors.indigo.700'),
        },
      },
    })`

**Comment by simonswiss** [comment]
Hey Damien! 👋🇦🇺

Sorry it took so long to get back to you!

In the [documentation for the custom forms plugin](https://tailwindcss-custom-forms.netlify.app/), here's a relevant paragraph for what you're trying to do:

> If you are using a custom icon and still want to use the `iconColor` property to make it easy to change the color without re-specifying your entire custom SVG, define your custom icon as a callback that receives the icon color:

```javascript
customForms: (theme) => ({
  default: {
    checkbox: {
      icon: (iconColor) =>
        `<svg fill="${iconColor}" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg" ><path d="M0 11l2-2 5 5L18 3l2 2L7 18z"/></svg>`,
      iconColor: theme("colors.gray.800"),
      "&:hover": {
        iconColor: theme("colors.gray.700"),
      },
    },
  },
});
```

So, in your case, you want to do something like this to keep the Tailwind UI icons, but apply your custom color to them:


```javascript
customForms: (theme) => ({
  default: {
    select: {
      icon: (iconColor) =>
        `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="none"><path d="M7 7l3-3 3 3m0 6l-3 3-3-3" stroke="${iconColor}" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/></svg>`,
      iconColor: theme("colors.indigo.700"),
    },
    checkbox: {
      icon: (iconColor) =>
        `<svg viewBox="0 0 16 16" fill="${iconColor}" xmlns="http://www.w3.org/2000/svg"><path d="M5.707 7.293a1 1 0 0 0-1.414 1.414l2 2a1 1 0 0 0 1.414 0l4-4a1 1 0 0 0-1.414-1.414L7 8.586 5.707 7.293z"/></svg>`,
      iconColor: theme("colors.indigo.700"),
    },
    radio: {
      icon: (iconColor) =>
        `<svg viewBox="0 0 16 16" fill="${iconColor}" xmlns="http://www.w3.org/2000/svg"><circle cx="8" cy="8" r="3"/></svg>`,
      iconColor: theme("colors.indigo.700"),
    },
  },
}),

```

Hope it helps! 👍

**Comment by damienbuckley** [comment]
Hey mate,

Got it, thanks!

Have a good one
D

**Comment by damienbuckley** [comment]
Hey Simon

Any ideas how I change this icon after upgrading to Tailwind 2?

Damien
