### ISSUE TITLE
Modals are always ABOVE any other element, even when hidden

### ISSUE THREAD

**Issue by kinxos** [tailwindlabs/tailwindui-issues#312]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/overlays
- Component name: Modals

**Describe the bug**
Modals have the following top element:
```html
<div class="fixed z-10 inset-0 overflow-y-auto">
```
This way, modals are ALWAYS ABOVE any other elements on the page, even though they're "hidden". According to the docs, that element should not be shown/hidden based on state. However, if it were (by adding, in Vue, v-show="show", for example), then the hide transition of the children doesn't play.

**To Reproduce**
Include the modal code alongside any other code on a page.
In my case, I made a component for the modal, so I have:
```html
<modal :show="showModal"></modal>
<button type="button" @click="showModal = true">Show modal</button>
```
The problem is that the button is not clickable because the modal element is above it.

**Expected behavior**
Modals should not affect the "clickability" of other elements on the page.
I have idea if it's possible, but maybe the top div could be the overlay itself.

**Comment by acabreragnz** [comment]
The solution is here:
https://github.com/tailwindlabs/tailwindui-issues/issues/263
