### ISSUE TITLE
iOS Scrolling Bug (e.g. fixed search header)

### ISSUE THREAD

**Issue by booni3** [tailwindlabs/tailwindui-issues#313]
A solution to fix one part of this has been proposed in #236, however, it feels like Tailwind UI should be compatible with iOS out of the box with all components? I would expect the application shells to work on Desktop and Mobile out of the box without any mods needed. Correct me if I am missing something here 😄 

**Issue**
- Any components that are using screen height (this may not be the root cause but what I have seen so far) produce scrolling issues where you have to make a double scroll to go the full length of the screen.

- An example of this which is easy to see is on the [full screen example](https://tailwindui.com/components/application-ui/page-examples/home-screens#component-af4086fe483fb8a418175cf0218dd5c4) with the **fixed search header** on iOS safari.

**Fix**

As suggested in #236 , you can make the following change:

```html
<div class="h-screen flex overflow-hidden bg-white">
```

to:

```html
<div class="h-full fixed inset-0 flex overflow-hidden bg-white">
```

This fixes the scrolling issue but introduces issues into other components such as the modal component (**which also uses a screen height directive**). I expect there will be other components that are broken by this change too.

**Comment by simonswiss** [comment]
Thanks for raising this. 

There are a bunch of issues of the same "family" of iOS `h-screen` issues. We're going to look at all of this soon 👍
