### ISSUE TITLE
When custom colors are specified, tailwindui colors are removed

### ISSUE THREAD

**Issue by Zippersk** [tailwindlabs/tailwindui-issues#314]
**Describe the bug**
When I specify some custom colors in `tailwind.config.js`, I can not access any of the tailwindui colors. I need to manually import them and merge them with my custom colors:

```js
const defaultTheme = require("tailwindcss/defaultTheme")
const tailwindUi = require("@tailwindcss/ui")
const tailwindUiColors = require('@tailwindcss/ui/colors')

module.exports = {
  theme: {
    extend: {
      colors: {
        /*
        * My custom colours are here
        */ 
        ...tailwindUiColors // colors from tailwind UI - imo this should not be needed
      },
    },
  },
  plugins: [tailwindUi],
};
```

**To Reproduce**
Steps to reproduce the behaviour:
1. Set `tailwind.config.js` to:
```js
const defaultTheme = require("tailwindcss/defaultTheme")
const tailwindUi = require("@tailwindcss/ui")
const tailwindUiColors = require('@tailwindcss/ui/colors')

module.exports = {
  theme: {
    extend: {
      colors: {
        darkness: "#000"
      },
    },
  },
  plugins: [tailwindUi],
};
```

2. Try to use some color from tailwindui:
```html
<div class="bg-gray-50">This div should have gray background but it does not.</div>
```

**Expected behaviour**
When applying tailwind plugin, colours should automatically merge with user-defined ones.

**Comment by adamwathan** [comment]
Hey @Zippersk! You shouldn't need to spread in the colors, I just tested with this config for example and all the Tailwind UI colors are preserved and `banana` is just added as an additional color:

```js
// tailwind.config.js
module.exports = {
  purge: [],
  theme: {
    extend: {
      colors: {
        banana: 'yellow',
      },
    },
  },
  variants: {},
  plugins: [require('@tailwindcss/ui')],
}
```

Can you create a GitHub repo that reproduces your issue reliably? I wonder if it's a configuration issue elsewhere.

Here's my sample repo for reference:

https://github.com/adamwathan/tailwind-plugin-color-extend-example
