### ISSUE TITLE
Item table with filtering

### ISSUE THREAD

**Issue by CodeAndWeb** [tailwindlabs/tailwindui-issues#316]
I'd like to have a nice header for filtering a list of items.

* Filter
* Clear filter
* Display number of visible/total items
* Display of an alert / info if filter results in an empty list

**Screenshots**
<img width="935" alt="2020-09-07_09-31-08" src="https://user-images.githubusercontent.com/716009/92360305-e13c6080-f0ec-11ea-8165-528cab8c25a1.png">

**Comment by simonswiss** [comment]
Great suggestion! 👍

I have captured this in our Trello roadmap under the "ideas" column, which is where the community can "upvote" component they'd like to see implemented.

https://trello.com/c/ZmNhrK9V/104-table-with-filtering-header

Closing this - but please go upvote your suggestion in Trello 😀
