### ISSUE TITLE
Tailwind CSS v1.7+ New Gap Utilities Support

### ISSUE THREAD

**Issue by rthaut** [tailwindlabs/tailwindui-issues#317]
**Describe the bug**
Most current components still use the [deprecated gap utilities](https://github.com/tailwindlabs/tailwindcss/releases/tag/v1.7.0#deprecated-gap-utilities). While these work on the Tailwind UI site, they do not work for users on Tailwind 1.7+ who have opted into the new names via `removeDeprecatedGapUtilities`.

**Additional context**
I did not see this on either repository (tailwindui-issues / tailwindcss), nor did I see it on the Trello Roadmap board that seemed to related. This may be something the team is already aware of, and it is an easy fix for users who intentionally have switched to the new utility names, but I thought it was worth pointing out because similar situations will likely arise as Tailwind continues to grow/evolve/expand.

Specifically for the gap utilities, I caught this on the Contact Sections (https://tailwindui.com/components/marketing/sections/contact-sections).

In a more general sense, I don't know if there is any long-term plans for Tailwind UI components to maintain Tailwind v1.x support or not. In my experience with corporate environments, you might find many teams will be stuck on v1.x long after v2+ is available, so there may be some desire (by users) for the team to maintain different versions of components for specific versions of Tailwind.

**Comment by simonswiss** [comment]
Hey - thanks for reporting this!

This is definitely something we need to refactor in the Tailwind UI components, and it's been captured in our list of "needs refactoring" for the component library.

We'll get around to it - like you said this will become a gradually increasing nuisance, and needs to be fixed. 👍

**Comment by simonswiss** [comment]
Happily reporting that this has now been implemented! The deprecated `col-gap` and `row-gap` utilities have been replaced by `gap-x` and `gap-y` in all of the components 👍
