### ISSUE TITLE
Inter font without CDN

### ISSUE THREAD

**Issue by iquito** [tailwindlabs/tailwindui-issues#32]
I do like the usage of the Inter font in Tailwind UI (as a recommended font), and including it via CDN is fine, but requires internet and I found that with spotty internet my local development is often having troubles just because of the Inter font (no internet needed for anything else).

It would be nice to have an easy way to include the Inter font locally. I did find the package [inter-ui](https://www.npmjs.com/package/inter-ui), but I have no clue how to integrate it with Tailwind. So some documentation on how to include Inter for internet-less development (or self hosting) would be nice, as I can imagine that many people would benefit from a quick way to enable this.

**Comment by maxbeatty** [comment]
Inter is in the final steps of being added to Google Fonts (https://github.com/google/fonts/issues/1455#issuecomment-593300195). Then, it'll be much easier to use locally ([FAQ](https://developers.google.com/fonts/faq#can_i_download_the_fonts_on_google_fonts_to_my_own_computer)).

**Comment by DanHarrin** [comment]
@maxbeatty Google Fonts won't work locally though.

I use [typeface-inter](https://www.npmjs.com/package/typeface-inter). Simply `require('typeface-inter')` in a JS file, compile and it just works!

Note: this package works out-of-the-box with Laravel Mix if you're using that!

@adamwathan - maybe include this as an alternative to the CDN in the docs?

**Comment by maxbeatty** [comment]
It’s live: https://fonts.google.com/specimen/Inter

**Comment by iquito** [comment]
@DanHarrin: Thanks, that was what I was looking for. I also needed to include `vendors~app.css` in my project (I am using Symfony & Webpack Encore) where the font-face definitions ended up.

@maxbeatty: That doesn't help, as I am making the project build itself via docker, so it will be the same on any platform. Having to install a font manually is not a nice step compared to just being able to run "docker/server-dev" and all dependencies are taken care of.
