### ISSUE TITLE
Use pseudo classes to reduce class-differences in looped elements

### ISSUE THREAD

**Issue by pA1nD** [tailwindlabs/tailwindui-issues#320]
**Component**
- URL for category: https://tailwindui.com/components/application-ui/navigation/tabs
- Component name: Navigation

**Describe the bug**
One of the things that slow me down when using tailwindUI are the slight difference in classes that will be created in a loop.

A very good example can be seen in the Navigation Links.

It is clear that hover: and focus: have to be different. But you also have to track down the `ml-4`. Which - as it happens quite frequently, consumes time and brain-power - and while it is fast for me to diff two class strings, it makes it harder if I have to diff three class strings.

Below a code example that shows how three elements I would create in a loop that have three different set of clases.

```html
    <nav class="flex">
      <a href="#" class="px-3 py-2 font-medium text-sm leading-5 rounded-md text-gray-600 hover:text-gray-800 focus:outline-none focus:text-gray-800 focus:bg-gray-200">
        My Account
      </a>
      <a href="#" class="ml-4 px-3 py-2 font-medium text-sm leading-5 rounded-md text-gray-600 hover:text-gray-800 focus:outline-none focus:text-gray-800 focus:bg-gray-200">
        Company
      </a>
      <a href="#" class="ml-4 px-3 py-2 font-medium text-sm leading-5 rounded-md text-gray-800 bg-gray-200 focus:outline-none focus:bg-gray-300" aria-current="page">
        Team Members
      </a>
    </nav>
```

It would be possible to handle this with a pseudo element instead. e.g. `not-first:ml-4`. This is aligned with what @adamwathan wrote here: https://github.com/tailwindlabs/discuss/issues/214#issuecomment-493628699

Aside from making copying over UI code simpler, I feel it would also make the code more expressive (idiomatic).

Here an example, how the above would look with a `not-first:` class:

```javascript
// tailwind.config.js
const plugin = require('tailwindcss/plugin')

module.exports = {
  variants: { margin: ['responsive', 'not-first'] },
  plugins: [
    require('@tailwindcss/ui')({ layout: 'sidebar' }),
    plugin(function ({ addVariant, e }) {
      addVariant('not-first', ({ modifySelectors, separator }) => {
        modifySelectors(({ className }) => {
          return `.${e(`not-first${separator}${className}`)}:not(:first-child)`
        })
      })
    }),
  ],
}

```

```html
    <nav class="flex">
      <a href="#" class="not-first:ml-4 px-3 py-2 font-medium text-sm leading-5 rounded-md text-gray-600 hover:text-gray-800 focus:outline-none focus:text-gray-800 focus:bg-gray-200">
        My Account
      </a>
      <a href="#" class="not-first:ml-4 px-3 py-2 font-medium text-sm leading-5 rounded-md text-gray-600 hover:text-gray-800 focus:outline-none focus:text-gray-800 focus:bg-gray-200">
        Company
      </a>
      <a href="#" class="not-first:ml-4 px-3 py-2 font-medium text-sm leading-5 rounded-md text-gray-800 bg-gray-200 focus:outline-none focus:bg-gray-300" aria-current="page">
        Team Members
      </a>
    </nav>
```

**Comment by simonswiss** [comment]
Hey!

In this particular scenario, you can handle the `ml-4` on every item except the first with the new [`space-between` utilities](https://tailwindcss.com/docs/space) added since Tailwind CSS version 1.3.

We've started going through the Tailwind UI components to replace these in many places, for components that were built before these spacing utilities existed, so... this will probably change at some point in the components you're looking at 👍

In your example, the code would look like this.. note the `space-x-4` class on the parent `nav` element, which allows us to remove the `ml-4` on the individual link elements 🙌

```html
    <nav class="flex space-x-4">
      <a href="#" class="px-3 py-2 font-medium text-sm leading-5 rounded-md text-gray-600 hover:text-gray-800 focus:outline-none focus:text-gray-800 focus:bg-gray-200">
        My Account
      </a>
      <a href="#" class="px-3 py-2 font-medium text-sm leading-5 rounded-md text-gray-600 hover:text-gray-800 focus:outline-none focus:text-gray-800 focus:bg-gray-200">
        Company
      </a>
      <a href="#" class="px-3 py-2 font-medium text-sm leading-5 rounded-md text-gray-800 bg-gray-200 focus:outline-none focus:bg-gray-300" aria-current="page">
        Team Members
      </a>
    </nav>
```

Hope it helps!

**Comment by simonswiss** [comment]
Going to close this now, please re-open if you have any more concerns 👍
