### ISSUE TITLE
Team Section row and column gap needs update

### ISSUE THREAD

**Issue by madsh93** [tailwindlabs/tailwindui-issues#321]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/marketing/sections/team-sections
- Component name: With large images

**Describe the bug**
Columns and rows are missing gap. Users using Tailwind > v1.7.0 will be experiencing this minor bug.

**To Reproduce**
1. Copy code using Tailwindcss v. 1.7.1+
2. Missing row and column gap

A simple Search and Replace fixes this issue.

**Comment by adamwathan** [comment]
Just deployed an update that updates all usage of the col-gap and row-gap utilities to gap-x and gap-y 👍🏻 Thanks!
