### ISSUE TITLE
Passing options from @tailwindcss/ui to typography plugin

### ISSUE THREAD

**Issue by thomasbrus** [tailwindlabs/tailwindui-issues#322]
So I already solved this but I figured it might be helpful to post it here still in case anyone else runs into this problem as well. Couldn't figure out how to pass a [custom class name](https://github.com/tailwindlabs/tailwindcss-typography/pull/28) to the @tailwindcss/typography plugin, but found a simple workaround.. Just disable the plugin and require it separately 👍 

```js
  plugins: [
    require('@tailwindcss/ui')({ typography: false }),
    require('@tailwindcss/typography')({ className: 'html' }),
  ],
```

However it'd be nice if `@tailwindcss/ui'` accepted a hash of options that is then passed to the typography plugin:

```js
require('@tailwindcss/ui')({ typography: { className: 'html' } })
```

**Comment by davidluhr** [comment]
@thomasbrus Would you let us know if this is still needed?

The recent Tailwind CSS 2.0 release and updates to Tailwind UI have a couple related changes:
1. There is no longer a dedicated Tailwind UI plugin
1. The typography plugin has improvements
1. There have been improvements to plugins with the new presets feature in Tailwind CSS

I'm not sure if these affect your use case or make it easier, but thought it might be relevant.

**Comment by thomasbrus** [comment]
Yep very cool improvements 👍 Was planning to upgrade this week:)

Since there is no dedicated Tailwind UI plugin anymore and I was already requiring the Typography plugin separately, the change is indeed no longer needed!

**Comment by davidluhr** [comment]
@thomasbrus Awesome! Thanks for the follow-up. Closing this now.
