### ISSUE TITLE
Single price with details component does not scale well

### ISSUE THREAD

**Issue by thomasschiet** [tailwindlabs/tailwindui-issues#323]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/marketing/sections/pricing
- Component name: Single price with details

**Describe the bug**
The  'Lifetime Membership' panel does not scale well with the descriptive text on `lg` or `xl` screen size.

**To Reproduce**
1. Replace `Lorem ipsum dolor sit amet consect etur adipisicing elit. Itaque amet indis perferendis blanditiis repellendus etur quidem assumenda.` with a short string.
2. The div with the shadow stays full width, but the inner part of the component shrinks. See screenshot.

**Expected behavior**
Component correctly scales, e.g. with`lg:flex-grow` in element `<div class="bg-white px-6 py-8 lg:p-12>`.

**Screenshots**
<img width="1278" alt="Screenshot 2020-09-19 at 16 38 00" src="https://user-images.githubusercontent.com/286026/93669731-7d277e00-fa96-11ea-8dfb-497c72e9d16c.png">

**Browser/Device (if applicable)**
 - OS: MacOS
 - Browser: Firefox
 - Version: 80

**Comment by simonswiss** [comment]
Thanks for raising this! 

Will merge a fix now 👍
