### ISSUE TITLE
Toggle with Text

### ISSUE THREAD

**Issue by black-forest-digital** [tailwindlabs/tailwindui-issues#324]
**Additional context**
In my daily use, toggles always have a label text. So how about adding the toggles with labels and also include them in the form layouts demo?

Best,
Philipp

**Comment by simonswiss** [comment]
Thanks for the suggestion - making note of this internally and also captured this in the Trello roadmap "suggestions/bag of ideas" column 👍

👉 https://trello.com/c/bGTywaom/103-toggles-with-label
