### ISSUE TITLE
Credit Card Input

### ISSUE THREAD

**Issue by leonardoviada** [tailwindlabs/tailwindui-issues#325]
Hi there, I have to say you've done an awesome job until now and I'm building my new Saas with your component.
Defining the billing section I came across the need of a credit card input widget. Down below some inspiration...

Again, great idea and components!
Looking forward to see what's next.

My best regards,
Leonardo

**Screenshots**
![image](https://user-images.githubusercontent.com/52712266/93885778-de449100-fce4-11ea-969d-80ceef53d445.png)
![cardInput](https://user-images.githubusercontent.com/52712266/93886081-4a26f980-fce5-11ea-945f-32860aaaa7b6.PNG)

**Comment by simonswiss** [comment]
Hey, thanks for the suggestion!

I have captured this idea in our "bag of ideas" in the Trello roadmap: https://trello.com/c/9PoJNdBx/102-credit-card-input

This doesn't mean it will necessarily be built, but it's definitely "in the mix" of things to be considered when planning the next batch of UI components 👍
