### ISSUE TITLE
Full-Width with Sidebar Truncate Not Working

### ISSUE THREAD

**Issue by brjohnson4** [tailwindlabs/tailwindui-issues#326]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/page-examples/home-screens
- Component name: Full-width with sidebar

**Describe the bug**
The @username on the sidebar does not truncate when longer than the sidebar width. Instead, the flex-div just expands .

**To Reproduce**
1. Replace "@jessyschwarz" with a much longer string.
2. You can then see the expanded @username that does not truncate

**Expected behavior**
The truncate class should cut the username off once it expands beyond the div, correct?

**Screenshots**
<img width="470" alt="Screen Shot 2020-09-22 at 8 35 57 PM" src="https://user-images.githubusercontent.com/8931326/93951065-545fec80-fd13-11ea-9846-a934976911b7.png">

**Browser/Device (if applicable)**
 - OS: MacOS
 - Browser: Safari, Chrome, Firefox

**Comment by simonswiss** [comment]
Confirming this - thatks for pointing it out - fixing now!
