### ISSUE TITLE
Team Sections: Full width with vertical images does not resize uniformly

### ISSUE THREAD

**Issue by davecardwell** [tailwindlabs/tailwindui-issues#327]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/marketing/sections/team-sections
- Component name: Full width with vertical images

**Describe the bug**
As you resize the section horizontally the images do not maintain the same height, at some points having four distinct image sizes.

**To Reproduce**
1. Go to https://tailwindui.com/components/marketing/sections/team-sections
2. Scroll down to “Team Sections: Full width with vertical images”
3. Drag the slider to decrease and increase the available horizontal space and watch each image resize independently

**Expected behavior**
I would expect the images to resize together and believe this would look much neater.

**Screenshots**
<img width="995" alt="Screen Shot 2020-09-23 at 7 27 45 PM" src="https://user-images.githubusercontent.com/7639/94084163-de22bf00-fdd2-11ea-91c3-8ccd28906727.png">

**Browser/Device (if applicable)**
 - OS: macOS Catalina 10.15.6 (19G2021)
 - Browser chrome
 - Version 85.0.4183.102

**Additional context**
N/A

**Comment by simonswiss** [comment]
Yep, good call - this is not how it's supposed to behave 👍

Your assumption of expected behaviour is correct. Thanks for reporting, will fix!
