### ISSUE TITLE
Login Page

### ISSUE THREAD

**Issue by sparkyspider** [tailwindlabs/tailwindui-issues#328]
Hey there,

Please can you put together a couple of nice login page options?

Preferably a full page with an optional nice background image and a login box floating in the middle, perhaps with some options for OpenID Connect Logins as well as username and password authentication.

Thanks,

**Comment by simonswiss** [comment]
Hi @sparkyspider 👋

Do you have a few examples to share as screenshots or URLs, so we can have a better idea of what you have in mind?

Also, have you seen [these](https://tailwindui.com/components/application-ui/forms/sign-in-forms)?

**Comment by sparkyspider** [comment]
Hi there,

I missed those somehow. Those are perfect.

Thank you.

Mark van Wyk,*  Co-Founder*



*Cell:* 082 831 9227 *Website:* www.flyh2.com
*LinkedIn:* Mark van Wyk <http://za.linkedin.com/in/markvwyk?trk=shareTw>
*Skype:* flyh2aero *Twitter: **@FlyH2 <https://twitter.com/flyh2>*

*All our latest tech developments are featured on our twitter page here:
@FlyH2 <https://twitter.com/flyh2>*

**Comment by simonswiss** [comment]
Great - thanks for getting back. Will close this issue now.
