### ISSUE TITLE
Footer - Newsletter form overflows container (Firefox)

### ISSUE THREAD

**Issue by dsturm** [tailwindlabs/tailwindui-issues#329]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/marketing/sections/footers#component-38c15f2c35def7c2c555175450d1448e
- Component name: 4-column with newsletter

**Describe the bug**
In Firefox the newsletter form overflows the container in screen `xl`.

**To Reproduce**
1. Expand to `xl`breakpoint.
2. See button overflows container.

**Expected behavior**
The newsletter form should not overflow the container.

**Screenshots**
![newsletter-form-overflows-container](https://user-images.githubusercontent.com/384815/94168586-14714480-fe8e-11ea-83e4-b3d8bda47c92.png)

**Browser/Device (if applicable)**
 - OS: macOS
 - Browser: Firefox
 - Version: 81.0

**Comment by simonswiss** [comment]
Hey! 👋

Confirming the overflow is happening - but funnily enough, it only happens in the component demo inside the iframe.

Here's a screenshot of the demo:

![image](https://user-images.githubusercontent.com/485747/94232911-5790ed80-ff4a-11ea-9219-6bde733aa462.png)

and here's what it looks like when I copy/paste the component markup (or even looking at the code that powers that component demo!):

![image](https://user-images.githubusercontent.com/485747/94233127-c110fc00-ff4a-11ea-88b8-cb4c051d348c.png)

Adding the `min-w-0` class to the `input` element fixes it:

![image](https://user-images.githubusercontent.com/485747/94234602-51e8d700-ff4d-11ea-911f-4606e32027ad.png)

Will check a few more things before committing this change. Thanks for reporting! 👍

**Comment by dsturm** [comment]
Hey @simonswiss, thanks for checking in. I did find this issue after using the code in a little project, not just in the iframe. But as you said, adding the `min-w-0` will fix it.
