### ISSUE TITLE
Intranet 

### ISSUE THREAD

**Issue by cesmanp** [tailwindlabs/tailwindui-issues#330]
I am interested in an intranet design that feature , new feed, staff birthday, marketing feed, stories and all other staff related information. Also reporting , forms and other modern reporting tools

**Comment by simonswiss** [comment]
Hey, thanks for the suggestion! 👍

Do you have some example screenshots and URLs that demonstrate what you have in mind?

Also, we're collecting component requests on our Trello roadmap, so I'll probably port this over there when I have a better understanding of what you are thinking of.

**Comment by simonswiss** [comment]
@cesmanp could you please provide some more info re: ☝️ so I can capture it in the Trello roadmap?

**Comment by cesmanp** [comment]
Unfortunately, i dont have a url or a screen shot to share with you, but
its would be a portal that display all the new blast, birthdays, report,
forms , just about anything that a company would like to push to its
employees or other employees with each other.

**Comment by simonswiss** [comment]
@cesmanp something like these two examples? 

https://dribbble.com/shots/9952902-Intranet-application-design/attachments/1987879?mode=media

https://dribbble.com/shots/9651475-Intranet-wireframe-design

The closest we have from this currently is the [App page examples](https://tailwindui.com/components/application-ui/page-examples/home-screens), which you could fill with different UI components from the different categories.

I like the idea of an "internal tool" UI though 👍

**Comment by simonswiss** [comment]
Hey - I have captured this suggestion in this Trello roadmap card: https://trello.com/c/CIJ9PLL1/110-intranet-company-platform-ui

Will close this issue now, but please go to the Trello card and upvote your suggestion to boost its community popularity 👍
