### ISSUE TITLE
2 componentes request for Tailwind. 

### ISSUE THREAD

**Issue by lmuzquiz** [tailwindlabs/tailwindui-issues#332]
I don´t know how to call these: (option boxes)?
<img width="1151" alt="Screen Shot 2020-09-29 at 15 40 12" src="https://user-images.githubusercontent.com/11865448/94613355-19593e00-026a-11eb-987c-b36af2b74476.png">
https://alyax.mx/campamentos/

![Screen Shot 2020-09-29 at 15 41 54](https://user-images.githubusercontent.com/11865448/94613572-61786080-026a-11eb-9b41-914712021e25.png)
https://alux.mx

Mosaics: Such as: 
![Screen Shot 2020-09-29 at 15 43 22](https://user-images.githubusercontent.com/11865448/94613663-8e2c7800-026a-11eb-8f12-fd4f95fad74a.png)
There is another version of this mosaic https://carolco.mx

Cheers.

**Comment by simonswiss** [comment]
Are the first one (option boxes) accordions? Aka at least one (and sometimes only one) is open at a time?

**Comment by lmuzquiz** [comment]
Yeah they are accordions. You can check em out in action at:  https://alyax.mx/campamentos/ and https://alux.mx/#productos slightly different versions.

**Comment by lmuzquiz** [comment]
> Hey, thanks for the suggestions and the screenshots! 👍
> 
> Are the first one (option boxes) accordions? Aka at least one (and sometimes only one) is open at a time?

Yeah they are accordions. You can check em out in action at: https://alyax.mx/campamentos/ and https://alux.mx/#productos slightly different versions.

**Comment by simonswiss** [comment]
Nice, thanks for the clarification.

I will move this to our Trello roadmap under the "ideas" column, where the community can upvote what they find interesting. If it gets enough traction, it could be moved in the backlog of things that are getting built!

https://trello.com/c/LYg43rY1/107-content-accordions

Thanks again for the suggestion! 👍

**Comment by dan003400** [comment]
I would love to see an accordion example in the components as well, possible under the navigation.

We basically need an easy headless ui transition for max height I would guess?

Thanks!

Dan
