### ISSUE TITLE
Pricing component width does not align to text

### ISSUE THREAD

**Issue by SaschaHeyer** [tailwindlabs/tailwindui-issues#334]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/marketing/sections/pricing
- Component name: Pricing component

**Describe the bug**
As soon as the lorem ipsum text is shortened the box on the right side does not adapt. 
An ugly empty space is visible (which is showing the background)

**To Reproduce**
1. Go to the component
2. Shorten the lorem ipsum text
4. See an error

**Expected behavior**
Either the box stays the same width. Or it shrinks down centered to the fit the text size

**Screenshots**
<img width="1403" alt="bug" src="https://user-images.githubusercontent.com/1991664/94894581-f2795280-0489-11eb-80af-ccc4b8eb2cd1.png">

**Browser/Device (if applicable)**
 - Browser Chrome
 - Version 85.0.4183.121

**Comment by simonswiss** [comment]
Are you still experiencing this bug now?

This was fixed a few days ago via https://github.com/tailwindlabs/tailwindui-issues/issues/323. I just checked in tailwindui.com and the component still looks good with a shorter description text.

![image](https://user-images.githubusercontent.com/485747/95031218-7b012880-0700-11eb-9d38-f28750a46324.png)

**Comment by simonswiss** [comment]
@SaschaHeyer can you confirm whether or not this is still a problem you can reproduce now?

**Comment by SaschaHeyer** [comment]
Confirmed it's solved 
Thanks 🙂

**Comment by simonswiss** [comment]
Thanks for following up Sascha! 👍
