### ISSUE TITLE
Close 'void' html tags

### ISSUE THREAD

**Issue by jeanmatthieud** [tailwindlabs/tailwindui-issues#336]
I just bought the Application UI package.
I'm using React (with NextJs) and trying Tailwind for the first time.

I love the fact that Tailwind have a package for basic UI components.
However, some HTML tags are missing the closing tag (input, img...) which is a pain in React.
Cloud you please add them by default ?

**Comment by chunlea** [comment]
Any update to this? This really painful when using with react

**Comment by RobinMalfait** [comment]
Hey! Those are the defaults for HTML, we are also working hard on Tailwind 2.0 and related changes, so we probably won't change this in the near future.
However, if you are using React, you can look at this small tool in the meantime: https://gist.github.com/RobinMalfait/a90e8651196c273dfa51eec0f43e1676

**Comment by chunlea** [comment]
Thank you, @RobinMalfait looks like the bookmark is updated, but I am still using the old version.
