### ISSUE TITLE
toggle component when using vue

### ISSUE THREAD

**Issue by HamptonNorth** [tailwindlabs/tailwindui-issues#339]
**What component (if applicable)**
- URL for category:  https://tailwindui.com/components/application-ui/forms/toggles
- Component name: toggles

**Describe the bug**
Using vue.js. When switching from off to on state, the off c gray cross svg icon is still visible beneath the on indigo tick svg icon

**To Reproduce**
1. Add vue.js js code as per comments
2. Click on toggle
3. See error

**Expected behavior**
On state tick should replace off state cross

**Screenshots**
![image](https://user-images.githubusercontent.com/1650551/95651170-474b4780-0ae0-11eb-873c-8d52a1df9a02.png)

**Browser/Device (if applicable)**
 - OS: Win 10 Pro
 - Browser [e.g. chrome, safari] chrome
 - Version [e.g. 22] 85.0.4183.121

**Additional context**
when used with vue.js for on/off js

**Comment by HamptonNorth** [comment]
Hi David

Yes - still persists. Here is codepen to show
https://codepen.io/HamptonNorth/pen/RwGaoxr . This uses
https://unpkg.com/tailwindcss@latest/dist/tailwind.min.css I added button
with focus ring utility to test actually using Tailwind v2

The first toggle is Tailwind UI Toggle with icon code unchanged except for
Vue code (Vue 2.5.13)

The second, visually correct toggle has had a bg-white added to to the <svg
tag class  - line 58

Hope this helps

Rob Collins

**Comment by davidluhr** [comment]
@HamptonNorth Thank you for your patience with this. I've added the background colors the the SVG and things appear to be working as expected. The fixed version should be live on the site shortly.
