### ISSUE TITLE
[Feature Request] 2-factor-authentification & conversations

### ISSUE THREAD

**Issue by gonewild22** [tailwindlabs/tailwindui-issues#340]
Thanks for this great framework and all your efforts! Would be great to have some kind of 2-factor-authentification layouts (for example for sms pin requests) and messaging/conversation templates :)

![pin_authentification](https://user-images.githubusercontent.com/49776905/95671733-8dfd7800-0b9a-11eb-90a8-1273feab6b6a.png)
![Conversations](https://user-images.githubusercontent.com/49776905/95671734-905fd200-0b9a-11eb-9435-716184dca4b0.png)

**Comment by simonswiss** [comment]
Hey! 👋

I have captured both these suggestions in our Trello roadmap!

https://trello.com/c/GNu5lGTm/108-2fa-input

and 

https://trello.com/c/vgB4qirE/109-email-like-ui

Both are pointing back to this issue from the Trello card.

Thank you for your suggestion! Will close this, but go ahead and vote for both these cards to bump up their popularity and give them a chance to be considered for something to build at some point 👍
