### ISSUE TITLE
Entity outside of span causes Vue to bail hydration

### ISSUE THREAD

**Issue by reillybuilt** [tailwindlabs/tailwindui-issues#341]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/overlays/modals
- Component name: Modals

**Describe the bug**
In Vue.js development mode, this causes Vue to bail hydration as invalid markup.

Code snippet causing the issue:
```html
<!-- This element is to trick the browser into centering the modal contents. -->
<span class="hidden sm:inline-block sm:align-middle sm:h-screen"></span>&#8203;
```

Changing it to this fixed the issue and works as expected:
```html
<!-- This element is to trick the browser into centering the modal contents. -->
<span class="hidden sm:inline-block sm:align-middle sm:h-screen">
  &#8203;
</span>
```

**Additional context**
More of a heads up for Vuejs users than anything else. Love the component library, great job!

**Comment by davidluhr** [comment]
@reillybuilt With the recent Tailwind UI release, we've fixed this issue by moving the special character inside the `<span>` as originally intended. I'm closing this issue for now, but feel free to re-open if the issue still persists.
