### ISSUE TITLE
Input type="range"

### ISSUE THREAD

**Issue by dan003400** [tailwindlabs/tailwindui-issues#343]
![image](https://user-images.githubusercontent.com/1211542/95784517-99839880-0c99-11eb-9c91-f769be6cbbc6.png)

**Comment by simonswiss** [comment]
Hey, thanks for the suggestion! 👍

Will close this and consolidate with https://github.com/tailwindlabs/tailwindui-issues/issues/96 which has a few other examples.

It has also been captured as [a suggestion in our Trello roadmap](https://trello.com/c/qYooawle/68-range-sliders) in the "bag of ideas".
