### ISSUE TITLE
Two 'Steps' components include non-standard height and width classes

### ISSUE THREAD

**Issue by jmadlena** [tailwindlabs/tailwindui-issues#344]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/navigation/steps
- Component name: Bullets, Circles with text

**Describe the bug**
Two of the Steps components (Bullets and Circles with text) use non-standard height and width classes, in this case 2.5. Using the example code will cause certain elements to be invisible. Changing the classes to h-2 and w-2 restores the visibility of the elements.

**To Reproduce**
1. Copy example code for the Bullets Steps component
2. Paste code into tailwindPlay (https://play.tailwindcss.com/0h2JnLAfhG) 
3. Only one bullet will be visible

**Expected behavior**
The example code should function as displayed on the TailwindUI page, without modification to the code or customization of the Tailwind config.

**Screenshots**
<img width="205" alt="Screen Shot 2020-10-12 at 10 34 41 PM" src="https://user-images.githubusercontent.com/4220680/95819569-2a2e9880-0cdb-11eb-8d0d-08b36aacdf53.png">

**Browser/Device (if applicable)**
 - OS: macOS 10.14.6
 - Browser Brave
 - Version 1.14.84

**Comment by adamwathan** [comment]
Those sizes exist in the @tailwindcss/ui plugin which is required for Tailwind UI. Check the documentation here:

https://tailwindui.com/documentation.

**Comment by jmadlena** [comment]
Ah, thanks so much for pointing me towards that.

You're right, I missed it in the header comment. I always delete the comment as soon as I paste the code into my project, but that's my fault for not reading it more thoroughly.

If all of the components require the plugin, then the header seems like the most reasonable place to put it. If it is only select components, then maybe some kind of note about that in the title on the components page?

Either way, thanks for pointing me to the solution that I missed. Love Tailwind CSS and Tailwind UI!
