### ISSUE TITLE
upload a file form element does not work

### ISSUE THREAD

**Issue by jhancock** [tailwindlabs/tailwindui-issues#346]
**What component (if applicable)**
- URL for category: 
https://tailwindui.com/components/application-ui/forms/form-layouts

- Component name: 
The form section for Cover photo has a button with link text "Upload a file".  

**Describe the bug**
It does not enable a file selection.

**Expected behavior**
Clicking the button area (svg) or link produces a file selection dialog

**Screenshots**
You don't need a screenshot.  This is obvious

**Additional context**
I submitted a feature request for an upload button on April 25.
It is here:  
wrapper for <input type="file"> #176
https://github.com/tailwindlabs/tailwindui-issues/issues/176

The issue is marked closed with a reference to an item in a trello board.  The trello board does not load.

**Comment by simonswiss** [comment]
Hey @jhancock 👋

Tailwind UI components provide HTML & CSS snippets only to this date. We've refrained from providing JavaScript behaviour before we can propose robust, accessible solutions to our components which don't include 100s of lines of gnarly JS in each component.

The _raison d'être_ for the [Headless UI](https://headlessui.dev/) is exactly this: provide functionality to Tailwind UI components, but where the complexity is abstracted away in an ergonomic manner.

Headless UI powered component will make it much easier to support that type of functionality, but unfortunately, right at this moment, we are not providing JS functionality. We're working on it, and you can follow the progress in the Headless UI repo on GitHub. 

To handle file uploads in the meantime, you'd need to use the File API in a way or another: https://developer.mozilla.org/en-US/docs/Web/API/File/Using_files_from_web_applications

## Trello board

The file upload component request is indeed captured in Trello, and has currently **57 upvotes**, which puts it in 4th most upvoted component request from the Tailwind UI community, so there is a decent chance that we put some effort in providing a few components that support this pattern 👍

![image](https://user-images.githubusercontent.com/485747/96407583-71fa7600-122d-11eb-8638-a92d7744d021.png)

https://trello.com/c/WdDvvJGC/55-file-upload-input

**Comment by jhancock** [comment]
HI Simon, I'm confused by your response.  
I'm just asking for a simple example that uses  <input type='file' />
It doesn't have to actually upload a file.
My original report is a bug as your code doesn't trigger the browser file selection dialog.

Please take a look at this:
https://tailwindcomponents.com/component/tailwind-file-upload
That does what I want.  I don't understand why I need to wait for yet another cool project by tailwind labs to provide an example of wrapping  <input type='file' /> ?

thanks, Jon

**Comment by simonswiss** [comment]
Hey,

Sorry about the confusion, I thought you were asking for a full implementation of a file upload UI 😅

The reason it's not working in our component is because it's implemented with a button, assuming that the behaviour would be wired up with some JavaScript hooked to the `onclick` event.

You can achieve an HTML file upload by using a hidden `<input type="file">` wrapped inside of a `<label>` element, which is the technique used in the component you shared in your response.

I have made a quick Tailwind Play example for you with this implementation: https://play.tailwindcss.com/051IIGreCf

I have basically replaced the `button` tag with a `label` tag, and added the `<input type="file" class="hidden" />` inside of it in line 10.

Hope it helps and clarifies it, sorry again about the misunderstanding.

**Comment by jhancock** [comment]
thanks for the reply.  that's what I was looking for ;)    I'd hope you could adjust your current taiwindui file select component to reflect this as I'm not aware of how to use a <button/> to trigger file selection.

**Comment by davidluhr** [comment]
As of today, we've updated the previously static "Upload a file" examples to be actual `<input type="file">` elements. Thanks for suggesting this improvement!
