### ISSUE TITLE
Unnecessary div?

### ISSUE THREAD

**Issue by thomasedwards** [tailwindlabs/tailwindui-issues#350]
**Component**

- URL for category: https://tailwindui.com/components/application-ui/forms/form-layouts
- Component name: Application UI > Forms > Form Layouts > Labels on left (however, can be seen elsewhere)

**Describe the bug**

At the start of the loop, a div is included to wrap all the items in the loop with the margin:

```
<div class="mt-6 sm:mt-5">
      <div class="sm:grid sm:grid-cols-3 sm:gap-4 sm:items-start sm:border-t sm:border-gray-200 sm:pt-5">
```

Then each subsequent loop has the same margin applied inside:

```
    <div class="mt-6 sm:mt-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:items-start sm:border-t sm:border-gray-200 sm:pt-5">
```

I’ve seen this in other places dotted around the site in places with a loop and a wrapping div.

**Expected behavior**

In order to make re-usable components, I just ignore the first one and the wrapping div, and make them all the same ast he second instance. It always looks and behaves the same. But I’d like to understand if there’s a logic or putting the margin on a wrapping div that effects the only first one, and if it’s worth putting that heavy logic into the component system. If not, would it be possible for the documentation to not include this wrapping div and just make them more component friendly?

**Comment by simonswiss** [comment]
Hey!

Thanks for pointing that out. 

As we're speaking, these components are probably being refactored, as this pattern is a sure sign that these components were implemented before the introduction of the `space-y-{n}` "space-between" components.

The way it's currently implemented, the first div with the margin acts as the layout spacer for the entire repeating block, and then each individual item handle spacing between each other.

These will probably be refactored to something like this:

```html
<div class="mt-6 sm:mt-5 space-y-6 sm:space-y-5">
  <div class="sm:grid sm:grid-cols-3 sm:gap-4 sm:items-start sm:border-t sm:border-gray-200 sm:pt-5">...</div>
  <div class="sm:grid sm:grid-cols-3 sm:gap-4 sm:items-start sm:border-t sm:border-gray-200 sm:pt-5">...</div>
  <div class="sm:grid sm:grid-cols-3 sm:gap-4 sm:items-start sm:border-t sm:border-gray-200 sm:pt-5">...</div>
</div>
```

Hopefully not too confusing - but the best way to think about why they are defined differently as of now is to think about "contextual layout of the whole component" versus "internal spacing".

Doing both from the parent wrapper with the use of `space-y` utilities is a far better approach 👍

Hope I make sense! 😅

**Comment by davidluhr** [comment]
@thomasedwards As @simonswiss mentioned previously, we recently did a lot of clean up to better take advantage of `space-` utilities.

With this in mind, any extraneous `<div>` elements should have been removed, so I'm closing this issue. If you have suggestions for further improvements, feel free to re-open this issue or open a new issue if needed.

**Comment by thomasedwards** [comment]
Thanks!
