### ISSUE TITLE
Pricing page has bg-gray-50 instead of bg-white

### ISSUE THREAD

**Issue by giraffesyo** [tailwindlabs/tailwindui-issues#351]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/marketing/sections/pricing
- Component name: Two tiers with extra tier

Two divs have bg-gray-50 on them where they should have bg-white on them. It produces this:

![image](https://user-images.githubusercontent.com/10459772/97058430-76879d00-1553-11eb-8e34-e2837f6d9c9d.png)

**Expected behavior**
Change the provided code to use `bg-white` instead of `bg-gray-50`

**Comment by simonswiss** [comment]
Hello!

The `bg-gray-50` is an off-white color in Tailwind UI, and is definitely the intended classname here which looks like so:

![image](https://user-images.githubusercontent.com/485747/97821537-e55cb700-1d06-11eb-87d6-a0846b2798c6.png)

If `bg-gray-50` doesn't resolve properly for you, I am going to make the assumption you forgot to [include the `@tailwindcss/ui` plugin](https://tailwindui.com/documentation) in your config file?

**Comment by giraffesyo** [comment]
Hey @simonswiss, thanks for your reply!

You're right! I had a mistake in the way I imported the plugin. Thank you!
