### ISSUE TITLE
DateTime Picker

### ISSUE THREAD

**Issue by markmottian** [tailwindlabs/tailwindui-issues#352]
**Screenshots**
Provide a screenshot of your existing solution or of examples you've seen elsewhere that you think would be helpful inspiration.

**Additional context**
Add any important details you think we need to know to make sure we build something that matches what you need.

**Comment by simonswiss** [comment]
Hey 👋!

Going to consolidate this with https://github.com/tailwindlabs/tailwindui-issues/issues/54 and close the issue. You can also see this component request captured in our Trello roadmap, in the "bag of ideas" column: https://github.com/tailwindlabs/tailwindui-issues/issues/54

Thanks!
