### ISSUE TITLE
Color swapping?

### ISSUE THREAD

**Issue by dustinleblanc** [tailwindlabs/tailwindui-issues#353]
This feels a smidge like looking the gift horse in the mouth, but something I'd love to see in tailwind UI is the ability to quickly swap the color palette around for previewing/copying the snippets. The examples/snippets default to using indigo as the 'brand' color, and the colors are made to accent that. I often need to experiment with swapping in our brand color when I am bringing a component into the site and working on tweaking it to fit. Sometimes it takes a bit to go around and replace the classes and check the result, and it would be really handy if I could do something like undraw allows where I can just pick the main accent color (I just change it to our brand orange color) and then it would update the components to match.

For a lot of the components, I understand there is more than one color to consider, but it would be pretty sweet to be able to set a primary, secondary, etc at the top of the UI, again similar to undraw.

For reference, undraw: https://undraw.co/illustrations

Here is a WIP mail signup form that is in the middle of orange-i-fying itself from it's indigo beginnings
![image](https://user-images.githubusercontent.com/3948808/97126028-230c7f00-170c-11eb-9ddf-d381b19100f6.png)

Still trying to figure out the right color for the CTA button, and obviously I need to change that paragraph text a bit, but it would be nice to just have a spot in the UI to swap those colors around so it's quick to experiment with them.

Thanks for all you do! Loving Tailwind and TailwindUI!

**Comment by fergusmeiklejohn** [comment]
+1 for for an easier way to change colour scheme. 

Whether you do it like quasar:
```
$primary   : #1976D2
$secondary : #26A69A
$accent    : #9C27B0

$dark      : #1D1D1D

$positive  : #21BA45
$negative  : #C10015
$info      : #31CCEC
$warning   : #F2C037
```
or like your example in Refactoring UI:
![Screenshot 2020-11-05 at 11 42 30](https://user-images.githubusercontent.com/11864025/98195200-20a3f380-1f5c-11eb-9a6c-f33d5071a031.png)

I

**Comment by fergusmeiklejohn** [comment]
Could we build colour scheme prototyping into the Figma Kit?

**Comment by davidluhr** [comment]
@dustinleblanc My current suggestion would be to use https://play.tailwindcss.com/ for quick color changes and previewing. You could copy/paste a component into Tailwind Play, and replace color utilities as needed, or even change up the config.

That might be the easiest way to accomplish this currently.

Building this functionality directly into Tailwind UI poses some big challenges.

Mainly, not all designs are conducive to swapping one color for another, even within the same value range (indigo-500 to green-500), as there are perceptual and contrast differences, as well as aesthetic preferences, to consider. As we create more page examples that explore various color theme opportunities, we're finding it's necessary to adjust several colors in a component and sometimes even change the value number (let's say going from indigo-600 to light-blue-800) to get something that both looks good and is accessible.

Additionally, some components are very complex, and it'd be difficult to present options for all the possible elements that could have color customizations. I can't think of an intuitive or convenient UI for such a complicated task.

**Comment by davidluhr** [comment]
@fergusmeiklejohn Good call. With Figma's recent color selection features, it will be pretty quick to highlight a full component and quickly swap one color style for another.
