### ISSUE TITLE
Yarn error log included in the package

### ISSUE THREAD

**Issue by divine** [tailwindlabs/tailwindui-issues#356]
**Describe the bug**
There is a **yarn-error.log** file in package **@tailwindcss/ui**

**To Reproduce**
1. Go to https://registry.yarnpkg.com/@tailwindcss/ui/-/ui-0.7.0.tgz or just install the package.
2. Open that file/folder
3. See that `yarn-error.log` file exists

**Expected behavior**
That file shouldn't exist and be here. Taking huge 26KB (joking)😁

Thanks!

**Comment by davidluhr** [comment]
@divine Thanks for reporting this. Closing this now, as the UI package is no longer a thing with recent Tailwind CSS 2.0 and Tailwind UI updates.
