### ISSUE TITLE
Small typo/misplaced text

### ISSUE THREAD

**Issue by GribouilleVert** [tailwindlabs/tailwindui-issues#357]
**Describe the bug**
Well, it's more a bad placed text than a bug in itself, but i am about sure that there should no be marked "Breadcrumb" there:
![image](https://user-images.githubusercontent.com/29147674/97849269-96a52200-1cf2-11eb-8de6-375647d19490.png)

**To Reproduce**
1. Go to https://tailwindui.com/components
2. Scroll down to  App UI - Elements sections

**Screenshots**
See above

**Comment by davidluhr** [comment]
@GribouilleVert As of 2020-11-24, this appears to have been resolved. Closing this issue now, but feel free to re-open if you're still seeing this.
