### ISSUE TITLE
Sidebar navigation flush against light logo background

### ISSUE THREAD

**Issue by simonswiss** [tailwindlabs/tailwindui-issues#359]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/application-shells/sidebar#component-966a548c3d7225d9155a443e979057b5
- Component name: Light sidebar with constrained content area

**Describe the bug**
The first element in the sidebar navigation is touching the light gray logo background, which is probably not by design. See screenshot attached. Reported by a customer on support ticket

**Expected behavior**
Probably needs some vertical spacing before the first element, or remove the logo background color?

**Screenshots**
![image](https://user-images.githubusercontent.com/485747/98075784-1d0f5e80-1ec1-11eb-87e6-de160f2d8034.png)

**Comment by davidluhr** [comment]
This has been fixed with the recent Tailwind 2.0 release. Closing now.
