### ISSUE TITLE
Create some of the base components using complex classes

### ISSUE THREAD

**Issue by fergusmeiklejohn** [tailwindlabs/tailwindui-issues#360]
A very small number of base components like the buttons would be more useful implemented as one button with complex classes to change them, as you describe in your Tailwind Labs YouTube video: https://youtu.be/naJ_rIK6ppQ

**Comment by davidluhr** [comment]
@fergusmeiklejohn The `@apply` feature can be really useful for people who are looking to reuse common sets of utilities throughout a project, but with Tailwind UI, we want any component's code to be a standalone example that has no cross-dependencies with other components.

As a result, we present all components purely with provided utility classes, so users can see how everything is built without having to dig into other files.
