### ISSUE TITLE
[Content - Image] columns that alternate on each row - picture always responsively breaks on top

### ISSUE THREAD

**Issue by msnewsome** [tailwindlabs/tailwindui-issues#361]
Essentially what I'm looking for is on a large display the setup is three rows of content and images where the objects alternate on every row like this:

![Content Desktop](https://user-images.githubusercontent.com/47337819/98275966-e71eb880-1f5a-11eb-8cf1-333f27e97a19.jpg)

Then when the layout responsively breaks for small displays the image will break on top like this:

![Content Mobile](https://user-images.githubusercontent.com/47337819/98275979-ed149980-1f5a-11eb-81dc-6f6e33303178.jpg)

**Comment by davidluhr** [comment]
Thanks for the suggestion—making note of this internally and also captured this in the Trello roadmap Ideas column

https://trello.com/c/wYSrpLsf/111-content-sections-alternating-columns
