### ISSUE TITLE
Request for Alpine.js version of each component

### ISSUE THREAD

**Issue by kenshepherd58** [tailwindlabs/tailwindui-issues#362]
Could you make the Alpine.js version of each component code available to copy/download?
Adam had mentioned each component code in Tailwind UI uses Alpine.js for Javascript interactivity (which is what we see in Preview mode)
Since the code has already been written with Alpine.js, it would be easy to offer it and very useful and educational to access it.
Alpine.js only requires a simple cdn in the HTML head section to activate it. It's an easy way to see the js interactivity of these components and would facilitate mapping to more robust frameworks like Vue and React (it has a Vue-like syntax).

Thanks for considering this request.
Ken

**Comment by davidluhr** [comment]
Thanks for the suggestion! I've made note of this internally with the team and also added it to our public Tailwind UI roadmap, where the community can vote for what they'd like to see

https://trello.com/c/8EZrsfzZ/121-provide-alpinejs-code-for-components
