### ISSUE TITLE
Video Components!

### ISSUE THREAD

**Issue by AtomSolar** [tailwindlabs/tailwindui-issues#363]
I love the component found at Marketing>Page Sections>CTA Sections "Brand panel with app screenshot"
It seems like a fantastic starter for a video component.. The video replaces the screenshot.

I know this is pretty simple to do but I thought it might be a popular request so I brought the attention here!

**Screenshots**
Provide a screenshot of your existing solution or of examples you've seen elsewhere that you think would be helpful inspiration.

**Additional context**
Add any important details you think we need to know to make sure we build something that matches what you need.

**Comment by davidluhr** [comment]
Thanks for the suggestion—making note of this internally and also captured this in the Trello roadmap Ideas column

https://trello.com/c/85k0Nu38/114-video-components
