### ISSUE TITLE
React-specific Copy functionality in Component preview

### ISSUE THREAD

**Issue by cbzehner** [tailwindlabs/tailwindui-issues#364]
**What component (if applicable)**
N/A

**Describe the bug**
This is actually a suggestion to improve the Tailwind UI copy-and-paste experience. I noticed that for React projects there are a couple repetitive changes needed:

Each time I copy a UI component I end up doing a global find-and-replace operation changing all instances of `class=` to `className=` and all instances of `for=` to `htmlFor=`. I'm sure there are other changes needed but I've only used a limited subset of the components so far.

**To Reproduce**
1. Create a new React app with [create-react-app](https://create-react-app.dev/)
2. Copy one of the [form layouts](https://tailwindui.com/components/application-ui/forms/form-layouts) and paste it into the `return (...)` block of `App.jsx`
3. Run the app with `yarn start` (or `npm start`) and see a failure

**Expected behavior**
It would be nice to have a React-specific copy functionality that already has these changes applied. Either an additional per-component button or a local "React-mode" that changed the copy functionality.

**Additional context**
I totally understand if this isn't something y'all are interested in supporting. Feel free to close this out if that's the case.

**Comment by tylerbrostrom** [comment]
They’re working on it! See Simon’s notes in #224

**Comment by cbzehner** [comment]
Excellent. I'm going to close this out then and follow along there. Thanks @tylerbrostrom.

I've been using https://chrome.google.com/webstore/detail/tailwind-ui-react/binfindfddkgfibeajgkmjioklcgigjn in the meantime (for posterity)
