### ISSUE TITLE
Long Table Loses Container Padding

### ISSUE THREAD

**Issue by davidhemphill** [tailwindlabs/tailwindui-issues#365]
**What component (if applicable)**
- URL for category: [https://tailwindui.com/components/application-ui/lists/tables]()
- Component name: Simple Striped

**Describe the bug**
When a table is very long, the table's overflow covers the containers padding.

**To Reproduce**
1. Go to [https://tailwindui.com/components/application-ui/lists/tables]()
2. Make "Simple Striped" table contents longer than the container
3. See right container padding is covered.

**Expected behavior**
The table contents should be covered by the container's padding

**Screenshots**
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/58970/98732349-a3fe8400-2364-11eb-9613-abbde6986349.png">

**Browser/Device (if applicable)**
 - OS: [macOS Catalina]
 - Browser [Safari]
 - Version [14.0.1]

**Additional context**
If you remove the `inline-block` class from the div *before* the div with the `shadow` class, it will display as expected, but will not be scrollable.

<img width="1281" alt="image" src="https://user-images.githubusercontent.com/58970/98732627-02c3fd80-2365-11eb-9e1a-ac614386f2b3.png">

**Comment by davidluhr** [comment]
@davidhemphill Thanks for reporting this! I believe we have a fix for this that should appear on the live site soon. Feel free to re-open this if the issue persists.
