### ISSUE TITLE
Light Blue missing

### ISSUE THREAD

**Issue by bcorcoran** [tailwindlabs/tailwindui-issues#367]
In the latest update (Settings screens), a color variant called "light-blue" is used in several places. That color is missing from the colors object in @tailwindcss/ui/colors

Can you add this or update the examples to use something that exists?

**Comment by RobinMalfait** [comment]
Hey!

If you click the "code" tab, then there is information right at the top about this color:

![image](https://user-images.githubusercontent.com/1834413/98933891-8e629900-24e1-11eb-83d7-aa5eb095514d.png)
