### ISSUE TITLE
Headers component flyout missing z-index

### ISSUE THREAD

**Issue by holygekko** [tailwindlabs/tailwindui-issues#368]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/marketing/elements/headers
- Component name: headers - centered with bottom border

**Describe the bug**
The flyout can appear underneath other elements, e.g. a dropdown, below it

**To Reproduce**
1. add "headers - centered with bottom border" to a page
2. add "header sections - simple with select menu dark" beneath it on the same page
3. See error

**Expected behavior**
I'd like the menu flyout to be on top at all times

**Suggested fix**
There is a z-20 class within the flyout, but it's not on the right part of the component. If you add it to the absolute positioned item that contains the flyout, it works as expected.

This issue is probably also present in other components with flyouts.

**Comment by davidluhr** [comment]
@holygekko Thanks for reporting this! We've fixed the flyout menu z-index in the Headers, as well as in Page Examples, to ensure they stack as expected when combined with other sections.
