### ISSUE TITLE
Apply Vue transitions on left menu of home screen

### ISSUE THREAD

**Issue by girardinsamuel** [tailwindlabs/tailwindui-issues#369]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/page-examples/home-screens#component-d7cea65e442e0c2c85f158472dd2a846

**Describe the bug**
It's not a real bug, but a clarification about use of Vue transitions in the case of the left menu of this home screen.

**To Reproduce**
I followed advices on TailwindUI doc about Vue transitions and for the left menu of the example above, I added the transitions which where commented out inside `transitions` blocks. I also added a way to toggle the menu, driven
by the state `leftMenuOpened` (false or true). 
```html
  <div
    class="flex h-screen overflow-hidden bg-cool-gray-100"
  >
    <!-- Off-canvas menu for mobile, show/hide based on off-canvas menu state. -->
    <div v-if="leftMenuOpened"
         class="lg:hidden"
    >
      <div class="fixed inset-0 z-40 flex">
        <!-- Off-canvas menu overlay, show/hide based on off-canvas menu state. -->
        <transition
          enter-active-class="transition-opacity duration-300 ease-linear"
          enter-class="opacity-0"
          enter-to-class="opacity-100"
          leave-active-class="transition-opacity duration-300 ease-linear"
          leave-class="opacity-100"
          leave-to-class="opacity-0"
        >
          <div v-show="leftMenuOpened"
               class="fixed inset-0"
          >
            <div class="absolute inset-0 opacity-75 bg-cool-gray-600" />
          </div>
        </transition>
        <!-- Off-canvas menu, show/hide based on off-canvas menu state. -->
        <transition
          enter-active-class="transition duration-300 ease-in-out transform"
          enter-class="-translate-x-full"
          enter-to-class="translate-x-0"
          leave-active-class="transition duration-300 ease-in-out transform"
          leave-class="translate-x-0"
          leave-to-class="-translate-x-full"
        >
          <div v-show="leftMenuOpened"
               class="relative flex flex-col flex-1 w-full max-w-xs pt-5 pb-4 bg-teal-600"
          >
              [...]
          </div>
        </transition>
        <div class="flex-shrink-0 w-14">
          <!-- Dummy element to force sidebar to shrink to fit close icon -->
        </div>
      </div>
    </div>
```
When I click on the button to open the menu, the menu opens but without transitions.

**Expected behavior**
Here is what I can think of :
The transition is not working because the two blocks (overlay and menu) which needs a transition are contained in a global div which also need to be toggled so there is no real transitioning from hidden to displayed. All is displayed at once. So I guess that's why it's not working.

Do you have some tips/insights on how to define the transitions for this Tailwind UI example ?

Thank you in advance ! 👍

**Comment by dfeinberg5** [comment]
@girardinsamuel I just tackled this exact issue. You're exactly right about why it's not working. I found that you can leverage the transition Javascript hooks documented [here](https://vuejs.org/v2/guide/transitions.html#JavaScript-Hooks). Specifically you want to use `@after-enter` and `@after-leave`.

I did the following:

1. Wrap the outer v-if div in a transition.
2. Add `@after-enter` to the new transition.
3. Change the v-show to be based on a different value, changed by the outer transition after that div enters.
4. Add `@after-leave` to the inner transition to change the value used by the v-if.

Basically, what's happening is:

On open:
Transition outer div by changing it's value to true > after that has entered, trigger inner menu by changing the value it's based on to true

On close:
Transition menu by changing it's value to false > after that has left, trigger outer div to close by changing the value it's based on to false

The key is these are based on different values. Example of this below:

```
<transition @after-enter="showMenu = true">
<div
    class="flex h-screen overflow-hidden bg-cool-gray-100"
  >
    <!-- Off-canvas menu for mobile, show/hide based on off-canvas menu state. -->
    <div v-if="open"
         class="lg:hidden"
    >
      <div class="fixed inset-0 z-40 flex">
        <!-- Off-canvas menu overlay, show/hide based on off-canvas menu state. -->
        <transition
          enter-active-class="transition-opacity duration-300 ease-linear"
          enter-class="opacity-0"
          enter-to-class="opacity-100"
          leave-active-class="transition-opacity duration-300 ease-linear"
          leave-class="opacity-100"
          leave-to-class="opacity-0"
          @after-leave="open = false"
        >
          <div v-show="showMenu"
               class="fixed inset-0"
          >
            <div class="absolute inset-0 opacity-75 bg-cool-gray-600" />
          </div>
        </transition>
        <!-- Off-canvas menu, show/hide based on off-canvas menu state. -->
        <transition
          enter-active-class="transition duration-300 ease-in-out transform"
          enter-class="-translate-x-full"
          enter-to-class="translate-x-0"
          leave-active-class="transition duration-300 ease-in-out transform"
          leave-class="translate-x-0"
          leave-to-class="-translate-x-full"
          @after-leave="open = false"
        >
          <div v-show="showMenu"
               class="relative flex flex-col flex-1 w-full max-w-xs pt-5 pb-4 bg-teal-600"
          >
              [...]
          </div>
        </transition>
        <div class="flex-shrink-0 w-14">
          <!-- Dummy element to force sidebar to shrink to fit close icon -->
        </div>
      </div>
    </div>
</transition>
```

**Comment by malalecherocks** [comment]
[Vue warn]: <transition> can only be used on a single element. Use <transition-group> for lists.

found in

---> <Transition>
       <Layouts/menu.vue> at layouts/menu.vue
         <Root>

**Comment by davidluhr** [comment]
Just following up on this. Is there something we can improve in the Tailwind UI code example to help with this, or is this a Vue-specific issue?

**Comment by girardinsamuel** [comment]
Thanks for your answers @dfeinberg5 @malalecherocks ! I'll implement this, it should work 👍 

@davidluhr I am not sure that something can be done or need to be done ? 🤔  

Maybe in the comments where transitions classes are defined, just add another comment when needed, referring to Vue documentation (https://vuejs.org/v2/guide/transitions.html#JavaScript-Hooks) explaining than for implementing this use case with Vue, javascript hooks are needed ?

**Comment by davidluhr** [comment]
@girardinsamuel Thanks for the feedback. I'll see how the team wants to improve documentation around this. We can add more detail to our existing Vue documentation: https://tailwindui.com/documentation#js-vue

**Comment by girardinsamuel** [comment]
> @girardinsamuel Thanks for the feedback. I'll see how the team wants to improve documentation around this. We can add more detail to our existing Vue documentation: https://tailwindui.com/documentation#js-vue

Yes that would be maybe cleaner to add something there !

**Comment by davidluhr** [comment]
Just following up on this on as we draft some improved documentation. One simple solution is the following:

1. Use `v-show` instead of `v-if` for conditionally rendering the element to be transitioned.
2. Wrap the outer element that uses `v-show` with a `<transition>`.
2. Add a `duration` prop to `transition`. `duration` can accept a single value that acts as both the enter/leave timing (`duration="300"`, or an object with each specified (`duration="{ enter: 300, leave: 100 }"` The duration value(s) should be the longest values of any child `<transition>` elements.

Here's what that looks like in the context of your original example:
```html
  <div class="h-screen flex overflow-hidden bg-gray-100">
    <!-- Off-canvas menu for mobile, show/hide based on off-canvas menu state. -->
    <transition :duration="300">
      <div v-show="leftMenuOpened" class="md:hidden">
        <div class="fixed inset-0 flex z-40">
          <transition
            enter-active-class="transition-opacity duration-300 ease-linear"
            enter-from-class="opacity-0"
            enter-to-class="opacity-100"
            leave-active-class="transition-opacity duration-300 ease-linear"
            leave-from-class="opacity-100"
            leave-to-class="opacity-0"
          >
            <div
              v-show="leftMenuOpened"
              class="fixed inset-0"
              aria-hidden="true"
            >
              <div class="absolute inset-0 bg-gray-600 opacity-75"></div>
            </div>
          </transition>
          <transition
            enter-active-class="transition duration-300 ease-in-out transform"
            enter-from-class="-translate-x-full"
            enter-to-class="translate-x-0"
            leave-active-class="transition duration-300 ease-in-out transform"
            leave-from-class="translate-x-0"
            leave-to-class="-translate-x-full"
          >
            <div
              v-show="leftMenuOpened"
              class="relative flex-1 flex flex-col max-w-xs w-full pt-5 pb-4 bg-indigo-700"
            >
              [...]
            </div>
          </transition>
          <div class="flex-shrink-0 w-14" aria-hidden="true">
            <!-- Dummy element to force sidebar to shrink to fit close icon -->
          </div>
        </div>
      </div>
    </transition>
    
    [...]
  </div>
```

Here's a link to the Vue 3 doucmentation on [Explicit Transition Durations](https://v3.vuejs.org/guide/transitions-enterleave.html#explicit-transition-durations).

As I mentioned, we'll improve the Tailwind CSS documentation to include this. I'm closing this issue for now. Thanks for reporting this!

**Comment by anujchhabria1** [comment]
Hey @davidluhr,

Attempted to wrap the outer div with the v-show, but the enter transition does not seem to work. You can check it out here:
https://adoring-goodall-bfde42.netlify.app/people/students

**Comment by adamwathan** [comment]
@anujchhabria1 Can you share the actual source code? Hard to tell how it's set up in just the final rendered demo. This stuff is annoying and tricky — sorry for the headache!

**Comment by anujchhabria1** [comment]
Sorry for not posting it earlier @adamwathan. Attached it below - 

`<transition :duration="300">
      <div class="md:hidden" v-show="showMobileMenu">
        <div class="fixed inset-0 z-40 flex">
          <transition
            enter-active-class="transition-opacity ease-linear duration-300"
            enter-from-class="opacity-0"
            enter-to-class="opacity-100"
            leave-active-class="transition-opacity ease-linear duration-300"
            leave-from-class="opacity-100"
            leave-to-class="opacity-0"
          >
            <div
              class="fixed inset-0"
              aria-hidden="true"
              v-show="showMobileMenu"
            >
              <div
                class="absolute inset-0 bg-gray-600 opacity-75"
                @click="toggleMobileMenu()"
                ></div>
            </div>
          </transition>
          <transition
            enter-active-class="transition ease-in-out duration-300 transform"
            enter-from-class="-translate-x-full"
            enter-to-class="translate-x-0"
            leave-active-class="transition ease-in-out duration-300 transform"
            leave-from-class="translate-x-0"
            leave-to-class="-translate-x-full"
          >
            <div
              class="relative max-w-xs w-full bg-gray-100 pt-5 pb-4 flex-1 flex flex-col"
              v-show="showMobileMenu"
            >
              <div class="absolute top-0 right-0 -mr-12 pt-2">
                <button
                  class="ml-1 flex items-center justify-center h-10 w-10 rounded-full focus:outline-none focus:ring-2 focus:ring-inset focus:ring-white"
                  @click="toggleMobileMenu()"
                >
                  <span class="sr-only">Close sidebar</span>
                  
                  <svg
                    class="h-6 w-6 text-white"
                    xmlns="http://www.w3.org/2000/svg"
                    fill="none"
                    viewBox="0 0 24 24"
                    stroke="currentColor"
                    aria-hidden="true"
                  >
                    <path
                      stroke-linecap="round"
                      stroke-linejoin="round"
                      stroke-width="2"
                      d="M6 18L18 6M6 6l12 12"
                    />
                  </svg>
                </button>
              </div>
              <div class="mt-5 flex-1 h-0 overflow-y-auto bg-gray-100">
                <div class="flex items-center flex-shrink-0 px-4">
                  <p class="mt-2 text-xl text-gray-900 font-semibold">
                    {{ subMenuOptions.name }}
                  </p>
                </div>
                <nav class="flex-1 px-2 space-y-8 bg-gray-100">
                  <BroadSidebarMenuOptions
                    :menu-options="primaryOptions"
                    @navigate="navigate"
                    :show-icons="true"
                    :setup-options="false"
                    classes="px-2"
                  />
                  <div
                    class="space-y-1"
                    v-if="secondaryOptions && secondaryOptions.length > 0"
                    >
                      <h3
                        class="px-3 text-xs font-semibold text-gray-500 uppercase tracking-wider"
                        >
                        Setup
                      </h3>
                      <BroadSidebarMenuOptions
                        :menu-options="secondaryOptions"
                        @navigate="navigate"
                        :show-icons="false"
                        :setup-options="true"
                        classes="px-3"
                      ></BroadSidebarMenuOptions>
                  </div>
                </nav>
              </div>
            </div>
          </transition>
          <div class="flex-shrink-0 w-14">
            
          </div>
        </div>
      </div>
    </transition>`

**Comment by anujchhabria1** [comment]
Sorry for not posting it earlier. Attached it below - 

`<transition :duration="300">

        <div class="md:hidden" v-show="showMobileMenu">
        <div class="fixed inset-0 z-40 flex">
          <transition
            enter-active-class="transition-opacity ease-linear duration-300"
            enter-from-class="opacity-0"
            enter-to-class="opacity-100"
            leave-active-class="transition-opacity ease-linear duration-300"
            leave-from-class="opacity-100"
            leave-to-class="opacity-0"
          >
            <div
              class="fixed inset-0"
              aria-hidden="true"
              v-show="showMobileMenu"
            >
              <div
                class="absolute inset-0 bg-gray-600 opacity-75"
                @click="toggleMobileMenu()"
                ></div>
            </div>
          </transition>
          <transition
            enter-active-class="transition ease-in-out duration-300 transform"
            enter-from-class="-translate-x-full"
            enter-to-class="translate-x-0"
            leave-active-class="transition ease-in-out duration-300 transform"
            leave-from-class="translate-x-0"
            leave-to-class="-translate-x-full"
          >
            <div
              class="relative max-w-xs w-full bg-gray-100 pt-5 pb-4 flex-1 flex flex-col"
              v-show="showMobileMenu"
            >
              <div class="absolute top-0 right-0 -mr-12 pt-2">
                <button
                  class="ml-1 flex items-center justify-center h-10 w-10 rounded-full focus:outline-none focus:ring-2 focus:ring-inset focus:ring-white"
                  @click="toggleMobileMenu()"
                >
                  <span class="sr-only">Close sidebar</span>
                  
                  <svg
                    class="h-6 w-6 text-white"
                    xmlns="http://www.w3.org/2000/svg"
                    fill="none"
                    viewBox="0 0 24 24"
                    stroke="currentColor"
                    aria-hidden="true"
                  >
                    <path
                      stroke-linecap="round"
                      stroke-linejoin="round"
                      stroke-width="2"
                      d="M6 18L18 6M6 6l12 12"
                    />
                  </svg>
                </button>
              </div>
              <div class="mt-5 flex-1 h-0 overflow-y-auto bg-gray-100">
                <div class="flex items-center flex-shrink-0 px-4">
                  <p class="mt-2 text-xl text-gray-900 font-semibold">
                    {{ subMenuOptions.name }}
                  </p>
                </div>
                <nav class="flex-1 px-2 space-y-8 bg-gray-100">
                  <BroadSidebarMenuOptions
                    :menu-options="primaryOptions"
                    @navigate="navigate"
                    :show-icons="true"
                    :setup-options="false"
                    classes="px-2"
                  />
                  <div
                    class="space-y-1"
                    v-if="secondaryOptions && secondaryOptions.length > 0"
                    >
                      <h3
                        class="px-3 text-xs font-semibold text-gray-500 uppercase tracking-wider"
                        >
                        Setup
                      </h3>
                      <BroadSidebarMenuOptions
                        :menu-options="secondaryOptions"
                        @navigate="navigate"
                        :show-icons="false"
                        :setup-options="true"
                        classes="px-3"
                      ></BroadSidebarMenuOptions>
                  </div>
                </nav>
              </div>
            </div>
          </transition>
          <div class="flex-shrink-0 w-14">
            
          </div>
        </div>
      </div>
    </transition>`

**Comment by adamwathan** [comment]
Any chance you can post the whole file in a gist or similar? In your code above you are missing the opening <transition> tag that is meant to have an explicit duration, but it looks like just a copy and paste error where you accidentally didn't copy everything before pasting it into GitHub.

**Comment by adamwathan** [comment]
Ah one thing I am realizing, you are probably on Vue 2.0 right since using Nuxt? If so, change all instances of `enter-from-class` to `enter-class` and `leave-from-class` to `leave-class`, that was a breaking change between Vue 2 and Vue 3.

**Comment by anujchhabria1** [comment]
Ah! Got it, works now!
