### ISSUE TITLE
Collapsible Sidebar Navigation

### ISSUE THREAD

**Issue by vmitchell85** [tailwindlabs/tailwindui-issues#37]
**Screenshots**

![image](https://user-images.githubusercontent.com/1248035/76014822-41590c80-5ee8-11ea-974e-cbca7b6fdb53.png)
![image](https://user-images.githubusercontent.com/1248035/76014839-49b14780-5ee8-11ea-8ac6-29b27a534510.png)

**Additional context**
Being able to collapse the sidebar would be very useful for some projects I work on.

**Comment by J05HI** [comment]
Additional examples:

https://dribbble.com/shots/6901378-Smart-Investment-Manager-Service-Website
![image](https://cdn.dribbble.com/users/466659/screenshots/6901378/investment_platform_website_4x.png?compress=1&resize=1200x900)

---

https://dribbble.com/shots/6767474-Sprint-Report-Dashboard
![image](https://cdn.dribbble.com/users/402414/screenshots/6767474/sprint_report_dashboard_4x.png?compress=1&resize=1200x900)

**Comment by hellerpdx** [comment]
We (early team access customer) would also love to see this added.

**Comment by ptrojanowski** [comment]
Sentry is a great example:

![2020-07-24_17-03](https://user-images.githubusercontent.com/7380923/88405494-a649cc00-cdcf-11ea-950b-932173d8f20e.png)


![2020-07-24_17-02](https://user-images.githubusercontent.com/7380923/88405403-7ef2ff00-cdcf-11ea-9a4c-c7ffd54944ef.png)

**Comment by simonswiss** [comment]
Thank you for suggesting this! 👍

This has been captured in our "bag of ideas" in the Trello roadmap: https://trello.com/c/X2Q2H9ot/75-collapsible-mini-sidebar-icons

This doesn't mean it's going to be implemented, but it definitely means that it's in the mix of the things we could consider implementing! 🎉

**Comment by vmitchell85** [comment]
Thanks @simonswiss
