### ISSUE TITLE
Closing all standalone tags with />

### ISSUE THREAD

**Issue by eykrehbein** [tailwindlabs/tailwindui-issues#370]
## The issue
Some standalone HTML elements in TailwindUI Components aren't closed with `/>` but just with `>`. 

Example: `<img src="...">`

What I would propose: `<img src="..." />`

## Why?

I'm using React as framework behind tailwind and JSX requires all tags to be closed. All images that I paste from TailwindUI lead to errors while compiling (`Syntax error: Expected corresponding JSX closing tag for <img>`). That makes it a lot hearder for me to use TailwindUI.

**Comment by eykrehbein** [comment]
Same for `<input>` (should be `<input />`)

**Comment by adamwathan** [comment]
Hey! We are hoping to add first-class "copy as JSX" support at some point, but for now we recommend this helpful bookmarklet:

https://gist.github.com/RobinMalfait/a90e8651196c273dfa51eec0f43e1676

It will handle the self-closing tags, as well as converting `class` to `className`, updating SVG attributes, etc. 👍
