### ISSUE TITLE
Suggestion about a potential ux improvement in the tailwindui docs

### ISSUE THREAD

**Issue by fonzane** [tailwindlabs/tailwindui-issues#372]
Hi :),

I just started using tailwindcss. While learning about utilizing your awesome framework I felt a bit uneasy deploying components from the tailwindui section. When adding the classes to the html elements I felt the wish to directly see what each class might cause. Being able to swap only between seeing the code or seeing the component made me feel a bit uneasy and I thought it might be a good idea to change this behavior so one can simultaneously see the code and what the code does (the components). So I just wanted to let you guys know about my experience so it can maybe help you improve user experience.

Kind regards
Fonzane

**Comment by davidluhr** [comment]
@fonzane This is a big reason why we built Tailwind Play (https://play.tailwindcss.com/) which is a sandbox environment that is ready to go for working with Tailwind.

You can copy/paste the code for Tailwind UI components, customize the included config as needed, and quickly iterate on markup and classes to see the changes in realtime. It even includes the Tailwind Intellisense functionality, so you can see a list of all possible classes when typing.

Here's an overview video to help get started: https://www.youtube.com/watch?v=eCWhTZ34Hck

I'm closing this issue for now, but feel free to reply with further feedback or re-open if needed.
