### ISSUE TITLE
Sidebar elements don't have comments with toggleable classes

### ISSUE THREAD

**Issue by alexbu92** [tailwindlabs/tailwindui-issues#373]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/application-shells/sidebar
- Component name: All

**Describe the bug**
TailwindUI documentation states 

> When an element needs different classes applied based on some state (like a toggle being on or off), we list the classes for each state in a comment directly above the element

and 

> the classes that you need to change when switching states are always at the very beginning of the class list so they are easy to find.

but in the sidebar code there is no class list for when you're on a route that coincides with one of the elements and the classes that need to be added and removed are not at the beginning of the class list.

**To Reproduce**
1. Go to https://tailwindui.com/components/application-ui/application-shells/sidebar
2. Click on code for any of the components
3. Scroll down to the <nav> section and look at any of the elements in there
4. Confirm missing info

**Expected behavior**
I would have expected to find what the documentation states I would have found.

**Comment by davidluhr** [comment]
@alexbu92 I've checked the Sidebar layouts code and I'm seeing these comments on my end. For example, the code of the first example includes the following

```html
…
<div class="h-screen flex overflow-hidden bg-gray-100">
  <!-- Off-canvas menu for mobile, show/hide based on off-canvas menu state. -->
  <div class="md:hidden">
    <div class="fixed inset-0 flex z-40">
      <!--
        Off-canvas menu overlay, show/hide based on off-canvas menu state.

        Entering: "transition-opacity ease-linear duration-300"
          From: "opacity-0"
          To: "opacity-100"
        Leaving: "transition-opacity ease-linear duration-300"
          From: "opacity-100"
          To: "opacity-0"
      -->
      <div class="fixed inset-0" aria-hidden="true">
        <div class="absolute inset-0 bg-gray-600 opacity-75"></div>
      </div>
      <!--
        Off-canvas menu, show/hide based on off-canvas menu state.

        Entering: "transition ease-in-out duration-300 transform"
          From: "-translate-x-full"
          To: "translate-x-0"
        Leaving: "transition ease-in-out duration-300 transform"
          From: "translate-x-0"
          To: "-translate-x-full"
      -->
      <div class="relative flex-1 flex flex-col max-w-xs w-full pt-5 pb-4 bg-indigo-700">
…
```

Is there other documentation you would expect to see here? Thanks for the follow-up!

**Comment by alexbu92** [comment]
That's documentation on transitions, I was referring to classes that change when for instance an item is selected i.e. on the branded sidebar the selected item has a darker background and doesn't have a hover state. But I've noticed that it has been largely improved with the release of 2.0, there still isn't documentation but at least the the common classes are put at the beginning of the class list and only the tail changes which is good.

**Comment by davidluhr** [comment]
Thank you for the clarification. That makes sense that the current route is reflected in the sidebar with a different visual state, but not represented in comments. I can make sure we indicate this for links with `aria-current="page"` across the components.

**Comment by davidluhr** [comment]
Thanks to your feedback, we've added comments to all components that have a "current" state, which clearly list the classes that need to be changed for the current state vs. default state. We appreciate this improvement you recommended!

**Comment by CHOMNANP** [comment]
I am having similar issue when passing the code into my project.
The style seem breaking.
![image](https://user-images.githubusercontent.com/5925050/111953371-181e1500-8b19-11eb-8c16-721cb740a964.png)


Any tips on this?
