### ISSUE TITLE
Component request: Chat interface

### ISSUE THREAD

**Issue by jschee** [tailwindlabs/tailwindui-issues#374]
A chat interface which includes a friends list and main window for the chat.

Have not seen this made yet on any production app.

Thank you to the Adam and Steve for such an awesome product so far. Have a great day!

**Comment by dacoto97** [comment]
+1

**Comment by jschee** [comment]
I'm making one right now @dacoto97 . It's not yet responsive, a wip but you can find it [here](https://github.com/jschee/sr-chat/tree/main/app/views/marketings). Start at the file chat.html.erb and make your way through the partials
![image](https://user-images.githubusercontent.com/24415168/99894865-c17cf900-2c54-11eb-8b32-dd43faf8f0d6.png)

**Comment by jschee** [comment]
I'm making one right now @dacoto97 . It's not yet responsive, a wip but you can find it [here](https://github.com/jschee/sr-chat/tree/main/app/views/marketingsl) Start at the file chat.html.erb and make your way through the partials.
![Screen Shot 2020-11-21 at 11 55 12 PM](https://user-images.githubusercontent.com/24415168/99894959-07d25800-2c55-11eb-908b-ff9edf0caf81.png)

**Comment by davidluhr** [comment]
Thanks for the suggestion—making note of this internally and also captured this in the Trello roadmap Ideas column

https://trello.com/c/C5jxPQZx/112-page-examples-chat-interface
