### ISSUE TITLE
Button groups, icon only has square shade

### ISSUE THREAD

**Issue by CatMonster** [tailwindlabs/tailwindui-issues#375]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/elements/button-groups#component-0d33369a2dac81cc4ed2f8b1e997a9cb
- Component name: Icon only

**Describe the bug**
Outer span has square shadow

**Expected behavior**
Shadow should be rounded

**Screenshots**
![image](https://user-images.githubusercontent.com/13244343/99576952-ef570900-29da-11eb-8072-7e1ba7829a50.png)

**Comment by davidluhr** [comment]
Great catch! Thanks for letting us know. This has been resolved and you should see the fixed version on the live site in just a moment.
