### ISSUE TITLE
Application UI Page Examples Settings Screens - With sidebar navigation and two-column form

### ISSUE THREAD

**Issue by tcoopman** [tailwindlabs/tailwindui-issues#378]
**Application UI Page Examples Settings Screens - With sidebar navigation and two-column form**
- URL for category: https://tailwindui.com/components/application-ui/page-examples/settings-screens
- Component name: With sidebar navigation and two-column form

**Describe the bug**
The billing history table doesn't render the border beyond amount on firefox 82. It works on chrome.
Removing the *relative* fixes the issue ( there is a comment:  `relative` is added here due to a weird bug in Safari that causes `sr-only` headings to introduce overflow on the body on mobile.)

**Expected behavior**
The border should go to the end of the table

**Screenshots**
![2020-11-20-092835_1638x430](https://user-images.githubusercontent.com/45546/99777915-465ff980-2b13-11eb-97b5-4101ba5d6c2b.png)

firefox on the left, chrome on the right

**Browser/Device (if applicable)**
 - OS: linux
 - Browser: firefox 82, chrome 86

**Comment by davidluhr** [comment]
@tcoopman Thanks for reporting this! We have a fix for this that should appear on the live site soon. Feel free to re-open this if the issue persists.
