### ISSUE TITLE
Banners outline

### ISSUE THREAD

**Issue by florianbouvot** [tailwindlabs/tailwindui-issues#379]
**What component**
- Component name: Banners

**To Reproduce**
Use the keyboard to navigate, "Learn more" link or button default outline is not "visible" (blue over indigo). 

**Expected behavior**
Using `focus:outline-white` or `ring` to improve contrast...

**Browser/Device**
 - OS: macOS
 - Browser: Safari
 - Version: 14

**Comment by davidluhr** [comment]
@florianbouvot With the recent release of Tailwind CSS 2.0, we've made a number of changes and improvements to focus styles that are detailed in this post: https://tailwindui.com/changes-for-v2 (specific information is found in the "Focus Styles" subsection within the "Updating for Tailwind UI users" section of the post).

In summary, the Learn more "button" in the banner is actually a link in terms of markup. To quote the above post:
> We've also removed custom focus styles for anything that doesn't receive focus when interacting with it with the mouse, so for example all <a> tags now just rely on the default browser focus style, as you only see it when navigating with the keyboard and using a familiar focus indicator where possible is much better for usability than using something custom.

This is our current approach for focus styles with `<a>` elements. I'm closing this issue for now, as this is the intended functionality, but please feel free to reply with your thoughts and feedback, as accessibility and usability are really important to us.

**Comment by florianbouvot** [comment]
@davidluhr thank you for your feedback.

I've read the detailed post and understand your approach but is it an accessibility issue that the default browser focus are not visible because of contrast with the background color?
