### ISSUE TITLE
Form elements don't have "name" attribute

### ISSUE THREAD

**Issue by vmitchell85** [tailwindlabs/tailwindui-issues#38]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/forms/form-layouts
- Component name: Any Forms

**Describe the bug**
Form elements don't have the `name` attribute by default. This means they will not be included in the form submission by default. Users would have to add them manually.

**Additional context**
[Mozilla](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#htmlattrdefname) states the following:
> Consider the `name` a required attribute (even though it's not). If an input has no `name` specified, or `name` is empty, the input's value is not submitted with the form.

**Comment by schmidtflo** [comment]
I don't think TUI should add name-parameters inside the templates -- as name is hugely individual per application and their logic and shouldn't be part of a template.

Also, copying from the docs for the JS, but also applying here:

> **Important: Our minimal JS examples are not meant to be "production-ready"**
>
> Tailwind UI is very focused on providing design and HTML. There are lots of intricacies you will inevitably be responsible for yourself with interactive components, like ensuring they are fully keyboard accessible, that focus is trapped properly for keyboard users, etc.
>
> Our Alpine.js examples are designed purely to communicate what classes you need to toggle on which elements and when, **they are not meant to be battle-tested JS reference implementations.**

**Comment by vmitchell85** [comment]
@schmidtflo While I agree that `name` is hugely individual per application so are `id` and `for` which are included in the components. I'm not suggesting they pick names for the user, just that they provide a default that can easily be changed. Right now I have to manually add the `name` attribute.

With current IDE/editors I can easily select the `for` and `id` contents using a shortcut key and replace them, if a `name` field was there with the same text as the other two I could quickly change them all at the same time.

It'd be better to include a blank `name` attribute IMO than not having the `name` attribute at all.

**Comment by DanHarrin** [comment]
I have to disagree with you about the `for` and `id` attributes. Browsers use these attributes to know which form element to focus when a label is pressed. They also have [accessibility advantages](https://www.w3.org/WAI/tutorials/forms/labels/).

**Comment by vmitchell85** [comment]
@DanHarrin Are you saying you disagree that `id` and `for` are application specific? I'm not sure I understand.

I think the simplest way I can put this is:

Every form component I use I have to add `name=""` to it and put in whatever name I want to use. I presume everyone would be doing this unless they are using some sort of ajax submission (aka `v-model` for vuejs). I'm recommending at least `name=""` be put into the components, or use the same string used for `id` and `for` in the `name` to make it easier to find and replace.

**Comment by DanHarrin** [comment]
Yes, `id` and `for` aren't application specific, they should be used everywhere.

**Comment by vmitchell85** [comment]
@DanHarrin ah... I meant the text inside the `id` and `for`... not that they shouldn't be used.

**Comment by davidluhr** [comment]
Returning to older issues, and I think this is a fair request.

As pointed out, we have to include opinionated/context-specific `for` and `id` attributes (as well as `name` attributes for checkbox/radio groups) anyway, so we might as well include `name` attributes where needed for valid markup.

I will do a pass of this soon.

**Comment by davidluhr** [comment]
As of today, we've added `name` attributes to all form elements, where needed. Thanks for suggesting this improvement!
