### ISSUE TITLE
Searchable select list

### ISSUE THREAD

**Issue by faxunil** [tailwindlabs/tailwindui-issues#384]
**Screenshots**
Provide a screenshot of your existing solution or of examples you've seen elsewhere that you think would be helpful inspiration.

**Additional context**
Add any important details you think we need to know to make sure we build something that matches what you need.

**Comment by davidluhr** [comment]
Thanks for the suggestion—making note of this internally and also captured this in the Trello roadmap Ideas column

https://trello.com/c/d3AHy86O/115-combobox-dropdown-search-filter-functionality
