### ISSUE TITLE
Big search bar

### ISSUE THREAD

**Issue by elvinaspredkelis** [tailwindlabs/tailwindui-issues#385]
Hey guys,
I'm a new member of the Tailwind community and absolutely love the framework so far. However, I find myself building something with a "big search bar" quite often. I think I might not be alone in this.

Tailwind UI components don't seem to have this component and I've only found a couple subpar examples on the internet.

Examples: Airbnb (with sections), Unsplash (just a big search bar)

**Screenshots**

<img width="896" alt="Screenshot 2020-11-27 at 12 44 04" src="https://user-images.githubusercontent.com/6149049/100440951-5a28d400-30ae-11eb-9778-fadb710456a3.png">
<img width="904" alt="Screenshot 2020-11-27 at 12 48 49" src="https://user-images.githubusercontent.com/6149049/100441301-e935ec00-30ae-11eb-8cd9-96c04637fbff.png">

**Comment by davidluhr** [comment]
Thanks for the suggestion—making note of this internally and also captured this in the Trello roadmap Ideas column

https://trello.com/c/hA5bQqH3/117-modal-popout-search-bar

Looking at our existing components, the closest thing we have is the full-width search inputs in the Sidebar Layouts: https://tailwindui.com/components/application-ui/application-shells/sidebar

I've made note that we could explore modal/popout searches as well.
