### ISSUE TITLE
The grid doesn't align element correctly

### ISSUE THREAD

**Issue by stefanodalpos** [tailwindlabs/tailwindui-issues#386]
**Describe the bug**
the first element on the grids appear upper than others

**Screenshots**
<img width="1328" alt="Schermata 2020-11-27 alle 14 28 06" src="https://user-images.githubusercontent.com/2254291/100454452-35882880-30bd-11eb-98c6-5486fa1936ef.png">

**Browser/Device (if applicable)**
 - OS: Mac Sur
 - Browser Chrome
 - Version 87.0.4280.67 (Build ufficiale) (x86_64)

**Additional context**
`<div class="bg-white shadow px-4 py-5 sm:rounded-lg sm:p-6">`
`                        <div class="md:grid md:grid-cols-3 md:gap-6">`
 `                           <div class="md:col-span-1">`
`                                <h3 class="text-lg font-medium leading-6 text-gray-900">Features</h3>`
`                                <p class="mt-1 text-sm text-gray-500">`
`                                    Tell more details about you... these details will used to find you better`
`                                </p>`
`                            </div>`
`                            <div class="mt-5 md:mt-0 md:col-span-2">`
`                              <form class="space-y-6" action="#" method="POST">`
`                                   <fieldset>`
`
`                                        <div class="grid grid-cols-6 gap-6 mt-4 space-y-4">`

**Comment by davidluhr** [comment]
@stefanodalpos Is this an issue found on TailwindUI.com, or in your own implementation of a component?

It appears your screenshot is based on https://tailwindui.com/components/application-ui/forms/form-layouts#component-b5675d2efaa71ec3767969fd53fc3b66

Looking at the live component example, I am not able to recreate this issue. Could you compare your code to the component code to begin troubleshooting?

If there's an issue with Tailwind UI, I'll get it fixed as soon as possible. If you need help building your own layout, you can hop on the Tailwind UI Discord server and use the #help channel there.

**Comment by stefanodalpos** [comment]
i found it in my vue js site, is not public at the moment i took the example founded in https://tailwindui.com/components/application-ui/forms/form-layouts#component-b5675d2efaa71ec3767969fd53fc3b66

this occurs when i cycle elements with vue js and put them in a grid inside the second column in each card hope that helps i had tried to debug it but i didn't find a solution yet

**Comment by stefanodalpos** [comment]
i find the solution class "space-y-4" applied to the grid div created the bug if we can call in this way

**Comment by davidluhr** [comment]
Glad you found a fix! Closing this issue for now.
