### ISSUE TITLE
Multiple select component

### ISSUE THREAD

**Issue by stefanodalpos** [tailwindlabs/tailwindui-issues#387]
**Screenshots**
<img width="1035" alt="Schermata 2020-11-27 alle 16 07 26" src="https://user-images.githubusercontent.com/2254291/100462525-b26dcf00-30ca-11eb-841d-04964997f38b.png">

**Comment by davidluhr** [comment]
Thanks for the suggestion—making note of this internally and also captured this in the Trello roadmap Ideas column

https://trello.com/c/yqHET3rV/116-multi-select-dropdown
