### ISSUE TITLE
Some gallery component 

### ISSUE THREAD

**Issue by stefanodalpos** [tailwindlabs/tailwindui-issues#388]
**Additional context**
Some light but functional gallery

**Comment by davidluhr** [comment]
@stefanodalpos Can you provide some examples of similar components you've seen? Would this be an image gallery specifically? What needs would this help solve?

Thanks for the additional information!

**Comment by stefanodalpos** [comment]
I think on a gallery like that or more complex even with a kind of hover effects 
<img width="985" alt="Schermata 2020-11-27 alle 21 01 07" src="https://user-images.githubusercontent.com/2254291/100481282-e4dff200-30f3-11eb-982f-51117ad3d6a9.png">
<img width="974" alt="Schermata 2020-11-27 alle 21 01 24" src="https://user-images.githubusercontent.com/2254291/100481285-e7424c00-30f3-11eb-9071-ca17eda1317a.png">

**Comment by davidluhr** [comment]
Thanks for the followup. Would the image gallery include interaction (such as clicking on the image to view a larger version), or do you mainly need an image grid?

The first example is currently possible using the `grid` utility classes to create a 3-column grid. The second example is likely also possible using CSS Grid and the `dense` setting for `auto-flow` (`grid-flow-row-dense` or `grid-flow-col-dense`).

In the near future, CSS is likely going to provide an actual masonry value: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Grid_Layout/Masonry_Layout

**Comment by davidluhr** [comment]
I've added this request to an existing item in our public Tailwind UI roadmap:

https://trello.com/c/PsNKad1C/61-image-galleries-grids

The community can vote for components they would like to see. Thanks for the suggestion!
