### ISSUE TITLE
Login ideas

### ISSUE THREAD

**Issue by code-press** [tailwindlabs/tailwindui-issues#389]
Thanks for the great work.  Excited to give my team great starter layout ideas for tailwind.

I was surprised that in the very robust library of samples there was not a login and/or password reset pages (unless I somehow missed them?).  Would you consider adding them?

**Comment by vincentdoerig** [comment]
Log-in components do exist: https://tailwindui.com/components/application-ui/forms/sign-in-forms

**Comment by davidluhr** [comment]
@code-press Yes, as @vincentdoerig mentioned, we do have sign-up and registration forms. Hopefully these examples provide a good starting point for your team. If you have new components you would like to see, let us know!
