### ISSUE TITLE
<body> element uses `antialiased`, but text does not appear to be

### ISSUE THREAD

**Issue by sebastienbarre** [tailwindlabs/tailwindui-issues#390]
**What component (if applicable)**

All the components, but my problem started with:

- URL for category:  https://tailwindui.com/components/application-ui/forms/sign-in-forms
- Component name: Simple card

**Describe the bug**

I was replicating the "Simple Card" example when I noticed that the input labels on TailwindUI.com were slightly but noticeably "heavier" than mine, even though I was using the EXACT same classes.

Yours on the left, mine on the right, both on Firefox:

![image](https://user-images.githubusercontent.com/329967/100488958-9d933a80-30ce-11eb-98fb-3f70f08ec3bd.png)

This got me scratching my head until I noticed in the "Computed Styles" debug panel that my label had `-moz-osx-font-smoothing: grayscale;`, and TailwindUI didn't.

This comes from the `antialised` class, which is placed on my `body` element. 
Sure enough, as soon as I removed `antialised`, both labels look the same.

But as it turns out... it is placed on TailwindUI.com `body` element too; if you inspect the input label on your site it reveals no `-moz-osx-font-smoothing: grayscale;`.

So I don't know how to explain it for sure, but my gut feeling is that you might be using (and recommending in the examples) `antialiased` but the variant itself might be disabled in your config? See https://tailwindcss.com/docs/font-smoothing#disabling

```
  // tailwind.config.js
  module.exports = {
    corePlugins: {
      // ...

     fontSmoothing: false,
    }
  }
```

I don't have any other explanation so far.

**To Reproduce**
1. Go to https://tailwindui.com/components/application-ui/forms/sign-in-forms
2. Click on Simple card
3. Inspect the label with a Web inspector
4. Notice the classes: `block text-sm font-medium text-gray-700`
5. Notice the `antialiased` class on the parent `body`
6. Notice there is no `-moz-osx-font-smoothing: grayscale;` in the computed styles.

**Expected behavior**

I would expect the font to be antialiased. There is no right or wrong choice of course here, but in trying to replicate the examples, it is useful (to me) to have visual consistency between my local sites and TailwindUI.com, to avoid chasing loose classes I may have forgotten :)

**Screenshots**

![image](https://user-images.githubusercontent.com/329967/100488958-9d933a80-30ce-11eb-98fb-3f70f08ec3bd.png)

**Browser/Device (if applicable)**
 - OS: macOS 10.14.6 (Mojave)
 - Browser: Firefox
 - Version: latest stable

**Comment by davidluhr** [comment]
@sebastienbarre Are you on Big Sur by chance? If so, `antialiased` doesn't have an effect anymore, and the OS may or may not provide a "Use font smoothing when available" checkbox in your General System Preferences.

This actually came up on a recent livestream that Adam did, which provides more context (at the 1:00:12 timestamp) https://youtu.be/u2jiRjyUbwA?t=3612

**Comment by sebastienbarre** [comment]
HI. I'm not using Big Sur, I'm using Mojave. The thing is, I can *see*, visually, that it is the issue for me. By removing "antialiased" from my `body` tag, my UI looks the same as TailwindUI.com. By putting it back on, I was back to a "less heavy" look of the font. Puzzling.

Thanks for the Youtube link, I forgot Adam was doing these now and then.

**Comment by davidluhr** [comment]
@sebastienbarre Thanks for the follow-up information. I'll have to research this further and will talk with the team to figure out what's going in.

**Comment by davidluhr** [comment]
@sebastienbarre I'm combing through existing issues again and it appears that this has been fixed. The font-smoothing properties appear in the computed styles, and toggling them has a noticeable effect on the text rendering. Closing this for now, but let me know if the issue persists for you!
