### ISSUE TITLE
Code-Snippet Component

### ISSUE THREAD

**Issue by Illuminatiiiiii** [tailwindlabs/tailwindui-issues#391]
A cool addition for us developers would be a code-snippet component like seen often on many sites including https://tailwindcss.com/ A component for line numbers vs a component variant for no line numbers would be useful. 

**Screenshots**
![image](https://user-images.githubusercontent.com/14157137/100495756-4e6ff880-3114-11eb-8a8e-f4da4b7ed24f.png)
![image](https://user-images.githubusercontent.com/14157137/100495799-a0188300-3114-11eb-9d45-0cd020dcdbd5.png)
![image](https://user-images.githubusercontent.com/14157137/100495811-b292bc80-3114-11eb-9325-274dc163f91a.png)

**Additional context**
Add any important details you think we need to know to make sure we build something that matches what you need.

**Comment by davidluhr** [comment]
Thanks for suggesting this! I've added it to our public Tailwind UI roadmap, where the community can vote for components they would like to see in the future.

https://trello.com/c/hKzg1OUW/118-code-snippet-component
