### ISSUE TITLE
example with stacked notifications

### ISSUE THREAD

**Issue by vesper8** [tailwindlabs/tailwindui-issues#392]
Currently the notifications examples are all in a fixed position and it only displays a single notification. I've found it difficult to modify the classes so that the notifications stack properly and neatly one under the other in the case of multiple notifications (and multiple types mixed together)

It would be appreciated if there was an example of how to achieve this correctly

**Comment by davidluhr** [comment]
Thanks for suggesting this! I've added it to our public Tailwind UI roadmap, where the community can vote for components they would like to see.

https://trello.com/c/mH0lEOVy/119-stacked-notifications-example

I'm guessing there's a way to add a wrapping `<div>` that has a column flex layout to get the notifications to stack, but I've made note of this request for a future component.

**Comment by vesper8** [comment]
@davidluhr there's something very odd about these notifications.. the moment you removed the fixed position class the inner widths go out of whack.. the only way I've made it work is by hardcoding widths for the inner columns of the different notification types
