### ISSUE TITLE
SVG in Marketing hero section with app screenshot

### ISSUE THREAD

**Issue by matthieumota** [tailwindlabs/tailwindui-issues#394]
- URL for category: https://tailwindui.com/components/marketing/sections/heroes#component-2b205c50497e231565b015fc1457839e
- Component name: Hero Sections

Hi Tailwind team. I use your amazing component collection.

I see a little bug on https://tailwindui.com/components/marketing/sections/heroes#component-2b205c50497e231565b015fc1457839e

Simply, svg is not present and because id pattern does not correspond in HTML. No worry at the moment, because we can easily fix it.

**Comment by davidluhr** [comment]
Thanks for pointing this out! It was a quick fix, as you mentioned, and should appear on the live site soon.
