### ISSUE TITLE
Simple Icon Card Header

### ISSUE THREAD

**Issue by dillingham** [tailwindlabs/tailwindui-issues#40]
> Just making note as Im making my own. I think it's a common / useful general component.

A basic plus icon list card heading. Maybe rounded-full.

Similar to the following, but with less markup for the title and additional action

**Screenshots**
![plus](https://user-images.githubusercontent.com/29180903/76023161-9ac83800-5ef6-11ea-974f-a937ed545c61.png)

Bad good example

![todo_list_new_2x](https://user-images.githubusercontent.com/29180903/76023486-44a7c480-5ef7-11ea-9f00-7932cd02b798.png)

**Comment by simonswiss** [comment]
Captured this in our ideas column in our roadmap: https://trello.com/c/l2HNvqOd/90-add-item-header-action - thanks for sharing! 👍
