### ISSUE TITLE
Responsive table widens whole page

### ISSUE THREAD

**Issue by anmartini** [tailwindlabs/tailwindui-issues#400]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/lists/tables
- Component name: All the tables

**Describe the bug**
When a table is viewed on a small screen the whole page becomes scrollable on the x-axis as if the table occupies its full width, even if the table is hidden inside its overflow-x-auto container.

**To Reproduce**
1. Go to https://tailwindui.com/components/application-ui/lists/tables
2. Reduce the width of the component
3. Scroll the horizontally
4. After the table ends the whole body keeps scrolling with a gray background

**Expected behavior**
The table should be scrollable without making the whole page larger than the screen width.

**Screenshots**
![Schermata 2020-12-03 alle 19 30 21](https://user-images.githubusercontent.com/2474517/101072296-164a3900-359e-11eb-98a8-0b9572fed8ce.png)

**Browser/Device (if applicable)**
 - OS: [macOS Big Sur]
 - Browser [Safari]
 - Version [14.0.1]
---
 - OS: [macOS Big Sur]
 - Browser [Chrome]
 - Version [87.0.4280.88]
---
 - OS: [iOS]
 - Browser [Safari]
 - Version [14.2]

**Additional context**
The problem appears also in a "regular" page not inside an iframe.

On Firefox v83.0 (macOS Big Sur) it works properly.

**Comment by davidluhr** [comment]
@anmartini Thanks for reporting this! I believe we have a fix for this that should appear on the live site soon. Feel free to re-open this if the issue persists.
