### ISSUE TITLE
Create react-ready copy-paste samples

### ISSUE THREAD

**Issue by las3r** [tailwindlabs/tailwindui-issues#401]
**Describe the bug**
The "code" parts of TailwindUI let's us copy paste code in order to use it in our apps. However, the code copied from (e.g.) the home screens (https://tailwindui.com/components/application-ui/page-examples/home-screens) requires _A LOT_ of manual correcting. Some samples of issues I'm getting:

1. IMG tags are not closed. Valid HTML, but react won't like it.
2. Input tags are not closed. Valid HTML, but react won't like it.
3. Comments are html comments, which error out in my jsx/tsx files
4. React uses className in stead of class.

**Comment by davidluhr** [comment]
This is a request that's definitely come up before. We are hoping to add first-class "copy as JSX" support at some point, but for now we recommend this helpful bookmarklet:

https://gist.github.com/RobinMalfait/a90e8651196c273dfa51eec0f43e1676

It will handle the self-closing tags, as well as converting class to className, updating SVG attributes, etc. 👍

**Comment by huntedman** [comment]
The gist didn't work for me, but a quick google search directed me to a simple [HTML to JSX compiler](https://magic.reactjs.net/htmltojsx.htm).
