### ISSUE TITLE
Navbars have space-y-1 on the wrong element

### ISSUE THREAD

**Issue by xt0rted** [tailwindlabs/tailwindui-issues#402]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/navigation/navbars
- Component name:
  - [Dark with quick action](https://tailwindui.com/components/application-ui/navigation/navbars#component-d833265bea66e95da3b499411d4d49b3)
  - [Simple dark](https://tailwindui.com/components/application-ui/navigation/navbars#component-1f0fd3139f66c75457637ca3746e3384)

**Describe the bug**

In the mobile menu the `space-y-1` class is on the first link instead of the container element.

**Screenshots**

![image](https://user-images.githubusercontent.com/831974/101239188-9ca46f00-36b3-11eb-9e40-6e9d39cbe142.png)

**Comment by davidluhr** [comment]
@xt0rted Great catch! I found this recently when working on the Figma Kits and your documentation here was very helpful. This issue is now fixed and will be live on the site shortly. Thanks for reporting this!
