### ISSUE TITLE
Headers - With full-width flyouts broken

### ISSUE THREAD

**Issue by enricoschaaf** [tailwindlabs/tailwindui-issues#403]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/marketing/elements/headers
- Component name:  With full-width flyouts

**Describe the bug**
Mobile menu does not  work.

**To Reproduce**
1. Go to https://tailwindui.com/components/marketing/elements/headers
2. Scroll down to "With full-width flyouts"
3. Resize till mobile menu is visible
4. Open mobile menu
5. See Error

**Expected behavior**
Expect the mobile menu to be above the nav bar.

**Screenshots**
![image](https://user-images.githubusercontent.com/54645197/101243239-1c0b6000-36ff-11eb-9f41-7f879249c8c7.png)

**Additional context**
Solution: Adding z-30 to the mobile menu.

**Comment by taftse** [comment]
Seems to be an Issue with the V2 component as the V1 component seems to work ok

**Comment by davidluhr** [comment]
@taftse Thanks for reporting this! Looks like we happened to catch this internally recently, and the issue has been fixed. The working version is currently live on the site.
