### ISSUE TITLE
Header - With full-width flyouts Links overlap at md viewport

### ISSUE THREAD

**Issue by enricoschaaf** [tailwindlabs/tailwindui-issues#404]
I am not sure if this is a bug, but it seemed of to me.

URL for category: https://tailwindui.com/components/marketing/elements/headers
Component name: With full-width flyouts
Describe the bug
Links overlap horizontally.

To Reproduce

1. Go to https://tailwindui.com/components/marketing/elements/headers
2. Scroll down to "With full-width flyouts"
3. Open mobile menu
4. Find viewport md where links are in 2 col grid
4. Hover over them to see that they overlap horizontally

Expected behavior
I expected them to be slightly spaced appart. Changing sm:gap-y-8 sm:gap-x-4 to sm:gap-8 did the trick for me.

**Comment by davidluhr** [comment]
@enricoschaaf Thanks for reporting this! This seems to have been related to a `z-index` issue that we caught internally while working on some related things recently. The issue should be fixed and the working version is live on the site.
