### ISSUE TITLE
Future Suggestion: a web extension like usewindy for tailwind CSS/UI

### ISSUE THREAD

**Issue by cliffordfajardo** [tailwindlabs/tailwindui-issues#405]
Hey tailwind team,
wasn't sure where to create this suggestion. I went to the discord & saw this comment in the tailwindUI server
![image](https://user-images.githubusercontent.com/6743796/101995059-13c1a080-3c7c-11eb-8488-c1600b617116.png)

## Suggestion
It would be nice to have a similar tool as [usewindy](https://usewindy.com/) for tailwind css
The utility of this would several:
- enhanced DX experience;  could potentially attract more people to tailwind
- easier for designers to share code with devs or use this stuff in Figma
- if it was open source, the community could help out. I feel like other tools would take notice of this awesomeness, get inspired and beginning doing similar things to attract users to their framework (healthy competition / innovation) 

### Web extension Example (source: https://usewindy.com/)
![000tailwind-devtool](https://user-images.githubusercontent.com/6743796/101994853-a2cdb900-3c7a-11eb-80d2-182da8f38e62.gif)

### Interactive Webpage Inspection (source: https://usewindy.com/)
if the devtools example above was imlemented, this probably wouldn't be necessary at all.
![0001tailwind](https://user-images.githubusercontent.com/6743796/101994857-a5c8a980-3c7a-11eb-96c0-e781c319e8e2.gif)

## Credits
- https://usewindy.com/

## 1. testing-playground chrome extension
   - chrome extension: https://chrome.google.com/webstore/detail/testing-playground/hejbmebodbijjdhflfknehhcgaklhano
   - github: https://github.com/testing-library/testing-playground
![000testing-playground](https://user-images.githubusercontent.com/6743796/101995037-d8bf6d00-3c7b-11eb-8a8c-41cec9c1faff.gif)

**Comment by davidluhr** [comment]
@cliffordfajardo I've made note of this request with the team. However, we currently don't have plans to build something like this tool, so feel free to use Windy if you find it valuable in your work.

Thanks for the suggestion!
