### ISSUE TITLE
blog card

### ISSUE THREAD

**Issue by willyw2k** [tailwindlabs/tailwindui-issues#406]
add more blog card example in blog section, i think card in laracast is very nice
![Screenshot_2020-12-16-00-18-46-04](https://user-images.githubusercontent.com/11731303/102248948-63ca8c80-3f34-11eb-9929-5a9aaebb6088.jpg)

**Comment by davidluhr** [comment]
Thanks for suggesting this! I've added this to our public roadmap in Trello, where the community can vote for what they would like to see added:

https://trello.com/c/jJf13sIa/83-media-cards

This is an existing request, so I've added a link to this issue for further reference.
