### ISSUE TITLE
Invalid markup in Application Stats components

### ISSUE THREAD

**Issue by imacrayon** [tailwindlabs/tailwindui-issues#407]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/data-display/stats
- Component name: Simple, With brand icon, With shared border

**Describe the bug**
The markup for these components groups the `<dt>` and `<dd>` element inside two nested `<div>` tags. According to the HTML spec only one `<div>` is allowed to wrap name-value groups within a `<dl>`

<img width="1046" alt="Screen Shot 2020-12-15 at 2 20 03 PM" src="https://user-images.githubusercontent.com/3410149/102268263-b8441c80-3ee0-11eb-85c6-7143529c50e8.png">

**Comment by davidluhr** [comment]
@imacrayon Thank for you reporting this. We'll look into a way to resolve this. It's a little tricky with some of the more complex Stats, but I think we can find a way to limit the markup to a single layer `<div>` tags within the `<dl>`.

**Comment by davidluhr** [comment]
@imacrayon Alright, after digging into all uses of `<dl>` in Tailwind UI, I've updated all related components to only have a single `<div>` between the `<dt>` and `<dd>`, which should pass the HTML Validator.

Thanks again for bringing this to our attention; accessible and valid HTML is really important to us! The corrected components should appear on the site shortly.

**Comment by imacrayon** [comment]
@davidluhr thanks for all the work on this and for keeping me updated 🙌
