### ISSUE TITLE
Input with inline leading add-on and trailing dropdown : Label "For" and Select "Id" have different value

### ISSUE THREAD

**Issue by jenjen75** [tailwindlabs/tailwindui-issues#408]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/forms/input-groups
- Component name: Input with inline leading add-on and trailing dropdown

**Describe the bug**
For currency element, sr-only label attribute is for="currency" and select is id="Currency"

**Expected behavior**
For currency element, sr-only label attribute is for="currency" and select is id="currency"

**Comment by davidluhr** [comment]
@jenjen75 Great catch! I've fixed this and the correct version should be live on the site soon.
