### ISSUE TITLE
Right aligned sidebars and sidebars for containers

### ISSUE THREAD

**Issue by tarraq** [tailwindlabs/tailwindui-issues#41]
I would love (i.e. need for a project) some sidebars that align right and also sidebar layouts that conform to a centered container instead of the page (unless this is already possible with current components).

**Comment by DanHarrin** [comment]
Maybe "sidebar navigation" will handle this?

![Screenshot 2020-03-06 at 17 56 04](https://user-images.githubusercontent.com/41773797/76109125-c10fd580-5fd3-11ea-8a8b-bdd9491872ae.png)

**Comment by simonswiss** [comment]
Nice one! 👍

Capturing this in our "bag of ideas" on the Trello roadmap. If it becomes a popular demand, we'll consider building it! 🎉 https://trello.com/c/365PwzYf/89-right-sidebar-container-sidebar
