### ISSUE TITLE
Disabled States

### ISSUE THREAD

**Issue by CraigIsOnGitHub** [tailwindlabs/tailwindui-issues#410]
For the interactive elements, such as Buttons/Menu Items/Inputs, etc., it would be great to have disabled states showcased too.

**Comment by davidluhr** [comment]
@CraigIsOnGitHub Great recommendation! I've add this suggestion to our public roadmap in Trello, where the community can vote for what they would like to have added in the future:

https://trello.com/c/Un55cxvx/124-disabled-states-for-interactive-elements
