### ISSUE TITLE
Two-column in full-width cards is not respecting the preview

### ISSUE THREAD

**Issue by StErMi** [tailwindlabs/tailwindui-issues#412]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/forms/form-layouts
- Component name: Two-column in full-width cards

**Describe the bug**

The code of the component is not respecting the preview on the TailwindUI site.
The problem is that the code is missing at least one wrapping `div` that is present in the preview  with this classes `max-w-7xl mx-auto py-6 space-y-6 sm:px-6 lg:px-8`

**To Reproduce**
1. Copy the code into Tailwind CSS Play and see the results

**Expected behavior**
I would expect the same layout as in the preview

**Screenshots**

![image](https://user-images.githubusercontent.com/146166/102529401-1d923c00-40a0-11eb-8dca-033f405beded.png)

**Browser/Device (if applicable)**
 - OS: MacOS Bigsur
 - Browser chrome
 - Version 87

**Additional context**

Nothing to add

**Comment by davidluhr** [comment]
The previews are an opinionated example of the component, but we do not include this surrounding example layout in the provided code. Components are intended to be used wherever needed, and we cannot predict the desired layout for all projects.

You are free to match the `<div class="max-w-7xl mx-auto py-6 space-y-6 sm:px-6 lg:px-8">` container if you like that presentation, but the component's code needs to remain the way it is for adaptability.

Thanks for the feedback!

**Comment by davidluhr** [comment]
Sorry for the closing/reopening/closing. I missed the `space-y-6` that was mistakenly part of the outer example wrapper, and the cause of the issue you mentioned. I've fixed this so the `space-y-6` is included in the component's code. Please note that the example layout details (`<div class="max-w-7xl mx-auto py-6 sm:px-6 lg:px-8">` remain outside the component code for the reasons mentioned above.

Thank you for reporting this!
