### ISSUE TITLE
Loading spinners

### ISSUE THREAD

**Issue by hrafnkellpalsson** [tailwindlabs/tailwindui-issues#413]
Having a couple of loading spinner to choose from would be nice!

**Comment by davidluhr** [comment]
@hrafnkellpalsson Thanks for this suggestion! We've received this request before, so I've added your request to the existing item in our public roadmap in Trello. This is where the community can vote for what they would like to have added in the future:

https://trello.com/c/whj4CPQS/48-loading-spinners-skeletons
