### ISSUE TITLE
Language picker

### ISSUE THREAD

**Issue by hrafnkellpalsson** [tailwindlabs/tailwindui-issues#414]
A language picker seems like a fairly universal and useful component to have

**Screenshots**
<img width="1680" alt="Screen Shot 2020-12-17 at 10 12 10" src="https://user-images.githubusercontent.com/1563739/102646806-8a95e800-4119-11eb-8745-711afe7cbee9.png">

**Additional context**
Twitter thread on the best way to implement a language picker
https://twitter.com/mmatuzo/status/1328940135719776257

**Comment by davidluhr** [comment]
@hrafnkellpalsson Depending on how you would to present the options, this could be possible with the current Dropdown or Modal components. Nonetheless, I've added this suggestion to our public roadmap in Trello, where the community can vote for what they would like to have added in the future:

https://trello.com/c/2AY4mxMI/125-language-picker
