### ISSUE TITLE
[REQUEST] Add badges for new components

### ISSUE THREAD

**Issue by LarryBarker** [tailwindlabs/tailwindui-issues#415]
First, thank you for all you do for the community! This isn't really a bug or specific component request, so I apologize if it is not the appropriate venue for my request. Feel free to chide me and put me in timeout if so 😆 

Anyhow, it would be super cool if you could add a badge to sections and the subsequent components that are new since the last release. I think this would be helpful to quickly find the new components.

I'm sure this will fall into the basement of the bottom of the stack of things to do, but I wanted to make the suggestion so thanks for listening!

**Comment by davidluhr** [comment]
@LarryBarker Good news! This was recently implemented on the site. It will now show a "New" badge next to components that have been added in the last 2 weeks. Due to the holidays, we don't have components that are that new, but keep a look out soon!
