### ISSUE TITLE
&#8203; outside <span>

### ISSUE THREAD

**Issue by wouterdorgelo** [tailwindlabs/tailwindui-issues#416]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/overlays/modals
- Component name: Simple alert with left-aligned buttons

**Describe the bug**
I've never heard about: `&#8203;` but it should be placed within the span tags

`<span class="hidden sm:inline-block sm:align-middle sm:h-screen" aria-hidden="true"></span>&#8203;`

**Comment by davidluhr** [comment]
@wouterdorgelo Great catch! This is a very specific and unusual fix needed to trick the browser into centering the modal contents. All the other modals correctly have this inside the `<span>`, but we missed this one. Thanks for letting us know. I've fixed this and it should be live on the site soon.
