### ISSUE TITLE
Short Toggle ring-offset leaves behind thin border

### ISSUE THREAD

**Issue by msobie** [tailwindlabs/tailwindui-issues#423]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/forms/toggles#component-b3e0a15571300f79fced5845f97fa972
- Component name: Short Toggle

**Describe the bug**
All elements with ring-offset leave behind a thin border from where the initial border resided.

**To Reproduce**
1. Copy Short Toggle component and paste into any project. Bug is available on TailwindUI's example as well.

**Expected behavior**
Thin border should not appear.

**Screenshots**
<img width="104" alt="Example" src="https://user-images.githubusercontent.com/70611133/103379709-8f14b600-4ab4-11eb-9267-dfa15b40ea4e.png">
<img width="128" alt="Example from TailwindUI" src="https://user-images.githubusercontent.com/70611133/103379907-41e51400-4ab5-11eb-9760-8db603314527.png">

**Browser/Device (if applicable)**
 - Browser: Persists on Chrome, Safari, and Firefox

**Additional context**
Click on the images to better visualize the bug.

**Comment by davidluhr** [comment]
@msobie Thanks for reporting this! The fixed version of this should be live on the site shortly.
