### ISSUE TITLE
Tailwind UI - Input with label and help text maybe with wrong text?

### ISSUE THREAD

**Issue by secretlifeof** [tailwindlabs/tailwindui-issues#424]
### Describe the problem:

Just noticed this maybe not correct help text. Definitely not so serious just something for a backlog.

<img width="1303" alt="image" src="https://user-images.githubusercontent.com/38684618/103234213-60290380-493f-11eb-89bd-4e0670c700b6.png">

**Comment by davidluhr** [comment]
@secretlifeof Thanks for reporting this! We have made note of this for a future round of example content/copywriting improvements.
