### ISSUE TITLE
div-based table layouts

### ISSUE THREAD

**Issue by ayb** [tailwindlabs/tailwindui-issues#427]
I think it would be very useful if there were at least 1 sample component in the tables section that used div elements to render tabular data.

i.e. https://tailwindui.com/components/application-ui/lists/tables

Most apps have at least some tabular data, and table based elements have some DOM related constraints around types of elements that can be used etc.

Since Tailwind has many utility classes around table widths etc. I think it could be very handy to have some good examples of table layouts that don't actually use HTML tables.

**Comment by davidluhr** [comment]
@ayb Can you please provide some examples of things that are only possible by diverging from semantic `<table>` markup?

The accessibility requirements for tabular data that doesn't use `<table>` markup are pretty involved, and don't have great support for assistive technology. I would be hesitant to go down this path unless it was absolutely necessary. Currently all our designs and functionality work fine with native elements, so we haven't seen a need for this.

What are some use cases that would benefit from this approach?

**Comment by ayb** [comment]
@davidluhr My thought process here was as follows:
- not everyone always wants to use tables to represent tabular data 
- Tailwind has great spacing tools 
- the table components section uses tables for every representation of data, though it seems table markup would not be necessary to render data in this manner
- some tools and frameworks (such as Rails' new Turbo frame tags) don't play nice with tabular data
- therefore, it would be handy to have at least one component that can display tabular data while not directly using table markup

To be honest I had not considered the accessibility requirements here.  Would that make my request unrealistic?

**Comment by davidluhr** [comment]
@ayb The accessibility of non-`<table>`-based table layouts is quite complicated to get correct, and not well supported.

As a result, we would only explore this direction if it was absolutely necessary to achieve a particular design. So far, we haven't encountered a design need that would require us to deviate from `<table>` markup. Have you found examples of tabular data that are presented in a way that's not possible using semantic markup? If so, I'd be happy to add this to our public roadmap in Trello where the community can vote for what they'd like to see added: https://trello.com/b/Nh6e9w8Q/tailwind-ui-roadmap

However, without a clear use case that is worth these large tradeoffs, I don't foresee us creating tabular components that don't use `<table>` elements.
