### ISSUE TITLE
Stats with brand icon: grey part does not stay attached to the bottom of the card

### ISSUE THREAD

**Issue by DamienFF** [tailwindlabs/tailwindui-issues#429]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/data-display/stats
- Component name:  Stats with brand icon

**Describe the bug**
The bottom grey part does not stay attached to the bottom of the card but goes up when the text is of different lengths in the cards.

**To Reproduce**
1. Go to 'https://play.tailwindcss.com/thb0V10pWU
2. Make the screen large enough so that the cards are side by side BUT that the number + unit in the first card is on two rows
4. See error in card 2 and 3

**Expected behavior**
The grey part stay sticked to the bottom

**Screenshots**
![image](https://user-images.githubusercontent.com/20799486/103770974-32bb1480-5027-11eb-95f0-a3cb7923999e.png)

**Browser/Device (if applicable)**
 - Chrome Version 87.0.4280.88

**Comment by davidluhr** [comment]
@DamienFF Thank you for reporting this and for providing the Tailwind Play recreation! That was very helpful in quickly finding a fix. The corrected version should be live on the site soon.

Basically, adding `flex flex-col` to each stat fixes this. For reassurance, I've also added `flex-grow` to the leading content section within each stat to ensure that it will always push the gray footer to the bottom of each card.
