### ISSUE TITLE
Stacked List doesn't truncate properly

### ISSUE THREAD

**Issue by cwohlman** [tailwindlabs/tailwindui-issues#431]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/lists/stacked-lists#component-09767d67facc566b4999c78410ffb81a
- Component name: With right-justified avatar group

**Describe the bug**
Truncate class has no effect on the main text of the component.

**To Reproduce**
1. Add enough text to overflow the component
2. See that the avatars become misaligned and the text interferes with the chevron icon

**Expected behavior**
The text should be truncated (or wrapped I suppose) when it bumps against the left content div

**Screenshots**
<img width="670" alt="Screen Shot 2021-01-07 at 5 14 26 PM" src="https://user-images.githubusercontent.com/4643896/103950956-cf56e280-510b-11eb-9d79-bec025bd54d8.png">

**Browser/Device (if applicable)**
 - OS: Mac
 - Browser Chrome

**Comment by cwohlman** [comment]
This seems to be related to flexbox. If I remove 'flex' from the affected component the issue goes away.

**Comment by davidluhr** [comment]
@cwohlman Thanks for reporting this, and for your patience on this. I've fixed this issue and the correct version should be live on the site shortly.
