### ISSUE TITLE
Multi-column detail screen directory column

### ISSUE THREAD

**Issue by edwinvdpol** [tailwindlabs/tailwindui-issues#432]
**What component**
- URL for category: https://tailwindui.com/components/application-ui/page-examples/detail-screens
- Component name: Multi-column directory

**Describe the bug**
This is probably not a bug, but simply not implemented. I would like to see the directory "button" working when the directory column is hidden.

**To Reproduce**
1. Resize the view until the directory column is hidden.
2. Click on '< Directory'.

**Expected behavior**
I would expect to see the directory column slide in from the left, over the content section.
Also an active state for the selected directory item would be greatly appreciated. :wink:

**Screenshots**

https://user-images.githubusercontent.com/9265514/104017991-64fc7b80-51b9-11eb-9610-91635c184093.mov

**Comment by adamwathan** [comment]
Hey! The way we intended for this UI to work when designing it was that the "< Directory" link would simply be a link back to a dedicated directory page on smaller screens 👍🏻 If you want to build a layout like this though and include a slide-over, there are a lot of examples here you can use and adapt to your needs:

https://tailwindui.com/components/application-ui/overlays/slide-overs

Hope that helps, no plans to make this example any more complex than it is at the moment. We try to provide as many useful ingredients as we can so folks can adapt them as needed in their own projects, but trying to piece together every possible combination of design ideas in larger screen examples isn't something we're setting out to do.

**Comment by edwinvdpol** [comment]
Hi Adam,

Thank you for your detailed explanation and I agree with your motivation.
Keep up the good work at Tailwind Labs, you guys are doing a great job!
