### ISSUE TITLE
Add Shapes

### ISSUE THREAD

**Issue by uurcank** [tailwindlabs/tailwindui-issues#433]
TailwindCSS is missing shape class set. This is quite common in bootstrap themes and should be part of TailwindUI with samples.

**Screenshots**
https://landkit.goodthemes.co/docs/shapes.html

**Additional context**
This class set can be used to create dividers as well.

**Comment by davidluhr** [comment]
@uurcank Because this involves Tailwind CSS (separate from Tailwind UI) I've added this as a Feature Request issue in the Tailwind CSS repo: https://github.com/tailwindlabs/tailwindcss.com/issues/709

Feel free to add further context there.

Thanks for the suggestion. Closing this now.
