### ISSUE TITLE
Class name typo in navbar example "Simple dark"

### ISSUE THREAD

**Issue by joshlarsen** [tailwindlabs/tailwindui-issues#434]
**What component (if applicable)**
https://tailwindui.com/components/application-ui/navigation/navbars
'Simple Dark'

**Describe the bug**
The class name `focus:ring-insest` is used on the toggle button and is not a Tailwind class name.

**To Reproduce**
1. Go to https://tailwindui.com/components/application-ui/navigation/navbars
2. Click on 'Code' for the 'Simple Dark' example
3. Search for 'focus:ring-insest'

**Expected behavior**
Should be a Tailwind class (`focus:ring-inset` presumably).

**Screenshots**
<img width="854" alt="screenshot-2021 01 10-17 53 11-lz4FFzC9@2x" src="https://user-images.githubusercontent.com/2565382/104137700-b8fb9180-536c-11eb-8786-41d8067668a9.png">

**Browser/Device (if applicable)**
 - OS: macOS 10.15.7
 - Browser Chrome
 - Version 87.0.4280.88 (Official Build) (x86_64)

**Comment by davidluhr** [comment]
@joshlarsen Thank you for reporting this. I've fixed the class name and the corrected version should be live on the site shortly.
