### ISSUE TITLE
Collapsible Table/Page Options Area

### ISSUE THREAD

**Issue by orware** [tailwindlabs/tailwindui-issues#436]
**Screenshots**
The first screenshot in this GitHub issue shows an example of the Search Tools area (after it's been expanded) in the Joomla CMS:
https://github.com/joomla/joomla-cms/issues/7588

**Additional context**

I'm sure you guys can come up with a much nicer way of creating this sort of feature but basically where I'm coming from with this request is that the Search Tools area in Joomla does a decent way of hiding some of the extra complexity on the page when it comes to filtering the tabular results beneath it.

I created my first Livewire project a few months ago and at the top of the page output here on my end I added a number of grouping/sorting/filtering features but I've been struggling with a good way to present them nicely so having an example included in Tailwind UI would be helpful.

For example, right now I have 4 dropdown menus at the top of my page, shown to the right of the current page heading/description area. I'm still relatively green with Tailwind CSS so a lot of this likely has to do with that lack of knowledge, but I eventually got my dropdowns to be nicely aligned when viewed in a full-screen desktop setting, however as the screen size goes down, the approach I went with no longer looks that good since the dropdowns to the right start to get cutoff (which I know is my fault due to how I currently have things structured).

Being able to filter/group things though for tables, and possibly hiding that functionality until an "Options" button of some sort is toggled seems like a common need however so I'm hoping others might think an example for this would be a good idea as well.

Thank you for the consideration!

**Comment by davidluhr** [comment]
@orware Thanks for suggesting this! I've added it to our public roadmap in Trello, where the community can vote for what they'd like to see added to Tailwind UI:

https://trello.com/c/e1I5hrIX/128-interactive-data-tables
