### ISSUE TITLE
Transitions in Vue 3 - Only working on leave.

### ISSUE THREAD

**Issue by matty0005** [tailwindlabs/tailwindui-issues#438]
**What component (if applicable)**
I've tested a few components, but the ones that mainly are an issue for me is the Slideover (https://tailwindui.com/components/application-ui/overlays/slide-overs) and also Circles with text (https://tailwindui.com/components/application-ui/navigation/steps)

**Describe the bug**
When the component is expanded, no transtion is applied, however, when minimised the transtion acts as expected.

**To Reproduce**
1. Use code from default examples
2. Open the slideover and observe. 

**Expected behavior**
Have a transition/animation on opening/entering.

**Browser/Device (if applicable)**
 - OS: Windows 10
 - Browser Chrome, Firefox (haven't tested others)

**Additional context**
These examples worked fine in Vue2, but after migrating to Vue 3, these examples don't fully work.

**Comment by davidluhr** [comment]
@matty0005 I believe we found some similar issues recently, and we have updated our Vue documentation as a result: https://tailwindui.com/documentation#js-vue

Can you see if the approach described in the "Co-ordinating multiple transitions" section resolves the issue you are experiencing?

**Comment by matty0005** [comment]
@davidluhr Unfortunately that did not seem to fix my issue. I will note that in some of the cases i have, there is only 1 transition or 1 item been displayed/hidden and not 2 like the documentation had. 

I have stripped it right back so that there is no other transitions on the page (including in the parent and child components), and i'm still experiencing the same issue.

**Comment by AlexH269** [comment]
I'm facing the same issue.

**Comment by AlexH269** [comment]
Looks like "enter-class" and "leave-class" were renamed to "enter-from-class" and "leave-from-class":
https://v3.vuejs.org/guide/transitions-enterleave.html#css-animations

Using the renamed props fixes the probloem for me.

**Comment by matty0005** [comment]
Yep, that seems to be the issue, it fixes it for me. Could we please get the docs updated for this change to help people down the line?
