### ISSUE TITLE
Input with label, help text and with validation error

### ISSUE THREAD

**Issue by seb-jean** [tailwindlabs/tailwindui-issues#44]
Hi :)

For "Input Groups", there are "Input with label and help text" and "Input with validation error" but it would be great to have "Input with label, help text and with validation error".

Thank you :)

**Comment by simonswiss** [comment]
Nice one! 👍

Capturing this in our "bag of ideas" on the Trello roadmap. If it becomes a popular demand, we'll consider building it! 🎉 https://trello.com/c/JlSlkuOE/88-input-group-with-all-elements
