### ISSUE TITLE
SVG element not clickable inside grid list

### ISSUE THREAD

**Issue by paulhennell** [tailwindlabs/tailwindui-issues#440]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/lists/grid-lists
- Component name:  Actions with shared borders

**Describe the bug**
The list is large clickable targets, with arrows in the corner. The targets are not however clickable on the arrows themselves (the first place I tried to click!)

**To Reproduce**
1. Go to 'Actions with shared borders'
2. Click on/close to one of the arrows icons
3. Nothing happens

**Expected behavior**
Should highlight as it does if you click on the target elsewhere but where the svg is

**Additional thoughts**
I know this can be resolved pretty quick with some z-index adjustments, but might as well be changed upstream 😉

**Comment by davidluhr** [comment]
@paulhennell Great catch! This was easy to fix with `pointer-events-none` on the SVG wrapper. The working version should be live on the site shortly. Thanks for reporting this!

**Comment by paulhennell** [comment]
Pointer-events-none! Knew there be a more elegant way to fix it 😄
