### ISSUE TITLE
Stacked Layouts with left-sidebar (aka mixed layout)

### ISSUE THREAD

**Issue by tianzhou** [tailwindlabs/tailwindui-issues#444]
**Screenshots**
![Screen Shot 2021-01-17 at 3 07 39 AM](https://user-images.githubusercontent.com/230323/104820698-9e944d00-5871-11eb-9ab4-5fd0f95edb56.png)

![Screen Shot 2021-01-17 at 3 07 46 AM](https://user-images.githubusercontent.com/230323/104820699-a2c06a80-5871-11eb-9aeb-ef88adc8b2e4.png)

**Additional context**
Quite useful for feature-rich applications requiring multi-level navigation.  e.g. GitLab, Jira

**Comment by davidluhr** [comment]
@tianzhou Thank you for the suggestion! I've added this to the public Tailwind UI roadmap in Trello, where the community can vote for what they would like to see added to Tailwind UI:

https://trello.com/c/1MXylXOc/129-application-shells-stacked-layouts-with-sidebar
