### ISSUE TITLE
Toggles should have pointer-events-none on slider

### ISSUE THREAD

**Issue by barrycenter** [tailwindlabs/tailwindui-issues#445]
The toggles in _Application > Forms > Toggles_ should all probably have `pointer-events-none` as one of the classes on the round slider so the clicks pass through to the underlying button. 

Otherwise, it only registers clicks in the background area which is likely to cause confusion with users.

**Comment by davidluhr** [comment]
@barrycenter Great callout! Thank you for letting us know. I've fixed this and the corrected version should be live on the site shortly.

I've been seeing `button > * { pointer-events: none; }` cropping up in reset stylesheets lately, which might be something for us to explore…
