### ISSUE TITLE
Table (list) page with filters and pagination components

### ISSUE THREAD

**Issue by alex-oleshkevich** [tailwindlabs/tailwindui-issues#446]
**Screenshots**
![image](https://user-images.githubusercontent.com/635848/104843307-f1eeb580-58da-11eb-9fac-05926ae5eda4.png)

**Additional context**
This is a very common component for CRMs and admin panels.

**Comment by davidluhr** [comment]
@alex-oleshkevich Thanks for the suggestion! We actually recently received a related request. I've added a link to this issue in a our public roadmap for Tailwind UI in Trello, where the community can vote for what they'd like to see added:

https://trello.com/c/e1I5hrIX/128-interactive-data-tables
