### ISSUE TITLE
Application UI > Home Screens > Constrained grid layout has incorrect grid list border on mobile

### ISSUE THREAD

**Issue by mitchdav** [tailwindlabs/tailwindui-issues#447]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/page-examples/home-screens#component-a75fa56c99de07250d40ffcf1c70283f
- Component name: Application UI > Home Screens > Constrained grid layout

**Describe the bug**
The grid list with the 6 actions has an incorrect bottom left rounded border on mobile. This isn't present in the [standalone grid list](https://tailwindui.com/components/application-ui/lists/grid-lists#component-a26a744b444974a4cc73cb5886b8da6a).

**To Reproduce**
1. Go to https://tailwindui.com/components/application-ui/page-examples/home-screens#component-a75fa56c99de07250d40ffcf1c70283f
2. Reduce the size of the viewport down to mobile
3. See error on the `Submit an expense` action

**Expected behavior**
The bottom left border should not be present on mobile.

**Screenshots**
![image](https://user-images.githubusercontent.com/3215585/104871035-25dedf00-599e-11eb-9bb5-437168b3e351.png)

**Additional context**
This can be resolved by adding the `sm:` prefix to the `rounded-bl-lg` class on the action container, which makes it consistent with the standalone grid list linked above.

![image](https://user-images.githubusercontent.com/3215585/104871318-dd73f100-599e-11eb-8284-8628550dae16.png)

**Comment by mitchdav** [comment]
I have just discovered that this also affects the `Benefits` action as well, which also just needs the `sm:` prefix added to the `rounded-tr-lg` class to resolve the issue.

**Comment by davidluhr** [comment]
@mitchdav Thank you for reporting this! Everything should appear as expected now. The fixed version will be live on the site shortly.m
