### ISSUE TITLE
TailwindUI: Img tags in "Avatar group with actions" are incorrectly closed

### ISSUE THREAD

**Issue by TedisAgolli** [tailwindlabs/tailwindui-issues#449]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/lists/stacked-lists#component-887cb27d2a36c9d38afe44b19d9a44c5
- Component name:  Avatar groups with actions

**Describe the bug**
All the _img_ elements in the code are missing a closing tag.
```  html     
    <img class="h-8 w-8 rounded-full" src="https://images.unsplash.com/photo-1519345182560-3f2917c472ef?ixlib=rb-1.2.1&amp;ixid=eyJhcHBfaWQiOjEyMDd9&amp;auto=format&amp;fit=facearea&amp;facepad=2&amp;w=256&amp;h=256&amp;q=80" alt="">
```

**Comment by davidluhr** [comment]
@TedisAgolli In HTML5, any self closing tags are valid as both `<img …>` and `<img … />`. In React and other frameworks, these are converted to always include the `/` at the end of the tag, but it is not standard practice when just writing HTML.
