### ISSUE TITLE
Invoice template

### ISSUE THREAD

**Issue by PolMrt** [tailwindlabs/tailwindui-issues#45]
**Screenshots**
<img width="702" alt="Capture d’écran 2020-03-06 à 15 46 11" src="https://user-images.githubusercontent.com/28253868/76093638-a03e8480-5fc1-11ea-9ef7-b6072f04edca.png">

**Additional context**
It would be nice to have an invoice template like tabler does.

**Comment by simonswiss** [comment]
Thanks for suggesting this! 👍

I have captured this in our bag of ideas on the roadmap: https://trello.com/c/4xQP5r6O/87-invoice-template

I will also consolidate this issue with the many ecommerce related suggestions at #268 🎉
