### ISSUE TITLE
Missing semicolon

### ISSUE THREAD

**Issue by tonykyriakidis** [tailwindlabs/tailwindui-issues#450]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/marketing/sections/content-sections#component-f6c39bd93fbb747d288f373cdbc039e3
- Component name: With testimonial and stats

**Describe the bug**
You are missing a semicolon that is causing the component to raise an error. 

```

<a href="#" class="text-base font-medium text-indigo-600">
    Learn more about how we're changing the world&nbsp&rarr;
</a>

```
**Fix**
`&nbsp&rarr;` should be: `&nbsp;&rarr;`

**Comment by davidluhr** [comment]
@tonykyriakidis Good catch! I've improved this by wrapping the `&rarr;` in `<span aria-hidden="true">` to clean up the experience for assistive technology users and provide the desired spacing. The fixed version should be live on the site shortly.
