### ISSUE TITLE
Image causing a horizontal scroll

### ISSUE THREAD

**Issue by anmolbajajnet** [tailwindlabs/tailwindui-issues#451]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/marketing/sections/feature-sections
- Component name: Alternating with optional testimonial

**Describe the bug**

**To Reproduce**
1. Go to the "Alternating with optional testimonial" component
2. Shrink the screen to mobile view (small)
3. See how the first feature image (https://tailwindui.com/img/component-images/inbox-app-screenshot-1.jpg) doesn't shrink properly and causes a horizontal scroll

**Expected behavior**
There should not be a horizontal scroll on the webpage because the screen size changed

**Browser/Device (if applicable)**
 - OS: iOS, MacOS
 - Browser: Safari, Chrome

**Additional context**

**Comment by davidluhr** [comment]
@anmolbajajnet Thanks for reporting this! The fixed version should be live on the site shortly.
