### ISSUE TITLE
stats - simple with card, redundant max width?

### ISSUE THREAD

**Issue by kanishka-work** [tailwindlabs/tailwindui-issues#452]
**What component (if applicable)**
- URL for category: 
- Component name: stats - simple with card

**Describe the bug**

 ```   
<div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
      <div class="max-w-4xl mx-auto text-center">
```
The first max-w-7xl mx-auto appears to do nothing given the max-w-4xl below. I am new to css, so feel free to close without explanation if there is an obvious reason why the max-w-7xl exists

**Comment by adamwathan** [comment]
Hey! Can you provide a direct link to the component you mean? The "Split with navbar" hero doesn't appear to use `max-w-4xl` anywhere, so I worry I'm not looking at the same component as you:

https://tailwindui.com/components/marketing/sections/heroes#component-e5c15b9d1a503738005e35302043c802

**Comment by kanishka-work** [comment]
Sorry, named wrong component. Meant to say "stats - simple in card" - https://tailwindui.com/components/marketing/sections/stats-sections#component-4292ee7bd2cb557f72dbaed04cb72c57

**Comment by kanishka-work** [comment]
This isn't particularly important to me, so I will close. Feel free to re-open if someone else is tracking looking into this.
