### ISSUE TITLE
IMG spacing BUG for background_image_hero_with_alternating_features.html

### ISSUE THREAD

**Issue by pascalandy** [tailwindlabs/tailwindui-issues#453]
**What component (if applicable)**
- URL for category: marketing/page-examples/landing-pages/
- Component name: background_image_hero_with_alternating_features.html

**Describe the bug**

The picture under "Marcia Hill, Digital Marketing Manager" creates on horizontal gap  (scrollbar left-right appear) on lg and smaller rez.

Here is the cause:
```
<div class="pl-4 -mr-48 sm:pl-6 md:-mr-16 lg:px-0 lg:m-0 lg:relative lg:h-full">
```

**Expected behavior**

Fixed using:

```
<div class="pl-4 -ml-48 sm:pl-6 md:-ml-16 lg:px-0 lg:m-0 lg:relative lg:h-full">
```

**Screenshots**
![Screen Shot 2021-01-23 at 11 35 39 AM](https://user-images.githubusercontent.com/6694151/105607973-2812b600-5d6f-11eb-96af-4557b56156ec.jpg)

**Browser/Device (if applicable)**
 - OS: mac 10.14.6
 - Browser Brave
 - Version V1.19.86

**Additional context**

**Comment by davidluhr** [comment]
@pascalandy Thanks for reporting this! The fixed version should be live on the site shortly.
