### ISSUE TITLE
As a client, I would love to use Discussions within Github

### ISSUE THREAD

**Issue by pascalandy** [tailwindlabs/tailwindui-issues#454]
As a client, I would love to use Discussion within Github because I have Discord. For me, it's impossible to follow public conversations.
Thanks

**Comment by davidluhr** [comment]
@pascalandy To make sure I understand your request, are you saying that you _don't_ have Discord, and would prefer to use Discussions in GitHub for Tailwind UI customers instead? Thanks for helping to clarify!

**Comment by pascalandy** [comment]
Exactly! I hate discord "forums"

But Discourse rocks.

**Comment by davidluhr** [comment]
Thanks for the suggestion! I've made note of this with the team and will respond to this issue if there are updates.
