### ISSUE TITLE
Multi-column directory sidebar

### ISSUE THREAD

**Issue by raphaelarias** [tailwindlabs/tailwindui-issues#455]
- URL for category:  https://tailwindui.com/components/application-ui/page-examples/detail-screens
- Component name: Multi-column directory

**Describe the bug**

**To Reproduce**
1. Go to Multi-column directory on mobile 
2. Try to open the sidebar

**Expected behavior**
The sidebar with the list of employees should show, but nothing happens.

**Browser/Device (if applicable)**
 - OS: Mac OS 11
 - Browser Chrome
 - Version 87

**Comment by davidluhr** [comment]
@raphaelarias I believe this is working as expected. On smaller screens, the app would change routes to show a directory screen. On larger screens, this experience can be accomplished in a single view. To build the directory screen, the directory column can be stacked with the mobile header/navigation.

I hope that helps! Feel free to re-open this issue if needed.
