### ISSUE TITLE
Data grid styling

### ISSUE THREAD

**Issue by las3r** [tailwindlabs/tailwindui-issues#457]
**Screenshots**
- [https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/filtering/](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/filtering/)
- [https://demos.telerik.com/kendo-ui/grid/index](https://demos.telerik.com/kendo-ui/grid/index)

**Additional context**
I'm building many line of business applications that sometimes do have some content, but 50+% of the screens consists out of data grids. Boring huge tables with filtering, sorting, pagination, and toolbars with icons and options.

With tailwind UI I'm able to style some of these parts separately, but I'm looking for a more complete example that brings all items together in a consistent way.

**Comment by davidluhr** [comment]
@las3r Thanks for the request! This has been a popular suggestion lately. I've added a link to this page among related requests in our public Tailwind UI roadmap that we have in Trello, where the community can vote for what they'd like to see added to Tailwind UI:

https://trello.com/c/e1I5hrIX/128-interactive-data-tables

**Comment by jelen07** [comment]
Hi guys! I can't add a comment to the Trello so I'm adding it here.

Another dope examples of very handy grids are
- https://examples.contributte.org/packages/datagrid/ (working demo)
- https://dribbble.com/shots/1903644/attachments/1903644-Data-Grid?mode=media (UX)

It would be really nice to have something like that with filtering (date inputs, ranges, ...) and so on.
