### ISSUE TITLE
Overflow needs fixing in the homepage features section

### ISSUE THREAD

**Issue by callmephilip** [tailwindlabs/tailwindui-issues#458]
**What component (if applicable)**

![overflow](https://user-images.githubusercontent.com/492025/105837186-39a1cb00-5fc6-11eb-8de3-fdb507173fa3.jpg)

**Describe the bug**
See image above

**Fix**

Fixed it by updating 

`<div class="relative pt-16 pb-32 lg:overflow-hidden">` to `<div class="relative pt-16 pb-32 overflow-hidden">` in the features section

**Comment by davidluhr** [comment]
@callmephilip Thanks for reporting this! The fixed version should be live on the site shortly.
