### ISSUE TITLE
Detailed search with filters

### ISSUE THREAD

**Issue by georgeboot** [tailwindlabs/tailwindui-issues#46]
Sites that offer detailed search usually give you a wide-bar or collapsible pane where you can check and uncheck certain criteria.

Some examples:
<img width="1049" alt="Schermafbeelding 2020-03-09 om 09 15 12" src="https://user-images.githubusercontent.com/884482/76194586-bda06800-61e6-11ea-969c-4e2bfd8dffd9.png">
<img width="1438" alt="Schermafbeelding 2020-03-09 om 09 15 37" src="https://user-images.githubusercontent.com/884482/76194587-be38fe80-61e6-11ea-98e5-0752f84daca3.png">

**Comment by DanHarrin** [comment]
Please could you possibly attach an implementation screenshot here so that we better know what you mean? Are you talking about list filters (#49)?

**Comment by georgeboot** [comment]
> Are you talking about list filters (#49)?
No, these are more aimed at data tables. What I mean are "index view" filters.

**Comment by simonswiss** [comment]
I think the technical term for these is "faceted search", and I have captured this suggestion in our bag of ideas on the Trello roadmap. Thanks for sharing! 👍

https://trello.com/c/0XxndZui/86-faceted-search
