### ISSUE TITLE
Add bottom navigation for mobile

### ISSUE THREAD

**Issue by seb-jean** [tailwindlabs/tailwindui-issues#460]
Hey :smiley:,

I think it would be to add a "Navigation Bottom" component, for instance:

![Capture](https://user-images.githubusercontent.com/12116264/106151856-18cfa600-617d-11eb-9885-939aa1545c7d.PNG)

With fixed bottom to 0.

**Comment by davidluhr** [comment]
@seb-jean Thanks for the suggestion! I've added this to our public roadmap for Tailwind UI in Trello, where the community can vote for what they'd like to see:

https://trello.com/c/bYk7DQSS/131-mobile-fixed-bottom-navigation
