### ISSUE TITLE
Not mobile friendly

### ISSUE THREAD

**Issue by martinwebits** [tailwindlabs/tailwindui-issues#461]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/marketing/sections/feature-sections
- Component name: Alternating with optional testimonial

**Describe the bug**
Not mobile friendly - overflow.. The first picture is pushing page to right.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Browser/Device (if applicable)**
 - OS: IOS, Windows etc.
 - Browser, Safari, Chrome

**Comment by davidluhr** [comment]
@martinwebits Thanks for reporting this! The fixed version should be live on the site shortly.
