### ISSUE TITLE
Application UI - Data Display category

### ISSUE THREAD

**Issue by holgerw** [tailwindlabs/tailwindui-issues#462]
Hi there.

I would like to suggest additional components in the Application UI - Data Display category. Right now there are only 2 types of components: Description Lists and Stats.

In your book "Refactoring UI" you show some alternatives to the description list pattern. Those alternatives are way more engaging and maybe more effective to communicate the displayed data. In the book the relevant chapter with good examples is "Hierarchy is everything - Labels are your last resort".

It would be great to have those UX ideas applied to the TailwindUI data display components. Can we expect new components similar to the examples given in your book?

**Comment by davidluhr** [comment]
@holgerw Comparing the Refactoring UI examples you referenced with Tailwind UI, we do have some very similar components in the Grid Lists category: https://tailwindui.com/components/application-ui/lists/grid-lists

Additionally, the Team Sections also demonstrate similar approaches: https://tailwindui.com/components/marketing/sections/team-sections

Are there other types of components that you would like to see?

**Comment by holgerw** [comment]
@davidluhr Thank's for your reply. You are right. Those 2 categories (Grid Lists, Team Sections) are more visual designs as taught by the RefactoringUI book.

I guess instead of suggesting a specific component, my suggestion is more about applying this visual design style to all categories where it applies. Especially for the "Data Display - Description Lists" category it would be valuable to provide each component with 2 designs, the current more "table like" design and a more visual design.

Providing components with visual designs (resulting in the elimination of text labels) would be valuable also as the typical TailwindUI customer is not an expert on accessible markup.

**Comment by davidluhr** [comment]
@holgerw Thanks for the feedback and expanding on your idea. I've added this request to our public Tailwind UI roadmap in Trello, where the community can vote for what they'd like to see added:

https://trello.com/c/1xYUB3sn/139-add-variations-of-definition-list-driven-components-with-hidden-labels
