### ISSUE TITLE
Phone input request

### ISSUE THREAD

**Issue by wheredidgogogo** [tailwindlabs/tailwindui-issues#463]
Hi Guys

Absolutely loving using tailwind UI

One of our biggest nightmares has always been telephone input and saving in e164 format.

Telephone numbers are now just as important as email.

Any chance you can add a telephone input to the dev list?

<img width="889" alt="Screen Shot 2021-01-31 at 5 44 23 pm" src="https://user-images.githubusercontent.com/2225376/106376722-ff806100-63eb-11eb-89c9-d68a3f73f0d9.png">

<img width="932" alt="Screen Shot 2021-01-31 at 5 44 32 pm" src="https://user-images.githubusercontent.com/2225376/106376725-0313e800-63ec-11eb-9f0c-9c16b65abb7e.png">

thanks!

Anthony

**Comment by davidluhr** [comment]
@wheredidgogogo Thanks for the suggestion! I've added this request to our public Tailwind UI roadmap in Trello, where the community can vote for what they'd like to see added:

https://trello.com/c/Mk8EVf3Y/138-form-number-input-with-country-code-and-number-formatting
