### ISSUE TITLE
Portfolio / Image Gallery

### ISSUE THREAD

**Issue by optimido** [tailwindlabs/tailwindui-issues#464]
**Screenshots**
Provide a screenshot of your existing solution or of examples you've seen elsewhere that you think would be helpful inspiration.

**Additional context**
Add any important details you think we need to know to make sure we build something that matches what you need.

**Comment by davidluhr** [comment]
@optimido Thanks for the suggestion! I've added this request to our public Tailwind UI roadmap in Trello, where the community can vote for what they'd like to see added. This idea has come up a few times before, so I've added a link to this issue in the existing card:

https://trello.com/c/PsNKad1C/61-image-galleries-grids
