### ISSUE TITLE
Ecommerce Components: product listing & details 

### ISSUE THREAD

**Issue by vasipuica** [tailwindlabs/tailwindui-issues#466]
Tailwind UI has components for pricing but it would be great if you had some e-commerce components for presenting a listing of products and a product details page.

**Comment by davidluhr** [comment]
@vasipuica Thanks for the suggestion! I've added this request to our public Tailwind UI roadmap in Trello, where the community can vote for what they'd like to see added. This idea has come up before, so I've added a link to this issue in the existing card:

https://trello.com/c/JXSeuzwO/113-ecommerce-category-and-components
