### ISSUE TITLE
More diverse components

### ISSUE THREAD

**Issue by martinowren** [tailwindlabs/tailwindui-issues#467]
Right now it feels like all the components have the use case of SaaS applications etc. Is it possible to get some components and landing page examples for different use cases?
For example:
* E-commerce store
* Corporate info page
etc etc

**Comment by davidluhr** [comment]
@martinowren Thanks for the suggestions. The existing component bundles are for Marketing and Application UI, which is why the components are tailored for these use cases. We've made note of these suggestions for future categories to consider!
