### ISSUE TITLE
Flyouts with arrows .. like the picture on the box :)

### ISSUE THREAD

**Issue by hecktarzuli** [tailwindlabs/tailwindui-issues#468]
![image](https://user-images.githubusercontent.com/2112282/106667910-2b781f80-656f-11eb-8f27-80eb23814e9b.png)

I'm wondering if you plan on making some examples of Flyouts with up arrows like your preview shows.

**Comment by davidluhr** [comment]
@hecktarzuli Thanks for the suggestion!

I recently learned that these triangle indicators are called "beaks" in some design systems, which I thought was cool.

I've added this request to our public Tailwind UI roadmap in Trello, where the community can vote for what they'd like to see added:

https://trello.com/c/xSVnS9lo/136-flyouts-with-beaks-triangle-indicators
