### ISSUE TITLE
With avatar, meta, and dropdown: missing menu background

### ISSUE THREAD

**Issue by Akryum** [tailwindlabs/tailwindui-issues#470]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/headings/card-headings#component-566f127b7b70db160352896d06794a7f
- Component name: With avatar, meta, and dropdown

**Describe the bug**
The dropdown menu doesn't have a background?

**To Reproduce**
1. Click on the 3-dots icon to open the dropdown

**Expected behavior**
A white background I think :cat2: 

**Screenshots**

![image](https://user-images.githubusercontent.com/2798204/106797501-f9dd8200-665c-11eb-918f-e0936ba915f4.png)

**Browser/Device (if applicable)**
 - OS: Linux (elementary OS)
 - Browser: Firefox
 - Version: 85.0

**Additional context**
N/A

**Comment by adamwathan** [comment]
Fixed, thanks!
