### ISSUE TITLE
Mobile layout with fixed bottom icon bar

### ISSUE THREAD

**Issue by Progression** [tailwindlabs/tailwindui-issues#472]
Navigation on mobile can work well with a bar along the bottom of the screen giving easy access for people's thumbs! Much like many phone apps provide. So it would be great if you could add an App layout for smaller screens, that takes the sidebar nav, or the top bar nav, for larger screens and moves it to a fix bottom bar with icons (and/or text). This would work particularly well with the latest narrow sidebar layout.

**Screenshots**
<img width="466" alt="Screenshot 2021-02-04 at 08 48 22 - mockup" src="https://user-images.githubusercontent.com/942531/106856236-122dbb00-66b6-11eb-8ffd-4254c675acaf.png">
<img width="1099" alt="Screenshot 2021-02-04 at 08 47 30" src="https://user-images.githubusercontent.com/942531/106856244-1528ab80-66b6-11eb-9652-ab11207332ab.png">

**Comment by davidluhr** [comment]
@Progression Thanks for the suggestion! I've added this request to our public Tailwind UI roadmap in Trello, where the community can vote for what they'd like to see added. A similar request came through recently, so I've added this issue to an existing card:

https://trello.com/c/bYk7DQSS/131-mobile-fixed-bottom-navigation
