### ISSUE TITLE
Good to have the file tree (file explorer) component

### ISSUE THREAD

**Issue by sundaycrafts** [tailwindlabs/tailwindui-issues#475]
**Screenshots**
Provide a screenshot of your existing solution or of examples you've seen elsewhere that you think would be helpful inspiration.

![image](https://user-images.githubusercontent.com/4732821/106929793-24603580-6758-11eb-907c-fbe617f4f5db.png)

**Additional context**
Add any important details you think we need to know to make sure we build something that matches what you need.

* I needed it when I make an Electron app that finds and edit local files.
* It also great to have a function (or it's enough that just have a UI) which let user to open/close directory

**Comment by davidluhr** [comment]
@sundaycrafts Thanks for the suggestion! I've added this request to our public Tailwind UI roadmap in Trello, where the community can vote for what they'd like to see added:

https://trello.com/c/b036aEtK/134-tree-grid
