### ISSUE TITLE
Gallery component

### ISSUE THREAD

**Issue by martinowren** [tailwindlabs/tailwindui-issues#476]
Just a simple component request for gallery components

**Comment by davidluhr** [comment]
@martinowren Thanks for the suggestion! I've added this request to our public Tailwind UI roadmap in Trello, where the community can vote for what they'd like to see added. This idea has come up a couple times before, so I've added a link to this issue in the existing card:

https://trello.com/c/PsNKad1C/61-image-galleries-grids
