### ISSUE TITLE
Email templates - verify account, forgot password, generic newsletter

### ISSUE THREAD

**Issue by 01jonathanf** [tailwindlabs/tailwindui-issues#478]
**Screenshots**
Provide a screenshot of your existing solution or of examples you've seen elsewhere that you think would be helpful inspiration.

**Additional context**
Add any important details you think we need to know to make sure we build something that matches what you need.

**Comment by davidluhr** [comment]
@01jonathanf Thanks for the suggestion! I've added this to our public Tailwind UI roadmap in Trello, where the community can vote for what they'd like to see added:

https://trello.com/c/qTTpjb4b/132-email-templates
