### ISSUE TITLE
Idea: copy code button per JS framework

### ISSUE THREAD

**Issue by sietzekeuning** [tailwindlabs/tailwindui-issues#479]
First of all, awesome work you guys are doing! Probably you have thought of this already, but would like to throw the idea to make a copy function in the docs section for each JS framework.

With this you remove the need to edit any transition classes afterwards by the user. So for example, the copy AlpineJS code would make sure all the necessary code for AlpineJS is directly copied and the whole page or component works directly after copying it.

This would make the workflow even faster.

**Comment by davidluhr** [comment]
@sietzekeuning Thanks for the suggestion! To help clarify, are you referring to the code examples found in the documentation pages for each framework? Or, when viewing a Tailwind UI component, being able to copy the code in framework specific markup, such as JSX?

**Comment by sietzekeuning** [comment]
I was referring to the code examples found in the documentation. And then have a button to export to either, Vue, Alpine, or any other framework from there, without the need to alter any transition classes. Even a short <script> block could be added, so everything would work directly out of the box when copying the code.

Groet,
Sietze Keuning
06 - 42 310 420
info@kingwebsites.nl

On 5 February 2021 at 11:38:29, David Luhr (notifications@github.com) wrote:

@sietzekeuning Thanks for the suggestion! To help clarify, are you referring to the code examples found in the documentation pages for each framework? Or, when viewing a Tailwind UI component, being able to copy the code in framework specific markup, such as JSX?

**Comment by sietzekeuning** [comment]
Ah, it looks like this has been in the works already: https://twitter.com/steveschoger/status/1360340147938689029/photo/1

**Comment by krubenrc** [comment]
In the platform, the previews have alpinejs for show all functionality, but the code tab not have alpinejs, to be agnostic of the javascript framework, but if you works with alpinejs, you may want copy the full preview, including the alpinejs code. I solved this using the inspector from browser and copying the code from the iframe preview, to can keep all functionality of alpinejs.

I would like have the option to copy the code with alpinejs directly from button or have other tab in "previews/code" where is the code with alpinejs.

**Comment by denvit** [comment]
This will be defo a huge lifesaver.

**Comment by davidluhr** [comment]
As noted above, this functionality is coming soon 🎉 https://tailwindui.com/react-and-vue-support/

You can sign up on this page to be notified when it's available.

@krubenrc I've made a note with the team about supporting alpinejs. Our current focus is React and Vue, but this is something we will evolve over time.

Closing this request for now since everything is underway. Thanks everyone!
