### ISSUE TITLE
Master-Detail

### ISSUE THREAD

**Issue by Batsirai** [tailwindlabs/tailwindui-issues#48]
A master-detail panel eg gmail, or ios contacts app... list of items... with a responsive detail view

**Screenshots**
![master-detail-example](https://user-images.githubusercontent.com/4148235/76104201-ef27f200-5fa0-11ea-97a1-add32ab13372.png)

**Additional context**
Add any important details you think we need to know to make sure we build something that matches what you need.

**Comment by DanHarrin** [comment]
If I understand you correctly, this layout could be created with a "narrow list" and a "description list" side by side.

**Comment by Batsirai** [comment]
Yes - but connected & responsive - so that the narrow list and detail panel turn into a list only on mobile with a transition to detail view onClick.

**Comment by DanHarrin** [comment]
Maybe this could be an example layout instead of a new component then?

**Comment by simonswiss** [comment]
Thanks for suggesting this - I have captured it in our ["bag of ideas" in the Trello roadmap](https://trello.com/c/kpPoBT0n/97-master-detail-ui-pattern). 

No concrete plans to do this right now, but you can go upvote it in Trello and if it becomes popular enough, we'll consider building it!
