### ISSUE TITLE
Tailwind UI - List Table 

### ISSUE THREAD

**Issue by javadebian** [tailwindlabs/tailwindui-issues#484]
tailwind ui is great but I think they should have more List Tables components since this is used a lot in information systems thank you for taking this suggestion into account.

**Comment by davidluhr** [comment]
@javadebian Could you please provide some examples (screenshots, links to existing sites, etc.) of the specific pattern you're referring to? I want to make sure I understand the request so we can track this request properly.

Thank you!

**Comment by SoftwareDesign-Solution** [comment]
I would like a grouping in the table 

![group datatable](https://user-images.githubusercontent.com/7149991/107933232-c1a04280-6f7e-11eb-99f6-12b9b929bb69.PNG)

**Comment by davidluhr** [comment]
@SoftwareDesign-Solution Thanks for the follow-up with the example! That is very helpful. I've added this request to our public Tailwind UI roadmap in Trello, where the community can vote for what they'd like to see added:

https://trello.com/c/S5Do0Dnb/144-add-tables-with-grouping-and-sorting
