### ISSUE TITLE
Action is not available at smaller widths

### ISSUE THREAD

**Issue by vangundy** [tailwindlabs/tailwindui-issues#485]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/page-examples/home-screens#component-41dce55c4cd0a0045706dcab2156c2f2
- Component name: With secondary nav and tertiary column

**Describe the bug**
The red "New Post" button has no corresponding equivalent to trigger action at narrower widths.

**To Reproduce**
1. Go to https://tailwindui.com/components/application-ui/page-examples/home-screens#component-41dce55c4cd0a0045706dcab2156c2f2
2. Resize to narrow width.
3. See missing action for "New Post"

**Expected behavior**
I expect that the drop down menu that appears for narrower widths would include an item for "New Post".

**Comment by davidluhr** [comment]
@vangundy Just looping back through older issues. Thank you for your patience on this, and thanks for the feedback! I've added the "New Post" and "Go Premium" CTAs to the mobile menu. The updated version should be live soon.

Thanks for helping us improve things!
