### ISSUE TITLE
Where find sign-in-forms components icons source?

### ISSUE THREAD

**Issue by AxelBriche** [tailwindlabs/tailwindui-issues#486]
https://tailwindui.com/components/application-ui/forms/sign-in-forms

Components svg icons here doesn't have a comment for indicate the source.

Where can I find the same icon for google online please?

**Comment by davidluhr** [comment]
@AxelBriche These icons are not included in an existing icon set. The easiest way to use them would be to inspect the HTML, copy the `<svg>...</svg>` code, and copy/paste it into your code editor as needed. The SVG can be used inline, or could be served as an asset, depending on your particular project.
