### ISSUE TITLE
Review component

### ISSUE THREAD

**Issue by dnsbty** [tailwindlabs/tailwindui-issues#487]
I don't know whether to be putting this here or more in the heroicons issues, but I would love to see a component for reviews. Think product reviews for e-commerce sites or Google Maps and Yelp reviews for businesses.

**Screenshots**
![Italic Stainless Steel Cookware Set Reviews](https://user-images.githubusercontent.com/3421625/107552957-668eda00-6b91-11eb-8614-8c501adffcd3.png)
![Chick-fil-A reviews on Yelp](https://user-images.githubusercontent.com/3421625/107553075-858d6c00-6b91-11eb-9664-dbbff963344c.png)
![Chick-fil-A reviews on Google Maps](https://user-images.githubusercontent.com/3421625/107553117-9807a580-6b91-11eb-9f71-ca79cf941d0c.png)

**Additional context**
I think the main thing that's currently missing from this would be a half-filled star icon. I'm happy to add an issue to the heroicons repo if you'd like. Otherwise I think everything necessary to build my own component is there already.

**Comment by davidluhr** [comment]
@dnsbty Thanks for the suggestion! This has come up before, so I've added a link to this issue in an existing card on our public Tailwind UI roadmap in Trello: https://trello.com/c/Xt8pehsw/105-star-review

Here, the community can vote for what they would like to see added.

We recently included a simple version of a rating element on the new Split with Screenshot Hero Section: https://tailwindui.com/components/marketing/sections/heroes#component-54294e7b86ddf5371565dbdfd133d79c

We will be sure to keep review components with plenty of variations in mind, though!
