### ISSUE TITLE
side-by-side testimonial avatar border breaks with long content

### ISSUE THREAD

**Issue by huphtur** [tailwindlabs/tailwindui-issues#488]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/marketing/sections/testimonials
- Component name: Side-by-side on brand

**Describe the bug**
With long names, titles, and/or company names, the avatar border extends.

**To Reproduce**
1. Go to https://tailwindui.com/components/marketing/sections/testimonials#component-457ad469e750400bb907272fd68b4561
2. Enter a lot of content next to the avatars
3. Decrease viewport

**Expected behavior**
white outline should stay around avatar no matter the height of the text next to it

**Screenshots**
![testimonial-sidebyside-bug](https://user-images.githubusercontent.com/469438/107593685-c357b800-6bc4-11eb-85ff-0c26ad22e63d.jpg)

**Browser/Device (if applicable)**
- all

**Comment by davidluhr** [comment]
@huphtur Thanks for reporting this! I've added `items-start` to the flex container, which allows the avatar and border to stay intact as the text to the side grows as needed. The fixed version should be live on the site soon.
