### ISSUE TITLE
Horizontal Overflow on Marketing Landing Page Example

### ISSUE THREAD

**Issue by SmashBrando** [tailwindlabs/tailwindui-issues#489]
Component: https://tailwindui.com/components/marketing/page-examples/landing-pages#component-6b663161ec9333a3e026306b01ae45f8

**Describe the bug**

The offset image in the "Stay on top of customer support" section causes horizontal overflow on the mobile version of the UI.

**To Reproduce**

- Go to https://tailwindui.com/components/marketing/page-examples/landing-pages#component-6b663161ec9333a3e026306b01ae45f8
- Minimize viewport width.
- Scroll right.

**Expected behavior**
Horizontal scroll should not be present.

**Comment by davidluhr** [comment]
@SmashBrando Thanks for reporting this! A week or two ago I fixed this in the Feature Section that gets used in this Landing Page, but forgot to fix it here. The fixed version should be live on the site soon.
