### ISSUE TITLE
Data-Tables: Extra-wide tables with filtering, sorting column selection

### ISSUE THREAD

**Issue by amalytix** [tailwindlabs/tailwindui-issues#49]
For data heavy applications it would be nice to have a set of components (filter section, column selector, tables with sortable columns, pagination) which allow to sort and filter data-heavy tables.

It should be possible to do the following:

- Users can quickly search without creating complex filters
- Users can sort
- Users can hide/show columns
- Users can click on icons in each row (actions)
- Tables rows can be "opened up" and show additional information
- Users can paginate

Real-world example:
<img width="1665" alt="grafik" src="https://user-images.githubusercontent.com/52069605/76104240-4b0b6e80-5fd3-11ea-8004-fc8ebdfe385b.png">

Relevant links:
https://medium.com/design-with-figma/the-ultimate-guide-to-designing-data-tables-7db29713a85a

**Comment by tanthammar** [comment]
Suggest to rename this topic to Data Table, it'll probably get more votes ...

**Comment by simonswiss** [comment]
Captured this suggestion in our bag of ideas to consider in the Trello roadmap: https://trello.com/c/Cx4cB0H8/78-sortable-data-tables

Thank you for suggesting! 👍
