### ISSUE TITLE
Update Year in copyright texts

### ISSUE THREAD

**Issue by henrikbjorn** [tailwindlabs/tailwindui-issues#490]
**What component (if applicable)**
- URL for category: 
- Component name: 
https://tailwindui.com/components/marketing/page-examples/landing-pages

**Describe the bug**
Some templates have "Copyright 2020" should propably be "Copyright 2021"

**To Reproduce**
1. Go to '.https://tailwindui.com/components/marketing/page-examples/landing-pages#component-c574f863382921bf9af9611c55f30ecc'
2. Scroll down to 'footer of template'
3. See error

**Comment by davidluhr** [comment]
@henrikbjorn I'll make note of this. This is simply example copy (that we wrote when the components were originally created), and not our official copyright, but I appreciate you letting us know!
