### ISSUE TITLE
Mobile menu container is not hidden for md breakpoint, causing UI to be unresponsive above md breakpoint

### ISSUE THREAD

**Issue by jseaborn4d** [tailwindlabs/tailwindui-issues#492]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/application-shells/multi-column#component-6e22fa5715141e2f842a9c887bcfb7a3
- Component name: `Full-width with narrow sidebar`

**Describe the bug**
When using the code provided by the component, the UI is unresponsive in viewports wider than the `md` breakpoint.

By unresponsive I mean browser events like hover and inability to enter the search field.

Looking at the code, there is a container div for the mobile menu on line 128 that does not have a breakpoint variant to hide above the `md` breakpoint.

```html
<!-- Mobile menu, show/hide this `div` based on menu open/closed state -->
    <div class="fixed inset-0 z-40">
        ...
    </div>
```

Adding a utility class to hide this div above breakpoint `md` resolves this issue:

```html
<!-- Mobile menu, show/hide this `div` based on menu open/closed state -->
    <div class="fixed inset-0 z-40 md:hidden">
        ...
    </div>
```

**To Reproduce**
Deploy the code in react app and rendering in macOS browsers including:
- Safari 14.0 (15610.1.28.1.9, 15610)
- Chrome  (87.0.4280.141)

**Expected behavior**
The component UI should not be unresponsive at size classes > `md`.

**Screenshots**
Resolution to the bug provided in report.

**Browser/Device (if applicable)**
 - OS: macOS 10.15.7 (19H2)
 - Browser
   - Safari 14.0 (15610.1.28.1.9, 15610)
   - Chrome  (87.0.4280.141)

**Additional context**
Resolution to the bug provided in report.

**Comment by davidluhr** [comment]
@jseaborn4d Good catch. That element is intended to be conditionally rendered only when the menu is open, but if the user opens the menu and then increases the viewport, that overlay indeed interferes with the other UI.

I've added the `md:hidden` per your suggestion, and the fix should be live on the website shortly.

Thanks for reporting this!
