### ISSUE TITLE
Weird shadow in pagination

### ISSUE THREAD

**Issue by davidmles** [tailwindlabs/tailwindui-issues#494]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/navigation/pagination
- Component name: Pagination (Card footer with page buttons)

**Describe the bug**
There's a weird squared shadow in the lower right corner, as seen in the attached screenshot.

**To Reproduce**
Just go to the URL above and zoom in the lower right corner of the sample pagination.

**Expected behavior**
The shadow should adapt to the form of the button.

**Screenshots**
<img width="251" alt="Screenshot 2021-02-12 at 19 14 12" src="https://user-images.githubusercontent.com/1402642/107806327-005bb000-6d67-11eb-887e-2fd89b51509a.png">

**Browser/Device (if applicable)**
 - OS: macOS
 - Browser: Chrome, Safari
 - Version: Latest

**Comment by davidluhr** [comment]
@davidmles Thank you for reporting this! The fixed version should appear on the site shortly.
