### ISSUE TITLE
Vue <transition> documents have invalid props

### ISSUE THREAD

**Issue by dustinboss** [tailwindlabs/tailwindui-issues#495]
**What component (if applicable)**
- URL for category: https://tailwindui.com/documentation#js-vue
- Component name: Docs - Vue Enter/Leave Transitions

**Describe the bug**
The current transition example looks like this:
```
<transition
      enter-active-class="transition ease-out duration-100 transform"
      enter-from-class="opacity-0 scale-95"
      enter-to-class="opacity-100 scale-100"
      leave-active-class="transition ease-in duration-75 transform"
      leave-from-class="opacity-100 scale-100"
      leave-to-class="opacity-0 scale-95"
    >
```
but the `enter-from-class` should actually be `enter-class` and the `leave-from-class` should be `leave-class`. So the new code should look like this: 

```
<transition
      enter-active-class="transition ease-out duration-100 transform"
      enter-class="opacity-0 scale-95"
      enter-to-class="opacity-100 scale-100"
      leave-active-class="transition ease-in duration-75 transform"
      leave-class="opacity-100 scale-100"
      leave-to-class="opacity-0 scale-95"
    >
```

Here are the supported Vue classes from Vue's docs: https://vuejs.org/v2/guide/transitions.html#Custom-Transition-Classes

**Comment by adamwathan** [comment]
Hey! It actually is enter-from and leave-from now:

https://v3.vuejs.org/guide/migration/transition.html#_3-x-update

We can update the docs to include both Vue 2 and Vue 3 though I suppose since Vue 2 is still very widely used.

**Comment by dustinboss** [comment]
Ah, my mistake! I didn't think to check Vue 3. Thanks!

**Comment by davidluhr** [comment]
@dustinboss I've added the equivalent Vue 2 `<transition>` code in code comments above the existing Vue 3 examples. These should appear on the site shortly. Thanks for the suggestion!
