### ISSUE TITLE
Missing space in class for inline actions

### ISSUE THREAD

**Issue by edhollinghurst** [tailwindlabs/tailwindui-issues#496]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/data-display/description-lists
- Component name: Left-aligned with inline actions

**Describe the bug**
Looks like missing space with use of class `ml-4flex-shrink-0`

**Comment by adamwathan** [comment]
Ah thanks for catching this 🤦  Fix will be live in a minute or two!
