### ISSUE TITLE
Please close Tags for example <img> should be closed like <img />

### ISSUE THREAD

**Issue by kivi** [tailwindlabs/tailwindui-issues#497]
**What component (if applicable)**
- URL for category: Heros for example.
- Component name: Example: https://tailwindui.com/components/marketing/sections/heroes, but all components having <img>-Tag

**Describe the bug**
<img>- Tag should be closed.

Example:
`<img class="h-8 w-auto sm:h-10" src="https://tailwindui.com/img/logos/workflow-mark-indigo-600.svg" alt="">`

Should be:             
`<img class="h-8 w-auto sm:h-10" src="https://tailwindui.com/img/logos/workflow-mark-indigo-600.svg" alt="" />`

**To Reproduce**
1. Go to a component containing <img>-Tag
2. Copy the code
3. Paste it in your React code as component 
4. Error is, React or better JSX needs that all Tags are closed.

**Expected behavior**
Pasted code should be more JSX compatible.

**Comment by adamwathan** [comment]
Hey! It's totally valid (and generally encouraged) to not close self closing tags in HTML5. Unfortunately it's impossible to make something work as both HTML and as JSX, for example "for" has to be "labelFor" in JSX which won't work in HTML.

We are working on support for copying JSX directly, hoping to have it available in March 👍

In the mean time I would recommend a tool like this:

https://transform.tools/html-to-jsx
