### ISSUE TITLE
Searchable Select Box

### ISSUE THREAD

**Issue by lloydowen** [tailwindlabs/tailwindui-issues#498]
It would be great if we could get a searchable dropdown/select component. 

Something similar to this:
https://tailwindcomponents.com/component/dropdown-with-search-box
https://dribbble.com/shots/12246033-Dropdowns

**Comment by davidluhr** [comment]
@lloydowen Thanks for the suggestion. This request has come up before, so I've added a link to this issue in an existing card in our public Tailwind UI roadmap in Trello, where the community can vote for what they'd like to see added:

https://trello.com/c/d3AHy86O/115-combobox-dropdown-search-filter-functionality
