### ISSUE TITLE
feature request: chat/conversation

### ISSUE THREAD

**Issue by jbergstroem** [tailwindlabs/tailwindui-issues#499]
Team license holder here! I'd love to see components for holding a chat/conversation. Speech bubbles, profile images, status changes and the like. Think Messages, Facebook messenger, WhatsApp and so on. A finished UI (including a chat context) could perhaps resemble what [Messagebird is up to](https://www.messagebird.com/en/inbox/).

**Comment by davidluhr** [comment]
@jbergstroem Thanks for the suggestion! A similar idea has come up before, so I've added a link to this issue to an existing card in our public Tailwind UI roadmap in Trello. This is where the community can vote for what they'd like to see added:

https://trello.com/c/C5jxPQZx/112-page-examples-chat-interface
