### ISSUE TITLE
Unlock Slider

### ISSUE THREAD

**Issue by lh-s-net** [tailwindlabs/tailwindui-issues#501]
Hello,
I need a 'unlock'-slider how https://codepen.io/SebastienP/pen/tKHnp with variable text (ex. "slide to unlock", "start alert", etc.).

**Comment by davidluhr** [comment]
@lh-s-net Thanks for the suggestion! I've added this to an existing request for range sliders that we have in our public Tailwind UI roadmap in Trello. This is where the community can vote for what they'd like to see added:

https://trello.com/c/qYooawle/68-range-sliders
