### ISSUE TITLE
Tags Input 

### ISSUE THREAD

**Issue by zbaloch** [tailwindlabs/tailwindui-issues#502]
Hi there,

I have been looking for an example tags input similar to GitHub topic tags but cant find it. Request you to add one similar to this.

<img width="454" alt="image" src="https://user-images.githubusercontent.com/8920243/108106756-6ca81d80-709f-11eb-9294-2890b778e771.png">

Regards,
Zaheer

**Additional context**
I am working on listing website where I would like the users to filter items by typing in categories. The number of tags to choose from can be thousands. 

[My website where I need this. Under development](https://githunt.dev)

**Comment by davidluhr** [comment]
@zbaloch Thanks for the suggestion! I've added this to our public Tailwind UI roadmap in Trello, where the community can vote for what they'd like to see added:

https://trello.com/c/ecLhidpB/143-pill-list-with-input

I included some additional context, such as this related example from WAI-ARIA that demonstrates the functionality of this "pill list" pattern: https://www.w3.org/TR/wai-aria-practices/examples/grid/LayoutGrids.html#ex2_label

Thanks again!

**Comment by zbaloch** [comment]
@davidluhr - Thank you so much for adding this on the roadmap. Much appreciated.
