### ISSUE TITLE
Add a fullscreen option for all component preview

### ISSUE THREAD

**Issue by AxelBriche** [tailwindlabs/tailwindui-issues#503]
Can you please add a fullscreen option for all component preview?

**Comment by davidluhr** [comment]
@AxelBriche Thanks for the suggestion! I've added this to our public Tailwind UI roadmap in Trello, where the community can vote for what they'd like to see added:

https://trello.com/c/ahNgNh87/142-add-fullscreen-option-for-component-previews

A workaround you could use in the meantime is copying/pasting a component's code into a Tailwind Play session: https://play.tailwindcss.com/

At the top, there is a dedicated button for a fullscreen preview.
