### ISSUE TITLE
input field with a clear button inside

### ISSUE THREAD

**Issue by lordisp** [tailwindlabs/tailwindui-issues#504]
like this... 
https://stackoverflow.com/questions/2803532/how-do-i-put-a-clear-button-inside-my-html-text-input-box-like-the-iphone-does

**Comment by davidluhr** [comment]
@lordisp I've added this request to our public Tailwind UI roadmap in Trello, where the community can vote for what they'd like to see added:

https://trello.com/c/05yKNdgG/141-form-input-with-clear-button

In the meantime, you could explore customizing the Input with Trailing Icon component for your use case: https://tailwindui.com/components/application-ui/forms/input-groups#component-474bd025b849b44eb3c46df09a496b7a

For example, something like:
```html
<!--
  This example requires Tailwind CSS v2.0+ 
  
  This example requires some changes to your config:
  
  ```
  // tailwind.config.js
  module.exports = {
    // ...
    plugins: [
      // ...
      require('@tailwindcss/forms'),
    ]
  }
  ```
-->
<div>
  <label for="account_number" class="block text-sm font-medium text-gray-700">Account number</label>
  <div class="mt-1 relative rounded-md shadow-sm">
    <input type="text" name="account_number" id="account_number" class="focus:ring-indigo-500 focus:border-indigo-500 block w-full pr-10 sm:text-sm border-gray-300 rounded-md" placeholder="000-00-0000">
    <button class="absolute inset-y-0 right-0 pr-3 flex items-center" type="button">
      <!-- Heroicon name: solid/x-circle -->
      <svg class="h-5 w-5 text-gray-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
        <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zM8.707 7.293a1 1 0 00-1.414 1.414L8.586 10l-1.293 1.293a1 1 0 101.414 1.414L10 11.414l1.293 1.293a1 1 0 001.414-1.414L11.414 10l1.293-1.293a1 1 0 00-1.414-1.414L10 8.586 8.707 7.293z" clip-rule="evenodd" />
      </svg>
    </button>
  </div>
</div>
```

This would allow you to add a button that you can attach an event listener to to clear the input's current value. Here, I've also added the solid "x-circle" Heroicon to better match the look you're going for. With some hover/focus styles, you'd be all set!
