### ISSUE TITLE
Circular avatars with building placeholder icon with other svg options

### ISSUE THREAD

**Issue by rvoorneveld** [tailwindlabs/tailwindui-issues#505]
**Screenshots**
![image](https://user-images.githubusercontent.com/6113682/108257177-b73c9f00-715e-11eb-830c-21a9ca3eb177.png)
![image](https://user-images.githubusercontent.com/6113682/108257341-eeab4b80-715e-11eb-8a0f-cf6271be5a67.png)

**Additional context**
It would be great to have multiple avatar svg options. For example a company avatar placeholder.

**Comment by davidluhr** [comment]
@rvoorneveld Thanks for the request! I've added this to our public Tailwind UI roadmap in Trello, where the community can vote for what they'd like to see added:

https://trello.com/c/Yh6p5BTU/140-add-avatar-with-placeholder-icon-options
