### ISSUE TITLE
With Fading Backgroun Image stats component

### ISSUE THREAD

**Issue by damienbuckley** [tailwindlabs/tailwindui-issues#506]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/marketing/sections/stats-sections
- Component name: With Fading Backgroun Image 

**Describe the bug**
Below 1260px wide the image drops into the bottom left corner

**To Reproduce**

**Expected behavior**
Not this

**Screenshots**
<img width="1410" alt="Screen Shot 2021-02-19 at 3 12 28 pm" src="https://user-images.githubusercontent.com/728153/108460893-4e236b80-72c5-11eb-8fa0-30abe68688a7.png">

**Browser/Device (if applicable)**
 - OS: OSX
 - Browser Safari, Firefox

**Additional context**

**Comment by davidluhr** [comment]
@damienbuckley Good catch! This is fixed and should be live on the site soon. Thank you!
