### ISSUE TITLE
Need color changer

### ISSUE THREAD

**Issue by tousif786** [tailwindlabs/tailwindui-issues#507]
Being a paid user I feel like the most important thing is missing that is a color changer.

It would be good if you have something like a theme builder where we can drag and drop components and create a whole page with colors.

It is very difficult to use this component as I have to change lots of colors to match my theme.

Not to be offense, with the price you are charging does not do justice. TailwinUI is very similar to this site https://tailblocks.cc/ and it's free. They have a color changer. You should add something beyond block like I said, theme builder.

**Comment by adamwathan** [comment]
Hey! Support for multiple color palettes is on the roadmap 👍🏻 There will always be some expectation that you have to tweak things if you don't want things to look "off-the-shelf" though — Tailwind UI is meant to give you a great starting point to customize and make your own.

**Comment by tousif786** [comment]
Thanks for your quick response. Great to hear it color palettes is on the way. What about theme builder or page builder by drag and drop components?

**Comment by adamwathan** [comment]
We haven't ruled out working on a page builder one day but I am pessimistic that it could actually be useful, especially once we have added JavaScript support. It's something we will likely experiment but my gut feeling is that pasting things into your text editor to build pages is always going to feel more productive. Maybe a builder can work for marketing pages where you are just stacking blocks on top of each other, but for anything more complex than that you'd have to recreate Webflow and I think right now we are more interested in building tools for people who like working with code.

**Comment by tousif786** [comment]
Actually, you are right. Once we have the color pallets feature it will be very easy to create your own page with our own matching colors. Thanks, Adam.
