### ISSUE TITLE
navigation dropdown

### ISSUE THREAD

**Issue by Manubi** [tailwindlabs/tailwindui-issues#508]
Hey,

I would like to see a simple dropdown for further links in a nav.
![CleanShot 2021-02-22 at 12 51 36](https://user-images.githubusercontent.com/20935138/108704785-c9c32980-750c-11eb-8592-14931a803889.png)
Thanks for your work!
cheers
Manuel

**Comment by ordago** [comment]
It already exist:

https://tailwindui.com/components/application-ui/navigation/sidebar-navigation#component-ea27fcb96a81748146d26ffa281c3f6d

**Comment by Manubi** [comment]
Thanks! It’s difficult to get the difference between **sidebar layouts** and **sidebar navigation**.
