### ISSUE TITLE
Dropdown gets cut off inside cards / tables

### ISSUE THREAD

**Issue by ordago** [tailwindlabs/tailwindui-issues#511]
**What component (if applicable)**
- [Dropdowns ](https://tailwindui.com/components/application-ui/elements/dropdowns)
- [Tables](https://tailwindui.com/components/application-ui/lists/tables)
- [Card Headings](https://tailwindui.com/components/application-ui/headings/card-headings)

**Describe the bug**
The overflow-hidden makes it so dropdowns would get cut off when inside cards or tables.

**To Reproduce**
1. Go to Dropdowns and get the markup for a dropdown that's long enough (e.g. With Icon)
2. Go to Card Headings, inspect with devtools and paste inside

**Expected behavior**
The dropdown should float on top

**Screenshots**

![chrome_TkWnkCmQVN](https://user-images.githubusercontent.com/6376814/109003778-c2805500-769f-11eb-8eb7-b2d98ebc7089.png)

**Browser/Device (if applicable)**
 - OS: Windows
 - Browser: chrome
 - Version 88

**Additional context**

**Comment by ep-01** [comment]
Hi ordago, I'm having the same issue, did you find a solution?

**Comment by ordago** [comment]
@ep-01 Thanks a lot. I searched before but somehow missed it.
