### ISSUE TITLE
Search and description on tailwindui.com

### ISSUE THREAD

**Issue by Manubi** [tailwindlabs/tailwindui-issues#512]
Hi,

I'd love to see a similar search as on tailwindcss.com where I can search eg for _nav header sticky_ or _sidebar_ 
As I didn't know that there is a _sidebar navigation_ and a _sidebar layout_ with different stylings it would help to get rid of such "errors".

Thanks!

**Comment by davidluhr** [comment]
@Manubi This isn't explained in the UI of the website, but the same search functionality actually exists on TailwindUI.com, and can be triggered with `Cmd + K` (Mac), `Ctrl + K` (Windows), or `/` (both).

I'll make note of this so we can make this more discoverable. Thanks for the feedback!
