### ISSUE TITLE
Help Tooltip

### ISSUE THREAD

**Issue by peterfox** [tailwindlabs/tailwindui-issues#513]
It would be quite useful to have a help/information tooltip design, something like the dropdown buttons premade in the kit. Maybe even one provided in a form control layout as it's a common pattern to have to provide additional information about a field for a user.

**Screenshots**
No Screenshots, but currently I'm just using a modal instead.

**Additional context**
Different examples of how to lay it out e.g. below, to the right etc. examples of transitions.

**Comment by davidluhr** [comment]
@peterfox Thanks for the request! I've added a link to this issue to an existing card in our public Tailwind UI roadmap in Trello, where the community can vote for what they'd like to see added:

https://trello.com/c/KVOX3uCK/56-tooltips-popups

**Comment by peterfox** [comment]
@davidluhr thank you
