### ISSUE TITLE
toggle component not marked as 'required js'

### ISSUE THREAD

**Issue by sairam** [tailwindlabs/tailwindui-issues#514]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/forms/toggles
- Component name: Toggle

**Describe the bug**
Does not work without js

**Expected behavior**
Not marked as 'required js' in the component UI

**Comment by davidluhr** [comment]
@sairam Thanks for reporting this! I believe this is due to an internal change that we should be able to resolve soon. I'll keep you updated when we have this corrected.

**Comment by davidluhr** [comment]
@sairam Alright, we've fixed this and Toggles now display the "Requires JS" badge as expected. Thanks again for letting us know!
