### ISSUE TITLE
Sticky list headers overlaps instead of pushing them

### ISSUE THREAD

**Issue by sukei** [tailwindlabs/tailwindui-issues#515]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/page-examples/detail-screens
- Component name: Multi-column directory

**Describe the bug (improvement in fact)**
The sticky behavior of the directory list can be improved when scrolling by allowing headers (A, B, C, etc.) to push them out of the screen instead of overlapping

**To Reproduce**
1. Scroll down the directory list
2. The letters (A, B, C, etc.) overlaps instead of pushing them out of the screen

**Expected behavior**
The next letter in the list should push the previous one while scrolling

**Screenshots**

**actual**
<img width="397" alt="overlap" src="https://user-images.githubusercontent.com/890645/109628446-0b725680-7b43-11eb-955c-eaef07f6cefb.png">

**expected**
<img width="403" alt="push" src="https://user-images.githubusercontent.com/890645/109628451-0ca38380-7b43-11eb-8392-484d8fd2e488.png">

**Additional context**
This can be easily achieved by wrapping each section with a div:

```html
<div><!-- added wrapper -->
  <div class="z-10 sticky top-0 border-t border-b border-gray-200 bg-gray-50 px-6 py-1 text-sm font-medium text-gray-500">
    <h3>C</h3>
  </div>
  <ul class="relative z-0 divide-y divide-gray-200">...</ul>
</div>
<div>...</div>
```

**Comment by davidluhr** [comment]
@sukei Thanks for the feedback. While either approach is a valid design choice, I brought this up with the team and we preferred your proposed treatment. I've updated the Detail Screen and the corresponding Stacked List to have sticky headings that push the previous heading away. These updates should be live on the site soon.

Thanks again!
