### ISSUE TITLE
Select menu with search option

### ISSUE THREAD

**Issue by TomSpitters** [tailwindlabs/tailwindui-issues#517]
**Screenshots**
To get an idea, visit this page: https://mdbootstrap.com/snippets/jquery/mdbootstrap/921549

**Additional context**
We would love to use a 'Select menu with a search option'. Can you provide this? It is realy helpfull with long lists of users.
https://tailwindui.com/components/application-ui/forms/select-menus

**Comment by davidluhr** [comment]
@TomSpitters Thanks for the suggestion. I've added a link to this issue to an existing card in our public Tailwind UI roadmap in Trello, where the community can vote for what they'd like to see added:

https://trello.com/c/d3AHy86O/115-combobox-listbox-dropdown-search-filter-functionality
