### ISSUE TITLE
Datepicker

### ISSUE THREAD

**Issue by TomSpitters** [tailwindlabs/tailwindui-issues#518]
**Screenshots**
![image](https://user-images.githubusercontent.com/14174597/110140404-56ef6380-7dd4-11eb-81da-1c32e48c3fd6.png)

**Additional context**
Can you provide us with a datepicker like: whttps://bootstrap-datepicker.readthedocs.io/en/latest/

**Comment by davidluhr** [comment]
@TomSpitters Thanks for the suggestion! This is one of our most popular requests. I've added a link to this issue to an existing card in our public Tailwind UI roadmap in Trello. This is where the community can vote for what they'd like to see added:

https://trello.com/c/jVnND6De/47-date-picker
