### ISSUE TITLE
Blog Sections Need Closing Tags for `img`

### ISSUE THREAD

**Issue by calendee** [tailwindlabs/tailwindui-issues#519]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/marketing/sections/blog-sections#component-dd3c64601fdbfd25f15758f61828ae01
- Component name: 3-column with badges

**Describe the bug**
When pasting this code into any JSX component with linting, it will show an error because the image tags are not self closed.

Example: 
```
<img class="h-10 w-10 rounded-full" src="https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?ixlib=rb-1.2.1&ixqx=pqVIDUxojI&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80" alt="">
```

**To Reproduce**
1. Create any React project using JSX and linting
2. Copy sample code from Tailwind UI
3. Paste code into JSX.
4. See error `Expected corresponding JSX closing tag for 'img'.ts(17002)`

**Expected behavior**
No errors should occur when pasting copied code into project.

**Screenshots**
<img width="1681" alt="tailwind-ui-unclosed-image-tags" src="https://user-images.githubusercontent.com/57374/110387889-e5a7ee80-8027-11eb-9cc8-27e37dda5119.png">

**Browser/Device (if applicable)**
 - N/A

**Additional context**
N/A

**Comment by davidluhr** [comment]
@calendee In HTML 5, self closing tags do not require the `/>` to self close, and this is the preferred convention.

Please note that we have official React and Vue support coming soon, which will allow you to copy JSX directly and will have the expected self-closing syntax for JSX. You can sign up to be notified when it's ready at this page: https://tailwindui.com/react-and-vue-support/
