### ISSUE TITLE
Missing space between classes of active item in a sidebar navigation component

### ISSUE THREAD

**Issue by bvalentino** [tailwindlabs/tailwindui-issues#520]
**What component**
- URL for category: https://tailwindui.com/components/application-ui/navigation/sidebar-navigation
- Component name: Simple with icons and badges

**Describe the bug**
The active item has the class `font-mediumrounded-md` and it should be `font-medium rounded-md`.

**To Reproduce**
1. Go to [https://tailwindui.com/components/application-ui/navigation/sidebar-navigation#component-d00114b9aebe18b49eeac9ab76005e07](https://tailwindui.com/components/application-ui/navigation/sidebar-navigation#component-d00114b9aebe18b49eeac9ab76005e07)
2. Note how the active item has a different font weight and is not rounded.

The preview and the code view have the same issue.
The rest of the components in that category are OK.

**Expected behavior**
The active item to have the class `font-medium rounded-md`.

**Screenshots**
<img width="1532" alt="Screen Shot 2021-03-09 at 4 05 46 PM" src="https://user-images.githubusercontent.com/1046184/110538711-561b4200-80f2-11eb-949a-47a468e74183.png">

**Comment by davidluhr** [comment]
@bvalentino Good catch! I've fixed this issue and the corrected version should be live on the site shortly.

Thanks for letting us know!
