### ISSUE TITLE
Consider adding JSX to TailwindUI Component

### ISSUE THREAD

**Issue by khalil1709** [tailwindlabs/tailwindui-issues#523]
TailwindUI Components are available just in HTML, and they are hard to use with react.
Changing the HTML Code to JSX can be really annoying and it can take a lot of time when you are working with a big component.
It will be actually very practical to be able to choose the language of the code.

Thanks

**Comment by adamwathan** [comment]
Totally agree and we're releasing this early next month!

https://tailwindui.com/react-and-vue-support/

**Comment by khalil1709** [comment]
I would like to help. I am working on a Project with react and if it is possible, I can help with "early testing" 
Note: I already have full access to TailwindUI
