### ISSUE TITLE
Tags input selector with typeahead dropdown

### ISSUE THREAD

**Issue by ds-perfit** [tailwindlabs/tailwindui-issues#524]
This is the idea:
**Screenshots**
![image](https://user-images.githubusercontent.com/10169287/110854686-15f3c500-8294-11eb-8e7c-90affb18cda0.png)

**Additional context**

**Comment by davidluhr** [comment]
@ds-perfit Thanks for the suggestion! This idea has come up before, so I've added a link to this issue to a card in our public Tailwind UI roadmap. This lives in Trello, where the community can vote for what they'd like to see added:

https://trello.com/c/ecLhidpB/143-pill-list-with-input
