### ISSUE TITLE
e-commerce components

### ISSUE THREAD

**Issue by georgedalai** [tailwindlabs/tailwindui-issues#525]
Hey there, it would be wonderful if you could add some e-commerce components as well. 

This is an example of a design system I have found online https://ecommerce-uikit.com/components.html

I think that it could work as a component guide for your design team.

**Comment by davidluhr** [comment]
@georgedalai Thanks for suggesting this! This request has come up before, so I've added a link to this issue to an existing card in our Tailwind UI public roadmap in Trello. This is where the community can vote for what they'd like to see added:

https://trello.com/c/JXSeuzwO/113-ecommerce-category-and-components
