### ISSUE TITLE
I would be super rad if there was a TWind component that combined the Centered Accordion with 'List with Description' radial group

### ISSUE THREAD

**Issue by brent-palmer** [tailwindlabs/tailwindui-issues#526]
**Screenshots**
Provide a screenshot of your existing solution or of examples you've seen elsewhere that you think would be helpful inspiration.

**Additional context**
Add any important details you think we need to know to make sure we build something that matches what you need.

**Comment by davidluhr** [comment]
@brent-palmer Can you please provide more information about this?

An accordion and a radio group have different functionality that can't be combined. Are you referring to having a radio group with the heading/layout treatment seen in the Centered Accordion?

**Comment by davidluhr** [comment]
@brent-palmer Closing this issue for now, but feel free to respond if you have further information. Thank you!
