### ISSUE TITLE
Long titles cut off

### ISSUE THREAD

**Issue by than** [tailwindlabs/tailwindui-issues#527]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/marketing/sections/content-sections#component-39249d619dcd4a64f3089bf550369572
- Component name: Two columns with image

**Describe the bug**
Long titles cut off by the absolutely positioned gray box on Two columns with image. See the word common cut off here.
![](https://than.d.pr/PaYy6s.png)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Browser/Device (if applicable)**

**Additional context**

**Comment by davidluhr** [comment]
@than Thanks for reporting this! I've adjusted the layout so the headings will wrap with the same width as the article text. Now, headings of any length should work.

If you would like to update your own code, here's the change.

Before:
```html
<div class="mx-auto text-base max-w-prose lg:max-w-none">
    <h2 class="text-base text-indigo-600 font-semibold tracking-wide uppercase">Case Study</h2>
    <h3 class="mt-2 text-3xl leading-8 font-extrabold tracking-tight text-gray-900 sm:text-4xl">Meet Whitney</h3>
</div>
```

After:
```html
<div class="mx-auto text-base max-w-prose lg:grid lg:grid-cols-2 lg:gap-8 lg:max-w-none">
  <div>
    <h2 class="text-base text-indigo-600 font-semibold tracking-wide uppercase">Case Study</h2>
    <h3 class="mt-2 text-3xl leading-8 font-extrabold tracking-tight text-gray-900 sm:text-4xl">Meet Whitney</h3>
  </div>
</div>
```

The fixed version will be live on the site shortly. Thanks again!
