### ISSUE TITLE
text-ls in multi-column inbox

### ISSUE THREAD

**Issue by seb-jean** [tailwindlabs/tailwindui-issues#530]
Hi,

There is an class text-ls on https://tailwindui.com/components/application-ui/page-examples/detail-screens#component-9a82234fc5cbca3875409b92effa3779

![Capture](https://user-images.githubusercontent.com/12116264/111635071-68cefe80-87f7-11eb-96bf-f5f7ea33f087.PNG)

**Comment by davidluhr** [comment]
@seb-jean Good catch! The fixed version should be live on the site shortly. Thanks for letting us know!
