### ISSUE TITLE
Chat Component

### ISSUE THREAD

**Issue by phwegner** [tailwindlabs/tailwindui-issues#531]
Do you consider adding a chat component to the ui components ?

**Comment by davidluhr** [comment]
@phwegner Thanks for suggesting this! This request has come up before, so I've added a link to this issue to an existing card in our Tailwind UI public roadmap in Trello. This is where the community can vote for what they'd like to see added:

https://trello.com/c/C5jxPQZx/112-chat-components-and-page-examples

**Comment by phwegner** [comment]
@davidluhr Okay thank you !
