### ISSUE TITLE
"Color Themed" Templates

### ISSUE THREAD

**Issue by KevinAst** [tailwindlabs/tailwindui-issues#532]
**Proposal**

I have a proposal for your consideration:

> For each of your template categories, I would suggest you offer an additional "color themed" solution that employs abstract [context colors] _(e.g. primary, secondary, etc.).

- This would be in addition to the hard-coded color samples you already provide.

- You would need to devise and promote the [context colors] used in your templates.  As an example _(this is just a sample - you would need to devise and promote this to your choosing)_:

  ```
  primaryLight
  primary
  primaryDark

  secondaryLight
  secondary
  secondaryDark

  onLight       ... typically black
  onDark        ... typically white

  accentBorder  ... typically a gray tone (e.g. 'coolGray-600')
                    used for borders in SideBar/NavBar/Menu/Dialog/etc.

  backdrop      ... universal background 
  ```

- With this addition, Tailwind UI users that employ "themed colors" could simply drop in your new themed templates.
  
- Your run-time catalog would add a simple UI Control that selects various color themes, allowing the colors to dynamically change on-the-fly.  This would **show off** your new "color themed" templates **extremely well**!

**Additional context**

I have recently published a tailwind utility called [tw-themes] that promotes tailwind color themes that are dynamically selectable at run-time.

The **best part** of this utility is it **automates [dark mode] through [shade inversion]!**

- you can find the docs here: https://tw-themes.js.org/
- and see a live demo here: https://tw-themes.js.org/seeItLive.html

While you may choose to use this utility to drive the color selection of your "color theme" templates, it would in no way tie you _(or your customers)_ to this utility.

- The output of the additional "color themed" templates would merely the abstract [context colors] _used in your html_.

- Your customers would be free to use the solution of their choosing to drive the run-time process.

Your consideration is greatly appreciated.

Thoughts?

[tw-themes]:       https://tw-themes.js.org/
[context colors]:  https://tw-themes.js.org/concepts/contextColors.html
[dark mode]:       https://tw-themes.js.org/concepts/darkMode.html
[shade inversion]: https://tw-themes.js.org/concepts/shadeInversion.html

**Comment by davidluhr** [comment]
@KevinAst Thanks for your suggestion. The intention behind Tailwind CSS and Tailwind UI is to offer utility classes that provide direct control over styling in markup.

The use of semantic/context classes isn't feasible with Tailwind UI due to limitations in naming convention and the abstraction they create for our users. Additionally, techniques like shade inversion can be problematic for accessibility, as color scales aren't necessarily perceptually consistent across shades, which means that generated dark modes might not have sufficient contrast. It's also important to consider that inversion techniques can interfere with visual layering. Elements with a higher z-index should be lighter than background elements in both light and dark themes, but with shade inversion, the lightest backgrounds become the darkest.

In Tailwind UI, users can find/replace color classes to quickly re-theme them for their own use, or add custom color classes to their Tailwind configuration, which is our current approach to allowing for theming. This also allows users to customize anything by quickly/directly changing class in the markup, in the spirit of Tailwind CSS.

I'm not saying this to discourage your individual efforts on the project, but I don't feel this approach is well suited for Tailwind UI to use for the reasons stated above.

Thanks for your understanding.

**Comment by KevinAst** [comment]
Hello @davidluhr,

Thanks for your thoughtful response.

Just to be clear, I was not suggesting that you tap into my utility.

I understand what you are saying regarding name-space limitations in promoting additional semantic/context colors.  However, I was not suggesting you promote a full solution to this.  Your deliverable would be two specific artifacts:

1. A set of abstract context colors consistently used throughout your new "color themed" templates (e.g. primaryLight, secondary, etc.).

2. A documented set of color themes, that define a number of color themes that map real colors to these context colors.

Both of these deliverables would be "expertly designed" by you (i.e. the design experts).  They would take into consideration all of the idiosyncrasies that you mentioned here (i.e. accessibility, etc.).

If you think about it, you are already providing some limited samples of varying color schemes, using hard-coded tailwind colors.  These new "themed colors" would merely extend that to an "expertly designed" abstraction promoting more color themes (all "expertly designed").

Optionally, these new "themed colors" could even internally automate your other hard-coded theme variations, through a post-process algorithm (if that makes sense).

Regarding the "full solution", it would be up to the Tailwind UI user to provide the engine that mapped these abstract colors to themed colors, ultimately defining these abstract colors in the tailwind configuration (typically using CSS Variables).  They could "roll their own" solution or use an existing utility.  Tailwind UI could provide a suggestion of how to do this, and you would in fact have an internal implementation for demonstration purposes only (i.e. it would not be publicly promoted).

Does this make sense and/or clarify my proposal?

I realize this may be a "tall order" involving a lot of work.

**On a side-bar**, thanks for you insight on shade inversion.  Regarding my utility, I don't like the fact the shade inversion is only available when seeded with tailwind colors.  I have been thinking about a design change where each theme would supply two colors to map to the context colors (i.e. [light, dark]).  It's really only a slight variation to providing one theme dedicated to light and another dedicated to dark.  Do you think this would be a better approach (from a design perspective)?

Thanks again for your consideration.

**Comment by davidluhr** [comment]
@KevinAst Thanks for the feedback! At the moment, authoring separate color themes for Tailwind UI isn't feasible for our team. An okay workaround for our users is to find/replace all instances of a color name in a component (such as replacing `indigo` with `cyan`) and then making any needed adjustments for color contrast. Our page examples can be a useful reference for re-theming components. Beyond that, authoring distinct themes in Tailwind UI is currently out of reach, but I appreciate your input!

**Comment by KevinAst** [comment]
Thanks @davidluhr ... I do appreciate your consideration!

I understand this is currently out of your scope, but please keep this in the back of your mind.  My vision is that each of your pages would promote a single template with a run-time control to select a color (and dark mode).  When visualizing the code it would show the selected hard-coded colors (as always), but would also support a new option to emit the abstract "themed" colors.  In my opinion, this would be an extremely elegant interface.

Internally, this would be accomplished through a post-process algorithm, ultimately streamlining your development effort (once it was in place).

Thanks again for your consideration, and keep up the great work!
