### ISSUE TITLE
Top Navigation with Dropdown for Application UI

### ISSUE THREAD

**Issue by bayramorhan** [tailwindlabs/tailwindui-issues#533]
There is a flyout menu that we can use in our application but it is only available for marketing. Can you make it available for Application UI also? There is many use cases for dropdown top menus in Applications.

Thanks in advance.

**Comment by sinanpostaci** [comment]
Would be nice to have a dropdown menu like flyout menu in Application UI.

**Comment by davidluhr** [comment]
@bayramorhan Thanks for the suggestion! I've added a link to this issue to a card in our public Tailwind UI roadmap in Trello, where the community can vote for what they'd like to see added:

https://trello.com/c/EnGYvFlB/154-add-application-ui-flyout-menus
