### ISSUE TITLE
leave-from leave-to not working VueJS 3

### ISSUE THREAD

**Issue by RomkaLTU** [tailwindlabs/tailwindui-issues#534]
**What component (if applicable)**
- URL for category:  https://tailwindui.com/components/application-ui/page-examples/home-screens#component-af4086fe483fb8a418175cf0218dd5c4
- Component name: Full-width with sidebar

**Describe the bug**
Leaving transition not working

**To Reproduce**

Wrap togglable element with:

```
<transition
                    enter-active-class="transition ease-in-out duration-300 transform"
                    enter-from-class="-translate-x-full"
                    enter-to-class="translate-x-0"
                    leave-active-class="transition ease-in-out duration-300 transform"
                    leave-from-class="translate-x-0"
                    leave-to-class="-translate-x-full">
                    <div v-show="sidebarOpen">...</div>
</stansition>
```

**Expected behavior**
Transition when closing

**Additional context**
Using Tailwind JIT, VusJS 3, InertiaJS

**Comment by davidluhr** [comment]
@RomkaLTU Thanks for reporting this.

I've tested the Home Screen: Full-width with sidebar component in Vue3 and the transitions (both `enter` and `leave`) work as expected (which use [`<TransitionRoot>` and `<TransitionChild>` from Headless UI](https://headlessui.dev/vue/transition) under the hood).

Can you provide a repo with a minimal reproduction of the issue?
