### ISSUE TITLE
Horizontal scroll on Simple with brand contact panel

### ISSUE THREAD

**Issue by huphtur** [tailwindlabs/tailwindui-issues#537]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/marketing/page-examples/contact-pages
- Component name: Simple with brand contact panel

**Describe the bug**
Example page has missing overflow-hidden class which causes horizontal scrolling due to svg pattern

**To Reproduce**
1. Go to https://tailwindui.com/components/marketing/page-examples/contact-pages#component-7826b0aaba4d4a57fe4faece3a58201e
2. Put mouse inside component iframe
3. Scroll right to see iframe move

**Expected behavior**
no scroll pls

**Browser/Device (if applicable)**
 - OS: all of them
 - Browser: all of em

**Additional context**
`<main class="overflow-hidden">` should do the trick right?

**Comment by rambii** [comment]
Another issue with this component would be that the same SVG is above the heading and subtitle (after the header comment) as well.

**Comment by davidluhr** [comment]
@huphtur and @rambii Thanks for reporting these issues!

I've fixed the overflow and prevented the dot pattern from sitting above long heading text.

The correct version should be live on the site shortly.
