### ISSUE TITLE
anythong with calendar components for appointments or milestones etc. Calendars for forms or important dates

### ISSUE THREAD

**Issue by federicosan** [tailwindlabs/tailwindui-issues#538]
**Screenshots**
Provide a screenshot of your existing solution or of examples you've seen elsewhere that you think would be helpful inspiration.

**Additional context**
Add any important details you think we need to know to make sure we build something that matches what you need.

**Comment by markwizpt** [comment]
A great component for Tailwind UI is a scheduler component. Most businesses have some type of scheduling need especially healthcare. 

KendoReact is one of the only companies having a flexible and fully functional scheduler. See below
https://www.telerik.com/kendo-react-ui/components/scheduler/

Would be a great addition to your component library

**Comment by davidluhr** [comment]
@federicosan Thanks for the suggestion! This request has come up before, so I've added a link to this issue to an existing card in our public Tailwind UI roadmap in Trello. This is where the community can vote for what they'd like to see us add:

https://trello.com/c/tc5JwcIn/91-calendar-view
