### ISSUE TITLE
Dark Mode toggle

### ISSUE THREAD

**Issue by MrLehiste** [tailwindlabs/tailwindui-issues#540]
Please add dark mode toggle into your components - you already have it in https://tailwindcss.com/

![image](https://user-images.githubusercontent.com/13542167/112714743-c20fef80-8ed3-11eb-96c0-74e845751c79.png)

**Comment by davidluhr** [comment]
@MrLehiste Thanks for the suggestion! I've added a link to this issue in our public Tailwind UI roadmap in Trello. This is where the community can vote for what they'd like to see us add:

https://trello.com/c/2BzBVDMF/149-toggles-dark-mode-selector
