### ISSUE TITLE
Select Menu with Input Field

### ISSUE THREAD

**Issue by timstrasser** [tailwindlabs/tailwindui-issues#541]
**Additional context**
The select menus (https://tailwindui.com/components/application-ui/forms/select-menus) could be extended with a user input field, that could be used as a filter.

**Comment by davidluhr** [comment]
@timstrasser Thanks for the suggestion!

This pattern is often referred to as a combobox or listbox.

This request comes up frequently, so I've added a link to this issue to an existing card in our public Tailwind UI roadmap in Trello. This is where the community can vote for what they'd like to see us add:

https://trello.com/c/d3AHy86O/115-combobox-listbox-dropdown-search-filter-functionality
