### ISSUE TITLE
multi-select component using <select> and <option>

### ISSUE THREAD

**Issue by henriquez** [tailwindlabs/tailwindui-issues#542]
I could really use a multi-select component that uses the <select> and <option> elements.  Competitive frameworks like Bulma have https://bulma.io/documentation/form/select/#multiple-select.  as does Bootstrap.

I found https://codepen.io/oidre/pen/bGEbVXo which is an implementation of multi-select for tailwind but its quite complex, is for a different framework and requires quite alot of js.

**Comment by davidluhr** [comment]
@henriquez Thanks for the suggestion! This request has come up before, so I've added a link to this issue to an existing card in our public Tailwind UI roadmap in Trello. This is where the community can vote for what they'd like to see us add:

https://trello.com/c/yqHET3rV/116-multi-select-dropdown
