### ISSUE TITLE
"Branded with supported text" select menu has preview issue

### ISSUE THREAD

**Issue by marcreichel** [tailwindlabs/tailwindui-issues#543]
**What component**
- URL for category: https://tailwindui.com/components/application-ui/forms/select-menus
- Component name: Branded with supported text

**Describe the bug**
On the preview page there is a shadow spanning the height of the preview window.

**To Reproduce**
1. Go to https://tailwindui.com/components/application-ui/forms/select-menus#component-d47b46d3ffea1f6b159f51be4bcae2ff
2. See error

**Expected behavior**
There should not be any shadow spanning the preview height.

**Screenshots**

![screenshot](https://user-images.githubusercontent.com/7645035/112879271-39f33b00-90c9-11eb-90bc-c36359a04e35.png)

**Browser/Device**
 - OS: macOS 11.2.3
 - Browser: Chrome
 - Version: 89

**Comment by davidluhr** [comment]
@marcreichel Good eye! I recently updated this component while fixing a browser-specific bug for some users and resolved this at the same time. The version that's live on the site should no longer have this issue. Thanks for reporting this!
