### ISSUE TITLE
Horizontal card layout

### ISSUE THREAD

**Issue by thinkerytim** [tailwindlabs/tailwindui-issues#544]
I've looked pretty hard and haven't found a good horizontal card layout with an image and data. An example might be a product or staff member, image left (or right) with details like phone, email, bio in the text block (or product info like price, stock #, description, etc. if it's a product card).

Maybe something very roughly like this:

![image](https://user-images.githubusercontent.com/122242/112879754-6df53e80-907e-11eb-81d2-72d00530fad8.png)

Extra points if it was demonstrated as full with and as a multi-column card usage, since these cards are typically used in multi-column layouts or sidebars, and they would be useful as "table" data or as page headers as well. Thanks!

**Comment by davidluhr** [comment]
@thinkerytim Thanks for the suggestion! I've added a link to this issue to an existing card in our public Tailwind UI roadmap in Trello. This is where the community can vote for what they'd like to see us add:

https://trello.com/c/ZLxRWo7C/151-grid-lists-horizontal-cards

**Comment by asaf** [comment]
@thinkerytim [card avatar](https://tailwindui.com/components/application-ui/headings/page-headings#component-9a6c0d01eb626ce1c5a63141be2e5271) is not far away from this.
