### ISSUE TITLE
Ecommerce components

### ISSUE THREAD

**Issue by holygekko** [tailwindlabs/tailwindui-issues#545]
I'd love to have some components to create a web shop and create a checkout flow. I know it's a lot, but I'm really interested to see how you'd tackle that.

**Comment by davidluhr** [comment]
@holygekko Thanks for the suggestion! This request is pretty popular, so I've added a link to this issue to an existing card in our public Tailwind UI roadmap in Trello. This is where the community can vote for what they'd like to see us add:

https://trello.com/c/JSmk7d31/41-e-commerce-ui-components
