### ISSUE TITLE
Notification with number

### ISSUE THREAD

**Issue by dcadlereii** [tailwindlabs/tailwindui-issues#546]
The image below shows a rough example of what I am looking for.

![image](https://user-images.githubusercontent.com/24572558/113055475-9f523500-9178-11eb-9cbe-c62a4a420811.png)

I would like to use an SVG bell like you use in your app shell examples, but with an offset circle with a number indicating the number of notifications.
  
[Here is a link that shows an example with Html and CSS](https://www.csscodelab.com/html-css-notification-bell-icon-animation/)

**Comment by davidluhr** [comment]
@dcadlereii Thanks for the suggestion! A similar request has come up before, so I've added a link to this issue to an existing card in our public Tailwind UI roadmap in Trello. This is where the community can vote for what they'd like to see us add:

https://trello.com/c/Pf0JsJYQ/71-button-badges-notifications
