### ISSUE TITLE
Side by side list

### ISSUE THREAD

**Issue by hugo-costa** [tailwindlabs/tailwindui-issues#547]
Would it be possible to have something like this for the TUI Marketing section?

![GIF 01-04-2021 01-42-50](https://user-images.githubusercontent.com/32790757/113228066-f8f75400-928b-11eb-8530-682a93c9f483.gif)

https://www.trysmudford.com/blog/fade-out-siblings-css-trick/

**Comment by davidluhr** [comment]
@hugo-costa Thanks for the suggestion! I've added a link to this issue to an existing card in our public Tailwind UI roadmap in Trello. This is where the community can vote for what they'd like to see us add:

https://trello.com/c/kmUSAkaa/150-marketing-navigation-sections
