### ISSUE TITLE
Select enhancements

### ISSUE THREAD

**Issue by asaf** [tailwindlabs/tailwindui-issues#548]
- [ ] Select with search for single item
- [ ] Select with search for multiple items (using badges)

**Comment by davidluhr** [comment]
@asaf Thanks for the suggestion!

The first pattern you're referring to is often called a combobox/listbox. The second pattern is sometimes referred to as a pill list.

Requests for these patterns have come up before, so I've added a link to this issue to some existing cards in our public Tailwind UI roadmap in Trello. This is where the community can vote for what they'd like to see us add:

https://trello.com/c/d3AHy86O/115-combobox-listbox-dropdown-search-filter-functionality
https://trello.com/c/ecLhidpB/143-pill-list-with-input

**Comment by asaf** [comment]
@davidluhr yes indeed, thanks!
