### ISSUE TITLE
Descenders clipped in illustrated hero with screenshot section

### ISSUE THREAD

**Issue by gregsullivan** [tailwindlabs/tailwindui-issues#549]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/marketing/page-examples/landing-pages
- Component name: Illustrated hero with screenshot section

**Describe the bug**
The descenders in the "ship web apps" `span` are clipped. This is less obvious with the letter P, but very obvious with lowercase G's and Y's.

**To Reproduce**
The error is present in the example; turning off the classes on the "ship web apps" `span` reveals longer descenders on the lowercase P's.

**Screenshots**
<img width="610" alt="Screen Shot 2021-04-05 at 12 09 50 PM" src="https://user-images.githubusercontent.com/2412655/113614839-e4a6b480-9607-11eb-8a8c-2c6785894c96.png">

**Browser/Device (if applicable)**
Tested in latest Chrome, Safari, Firefox

**Comment by gregsullivan** [comment]
Removing the top margin from the paragraph below and adding the same amount of bottom padding to the affected span solves the problem, though it could likely be solved in other ways as well.

**Comment by davidluhr** [comment]
@gregsullivan Thanks for reporting this, and for the fix. I've implemented this fix and it should be live on the site shortly.

**Comment by gregsullivan** [comment]
@davidluhr You're very welcome—thanks for implementing the fix!
