### ISSUE TITLE
Improvement: indent input labels

### ISSUE THREAD

**Issue by aparajita** [tailwindlabs/tailwindui-issues#55]
Because the left edge of a rounded input field is falling down, a label that is left aligned optically looks like it is slightly overhanging the input to the left.

Indenting the labels with `pl-1` creates a much more balanced and pleasing effect because the label starts at the horizontal part of the input outline.

Judge for yourself by looking at the difference below!

**Without indent:**

<img width="450" alt="No indent" src="https://user-images.githubusercontent.com/22218/76125066-e17a6880-5fb0-11ea-9705-a372749c0bd5.png">

**With indent:**

<img width="450" alt="With indent" src="https://user-images.githubusercontent.com/22218/76125088-ea6b3a00-5fb0-11ea-8716-caf64bd19dd3.png">

**Comment by simonswiss** [comment]
We're quite happy with the flush left alignment of labels with form fields as it is currently. 

Your solution looks good too, and the good news is it's not a lot of work to implement to tweak your form fields UI to your liking! 👍
