### ISSUE TITLE
Product comparison

### ISSUE THREAD

**Issue by mstnorris** [tailwindlabs/tailwindui-issues#550]
A means to compare two or more similar products or items. Should be able to cope with:
• Images and icons
• Sections with headers
• Text (with and without a header)
• Numerical values such as standard values, monetary or percentages

**Screenshots**
![Screenshot 2021-04-07 at 11 56 51](https://user-images.githubusercontent.com/1919816/113856051-a391da00-9798-11eb-8458-64e101f0377c.png)

**Additional context**
https://www.apple.com/uk/iphone/compare/

**Comment by davidluhr** [comment]
@mstnorris Thanks for the suggestion! I've added a link to this issue to an existing card in our public Tailwind UI roadmap in Trello, where the community can vote for what they'd like to see added. This card tracks requests for e-commerce UI components:

https://trello.com/c/JSmk7d31/41-e-commerce-ui-components
