### ISSUE TITLE
Link through to https://play.tailwindcss.com from component library

### ISSUE THREAD

**Issue by mstnorris** [tailwindlabs/tailwindui-issues#551]
Alongside the Preview, Code, and Copy buttons, an option to open in https://play.tailwindcss.com would be great!

<img width="1623" alt="Screenshot 2021-04-07 at 14 41 46" src="https://user-images.githubusercontent.com/1919816/113876187-66851200-97af-11eb-9bcd-6d8c9803a6dc.png">

**Comment by davidluhr** [comment]
@mstnorris Thanks for the suggestion! I've added a link to this issue to a card in our public Tailwind UI roadmap, where the community can vote for what they'd like to see added:

https://trello.com/c/FvWbaoj0/155-add-tailwind-play-link-to-component-previews
