### ISSUE TITLE
Share

### ISSUE THREAD

**Issue by johngrimsey** [tailwindlabs/tailwindui-issues#552]
**Screenshots**

<img width="1364" alt="sharing" src="https://user-images.githubusercontent.com/898591/114296094-29679b00-9aa1-11eb-8e6c-3142ad59c13b.png">

<img width="416" alt="notion share page" src="https://user-images.githubusercontent.com/898591/114296096-2bc9f500-9aa1-11eb-96ac-c129bbad77cd.png">

**Additional context**
Sharing an item is a very common pattern, often with one or more of the following features:

* Share method (e.g. copy link, send via email)
* Toggle public link on/off
* Add/remove people by email
* Grant each person edit/view permission

👏 👏 on Tailwind UI - amazing work!

**Comment by davidluhr** [comment]
@johngrimsey Thanks for the suggestion! I've added a link to this issue to a card in our public Tailwind UI roadmap in Trello, where the community can vote for what they'd like to see added:

https://trello.com/c/FIorDfMb/153-share-screen-example

I've noted that this would be a share screen example, similar to the screenshots you provided. At the moment, you could manually create this type of screen or modal with the following components:

- [Modals](https://tailwindui.com/components/application-ui/overlays/modals)
- [Input Groups](https://tailwindui.com/components/application-ui/forms/input-groups)
- [Toggles](https://tailwindui.com/components/application-ui/forms/toggles)
- [Dropdowns](https://tailwindui.com/components/application-ui/elements/dropdowns)
