### ISSUE TITLE
Marketing header with cards doesn't support variable length text

### ISSUE THREAD

**Issue by cwohlman** [tailwindlabs/tailwindui-issues#554]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/marketing/sections/header#component-547517d4dc48e1bf0ccab051ebb0dcba
- Component name: With background image and overlapping cards

**Describe the bug**
If text in the 3 cards is not identical in length then the contact button is misaligned (it's no longer at the bottom)

**To Reproduce**
1. Edit the text of any card to be 1/2 the length of the text on the other cards

**Expected behavior**
I expect the button to be sticky and stay at the bottom of the card

**Screenshots**

[Issue with contact us button alignment.pdf](https://github.com/tailwindlabs/tailwindui-issues/files/6299561/Issue.with.contact.us.button.alignment.pdf)

**Comment by davidluhr** [comment]
@cwohlman Good find! I've fixed this issue and the corrected version should be live on the site shortly.
