### ISSUE TITLE
Multiselect

### ISSUE THREAD

**Issue by frenchqwerty** [tailwindlabs/tailwindui-issues#556]
Hello,

I have a component suggestion for you.

A Multiselect would be needed in order to give developers the possibility of easily integrating such a component.

I am making this suggestion because I need it for a project. I think a lot of your customers will need this component.

Here is an example : https://mdbootstrap.com/docs/standard/extended/multiselect/

Thank you

**Comment by NagariaHussain** [comment]
+1

**Comment by davidluhr** [comment]
@frenchqwerty Thanks for the suggestion! I've added a link to this issue to an existing card in our public Tailwind UI roadmap in Trello, where the community can vote for what they'd like to see added:

https://trello.com/c/8s98FSe9/84-multi-select-control
