### ISSUE TITLE
Contact list example : truncate not works

### ISSUE THREAD

**Issue by seb-jean** [tailwindlabs/tailwindui-issues#557]
Hi,

On page : Contact list example
In page : https://tailwindui.com/components/application-ui/overlays/slide-overs#component-e925f5b20e7d4110cc16920f1cf1a6fc

![Capture](https://user-images.githubusercontent.com/12116264/114710250-ca6a8600-9d2d-11eb-8fe6-1e85d2d95382.PNG)

The text is not truncated

**Comment by davidluhr** [comment]
@seb-jean Thanks for reporting this! I was able to fix the issue and the working version should be live on the site soon.
