### ISSUE TITLE
Feature: Default Color | Color Palettes

### ISSUE THREAD

**Issue by underwood** [tailwindlabs/tailwindui-issues#558]
I've seen some similar issues on this.

Just thought I'd raise this feature request again.

TailwindUI has been really great I've been getting lots of value out of it.

I do spend a lot of time doing quick find/replace the colors though.

Default Color

For a quick WIN it would be great to allow each user to set their default color (this would replace indigo/purple across the components for displaying them and in the code). This would be a huge time saver if this was built in to TailwindUI.

Color Palette Feature

What would be next level, would be actual palettes you could choose from and add your own. This would adjust/palettize each component so everything was complimentary. Something like the palettes in Refactoring UI applied to all the components in Tailwind UI. 

I'd be ok with a big undertaking like this being a paid module, or Tailwind UI Pro.

**Comment by davidluhr** [comment]
@underwood Thanks for the suggestion. There are some major challenges with this approach. Mainly, it should be noted that similar color stops in each color scale aren't perceptually identical when it comes to color contrast.

For example, `indigo-600` and `amber-600` on white have substantially different contrast ratios (indigo is sufficient, amber isn't). Offering a perceptually consistent color palette severely restricts the actual colors we can provide, and makes certain colors fairly unusable (yellows in particular wouldn't look great or offer much value).

As a result, swapping one color for another isn't guaranteed to result in a usable interface.=-

The work required to redesign each component/screen for each color in the Tailwind CSS color palette to ensure everything has sufficient contrast is not feasible.

With this in mind, we design Tailwind UI components to use indigo as a default, and demonstrate how color customizations can be performed with page examples. Please note that a lot of effort goes into designing each page example to ensure that the color treatment works. Doing this for each color in the palette would essentially mean we wouldn't be able to dedicate any time to developing new components.

That being said, this is a recurring request, and something we do consider seriously. Unfortunately, color is extremely difficult to implement consistently and correctly, so thank you for hearing out some of the challenges this involves.
