### ISSUE TITLE
Autocomplete Input

### ISSUE THREAD

**Issue by NagariaHussain** [tailwindlabs/tailwindui-issues#559]
A modern looking autocomplete input component. For example, once that are in e-commerce sites that show instantly show products, categories etc.

**Comment by davidluhr** [comment]
@NagariaHussain Thanks for the suggestion! This request comes up often, so I've added a link to this issue to an existing card in our public Tailwind UI roadmap in Trello, where the community can vote for what they'd like to see added:

https://trello.com/c/d3AHy86O/115-combobox-listbox-dropdown-search-filter-functionality

**Comment by NagariaHussain** [comment]
Great!
