### ISSUE TITLE
Tailwind UI Unique Favicon

### ISSUE THREAD

**Issue by underwood** [tailwindlabs/tailwindui-issues#560]
It would make it easier to find Tailwind UI vs Tailwind tabs if UI had a unique favicon.

Admittedly I always have way too many tabs open.

Maybe just the UI part of the logo or just a tailwind logo in a different color or modified where it's unique.

**Comment by drmzio** [comment]
+1 Here's an example from Webflow that separates the Editor from the Marketing site.

![Image 2021-04-14 at 11 39 34 PM](https://user-images.githubusercontent.com/6914518/114825317-e8120c80-9d7a-11eb-88bf-3622c7d89d59.jpg)

**Comment by davidluhr** [comment]
@underwood Thanks for the suggestion.

I guess the 2px difference just isn't enough, huh?

![Comparison of Tailwind UI and Tailwind CSS favicons](https://user-images.githubusercontent.com/16038754/115897192-04fcae80-a411-11eb-8d47-eba8cab04d0e.png)

Just kidding. I'll make note of this with the team and see what we can do.

**Comment by davidluhr** [comment]
@underwood Forgot to close this issue previously. I passed this idea along to the team and we'll consider it for future cycles/cooldowns. Thanks for the feedback!
