### ISSUE TITLE
all the components used in developing tailwind ui

### ISSUE THREAD

**Issue by pranavquze** [tailwindlabs/tailwindui-issues#562]
**Additional context**
if you guys can add the components that are used in the tailwind UI will very help full

**Comment by davidluhr** [comment]
@pranavquze Thanks for the suggestion. Are you referring to the visual design of TailwindUI.com itself? If so, please note that the website has a different visual style/brand than the components themselves, and we update this visual design occassionally (such as the visual update last week). Beyond stylistic differences, there should be components that serve the same purpose (Navbars, Dropdowns, Buttons, Grid Lists, etc.).

I'm closing this issue for now, but feel free to reply if there are specific requests of things we can add.
