### ISSUE TITLE
Add default breakpoints in addition to the responsive viewport slider to the TailwindUI Docs

### ISSUE THREAD

**Issue by mstnorris** [tailwindlabs/tailwindui-issues#563]
I wanted to grab a screenshot from the TailwindCSS docs to explain what I'm referring to here but they appear to have gone. You used to be able to select the mobile, tablet, and desktop devices to alter the screen width of the examples.

While the TailwindUI docs has the slider, it would be neat to have at the top of each example the "device toggles" which shows all the examples on the page confined to the same width for easy comparison (in the same way that selecting Vue/React now changes all the other components code).

**Comment by davidluhr** [comment]
@mstnorris Thanks for the suggestion! I've added this to a card in our public Tailwind UI roadmap in Trello, where the community can vote for what they like to have added:

https://trello.com/c/0bKrdM6Z/156-add-breakpoint-selector-to-component-previews
