### ISSUE TITLE
kanban board

### ISSUE THREAD

**Issue by logemann** [tailwindlabs/tailwindui-issues#564]
A Kanban board where you can drag&drop cards would be awesome. I know its kind of complex but anyway.

**Comment by davidluhr** [comment]
@logemann Thanks for the suggestion! I've added a link to this issue to a card in our public Tailwind UI roadmap in Trello, where the community can vote for what they'd like to see added:

https://trello.com/c/z447COge/152-kanban-board-with-drag-and-drop
