### ISSUE TITLE
Cards

### ISSUE THREAD

**Issue by sandro-git** [tailwindlabs/tailwindui-issues#567]
I Things It Will be great to have cards components. With image without image popover etc...

**Comment by davidluhr** [comment]
@sandro-git Thanks for the suggestion! I've added a link to this issue to an existing card in our public Tailwind UI roadmap in Trello, where the community can vote for what they'd like to see added:

https://trello.com/c/jJf13sIa/83-media-cards

Some existing cards that we have can be found in the [Grid Lists](https://tailwindui.com/components/application-ui/lists/grid-lists) and [Blog Sections](https://tailwindui.com/components/marketing/sections/blog-sections) categories, but we will think of ways to offer more card components.
