### ISSUE TITLE
Would be amazing to have an assortment of "loaders" or "spinners"

### ISSUE THREAD

**Issue by Saeven** [tailwindlabs/tailwindui-issues#568]
I know I'm being selfish here, but I saw that we could request components.  The UI set is very complete, but the one thing that I hate drawing up each time is load indicators.  It would be amazing if the library provided these - would love to see how the master TailwindCSS artists could creatively produce simple and effective loaders.

I won't be hurt if this is deemed too far from the library's mission!  

Thanks for all your work.

**Comment by davidluhr** [comment]
@Saeven Thanks for the suggestion! This request is pretty popular, so I've added a link to this issue to an existing card in our public Tailwind UI roadmap in Trello, where the community can vote for what they'd like to see added:

https://trello.com/c/whj4CPQS/48-loading-spinners-skeletons
