### ISSUE TITLE
Visual aids for open / closing tags in sample source

### ISSUE THREAD

**Issue by AlexZeitler** [tailwindlabs/tailwindui-issues#570]
It's not really a component request but sometimes (when I just want to copy fragments of the sample) it would really help to have visual match of opening / closing tags for the sample code.

**Screenshots**

That's how it's now:

![image](https://user-images.githubusercontent.com/287480/115161208-98925000-a09c-11eb-8b29-7937ceadc57a.png)

Some visual aids like this would be useful:

![image](https://user-images.githubusercontent.com/287480/115161327-603f4180-a09d-11eb-97ab-8f571a863380.png)

**Additional context**
Add any important details you think we need to know to make sure we build something that matches what you need.

**Comment by davidluhr** [comment]
@AlexZeitler Thanks for the suggestion! I've made a note with the team to consider some sort of visual aid, such as the indentation guides you demonstrated here, code comments, or some other way to help separate sections of markup for easier copying.
