### ISSUE TITLE
RTL view

### ISSUE THREAD

**Issue by alighasemzadeh** [tailwindlabs/tailwindui-issues#573]
**What component (if applicable)**
- URL for category: 
![image](https://user-images.githubusercontent.com/26847446/115188456-349e7480-a0fa-11eb-80e1-efc2086f9c9f.png)

- Component name: contact-sections/Split brand panel

**Describe the bug**
I want to use all component in RTL.

**Expected behavior**
I am using https://www.npmjs.com/package/tailwindcss-rtl which I want to use RTL mode.
But there is some bugs.

**Screenshots**
![image](https://user-images.githubusercontent.com/26847446/115188924-e5a50f00-a0fa-11eb-90ff-0f630f39432f.png)

**Browser/Device (if applicable)**
 - OS: Any
 - Browser: Any
 - Version: Any

**Additional context**
I think TailWindUI should has native rtl plugin.

**Comment by davidluhr** [comment]
@alighasemzadeh The code in Tailwind UI is pretty standard (just `margin-` and `space-` utilities), which this outside package seems to handle fine in their demo.

I'd recommend filing an issue with the package: https://github.com/20lives/tailwindcss-rtl/issues

It's possible that `sr-only`, which is used alongside each of the icons in this example, is causing the issue, but I'm not sure. I'm closing this issue, as this it outside of the scope of Tailwind UI, but feel free to reply if there's anything else we can do to help. Thanks!
