### ISSUE TITLE
Modal Overlay, Click or ESC doesn't work

### ISSUE THREAD

**Issue by brainlet-ali** [tailwindlabs/tailwindui-issues#574]
**What component (if applicable)**
- URL for category: 
- Component name: Modals => Simple with dismiss button

**Describe the bug**
When I remove the footer in any of the modals like:
  <div class="mt-5 sm:mt-6">
                            <button type="button" class="inline-flex justify-center w-full rounded-md border border-transparent shadow-sm px-4 py-2 bg-indigo-600 text-base font-medium text-white hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 sm:text-sm" @click="open = false">
                                Go back to dashboard
                            </button>
                        </div>

The click or esc key doesn't work and modal not disappears

**Comment by davidluhr** [comment]
@brainlet-ali To help recreate the issue, which version of the component are you using: HTML, React, or Vue? I haven't been able to recreate this issue on my end so far.

One possibility is if you remove both the close button and any buttons in the "footer" of the modal, there is nothing to focus inside the modal when it opens. This might be causing an error and preventing the overlay from working as expected.

**Comment by brainlet-ali** [comment]
I'm using the Vue template. We as web developers tend to wrap our head around Bootstrap as a reference. If you delete anything from the modal, header body or footer, it still opens/closes with same accessibility. And Modal is one of the most important component in developing CRUD UI. There should not an element which you want me to put there just simply to have a focus element.

**Comment by brainlet-ali** [comment]
well it's your framework and I think you can decide. From outside if there is a p tag it should behave the same as with any other content do which you are saying have to be a focus element.

**Comment by davidluhr** [comment]
@brainlet-ali It's not a matter of choosing how to implement it in Tailwind UI, this is a firm requirement for accessibility that modals must have a focusable element.

Again, I believe the component is working at intended, so I'm closing this issue for now, but feel free to reply if you have further suggestions.
