### ISSUE TITLE
Lists > Tree view

### ISSUE THREAD

**Issue by joanllenas** [tailwindlabs/tailwindui-issues#575]
# Request

A tree view to render a hierarchy of nodes.

# Example

![Screenshot 2021-04-19 at 14 46 57](https://user-images.githubusercontent.com/213787/115238761-54e02a80-a11e-11eb-8f82-92b71a796d51.png)

**Comment by davidluhr** [comment]
@joanllenas Thanks for the suggestion! I've added a link to this issue to a card in our public Tailwind UI roadmap in Trello, where the community can vote for what they'd like to see added:

https://trello.com/c/oupB2Ges/52-tree-view

If you only need one level of nesting, we have a sidebar with expandable sections that might work for you in the meantime: https://tailwindui.com/components/application-ui/navigation/sidebar-navigation#component-34180dd5b86e303286a8aa59b2ca9c34
