### ISSUE TITLE
Two `open` variables (shadowing) on Dark nav with Overlap

### ISSUE THREAD

**Issue by filipenevola** [tailwindlabs/tailwindui-issues#576]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/application-shells/stacked#component-2573937b459d64c1734b4141b1eff8d7
- Component name: Dark nav with Overlap

**Describe the bug**
Two `open` variables (shadowing). ESLint was complaining about it.

**To Reproduce**
1. Use the component
2. Check ESLint rules
3. See error

**Expected behavior**
A different name in the second one, like renaming it: `{ open: openProfileMenu }`

**Screenshots**
N/A

**Browser/Device (if applicable)**
 N/A

**Additional context**
I'm recording videos for my channels ([English](https://www.youtube.com/c/HowToCreateAnAppDev) and [Portuguese](https://www.youtube.com/channel/UCZo_DmCzwmxMtv5Kv_dukpA)) and I'm starting to use Tailwind UI. The videos are being edit yet, I'll update with the links here when they are out.

I also created the example to use [Tailwind](https://github.com/meteor/examples/tree/main/tailwindcss) with Meteor.

I'm also Meteor's CTO, etc, if you want to discuss a partnership, affiliate, etc let me know.

I'm really enjoying the product. Congrats.

**Comment by davidluhr** [comment]
@filipenevola Thank you for reporting this. Our recommendation is to rename the variable when destructuring, as you pointed out:

Before:
```js
({ open }) =>
```
After:
```js
({ open: menuOpen }) =>
```

The current code is valid, so hopefully this is a quick workaround to satisfy ESLint. It's possible that a future version of Headless UI will simplify this further.
