### ISSUE TITLE
Carousels and Sliders

### ISSUE THREAD

**Issue by mxdi9i7** [tailwindlabs/tailwindui-issues#578]
**Screenshots**
Provide a screenshot of your existing solution or of examples you've seen elsewhere that you think would be helpful inspiration.

**Additional context**
Add any important details you think we need to know to make sure we build something that matches what you need.

**Comment by davidluhr** [comment]
@mxdi9i7 Thanks for the suggestion! I've added a link to this issue to a card in our public Tailwind UI roadmap in Trello, where the community can vote for what they'd like to see added:

https://trello.com/c/E2A3rBEz/60-carousels
