### ISSUE TITLE
Janky corners on the photo grid

### ISSUE THREAD

**Issue by brandonpittman** [tailwindlabs/tailwindui-issues#580]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/lists/grid-lists#component-d6b6c178a9f460d37c542870139e940e
- Component name: Image with details

**Describe the bug**
Janky corners on the photo grid.

**Screenshots**

![CleanShot 2021-04-20 at 14 10 48@2x](https://user-images.githubusercontent.com/967145/115340783-5410cc80-a1e2-11eb-8a28-5d23322b3c06.png)

**Comment by davidluhr** [comment]
@brandonpittman Thanks for reporting this! We needed to remove the default focus ring on the the nested button, and allow the `focus-within` styles to appear without this visual conflict.

The fixed version should be live on the site now.

**Comment by brandonpittman** [comment]
@davidluhr Awesome! Done this myself plenty of times.
