### ISSUE TITLE
Simple image at documentation

### ISSUE THREAD

**Issue by Pblfer** [tailwindlabs/tailwindui-issues#581]
Link:
https://tailwindui.com/components/application-ui/forms/sign-in-forms

Component:
Split screen

![image](https://user-images.githubusercontent.com/1414796/115510493-0d9c8b80-a23d-11eb-9e5e-060cb7cdfe7e.png)

**Comment by Pblfer** [comment]
sorry all images are the same, maybe is intentional. 🤦‍♂️

**Comment by davidluhr** [comment]
@Pblfer All images come directly from Unsplash, which uses Imgix. It's possible they were down temporarily. Does this issue still persist for you?

**Comment by davidluhr** [comment]
@Pblfer I haven't heard back on this, and haven't observed image loading issues on our site over the past couple weeks, so I'm closing this issue.

If this happens again on your end, feel free to reply here and we can investigate further.
