### ISSUE TITLE
Data Display: Thermometer/Progress Bars?

### ISSUE THREAD

**Issue by caroseuk** [tailwindlabs/tailwindui-issues#583]
**Screenshots**
I dont have screenshots, however when trying to create a scorecard/progress dashboard. Similar to bar graphs, it would be good to see progress bars (vertical and horizontal?)

**Additional context**
I would like to display multiple metrics in a graphical way, in the same way that a thermometer shows temperature. It would be great if there was something similar to this available within the Data Display section of components of Tailwind UI.

**Comment by davidluhr** [comment]
@caroseuk Thanks for the suggestion! I've added a link to this issue to a card in our public Tailwind UI roadmap in Trello, where the community can vote for what they'd like to see added:

https://github.com/tailwindlabs/tailwindui-issues/issues/583
