### ISSUE TITLE
Publishing custom element markup

### ISSUE THREAD

**Issue by marcobeierer** [tailwindlabs/tailwindui-issues#586]
Hi Tailwind UI team

Thanks for your great work on Tailwind UI.

When I'm working with the Tailwind UI components I mostly implement them as custom web components with [Lit](https://lit.dev/) (previously named Lit-Element).

Working with the provided HTML is fine, but the orientation in larger examples is often confusing. In a [recent blog post](https://blog.tailwindcss.com/building-react-and-vue-support-for-tailwind-ui) by @adamwathan I saw that you internally work with custom elements and the markup of those looks very similar to what I end up with.

So I expect working with them would be much more pleasant for me.

Is there any change that you could publish your custom elements markup too? I can implement the logic and elements with Lit by myself, but this would make copy-pasting the markup much easier for me and probably others, who implement their own custom elements, too.

**Comment by davidluhr** [comment]
@marcobeierer Thanks for the feedback!

The custom elements we use internally actually wouldn't offer much convenience to outside users. They are essentially hooks in our markup to make transformations into the code we provide in the component previews (HTML, React, Vue). All of the functionality comes from these transformations, and isn't very useful as standalone components. The component previews themselves run AlpineJS code that is stripped away to provide the final HTML, but it should be noted that this AlpineJS code only contains just enough to create a functional demo. The full functionality of Headless UI is for React and Vue at the moment.

That being said, it's possible that we will expand Headless UI (and Tailwind UI, as a result) to support other targets, and there may be a more useful way we can deliver code to be adapted as web components.

I'm closing this issue for now, as I've passed these feedback along to the team to consider for future Headless UI updates, but I appreciate your thoughts, and feel free to reply here further with additional ideas! I'll be sure to update this issue if there are any developments.
