### ISSUE TITLE
Problem with Listbox - Options and Z-Index

### ISSUE THREAD

**Issue by impactmediaweb** [tailwindlabs/tailwindui-issues#587]
Listbox
https://tailwindui.com/components/application-ui/forms/select-menus
- Component name: Listbox -> Simple Custom Variant

When you place multiple list boxes among each other and open one of them the listbox options will be rendered z-index wise under the followed select boxes.

**To Reproduce**
Place multiple list boxes below each other. Open one of them.

The <ul> Menu with the list items should have a higher z-index than the select boxes themselves

<img width="255" alt="screenshot" src="https://user-images.githubusercontent.com/775339/115786160-baebdc80-a3c0-11eb-9a1b-09e11aea6fc1.png">

**Comment by lensbart** [comment]
Same here

**Comment by davidluhr** [comment]
@impactmediaweb You can adjust this as needed by adding `z-10` (or whatever layer of z-index suits your scenario) to the `<ul>` containing the options. If you are using the React or Vue component, then this can be added to `<Listbox.Options>` or `<ListboxOptions>`, respectively.

For now, I've added `z-10` to the standalone Select Menu examples, but please note that this cannot account for every situation, a higher z-index value may be occasionally needed.
