### ISSUE TITLE
radio-groups -> List with description (radio circle gets oval when 2 lines of description)

### ISSUE THREAD

**Issue by logemann** [tailwindlabs/tailwindui-issues#588]
**What component (if applicable)**
- https://tailwindui.com/components/application-ui/forms/radio-groups
- Component name: List with description

**Describe the bug**
radio circle gets oval when 2 lines of description (see image)

**To Reproduce**
use example code and make a 2 lines description text

**Expected behavior**
radio circle keeps being a circle

**Screenshots**
![Bildschirmfoto 2021-04-23 um 13 20 52](https://user-images.githubusercontent.com/346353/115864250-e90c0380-a436-11eb-85d6-5a49282fe362.png)

**Browser/Device (if applicable)**
 - OS: latest Mac OS
 - Browser latest Chrome

**Comment by davidluhr** [comment]
@logemann Thanks for reporting this.

I haven't been able to recreate this issue on Chrome, Firefox, or Safari on MacOS:

![Radio group input with long description](https://user-images.githubusercontent.com/16038754/116276661-92a20c00-a739-11eb-80c1-255e8edb36ce.png)

I'm not sure what would cause this on your end. Does adding `items-start` to the `<label>` that wraps the input help? It shouldn't be need, but might help prevent this.

**Comment by logemann** [comment]
wow. Thats weird. I just copied the example but you are right. When chaging the example itself on the fly on your site, it works as expected. Need to dig in deeper.

**Comment by logemann** [comment]
for some reason the text will be pushed to the left and makes the cell for the radio very small so that it becomes oval.
Can i give you the URL of the original site so that you can have a look at? Unfortunately its PW protected so that i need a way to submit it to you.  I really cant see why there is a problem here. I really just copy pasted your example and still get it on a nearly empty gatsby page.

**Comment by davidluhr** [comment]
@logemann Thanks for the additional feedback. Does it fix the issue on your site if you add `flex-shrink-0` to the input that have `w-4` on it? I'm hoping that's all that's needed.

If so, I will update the Tailwind UI examples to also include this, just in case this occurs in other scenarios.

**Comment by logemann** [comment]
@davidluhr that did it. Many thanks for that. Would it be useful to put it also in the example so that perhaps other gatsby users profit from it? (dont even know if its a gatsby thing, its just a guess)
