### ISSUE TITLE
Vue Transition :show props are undefined for slide-overs

### ISSUE THREAD

**Issue by nathanheffley** [tailwindlabs/tailwindui-issues#589]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/overlays/slide-overs
- Component name: Contact list example
- (but it also happens for "Wide horizontal user profile example" and "User profile example" at least as well)

**Describe the bug**
In the three slide-over components listed above, the slide-over has dropdown menus inside of the example. In the Vue examples, these dropdowns use the Menu component, and the menu items are wrapped inside of of a `TransitionRoot` component. The Transition Root needs to have a `:show` component to work, but currently it is being passed `undefined` instead of the expected `open` property, and the `Menu` component isn't even exposing the `open` property using a `v-slot` which is where I imagine the issue stems from.

By having the `:show` property set to `undefined` on the `TransitionRoot`, it causes the page to hang and finally crash with an error starting with `Error: Maximum recursive updates exceeded.`

**To Reproduce**
1. Copy the "Contact list example" slide-over into a Vue project.
2. Attempt to load the page with the component and it will hang, crash, and your console will log the error listed above.

**Expected behavior**
I expect the page to not crash when copy-pasting these slide-over examples.

**Browser/Device (if applicable)**
 - It happened on every browser I tested on both Windows and Mac.

**Comment by bradlc** [comment]
Hey @nathanheffley. Thanks for reporting, this has now been fixed! `TransitionRoot` has been changed to `transition` and the `:show` prop has been removed 👍
