### ISSUE TITLE
Table are not responsive on mobile

### ISSUE THREAD

**Issue by StErMi** [tailwindlabs/tailwindui-issues#593]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/lists/tables
- Component name: Table

**Describe the bug**
When you shrink the page emulating a tablet/mobile view the page doesn't behave correctly

**To Reproduce**
1. Go to https://tailwindui.com/components/application-ui/lists/tables
2. Shrink the Preview to tablet/mobile

**Expected behavior**

I would expect an example that showcases how I should handle a mobile/tablet version of a table.
On the desktop you can show the whole table, under some screen side you should show fewer columns, on the mobile screen size you should switch to a List view.

**Screenshots**

Mobile/Tablet

![image](https://user-images.githubusercontent.com/146166/116040904-e09d0e00-a66c-11eb-9d1e-043d5c46d167.png)

**Browser/Device (if applicable)**
 - OS: macOS
 - Browser chrome
 - Version 90.0.4430.85

**Comment by davidluhr** [comment]
@StErMi Thanks for the feedback. I've changed this to a component request, as this is not a bug with our current components. The most common and widely usable approach to making tables responsive is to simply allow for horizontal scrolling so there is no data loss on smaller screens. Here's a great article on the topic: https://adrianroselli.com/2020/11/under-engineered-responsive-tables.html

While it is possible to create a semantic and accessible table that switches to more of a list view on smaller screens, the complexity and considerations go up considerably, and each implementation is typically purpose-built to a single table, or requires JavaScript to dynamically modify the markup. Here's another article by Adrian Roselli that covers all the needed details: https://adrianroselli.com/2017/11/a-responsive-accessible-table.html

For now, I'm adding a link to this issue to an existing card in our public Tailwind UI roadmap in Trello, where the community can vote for what they'd like to us add:
https://trello.com/c/2JwXAYR4/59-responsive-table-card-on-small-screens
