### ISSUE TITLE
<Switch /> toggles when I press Enter when another input field is in focus

### ISSUE THREAD

**Issue by lensbart** [tailwindlabs/tailwindui-issues#594]
**What component (if applicable)**
`import { Switch } from '@headlessui/react'`

**Describe the bug**
See title

**To Reproduce**
- Copy & paste a `<Switch />` from the example docs
- Have an `<input type="text" />`

**Expected behavior**
No toggling when you press enter in a text input

**Screenshots**
N/A

**Browser/Device (if applicable)**
 - OS: Windows unfortunately
 - Browser Firefox
 - Version 88.0

**Additional context**
Maybe it has something to do with the form being submitted, but I doubt so, and in any case it shouldn't happen

**Comment by davidluhr** [comment]
@lensbart Thanks for reporting this! As this is an issue with Headless UI, could you please file the issue there? https://github.com/tailwindlabs/headlessui/issues Thank you!


>OS: Windows unfortunately

Haha! It's ok, I mainly use Windows 😉
