### ISSUE TITLE
Form elements with error states

### ISSUE THREAD

**Issue by iwarshak** [tailwindlabs/tailwindui-issues#597]
It would be really nice to have some form elements with error states shown. 

For example, I came up with this, where borrowed the 'X' element technique from bootstrap, but am not confident it's that great:

<img width="434" alt="Screen Shot 2021-04-27 at 11 40 51 AM" src="https://user-images.githubusercontent.com/471/116279704-790abf80-a74d-11eb-855e-58bd3c5fbe09.png">

A spinner background object, similar to the 'X' above would be great for when a field is being validated on the server.

Lastly, some error messages to display a summary of errors would be super great.

**Comment by davidluhr** [comment]
@iwarshak We have the Input with validation error component. Does this serve your needs? https://tailwindui.com/components/application-ui/forms/input-groups#component-7a5297f99a5ed22df80939dd1986de5f

**Comment by iwarshak** [comment]
@davidluhr Yes - I must have completely missed this. I was always looking on the 'form' page. Thank you!

**Comment by davidluhr** [comment]
@iwarshak You're welcome! Glad this works for you.
