### ISSUE TITLE
Single Blog post template

### ISSUE THREAD

**Issue by logemann** [tailwindlabs/tailwindui-issues#600]
One or two variations of Single Blog Post pages would be awesome.  

**Screenshots**
layouts like this one for example.

<img width="1519" alt="Bildschirmfoto 2021-05-01 um 02 06 17" src="https://user-images.githubusercontent.com/346353/116764586-dc347480-aa21-11eb-8baf-534b6ee017ae.png">

**Comment by davidluhr** [comment]
@logemann Thanks for the suggestion! I've add a link to this issue to an existing card in our public Tailwind UI roadmap in Trello. This is where the community can vote for what they'd like to see added:

https://github.com/tailwindlabs/tailwindui-issues/issues/600
