### ISSUE TITLE
Build an autosuggest input - useful for search or autocomplete inputs

### ISSUE THREAD

**Issue by emotu** [tailwindlabs/tailwindui-issues#601]
![Screen Shot 2021-05-01 at 11 59 54 PM](https://user-images.githubusercontent.com/4973763/116797058-67247600-aad9-11eb-9fae-06d18a8a7bc8.png)
![Screen Shot 2021-05-02 at 12 00 08 AM](https://user-images.githubusercontent.com/4973763/116797059-68ee3980-aad9-11eb-8572-05e163142f71.png)

Can you bulid an auto complete input component that can be used in as a search bar? I've included images that show the best example I can find - the search input in the tailwindui dashboard.

**Comment by connordoner** [comment]
Seconded. :+1:

**Comment by davidluhr** [comment]
@connordoner Thanks for the suggestion! This request comes up often, so I've add a link to this issue to an existing card in our public Tailwind UI roadmap in Trello. This is where the community can vote for what they'd like to see added:

https://trello.com/c/d3AHy86O/115-combobox-listbox-dropdown-search-filter-functionality

**Comment by connordoner** [comment]
Credit on this one goes to @emotu! Thanks for adding it to the roadmap, @davidluhr.

**Comment by davidluhr** [comment]
@connordoner Oops, you're right! Thanks for pointing that out 🙇‍♂️
