### ISSUE TITLE
Drop `bg-white` on SVGs in the "Toggle with Icons" component

### ISSUE THREAD

**Issue by sauladam** [tailwindlabs/tailwindui-issues#602]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/forms/toggles#component-bcaf782196186836b6ea686e7096e734
- Component name: Toggle with Icon

**Describe the bug**
The icon SVGs do have a "bg-white" on them, but the "source of truth" for the background color seems to be provided and controlled by the outer wrapping `<span>`. So setting a background color on the SVG itself doesn't seem to have a real purpose. 

This is a little annoying when you want to make the visible background smaller while keeping the size of the SVG the same. The corners then just poke out or overlap the round background entirely: 
![Screenshot from 2021-05-03 19-33-41](https://user-images.githubusercontent.com/5918276/116911132-bb009d80-ac46-11eb-9481-adb159c3b0b7.png)

And if you want to change the background color depending on the state, you would have to do it in 2 places: on the outer `<span>` and on the `<svg>` itself, which seems unnecessary and also would make the background color transition invisible. 

#### Both of these issues could be avoided by just not setting an explicit background-color on the SVGs.

**To Reproduce**
```html
<!-- This span should be responsible for the background color -->
<!-- 
The corners of the square SVGs will poke out from the rounded background. 
If we make it even smaller while keeping the size of the SVGs the same, the SVGs 
will overlap the background entierly. 
This could easily be avoided by keeping the background color of the SVGs transparent 
-->
<span :class="[enabled ? 'translate-x-5' : 'translate-x-0', '... bg-white h-4 w-4 ....]">
    <span class="....">
      <!-- The SVGs should not have a background color at all -->
      <svg class="bg-white h-3 w-3 ...">...</svg>
    </span>

    <span class="...">
      <!-- The SVGs should not have a background color at all -->
      <svg class="bg-white h-3 w-3 ...">...</svg>
    </span>
</span>
```

So when I do something like this (don't mind the weird positioning):

```html
<span :class="[enabled ? 'translate-x-5 bg-yellow-500' : 'translate-x-0 bg-blue-500', '... h-3 w-3 ....]">
```

What I actually want | What I get out of the box
--- | ---
![Screenshot from 2021-05-03 21-40-00](https://user-images.githubusercontent.com/5918276/116924448-2d2dae00-ac58-11eb-9226-3914a17e7604.png)  | ![Screenshot from 2021-05-03 21-38-50](https://user-images.githubusercontent.com/5918276/116924326-04a5b400-ac58-11eb-8515-24aa02c50ab2.png)

'tis but a scratch, but I think not having to deal with this would still make a small QoL and DX improvement.

**Comment by davidluhr** [comment]
@sauladam Thanks for catching this! I've removed the background colors on the SVGs, so hopefully that helps!
