### ISSUE TITLE
Page examples do not print correctly with multi-page content

### ISSUE THREAD

**Issue by pjbakker** [tailwindlabs/tailwindui-issues#604]
**What component (if applicable)**
- URL for category: e.g. https://tailwindui.com/components/application-ui/page-examples/detail-screens
- Component name: e.g.Multi-column directory

**Describe the bug**

When using example pages (such as described above) in a real-world app and printing it (Print in browser), only the current 'active part of the screen' is printed by the browser and not all content.

Reason is that example pages have "h-screen" on the outermost div, thus limiting the window to print.

**To Reproduce**
1. Make a page with enough content that it does not fit on a single screen of "Multi-column directory detail screen"
2. Scroll down
3. Cmd-P/Windows-P/whatever it is on your OS / Browser
4. Look at Preview and only see current viewport (and only 1 page to print)

**Expected behavior**

Print 3 pages of content

**Additional context**

Solution: change "h-screen" to "min-h-screen" on the outermost div, and add "h-screen" to the div below  

This issue is present on more than just this detail screen. Just using this one to illustrate.

**Comment by davidluhr** [comment]
@pjbakker Thank you for reporting this. Could you describe your printing use case further? For example, would you prefer a print format that strips out most layout and styling to present the content in a more print-friendly format?

We currently don't have a dedicated print stylesheet in Tailwind UI, as our focus in on a web experience, but I appreciate any feedback you have on what your needs are.

**Comment by pjbakker** [comment]
Well I think having a print stylesheet is a nice bonus. I've currently done the print stylesheet myself. Primarily it means removing the menu (either at the side or top). Part will be site specific, so I wouldn't do too much from the basic tailwind UI examples. But the menu hiding is probably going to be standard for everyone.

But the basic print use-case is useful for almost everybody. TailwindUI has a nice Blog part, but if I now use Tailwind for a Blog or Report and now press print (to PDF), you only get one viewport-height of the full blog (because of the `h-screen` limitation). With `min-h-screen` the vertical size can grow to cover the full blog in height.

In my case I use Tailwind on an App site which contains:

* articles (multi-page that some people want the print to PDF from time to time)
* reports from the application that really need to be printed to PDF for exporting

**Comment by davidluhr** [comment]
@pjbakker Thanks for the feedback. Since creating page or component-specific print styles isn't feasible (and we can't predict how they will be used), would you find it useful to essentially strip most styling/layout and simply present formatted text?

**Comment by pjbakker** [comment]
As a developer I'd say that's too use-case specific...

My goal was to have fix the current examples (with the min-h-screen fix), that just don't make sense using h-screen..
