### ISSUE TITLE
Window Titlebar

### ISSUE THREAD

**Issue by mdemuth1982** [tailwindlabs/tailwindui-issues#605]
Many of the example components display a window toolbar in the thumbnail image, but from what I can tell there is no example that actually has the css necessary to create the window toolbar.  This would come in handy when creating an electron application as you can actually hide the native window frame and then style your own. 

**Screenshots**
<img width="1172" alt="Custom Window Toolbar" src="https://user-images.githubusercontent.com/1172427/116992632-58d68580-aca4-11eb-88b5-a0946bd2b2d4.png">

**Comment by davidluhr** [comment]
@mdemuth1982 The titlebars in the thumbnail images are only there to provide context to the low-fidelity representations of the components in the browser.

Offering actual titlebars is outside the scope of Tailwind UI, as it is primarily intended for websites and web apps. Most customers use Tailwind UI as a starting point for bringing their own branding and theming to components and pages, so the final UI chrome in an Electron app would be largely dependent on the specific project.

It's not likely that we will add these to Tailwind UI, but we appreciate the suggestion, and it's good to know of the use case of Tailwind UI being used in desktop apps.
