### ISSUE TITLE
Search suggestion / auto complete

### ISSUE THREAD

**Issue by jamesiscool** [tailwindlabs/tailwindui-issues#606]
A search input with suggestions / auto complete would be great. Mainly to have an example of an idiomatic way to do it with Headless UI, including the keyboard nav and click outside closing

<img src="https://user-images.githubusercontent.com/6336376/117102959-bb22a980-adbc-11eb-8e96-33254a8691b8.png" width="250">

**Comment by davidluhr** [comment]
@jamesiscool Thanks for your request! This suggestion has come up a ton, so I've added a link to this issue to our Tailwind UI public roadmap in Trello, where the community can vote for what they'd like us to add:

https://trello.com/c/d3AHy86O/115-combobox-listbox-dropdown-search-filter-functionality
