### ISSUE TITLE
Search Filters

### ISSUE THREAD

**Issue by Lobosque** [tailwindlabs/tailwindui-issues#609]
First of all, contratulations for the project! As a mostly backend-oriented developer, tailwindui has been helping to deliver working prototypes/mvps faster than ever, and for the first time they look GOOD.

One thing I really miss in the current pages/component selection is an example of a table with many search parameters, this kind of interface is very common on long tables / report pages. Some of them have basic/advanced filters.

While I'm starging to get comfortable with the tailwind syntax, my design skills limitations keep me from doing a filters sections that actually belongs there.

Thanks and keep up the good work!

**Comment by davidluhr** [comment]
@Lobosque Thanks for the positive feedback! Glad you're finding Tailwind UI useful in your team.

As per your request, we've received similar suggestions in the past, so I've added a link to this issue to our Tailwind UI public roadmap in Trello, where the community can vote for what they'd like us to add:

https://trello.com/c/Cx4cB0H8/78-sortable-data-tables

Thanks again!
