### ISSUE TITLE
select2 (autocomplete)

### ISSUE THREAD

**Issue by abepark01** [tailwindlabs/tailwindui-issues#61]
First, thanks for releasing TailwindUI.  I purchased the marketing + application UI bundle.

I use autocomplete for a lot of web applications that I build and it would be great to have add this as one of the dropdown components.

I use select2, but don't like the fact that it's dependent on jQuery.
In the React ecosystem, there is also autocomplete npm packages, but it would be nice to be able to build my own version using tailwindui.

What do you  think?

**Screenshots**
Provide a screenshot of your existing solution or of examples you've seen elsewhere that you think would be helpful inspiration.

<img width="900" alt="select2" src="https://user-images.githubusercontent.com/7087312/76153298-ec033380-607e-11ea-9bb9-cc7c0781f1d9.png">

**Additional context**
Add any important details you think we need to know to make sure we build something that matches what you need.

Select2 website: https://select2.org/dropdown

**Comment by sas1ni69** [comment]
@abepark01 have you been able to make it work with Tailwind UI?

**Comment by Christophvh** [comment]
You can just override the styles inside a custom stylesheet, that's how I made it work. Also take a look at this:  https://github.com/jshjohnson/Choices Has similar functionality without jquery.

**Comment by J05HI** [comment]
Additional examples:

https://element.eleme.io/#/en-US/component/select#select

![image](https://user-images.githubusercontent.com/16399787/80517873-02928080-8986-11ea-9851-c4826400b4f2.png)

**Comment by J05HI** [comment]
Related to #93

**Comment by simonswiss** [comment]
Captured this suggestion in our "bag of ideas to consider" on the Trello roadmap 👍 

https://trello.com/c/8s98FSe9/84-multi-select-control

**Comment by hejsfj** [comment]
I would love to see something to assign employees

**Comment by gak** [comment]
Interesting to see the tailwindui ecommerce announcement when something like this isn't implemented!
