### ISSUE TITLE
DateRange Component

### ISSUE THREAD

**Issue by subramanian-suresh** [tailwindlabs/tailwindui-issues#610]
I do not see Date & DateRange component. If not possible, I would like to know what is the correct way to implement in html using tailwindcss.  I found few third party components like litepie and it requires vue.js etc.,

**Comment by davidluhr** [comment]
@subramanian-suresh Thanks for your request! This suggestion comes up often, and is actually the most popular request we receive. I've added a link to this issue to a dedicated card in our Tailwind UI public roadmap in Trello, where the community can vote for what they'd like us to add:

https://trello.com/c/jVnND6De/47-date-picker
