### ISSUE TITLE
add featured Tailwind prefix

### ISSUE THREAD

**Issue by IRediTOTO** [tailwindlabs/tailwindui-issues#612]
Hi, I need prefix my css so I add `prefix:"tw-"` in my` tailwind.config.js `file. Can you do that for TailwindUI too ? Thank you

**Comment by davidluhr** [comment]
@IRediTOTO There are some external tools you can try that should help convert existing Tailwind UI code to use prefixed classes:

https://tailwind-prefix.le-cab-politique.fr/

This closed issue has some further explanation and options: https://github.com/tailwindlabs/tailwindui-issues/issues/480

Thank you!
