### ISSUE TITLE
Copying components from devtools no longer works

### ISSUE THREAD

**Issue by bastinald** [tailwindlabs/tailwindui-issues#613]
I'm using laravel livewire so I have no need for Vue or React

I used to be able to copy iframe contents from devtools but that no longer works, because there are a bunch of extra javascript functions in the code.

Will easy-to-copy tailwind + alpine examples ever become available?

**Comment by davidluhr** [comment]
@bastinald The iframe examples still use Alpine for providing the interactivity. I believe copying the code from there should still be feasible, as that is unaffected by the React and Vue code. Is the iframe no longer showing any Alpine attributes on your end?

Please note, however, that our Alpine code is for demonstration purposes only. We cannot guarantee the same level of accessibility and resiliency as the React and Vue components from Headless UI. It's possible that Alpine might be added to Headless UI in the future, but until then, just know that what you find in the iframes is intended only to make the examples interactive.

**Comment by davidluhr** [comment]
@bastinald I'm closing this issue for now, as it seems there is nothing actionable at the moment. Feel free to reply here if you're stilling having issues, though!
