### ISSUE TITLE
Alternative side-by-side with images  in tailwind

### ISSUE THREAD

**Issue by alighasemzadeh** [tailwindlabs/tailwindui-issues#614]
![image](https://user-images.githubusercontent.com/26847446/118308444-3133b880-b501-11eb-9049-3c2072b04e01.png)

Hi Please make this image as code.

**Comment by davidluhr** [comment]
@alighasemzadeh Thanks for the suggestion! We'll consider this for future components. Over the next few months, we are working on a new Ecommerce package for Tailwind UI, so there may be some new components that are close to this example app screenshot. Keep a look out for those!
