### ISSUE TITLE
Sidebar Layouts are not in the figma file

### ISSUE THREAD

**Issue by patbranchaud** [tailwindlabs/tailwindui-issues#615]
**What component (if applicable)**
- URL for category:  https://tailwindui.com/components/application-ui/application-shells/sidebar
- Component name: application-ui/application-shells/sidebar

**Describe the bug**
I just dowloaded the figma file from your site menu and a lot of the components are missing
Sidebar Layouts is the one I need now but I was expecting all the components in the demo available in the figma so I would save time...

**To Reproduce**
1. Go to https://tailwindui.com/
2. Buy the package
3. Open the navigation menu
4. Download the Figma Assets
5. Upload to Figma
6. Realize it's missing stuff 
7. Be disappointed

**Expected behavior**
I expect to get what I pay for.

**Screenshots**
What I want :
<img width="1253" alt="Capture d’écran, le 2021-05-14 à 13 39 57" src="https://user-images.githubusercontent.com/79772987/118308466-f8242580-b4b9-11eb-8c13-5c318b0f8f9f.png">

What I see in Figma :
<img width="929" alt="Capture d’écran, le 2021-05-14 à 13 40 52" src="https://user-images.githubusercontent.com/79772987/118308524-0a9e5f00-b4ba-11eb-8faf-7284e496f3ce.png">

**Additional context**
I bought the Team License

**Comment by adamwathan** [comment]
Hey! That screenshot is not our Figma file — are you sure you opened the correct file?

This is what you should see when you first open the file (just confirmed by downloading and importing it myself):

<img width="1972" alt="image" src="https://user-images.githubusercontent.com/4323180/118309052-b6e04580-b4ba-11eb-856f-d1d977719828.png">

All of the sidebar layouts are present as expected on the "Application Shells/Sidebar Layouts" page:

<img width="1972" alt="image" src="https://user-images.githubusercontent.com/4323180/118309114-ca8bac00-b4ba-11eb-9720-4598ce0fa1f4.png">

**Comment by patbranchaud** [comment]
ok my bad!!!!!! 

Thank you very much for the quick response!
