### ISSUE TITLE
paginated tables?

### ISSUE THREAD

**Issue by thinkerytim** [tailwindlabs/tailwindui-issues#616]
Could we get some table examples showing pagination? Bonus if it's got react / vue

**Comment by davidluhr** [comment]
@thinkerytim Thanks for the suggestion! We've had related requested for tables with pagination, sorting, and filtering functionality, so I've added a link to this issue to an existing card in our Tailwind UI public roadmap in Trello. This is where the community can vote for what they'd like us to add:

https://trello.com/c/e1I5hrIX/128-interactive-data-tables-aka-data-grids
