### ISSUE TITLE
DateTime Selector with Range 

### ISSUE THREAD

**Issue by ramkumarkb** [tailwindlabs/tailwindui-issues#617]
**Screenshots**
Today in our application, we could use most of the Form elements from TailwindUI but for DateTime Range selector. For that, we used - https://projects.wojtekmaj.pl/react-datetimerange-picker/ - this is great except that styling this component using Tailwind classes turned out to be not-so-trivial.

**Additional context**
Forms are really important part of any application UI and having a DateTime selector (with range option) would be immediately useful. Thank you for considering this request.

**Comment by davidluhr** [comment]
@ramkumarkb Thanks for the suggestion! This request has come up multiple times before, so I've added a link to this issue to an existing card in our public Tailwind UI roadmap in Trello. This is where the community can vote for what they'd like us to add:

https://trello.com/c/jVnND6De/47-date-picker
