### ISSUE TITLE
Allow us to see mobile layout on main page without resizing browser window

### ISSUE THREAD

**Issue by drmanhatin** [tailwindlabs/tailwindui-issues#619]
I am building a mobile app, and its becoming a pain to have to resize my window to see how the component will look on a smaller width screen. Maybe add a button to do this?

**Comment by davidluhr** [comment]
@drmanhatin Thanks for the suggestion. I'll make note of this request with the team.

One quick workaround is to open Dev Tools and use responsive design mode to browse the site. You can even set up custom devices to swap between viewport sizes, or just keep everything at a mobile-ish size.
