### ISSUE TITLE
Scrolling testimonials

### ISSUE THREAD

**Issue by scopendo** [tailwindlabs/tailwindui-issues#622]
It would be helpful to have an example testimonial component that scrolls.  The thumbnail for testimonials in the marketing section of the Tailwind UI components gives (me) the suggestion that there's a component for scrolling through a number of testimonials, yet none of the testimonial components appears to scroll.

This would probably be good for the hero section too.

**Comment by davidluhr** [comment]
@scopendo Thanks for your request! I've added a link to this issue to our public Tailwind UI roadmap in Trello, where the community can vote for what they'd like us to add:

https://trello.com/c/go9Zaq2t/157-testimonial-section-with-scrolling-gallery-functionality
