### ISSUE TITLE
Headers Section: open menu on hover

### ISSUE THREAD

**Issue by Manubi** [tailwindlabs/tailwindui-issues#625]
Hey,
I just was wondering why TailwindUi [Header Section](https://tailwindui.com/components/marketing/elements/headers) is not using onMoseOver or similar to open the Menu? People always have to click the Link to open the menu which is an unnecessary move. Almost every site uses onHover to open the menu. Eg. [stripe](https://stripe.com) or [intercom](https://intercom.com)
![CleanShot 2021-05-25 at 11 42 43](https://user-images.githubusercontent.com/20935138/119476482-64bae200-bd4e-11eb-9ae4-77b7dca0ba38.png)

**Comment by davidluhr** [comment]
@Manubi Thanks for your feedback. Our flyout menus follow accessibility best practices and are toggled with a button click, and use [Headless UI](https://headlessui.dev/react/popover) under the hood.

Opening the menus on hover has some difficult challenges, such as preventing the menu from closing unexpectedly if the mouse leaves the menu. This is especially true when the menu and trigger button are separated visually with a gap, which is true in most cases (and is how they are designed in Tailwind UI). Some websites create an invisible region between the trigger button and the menu to ensure that hover is continuous (such as SVG path "exit areas") , but often these are quite intricate implementations, specific to a particular instance, and can still be unreliable.

Many patterns that you see commonly, even from quite prominent companies, aren't guaranteed to be accessible, or even desirable from a user experience perspective. Many users find hover menus to be unpredictable and frustrating if they close unexpectedly when trying to move their mouse to menu items.

With a quick search, here's a recent article that has a nice summary of these considerations: https://www.smashingmagazine.com/2021/05/frustrating-design-patterns-mega-dropdown-hover-menus/
