### ISSUE TITLE
Need date pickers 

### ISSUE THREAD

**Issue by ybhandari05** [tailwindlabs/tailwindui-issues#627]
**Screenshots**
Provide a screenshot of your existing solution or of examples you've seen elsewhere that you think would be helpful inspiration.

**Additional context**
Add any important details you think we need to know to make sure we build something that matches what you need.

**Comment by davidluhr** [comment]
@ybhandari05 Thank you for your request. This is a popular request in our public Tailwind UI roadmap in Trello. I've added a link to this issue to the existing card for this request:

https://trello.com/c/jVnND6De/47-date-picker
