### ISSUE TITLE
Need Rich text editor (WYSIWYG editors) please. 

### ISSUE THREAD

**Issue by ybhandari05** [tailwindlabs/tailwindui-issues#628]
**Screenshots**
Provide a screenshot of your existing solution or of examples you've seen elsewhere that you think would be helpful inspiration.

**Additional context**
Add any important details you think we need to know to make sure we build something that matches what you need.

**Comment by davidluhr** [comment]
@ybhandari05 Thanks for your request. This suggestion has come up before, so I've added a link to this issue in an existing card in our public Tailwind UI roadmap:

https://trello.com/c/YLE3v6zB/126-rich-text-wysiwyg-editor
