### ISSUE TITLE
Adobe XD Components

### ISSUE THREAD

**Issue by atreya2011** [tailwindlabs/tailwindui-issues#629]
My apologies if this is not the right place for this. 

I searched the Trello board and existing issues here and could not find any issues related to Adobe XD Component Assets.

At present, Tailwind UI provides Figma assets and I would like to know if there are any plans to provide Adobe XD assets as well?

**Comment by davidluhr** [comment]
@atreya2011 Our focus is on Figma at the moment, as that by far has the largest demand. I'll make note of this request, but currently, it's not very likely that we will be able to create a dedicated design kit for Adobe XD.

Thanks for your feedback!

**Comment by atreya2011** [comment]
@davidluhr Thank you for your swift response. Understood regarding the current demand for Figma and Adobe design kits.
