### ISSUE TITLE
Component versioning and diffs

### ISSUE THREAD

**Issue by ivosabev** [tailwindlabs/tailwindui-issues#63]
In its current form the UI library is unusable for unless you wrap everything in a components to hide the huge amount of repetitive html. But by breaking the markup and classes into components it gets really hard to keep with TailwindUI updates. 

Therefore it would be really helpful if there is a source controlled version of TailwindUI where we can do a diff of each component or an utility similar to the RN update helpers (https://react-native-community.github.io/upgrade-helper/?from=0.61.5&to=0.62.0-rc.4).

**Comment by DanHarrin** [comment]
There's a [changelog](https://www.notion.so/Tailwind-UI-Changelog-3698ab7cba254cd2bbcbcc30d132651d) that was released the other day.

**Comment by ivosabev** [comment]
I am aware of the changelog, but it doesn't list the exact +/- to the classes.

**Comment by kiliman** [comment]
I created a script that will download all the components as individual files. You can add to a local repo then periodically pull down changes to get a diff.

https://github.com/kiliman/tailwindui-crawler

**Comment by ivosabev** [comment]
Thanks for your work, I hope there is an official solution soon!

**Comment by davidluhr** [comment]
@ivosabev I've been going back to long-standing issues, so thank you for your patience. I've added this to the public roadmap for Tailwind UI in Trello, where the community can vote for what they would like to see added:

https://trello.com/c/EYcOhSwZ/130-component-versioning-diffs
