### ISSUE TITLE
Textarea component in Form Layouts is missing the border class

### ISSUE THREAD

**Issue by aespichan** [tailwindlabs/tailwindui-issues#630]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/forms/form-layouts
- Component name: Labels on left

**Describe the bug**
When copying the `textarea` component from the TailwindUI page to another project, the created text area doesn't show the expected gray border.

```
<textarea
  id="about"
  name="about"
  rows={3}
  className="max-w-lg shadow-sm block w-full focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm border-gray-300 rounded-md"
  defaultValue={''}
/>

```
**To Reproduce**
1. Go to `Labels on left` component
2. Click on 'Code' and select 'React'
3. Scroll down to 'About' section in the code
4. Copy `textarea` code and use it in another project
5. See that the created textarea doesn't have the expected gray border

**Expected behavior**
The textarea created in the other project should look as the TailwindUI page's textarea with the correct border color.

**Screenshots**
Actual behavior:
![image](https://user-images.githubusercontent.com/18277115/120040855-e1f38a80-bfcc-11eb-9abc-e63e75dee2c9.png)

Expected behaviour:
![image](https://user-images.githubusercontent.com/18277115/120041001-2aab4380-bfcd-11eb-897d-3b5068b14f0c.png)

**Additional context**
Adding the `border` class fixes the issue:
`className="max-w-lg shadow-sm block w-full focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm border border-gray-300 rounded-md"`

**Comment by davidluhr** [comment]
@aespichan Thank you for reporting this! Not sure why the `border` class was missing, but I've checked all instances of `<textarea>` in Tailwind UI to make sure it was included to make sure it renders as expected in isolation.

The fixed versions should be live on the site shortly. Thanks again!
