### ISSUE TITLE
Please build tooltips for the TailWind UI

### ISSUE THREAD

**Issue by shadrchy** [tailwindlabs/tailwindui-issues#631]
Urgently need tooltips for the TailWind UI.

**Comment by davidluhr** [comment]
@shadrchy Thanks for your request! This suggestion has come up before, so I've added a link to this issue to an existing card in our public Tailwind UI roadmap. This is where the community can vote for what they'd like to us to add:

https://trello.com/c/KVOX3uCK/56-tooltips-popups
