### ISSUE TITLE
Undeclared Index usage in React .map's

### ISSUE THREAD

**Issue by JacobJaffe** [tailwindlabs/tailwindui-issues#633]
**What component (if applicable)**
- URL for category:  https://tailwindui.com/components/marketing/sections/pricing#component-49165a9c77f14e07c2b4e18468dbfc6f
- Component name: Three tiers on brand and feature comparison

**Describe the bug**
Indexes from map functions are used without being declared.

**Screenshots**
<img width="924" alt="image" src="https://user-images.githubusercontent.com/25315679/120397586-91e73180-c306-11eb-9577-bc4b100f8a76.png">

**Comment by davidluhr** [comment]
@JacobJaffe Thank you for reporting this! We were able to catch a bug thanks to your issue, which should now be fixed. A corrected version of this page example should be live on the site shortly.

Thanks again!
