### ISSUE TITLE
Alpine JS

### ISSUE THREAD

**Issue by moulayecisse** [tailwindlabs/tailwindui-issues#636]
**Alpine JS**
Add Alpine JS support for HTML components.

**Comment by davidluhr** [comment]
@moulayecisse Thanks for your request! This suggestion has come up before, so I've added a link to this issue to an existing card in our public Tailwind UI roadmap. This is where the community can vote for what they'd like to us to add:

https://trello.com/c/8EZrsfzZ/121-provide-alpinejs-code-for-components
