### ISSUE TITLE
Tabs with underline issue

### ISSUE THREAD

**Issue by taylormaguire** [tailwindlabs/tailwindui-issues#637]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/navigation/tabs
- Component name: Tabs with underline

**Describe the bug**
`whitespace-nowrap` should be `whitespace-no-wrap` on v2 components

I would also like to suggest that the Select dropdown when tabs are on the mobile breakpoints have a placeholder option.
<option value="" disabled selected hidden>Choose an option...</option>

**Comment by davidluhr** [comment]
@taylormaguire `whitespace-nowrap` is the correct class name: https://tailwindcss.com/docs/whitespace

As for the select dropdown on mobile, there must be a selection. It is not possible to have tabs without any current tab, so a placeholder option is not necessary/possible in this use case.

Thank you!
