### ISSUE TITLE
multi level drop down

### ISSUE THREAD

**Issue by switch-cheehau** [tailwindlabs/tailwindui-issues#638]
![image](https://user-images.githubusercontent.com/82187386/120741156-1b754a00-c527-11eb-9a07-c61365b18430.png)

**Comment by davidluhr** [comment]
@switch-cheehau Thanks for your request! I've added a link to this issue to an existing card in our public Tailwind UI roadmap. This is where the community can vote for what they'd like to us to add:

https://trello.com/c/eLWZxsAv/158-multi-level-dropdown
