### ISSUE TITLE
Multi Select menu

### ISSUE THREAD

**Issue by vignejs** [tailwindlabs/tailwindui-issues#639]
It'd be great if we get an example for multi select menu with headless ui.

Here is an example from [dribble](https://dribbble.com/shots/7861235-Multi-select-UI?utm_source=Clipboard_Shot&utm_campaign=alevairi&utm_content=Multi-select%20UI&utm_medium=Social_Share&utm_source=Clipboard_Shot&utm_campaign=alevairi&utm_content=Multi-select%20UI&utm_medium=Social_Share) .
![image](https://user-images.githubusercontent.com/20106549/120763932-567e7a00-c535-11eb-9193-798ad6e22aa0.png)

**Comment by davidluhr** [comment]
@vignejs Thanks for your request! This suggestion has come up before, so I've added a link to this issue to an existing card in our public Tailwind UI roadmap. This is where the community can vote for what they'd like to us to add:

https://trello.com/c/ecLhidpB/143-pill-list-with-input
