### ISSUE TITLE
Framework specific components

### ISSUE THREAD

**Issue by jescowuester** [tailwindlabs/tailwindui-issues#64]
**the problem:**
I lose a lot of time removing all the alpinejs things and replacing it with (in my case) react code. I love using the web interface and would love to be able to just copy-paste my components directly into react.

**the sollution:**
I (and I'm sure many others) would be happy to provide you with the react (or whatever framework) code. If you could provide an option in the web interface to choose your framework and then receive the corresponding code that would be great.

**Comment by RobinMalfait** [comment]
This is not official, but I created a bookmark that allows you to convert the html to valid React code.

Take a look here: https://gist.github.com/RobinMalfait/a90e8651196c273dfa51eec0f43e1676

**Comment by simonswiss** [comment]
There will also be some official React & Vue components coming to Tailwind UI at some point, in addition to the existing HTML snippets. 🎉

Closing this, but rest assured that there will be some good stuff happening in that regard!
