### ISSUE TITLE
ring-black in navbars instead of ring-gray-300

### ISSUE THREAD

**Issue by nsursock** [tailwindlabs/tailwindui-issues#640]
**What component (if applicable)**
- URL for category: https://tailwindui.com/preview
- Component name: marketing > element > headers > centered with bottom border

**Describe the bug**
when copying pasting the code to my app, suddenly the menus had a black border instead of gray. I checked the code and it seems modifying ring-black to ring-gray-300 fixes the bug

**Expected behavior**
borders of menus should be gray

**Comment by davidluhr** [comment]
@nsursock I've checked the code and this is intentional. Please note `ring-black` is used alongside `ring-opacity-5`, which results in a subtle border. This is our go-to treatment for popup menus, in combination with a `shadow-` class.
