### ISSUE TITLE
progress bar

### ISSUE THREAD

**Issue by nsursock** [tailwindlabs/tailwindui-issues#641]
add a progress bar to tailwindui for loading indicators

**Screenshots**
https://www.creative-tim.com/learning-lab/tailwind-starter-kit/documentation/css/progressbars

**Comment by davidluhr** [comment]
@nsursock Thanks for your request! This suggestion has come up before, so I've added a link to this issue to an existing card in our public Tailwind UI roadmap. This is where the community can vote for what they'd like to us to add:

https://trello.com/c/qMtkbuST/81-progress-bars
