### ISSUE TITLE
Error Pages Design

### ISSUE THREAD

**Issue by jie10** [tailwindlabs/tailwindui-issues#643]
Hello Good Day!,

I would like to request an error pages design for 404, 403 , 405 , etc..

thank you.

**Comment by davidluhr** [comment]
@jie10 Thanks for your request! This suggestion has come up before, so I've added a link to this issue in our public Tailwind UI roadmap in Trello, where the community can vote for what they'd like us to add:

https://trello.com/c/kRQ9ko38/70-404-pages
