### ISSUE TITLE
Dropdown menu bug

### ISSUE THREAD

**Issue by jie10** [tailwindlabs/tailwindui-issues#644]
![Screenshot (5)](https://user-images.githubusercontent.com/47737350/120901786-6ef2af80-c66f-11eb-85ed-a96daecc32bb.png)

i encounter this drop down menu bug when i try to paste the header section. but when i resize to small screen it shown up. 
is there any way to fix this?

**Comment by davidluhr** [comment]
@jie10 The image on the right half has `absolute`, and is further down in the DOM, so it is sitting above the dropdown menu.

On the menu itself, you can add `z-10`, which should hopefully make it sit above the image.

Hope this helps!
