### ISSUE TITLE
With tiered sidebar navigation[Setting Screens]

### ISSUE THREAD

**Issue by alighasemzadeh** [tailwindlabs/tailwindui-issues#645]
I think navigation sidebar can be look like:
https://tailwindui.com/components/application-ui/page-examples/settings-screens#component-de918ddc41eab4f395f5e48ce2815937
 
In mobile view.

**Comment by davidluhr** [comment]
@alighasemzadeh Thanks for this suggestion! I've made note of it with the team and we'll consider ways to incorporate the tiered navigation in a mobile menu.
