### ISSUE TITLE
Request: Refactor common elements (e.g. Buttons) to be more reusable

### ISSUE THREAD

**Issue by timfee** [tailwindlabs/tailwindui-issues#646]
Hi there,

Thanks for the great resource! I found myself composing several [`Button`](https://tailwindui.com/components/application-ui/elements/buttons) elements throughout my app, and wanted to avoid `@apply` workarounds but still have a semantically meaningful way to incorporate the best practices from the site across components. 

This may be too far in the weeds, but it would be great to have some boilerplate code similar to the below: 

```tsx
import cx from 'classnames'
import { ButtonHTMLAttributes, FC } from 'react'

interface ButtonType extends ButtonHTMLAttributes<HTMLButtonElement> {
  size?: size
  theme?: theme
}

enum size {
  XS = -2,
  SM = -1,
  MD = 0,
  LG = 1
}

enum theme {
  FILLED,
  SECONDARY,
  OUTLINE
}

export const Button: FC<ButtonType> = ({
  size = 'MD',
  theme = 'FILLED',
  children,
  ...props
}) => (
  <button
    {...props}
    type='button'
    className={cx(
      'inline-flex items-center font-medium',
      {
        'shadow-sm text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500':
          theme === 'FILLED',
        'shadow-sm text-indigo-700 bg-indigo-100 hover:bg-indigo-200 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500':
          theme === 'SECONDARY',
        'border border-gray-300 shadow-sm text-gray-700 bg-white hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500':
          theme === 'OUTLINE'
      },
      {
        'px-2.5 py-1.5 text-xs rounded': size === 'XS',
        'px-4 py-2 text-sm rounded-md': size == 'SM',
        'px-4 py-2 text-base rounded-md': size === 'MD',
        'px-6 py-3 text-base rounded-md': size === 'LG'
      }
    )}>
    {children}
  </button>
)
```

**Comment by davidluhr** [comment]
@timfee This is a nice approach! I agree that this is probably too opinionated for us to provide directly in Tailwind UI. We can't predict how many/which type of buttons each customer's project will use, so it would be difficult to provide a component without a bloated API. We definitely encourage users to componentize patterns instead of using `@apply`, but we can't necessarily provide the components in a way that best suits everyone's unique needs.
