### ISSUE TITLE
Sidebar Navigation - Page Section

### ISSUE THREAD

**Issue by kevmille** [tailwindlabs/tailwindui-issues#647]
I would like to request a sidebar navigation for the page section similar to the following website:

[https://cdp-japan.jp/english](https://cdp-japan.jp/english)

I really like how the hamburger and closing icons. 

**Screenshots**
Provide a screenshot of your existing solution or of examples you've seen elsewhere that you think would be helpful inspiration.

<img src="https://res.cloudinary.com/hakata/image/upload/v1623673328/cdpj-1_g9mmqd.png" />

<img src="https://res.cloudinary.com/hakata/image/upload/v1623673329/cdpj-2_qnzye3.png" />

**Additional context**
I want to use this for an Indian restaurant website. I have a current website with one of the TailwindUI flyout menus but I need to add more links. The flyout menu is limited for content. If I had too much links, the menu will flow off screen to the bottom.

**Comment by davidluhr** [comment]
@kevmille Thank you for your request. This is beyond the scope of Tailwind UI to create bespoke patterns and designs that don't fit within the existing design language of the rest of the components.

I would encourage you to use the sidebar navigation components as a helpful reference or starting place in creating a custom component that more closely aligns with the screenshots you provided. For example, you could adapt the existing sidebar and mobile menu components to have a wider width when expanded, and modify the layout as needed.

You can also use [Headless UI](https://headlessui.dev/) to get all the needed functionality, without any styling, which would allow you to build it exactly how you want.

We aren't likely to build this pattern into Tailwind UI, but I hope this helps with your specific project.
