### ISSUE TITLE
Strange layout issue when opening dropdown control - Dropdown (Simple)

### ISSUE THREAD

**Issue by rax-pinchpop** [tailwindlabs/tailwindui-issues#648]
Hi, 

I've come across a strange layout and styling issue with the dropdown control. Please see the details under the description section.

**Dropdowns**
- URL for category:  https://tailwindui.com/components/application-ui/elements/dropdowns
- Component name: Dropdowns - Simple

**Describe the bug**
On opening the the dropdown, styling on the list of items is not applied. Instead, styling is applied as the mouse hovers over each item. 

The recording of the issue can be found here:
https://user-images.githubusercontent.com/68146860/121913648-7aa63c00-cd29-11eb-9c7b-20464ad5d95a.mov

Example project:
[tailwindplayground.zip](https://github.com/tailwindlabs/tailwindui-issues/files/6649396/tailwindplayground.zip)

**To Reproduce**
1. Follow Tailwind steps to create a new Vue (javascript) project using Vite
2. Follow steps in TailwindUI to install TailwindUI components
3. Create a new component with the Simple Dropdown component
4. Run the project using npm run dev
5. Click on button to dropdown the list of items. Button is called Options in the example in TailwindUI components
6. No styling is applied to the opened items
6. Hover over each item in the opened dropdown and see the styling being applied.

**Expected behavior**
The dropdown items are styled when the list is opened.

Screen Shot
![Screenshot 2021-06-14 at 16 14 51](https://user-images.githubusercontent.com/68146860/121916025-ade9ca80-cd2b-11eb-8fec-db6fd9e8ba9b.png)

![Screenshot 2021-06-14 at 16 15 37](https://user-images.githubusercontent.com/68146860/121916147-cb1e9900-cd2b-11eb-9220-36794065f055.png)

**Browser/Device (if applicable)**
 - OS: macOS Cataline version 10.15.7
 - Browser Chrome, Firefox
 - Version Chrome Version 91.0.4472.101 (Official Build) (x86_64). 
 - Vue 3 (3.0.5)
 - Vite 2.3.7

**Additional context**
I have also managed to replicate the issue using the headless example using the code snippet for the Menu (Dropdown) example

Any help with this would be really appreciated. Thank you.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

This should be fixed, and will be available in the next release.
You can already try it using `npm install @headlessui/vue@dev` or `yarn add @headlessui/vue@dev`.

**Comment by rax-pinchpop** [comment]
Nice! that was quick and yes it worked.

I assume I should close this issue once the new release is officially available.

BTW love the work you guys are doing.

**Comment by rax-pinchpop** [comment]
Fixed in @headlessui/vue: 1.3.0
