### ISSUE TITLE
[JIT] Tailwind does not update classes after saving in NextJS

### ISSUE THREAD

**Issue by Seanmclem** [tailwindlabs/tailwindui-issues#649]
A Clone of [this issue](https://github.com/tailwindlabs/tailwindcss/issues/4081), to try and get a real fix

> What version of Tailwind CSS are you using?
> 2.1
> 
> What build tool (or framework if it abstracts the build tool) are you using?
> "next": "10.1.3", 
> What version of Node.js are you using?
> v14.15.1
> 
> What browser are you using?
> chrome
> 
> What operating system are you using?
> macOS for M1
> 
> Reproduction repository
> https://github.com/mwarger/next-tailwind-jit-repro
> 
> Describe your issue
> I've also put reproduction instructions in the repro repo.
> 
> It seems that changes made while in jit mode are not being picked up. As it stands now, with jit mode enabled, only initial styles are applied, and kept. Any changes or additions result in loss of styles. Please advise. Thanks!

**Comment by davidluhr** [comment]
@Seanmclem This is the place for reporting Tailwind UI issues, not Tailwind CSS. I am closing this issue for now. I would encourage you to add a reply to the original issue you linked, so we can keep track of everything there. Thank you!

**Comment by Seanmclem** [comment]
> @Seanmclem This is the place for reporting Tailwind UI issues, not Tailwind CSS. I am closing this issue for now. I would encourage you to add a reply to the original issue you linked, so we can keep track of everything there. Thank you!

Sure thanks I'll do that. I created my issue here because this was the support link for TailwindUI.
