### ISSUE TITLE
Complete card views

### ISSUE THREAD

**Issue by fillipvt** [tailwindlabs/tailwindui-issues#65]
**Screenshots**
![](https://miro.medium.com/max/5004/1*bQvhdLvbMqMtijZ5t11f1w.jpeg)
![](https://www.webdesignerdepot.com/cdn-origin/uploads/2017/01/facebookdesign.jpg)

**Additional context**
There are several possibilities here. The card has 3 sections: 

- Header: user, title, actions, etc.
- Content: text, images, video
- Actions: buttons (of diff styles), links, etc. 

I understand we have already [card headings](https://tailwindui.com/components/application-ui/headings/card-headings) but, as for now, a complete card is missing. Especially if it takes into account the different states it could have: hover, focus active and the different orders in which these 3 elements can be organized in.

**Comment by austriker27** [comment]
I agree! In the past I've taken the cards from the tailwindCSS [docs](https://tailwindcss.com/components/cards/) edited them, but it would be great to have cards in tailwindUI!

**Comment by evdama** [comment]
should go onto https://trello.com/b/Nh6e9w8Q/tailwind-ui-roadmap

**Comment by simonswiss** [comment]
Nice one! 👍

Capturing this in our "bag of ideas" on the Trello roadmap. If it becomes a popular demand, we'll consider building it! 🎉 https://trello.com/c/jJf13sIa/83-media-cards
