### ISSUE TITLE
Selected row colour in Simple table radio group should not be text-gray-900

### ISSUE THREAD

**Issue by Krystofee** [tailwindlabs/tailwindui-issues#650]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/forms/radio-groups
- Component name: Simple table

**Describe the bug**
I may be mistaken, but I think the selected row text should be `text-indigo-900` like it's in similar components. There is just `text-gray-900` and I think it was just left out.

**To Reproduce**
Look on selected row Business.

**Expected behavior**
It should be `text-indigo-900`.

**Screenshots**
![Snímek obrazovky 2021-06-15 v 13 13 24](https://user-images.githubusercontent.com/24443367/122043717-f365d080-cddb-11eb-8a4f-2960884c6d71.png)

**Comment by davidluhr** [comment]
@Krystofee Thank you for reporting this. You are correct; the intention was to have the actively selected option text be `text-indigo-900`.

The fixed version should be live on the site shortly. Thanks again!

**Comment by kevinvayro** [comment]
I'm not 100% sure if this is a new issue as a result of fixing the original concern but the code (in the React example) now shows as following on the `RadioGroup.Label` component.

```
className={classNames(
  not - checked ? 'text-gray-900' : '',
  checked ? 'text-indigo-900' : '',
  'ml-3 font-medium'
)}
```
This causes and error on loading the page as `not` is undefined. I've not seen the `not - ???` syntax before so I can't say for sure that it is an error and I'm just doing something incorrectly but the following code produces the intended result in one line and is also the same syntax used in other examples.

```
className={classNames(
  checked ? 'text-indigo-900' : 'text-gray-900',
  'ml-3 font-medium'
)}
```
