### ISSUE TITLE
Getting "Can't call "this.setState" on an unmounted component." with Preact when pages include headlessUI

### ISSUE THREAD

**Issue by FelDev** [tailwindlabs/tailwindui-issues#651]
**Describe the bug**
I'm using Gatsby with Preact and Tailwind UI. 

If - and only if - my pages contain components from Headless UI, I get this warning message multiples times when navigating to another page using [Gatsby's Link](https://www.gatsbyjs.com/docs/reference/built-in-components/gatsby-link/):

```
Can't call "this.setState" on an unmounted component. 
This is a no-op, but it indicates a memory leak in your application. 
To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
```

**To Reproduce**
I made a minimal example: https://github.com/FelDev/headlessui_bug_repro
1. Clone the repo, run `npm i` and `npm run start` 
2. Go to http://localhost:8000
3. Click on "page 2"
4. Look at the warnings in the console

What I did is:
1. Take the first example at https://tailwindui.com/components/application-ui/forms/radio-groups without changing anything  and made it a component, `RadioDemo.js`.
2. Used it pretty much like this:
 ```js
import RadioDemo from '../components/RadioDemo'

export default function example() {
  return <RadioDemo />
}
```
3. That's it. The warning is thrown about 17 times when clicking on a `<Link>` to another page even though there's no async call or setTimeouts or the like.

Also, if I remove everything inside `<RadioGroup>` and leave only this:
```js
    <RadioGroup value={selected} onChange={setSelected}>
      <RadioGroup.Label className="sr-only">Server size</RadioGroup.Label>
    </RadioGroup>
``` 

The warning is thrown only once because of `<RadioGroup.Label>` (it doesn't happen at all if I remove it the label).

---

**Browser/Device (if applicable)**
 - OS: Big Sur
 - tested in chrome, firefox and safari

---

This only happens when using Preact.

**Comment by FelDev** [comment]
UPDATE: ok, so seconds after posting this I realized the big difference between our project and my repro is that we use Preact and not the minimal repro.

Digging...

**Comment by davidluhr** [comment]
@FelDev Thank you for reporting this, and for all the great details and the reproduction. We really appreciate all your effort in helping us figure out the cause of the issue.

@RobinMalfait Do you have insights into why this may be happening? Seems like it's related to components unmounting on SPA route changes?

**Comment by reinink** [comment]
Hey thanks for submitting this. Unfortunately we don't support Preact in Headless UI.

That said, I'm not sure that this is even an issue related to Headless UI, as we don't use `this.setState` anywhere in that library.
