### ISSUE TITLE
Knowledge base landing page components

### ISSUE THREAD

**Issue by btkostner** [tailwindlabs/tailwindui-issues#654]
**Screenshots**
![support zendesk com_hc_en-us](https://user-images.githubusercontent.com/3385679/122483231-5ba8e380-cf8f-11eb-9370-c81a2096117c.png)
from https://support.zendesk.com/

![help moonfruit com_en_](https://user-images.githubusercontent.com/3385679/122483305-82671a00-cf8f-11eb-9ad6-b2a60bd0aa33.png)
from http://help.moonfruit.com/en/

![help piwik pro_](https://user-images.githubusercontent.com/3385679/122484425-d3780d80-cf91-11eb-8a2d-3aecfe159e1d.png)
from https://help.piwik.pro/

**Additional context**
Looking at different knowledge base and help guide landing pages I can see a couple of missing components that would be nice to add. I know there is a marketing contact page with overlapping cards example, but the screenshots above show more article links and categories. Overall, they are much more content heavy than regular marketing pages. They also (typically) do not have great marketing images making displaying a group of them and making it look nice, very difficult.

- Hero components. The current ones designed are focused on selling, or getting the user to sign up. Knowledge bases commonly have just a huge search bar.
- A list of categories (with maybe a couple of child articles.)

**Comment by davidluhr** [comment]
@btkostner Thanks for your request! Ive added a link to this issue in our public Tailwind UI roadmap in Trello, where the community can vote for what they'd like us to add:

https://trello.com/c/iPvezZca/159-knowledge-base-help-guide-landing-pages
