### ISSUE TITLE
`sociallink` is not defined

### ISSUE THREAD

**Issue by merelinguist** [tailwindlabs/tailwindui-issues#655]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/marketing/page-examples/pricing-pages
- Component name: With three tiers and feature comparison

**Describe the bug**

See the footer:

```jsx
<div className="flex space-x-6">
	{footerNavigation.social.map((socialLink) => (
		<a key={socialLink.name} href={socialLink.href} className="text-gray-400 hover:text-gray-500">
			<span className="sr-only">{socialLink.name}</span>
			<sociallink.icon className="h-6 w-6" aria-hidden="true" />
		</a>
	))}
</div>
```

On line 868, `sociallink.icon` is wrong - it should be `socialLink.icon`.

**Comment by bradlc** [comment]
Thanks for reporting, this is now fixed 👍
