### ISSUE TITLE
Simplicity

### ISSUE THREAD

**Issue by lotestudio** [tailwindlabs/tailwindui-issues#656]
First of all: good work.
I'd like to see more simple components in:
- containers and layouts without "design noise" of nav and side bars which use best practice for responsive design.
- form elements without complexity of full forms

I don't need to build another bootstrap like framework, but more easily to grab the components from complex examples that you build.

**Comment by davidluhr** [comment]
@lotestudio Thank you for your suggestion. I'll make note of this request with the team for future components.
