### ISSUE TITLE
Dark and colors themes

### ISSUE THREAD

**Issue by lotestudio** [tailwindlabs/tailwindui-issues#657]
It will be good if components has options for dark and different color themes.

**Comment by davidluhr** [comment]
@lotestudio Thanks for your request! This suggestion has come up before, so I've added a link to this issue in our public Tailwind UI roadmap in Trello, where the community can vote for what they'd like us to add:

https://trello.com/c/7JQsz9og/120-create-dark-mode-versions-of-components
