### ISSUE TITLE
Pagination example is missing from the figma UI kit

### ISSUE THREAD

**Issue by robbevp** [tailwindlabs/tailwindui-issues#659]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/navigation/pagination
- Component name: Card footer with page buttons

**Describe the bug**
The card footer with page buttons (1 2 3 ... 7 8 9 ), not just next & previous seems to be missing from the figma kit (ver 2021/5/7).

The page Navigation / Pagination does contain an component named card footer with page buttons, but this does not correspond to the example from the website.
The page Parts does contain some pagination elements, but nothing to quickly generate a pagination with page number styled as buttons.

**Expected behavior**
I expected to find a component/example of pagination with page numbers as a large button group, since it is present on the website

**Browser/Device (if applicable)**
 -  Figma kit ver 2021-05-07

**Comment by davidluhr** [comment]
@robbevp Good catch! This is definitely a mistake, where I accidentally kept the mobile UI on desktop. I'll be sure to get this updated and we'll have the corrected version in the next Figma kit update.

Thank you for reporting this!

**Comment by robbevp** [comment]
@davidluhr Thanks!
Is there a way to know when a new version of the kit of released? Or does this always coincide with an update to Tailwind UI?
