### ISSUE TITLE
Issue with Input field in Form Components

### ISSUE THREAD

**Issue by lintonmack** [tailwindlabs/tailwindui-issues#661]
**What component (if applicable)**
- URL for category:  https://tailwindui.com/components/application-ui/forms/form-layouts
- Component name:  All components with Input field in this category.

**Describe the bug**
The text input fields seem to not be adopting the majority of their styles and look different to the forms on the form layout components page. The rest of the attributes for the form, e.g. the select's and text areas look fine.

**To Reproduce**
1. Go to https://tailwindui.com/components/application-ui/forms/form-layouts.
2. Click on the top component, select the code, copy the code into nextjs component.
3. Run server in dev.
4. See most styles aren't applied to the input.

**Expected behavior**
The inputs should adopt the same styles as shown in the example on the website.

**Screenshots**

**Browser/Device (if applicable)**
 - Browser: Chrome
 - Version Version 91.0.4472.114 (Official Build) (x86_64)

**Additional context**

**Comment by davidluhr** [comment]
@lintonmack I believe you are missing the `@tailwindcss/forms` plugin: https://github.com/tailwindlabs/tailwindcss-forms

At the top of the code for each component, we have a comment that notes any additional dependencies. For example, at the top of the code for the component you linked is the following:
```html
/*
  This example requires Tailwind CSS v2.0+ 
  
  This example requires some changes to your config:

  // tailwind.config.js
  module.exports = {
    // ...
    plugins: [
      // ...
      require('@tailwindcss/forms'),
    ]
  }
*/
```

With the forms plugin in place, I added the component to a fresh NextJS setup, and everything appears as expected.

Can you verify that you have the plugin in your project and let me know if it works? Thank you!

**Comment by lintonmack** [comment]
Hey @davidluhr,

Thank you for looking into this for me. 
I checked the config and I did not have the plugin installed. I have installed it and added it to the plugins config and it works great.
Thank you for you help with this.
