### ISSUE TITLE
Svelte support on components

### ISSUE THREAD

**Issue by georgedalai** [tailwindlabs/tailwindui-issues#663]
**Screenshots**
Provide a screenshot of your existing solution or of examples you've seen elsewhere that you think would be helpful inspiration.

**Additional context**
Add any important details you think we need to know to make sure we build something that matches what you need.

**Comment by davidluhr** [comment]
@georgedalai Thank you for this suggestion! I've made note of this with the team to consider adding Svelte support in the future.
