### ISSUE TITLE
Tailwind UI Figma library is missing layouts that are listed in the Components screens

### ISSUE THREAD

**Issue by danieljarrett74** [tailwindlabs/tailwindui-issues#664]
There's a number of layouts listed on the components screens that don't have corresponding figma components.  It's a bit frustrating when you're using the web components pages as a reference for your UX person and they can't reproduce it without creating a layout from scratch.

**Comment by davidluhr** [comment]
@danieljarrett74 If this in reference to Page Examples, those are beyond the scope of the Figma kit. Page Examples are intended to demonstrate what's possible using Tailwind UI components to create pages with very specific use cases. They can be created using the components provided in the kit, and customers have found it's a good learning challenge if they are new to the kit/Figma to use and adapt the provided components.
