### ISSUE TITLE
click events dont' work on small screen

### ISSUE THREAD

**Issue by AndreiMotinga** [tailwindlabs/tailwindui-issues#666]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/page-examples/home-screens
- Component name: first home screen

**Describe the bug**
trying to add dropdowns, it's inclear where to add click events. 
on small screen right menu doesn't work, because z-index issues.  click isn't being registered on appropriate element. 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Browser/Device (if applicable)**

**Additional context**

**Comment by davidluhr** [comment]
@AndreiMotinga Can you provide detail on what isn't working?

Are you building dropdown components from scratch? If so, can you elaborate on what you're adding click events to, and how z-index is affecting this?

While Headless UI currently supports React and Vue, our Accessibility Notes on the provided functionality is a handy reference for building components on your own: https://headlessui.dev/react/menu#accessibility-notes

I'm closing this issue for now, as this is beyond the scope of Tailwind UI, but feel free to reply here with further questions.

**Comment by aboyer1013** [comment]
I ran into the same thing. The z-indexing was causing the click event not to fire. I had to add `pointer-events-none` and `pointer-events-auto` so the user can click behind the element.

Example bug is located on the [Marketing section > Heroes component > HTML code viewer](https://tailwindui.com/components/marketing/sections/heroes#component-a3c09c7a3b8f4bd90d280722eaff9634)

Excerpt from the HTML
```
<!--
  Mobile menu, show/hide based on menu open state.

  Entering: "duration-150 ease-out"
    From: "opacity-0 scale-95"
    To: "opacity-100 scale-100"
  Leaving: "duration-100 ease-in"
    From: "opacity-100 scale-100"
    To: "opacity-0 scale-95"
-->
<div class="absolute z-10 top-0 inset-x-0 p-2 transition transform origin-top-right md:hidden">
```

The `<div>` needs to have a `pointer-events-none` when the menu is closed, and `pointer-events-auto` when the menu is closed. Hope this helps.

Fix when menu is in closed state:
```
<div class="pointer-events-none absolute z-10 top-0 inset-x-0 p-2 transition transform origin-top-right md:hidden">
```

Fix when menu is in opened state:
```
<div class="pointer-events-auto absolute z-10 top-0 inset-x-0 p-2 transition transform origin-top-right md:hidden">
```
