### ISSUE TITLE
Radio buttons are 

### ISSUE THREAD

**Issue by uncvrd** [tailwindlabs/tailwindui-issues#667]
**What component (if applicable)**
- URL for category: 
- Component name: 

**Describe the bug**

![image](https://user-images.githubusercontent.com/25097099/123763832-0b782e00-d879-11eb-929a-b455802d709c.png)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Browser/Device (if applicable)**

**Additional context**

**Comment by davidluhr** [comment]
@uncvrd Thank you for reporting this. This bug has been fixed in a recent update, so I'm closing this issue, but appreciate you letting us know!

**Comment by uncvrd** [comment]
@davidluhr apologies on the duplicate issue here!! Not quite sure how that happened haha. Thanks for closing
