### ISSUE TITLE
Make component name searchable through Cmd+K

### ISSUE THREAD

**Issue by kylemilloy** [tailwindlabs/tailwindui-issues#669]
This is a feature for the tailwind website which deals more with my experience on building designs for my team to integrate.

Right now we can search at a high-level for components by their category...example "Feature Sections", "Hero Sections", etc. What we're finding is that the naming convention in Figma doesn't quite align to this and when I bring components into a design they're listed in designs as "4-column with newsletter dark/Desktop" or "With large screenshot/Desktop". With read-only access the dev might not be able to access the component to see what page it has come from.

It would be great if I could search by these component names on the site so that when my devs start building it they can easily find the components on the site with Cmd+K. Alternatively, including "Feature Section" or whatever section it came from in the component name in Figma would be great (which is a fix we're doing now...but sometimes we forget)

**Screenshots**
![Screen Shot 2021-06-29 at 09 55 18](https://user-images.githubusercontent.com/15757117/123830268-61bc8f80-d8c0-11eb-89b4-da89a86fee04.png)
![Screen Shot 2021-06-29 at 09 56 05](https://user-images.githubusercontent.com/15757117/123830271-62552600-d8c0-11eb-8392-7798c6632617.png)

This would be the preferable end goal...
![Screen Shot 2021-06-29 at 10 01 14](https://user-images.githubusercontent.com/15757117/123830870-f58e5b80-d8c0-11eb-9782-ffdecda1220d.png)

**Comment by davidluhr** [comment]
@kylemilloy Thanks for your suggestion! I've added a link to this issue in our public Tailwind UI roadmap in Trello, where the community can vote for what we should add:

https://trello.com/c/tNKVIa2U/161-make-component-names-searchable
