### ISSUE TITLE
Knowledge Base Article

### ISSUE THREAD

**Issue by platomedical** [tailwindlabs/tailwindui-issues#670]
**Example**
https://stripe.com/docs/billing/customer

**Comment by davidluhr** [comment]
@platomedical Thanks for your suggestion! This idea has come up before, so I've added a link to this issue to an existing card in our public Tailwind UI roadmap in Trello, where the community can vote for what we should add:

https://trello.com/c/iPvezZca/159-knowledge-base-help-guide-landing-pages
