### ISSUE TITLE
Add Svelte support

### ISSUE THREAD

**Issue by fabiot21** [tailwindlabs/tailwindui-issues#671]
It would be nice if you add Svelte support!

The trend is clear over React or Vue... https://2020.stateofjs.com/en-US/technologies/front-end-frameworks/

Thank you!

**Comment by davidluhr** [comment]
@fabiot21 Thanks for your suggestion! I've added a link to this issue in our public Tailwind UI roadmap in Trello, where the community can vote for what we should add:

https://trello.com/c/jIF9tZpZ/162-add-svelte-code-output
