### ISSUE TITLE
Row height in two column FAQ is affected by content in a different row

### ISSUE THREAD

**Issue by rahimnathwani** [tailwindlabs/tailwindui-issues#672]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/marketing/sections/faq-sections
- Component name: Two columns

**Describe the bug**
When the answer to one of the questions is very long, it affects the vertical height of the following row.

**To Reproduce**
1) Start with the 6 FAQ items in the example.
2) Edit the answer for 'Why do you never see elephants hiding in trees?' so that it's 10x as long as the other answers.

**Expected behavior**
The vertical size of the other answer on the same row increases.
Other rows maintain their vertical height.

**Screenshots**
https://imgur.com/jZsmr0K.png

**Browser/Device (if applicable)**
 - MacOS
 - Chrome
 - Latest

**Comment by davidluhr** [comment]
@rahimnathwani Thank you for reporting this! Looks like there was an unnecessary `md:grid-rows-2` class, which was explicitly setting rows to all have the same height. The correct version should be live on the site soon.

Thanks for helping us improve the components!
