### ISSUE TITLE
We want a Loading component

### ISSUE THREAD

**Issue by lelelaileabc** [tailwindlabs/tailwindui-issues#674]
We want a Loading component, like：https://element-plus.gitee.io/#/en-US/component/loading

Thanks!

**Screenshots**
Provide a screenshot of your existing solution or of examples you've seen elsewhere that you think would be helpful inspiration.

**Additional context**
Add any important details you think we need to know to make sure we build something that matches what you need.

**Comment by davidluhr** [comment]
@lelelaileabc Thanks for your suggestion! This idea has come up a few times before, so I've added a link to this issue to an existing card in our public Tailwind UI roadmap in Trello, where the community can vote for what we should add:

https://trello.com/c/whj4CPQS/48-loading-spinners-skeletons
