### ISSUE TITLE
Background patterns, wave & angled borders

### ISSUE THREAD

**Issue by EricBusch** [tailwindlabs/tailwindui-issues#675]
One thing I always find myself struggling with when designing a site are the repeating background patterns, images as backgrounds and wavy/angled borders.

I would like to see a component group which included:

- Various repeating background patterns
- Various background image techniques
- Wavy & angled horizontal and vertical "borders"

Here are some examples of the above requests.

### Repeating background patterns
<img width="1346" alt="Screen Shot 2021-07-09 at 9 58 36 AM" src="https://user-images.githubusercontent.com/12106436/125089396-59bcd680-e09c-11eb-9a1e-8ed55770bd23.png">

### Wavy background patterns
<img width="1247" alt="Screen Shot 2021-07-09 at 9 55 39 AM" src="https://user-images.githubusercontent.com/12106436/125089408-5b869a00-e09c-11eb-9480-0f10d13cf825.png">

### Multi-angled border
<img width="1156" alt="Screen Shot 2021-07-09 at 9 52 05 AM" src="https://user-images.githubusercontent.com/12106436/125089413-5b869a00-e09c-11eb-968b-a5c6f79d6ac7.png">

### Top-Angled border
<img width="1156" alt="Screen Shot 2021-07-09 at 9 51 10 AM" src="https://user-images.githubusercontent.com/12106436/125089415-5c1f3080-e09c-11eb-93f9-aeb61815b943.png">

### Background image
<img width="1286" alt="Screen Shot 2021-07-09 at 9 49 37 AM" src="https://user-images.githubusercontent.com/12106436/125089418-5cb7c700-e09c-11eb-8a50-758d4810f650.png">

### Border shape
<img width="1333" alt="Screen Shot 2021-07-09 at 9 48 26 AM" src="https://user-images.githubusercontent.com/12106436/125089426-5de8f400-e09c-11eb-8468-feb76e2205d9.png">

### Background pattern (circle)
<img width="949" alt="Screen Shot 2021-07-09 at 9 47 23 AM" src="https://user-images.githubusercontent.com/12106436/125089427-5de8f400-e09c-11eb-8736-4e1dc9e5b156.png">

### Another angled border
<img width="1231" alt="Screen Shot 2021-07-09 at 9 45 00 AM" src="https://user-images.githubusercontent.com/12106436/125089431-5e818a80-e09c-11eb-834c-a6698d3c2e35.png">

Thanks!

**Comment by davidluhr** [comment]
@EricBusch

Our Page Examples in Tailwind UI often feature various background treatments and decorative elements to give some initial ideas. Here are a couple examples:

- https://tailwindui.com/components/marketing/page-examples/landing-pages#component-c574f863382921bf9af9611c55f30ecc
- https://tailwindui.com/components/marketing/page-examples/landing-pages#component-c574f863382921bf9af9611c55f30ecc

As for repeating background patterns, I'd recommend Hero Patterns, which was created by none other than Steve Schoger 😉

https://www.heropatterns.com/
