### ISSUE TITLE
Can't have a key:="" in a template tag

### ISSUE THREAD

**Issue by ccleve** [tailwindlabs/tailwindui-issues#676]
**What component (if applicable)**
https://tailwindui.com/components/application-ui/application-shells/stacked

**Describe the bug**
Lines 17 and 102: 
[vue/no-v-for-template-key]
'<template v-for>' cannot be keyed. Place the key on real elements instead.
eslint-plugin-vue

This isn't just eslint fussing. You really can't do this. :key="item" must be on a div or another real element. In the case of the line 17 bug, you have to put it on both of the enclosed &lt;a> tags.

I strongly recommend you develop your Vue components using VS Code with the Vetur plugin. Bugs of this nature will appear in red at design time.

**Comment by bradlc** [comment]
Thanks for reporting, this is now fixed 👍
