### ISSUE TITLE
Files/Documents

### ISSUE THREAD

**Issue by iam-pac-man** [tailwindlabs/tailwindui-issues#68]
Thank you for the awesome UI components! I suggest a file/document component or even a layout.

**Screenshots**
![documents@2x](https://user-images.githubusercontent.com/15112900/76173895-ea7f5b80-61a3-11ea-816e-34074dd70dc3.png)
![file-qSGZlQGOLU](https://user-images.githubusercontent.com/15112900/76173890-e18e8a00-61a3-11ea-81c7-537782786f27.gif)
<img width="1440" alt="Screen Shot 2020-03-09 at 1 16 12 AM" src="https://user-images.githubusercontent.com/15112900/76173893-e7846b00-61a3-11ea-8445-6052a683731c.png">

**Comment by simonswiss** [comment]
Nice one! 👍

Capturing this in our "bag of ideas" on the Trello roadmap. If it becomes a popular demand, we'll consider building it! 🎉 
https://trello.com/c/RkV9zhrH/82-files-documents
