### ISSUE TITLE
Skeleton State UI

### ISSUE THREAD

**Issue by sfearl1** [tailwindlabs/tailwindui-issues#680]
**Screenshots**
<img src="https://cssgurubd.files.wordpress.com/2017/07/skeleton_screen.png" />

**Additional context**
Skeleton state / component to indicate something is happening while data is loading. Usually represented by a series of animated placeholders.

**Comment by ordago** [comment]
I think the skeleton is usually dependent on the data it's loading.

Anyway, you have an example here:
https://tailwindcss.com/docs/animation#pulse

**Comment by davidluhr** [comment]
@sfearl1 Thanks for your suggestion! This idea has come up before, so I've added a link to this issue to an existing card in our public Tailwind UI roadmap in Trello, where the community can vote for what we should add:

https://trello.com/c/whj4CPQS/48-loading-spinners-skeletons
