### ISSUE TITLE
Couldn't find these pages on Figma

### ISSUE THREAD

**Issue by furkanarius** [tailwindlabs/tailwindui-issues#682]
Hi,

I couldn't find these pages on Figma. Will they be added later?

https://tailwindui.com/components/application-ui/page-examples/detail-screens
https://tailwindui.com/components/application-ui/page-examples/home-screens
https://tailwindui.com/components/application-ui/page-examples/settings-screens

**Comment by davidluhr** [comment]
@furkanarius Page examples are intended to be demonstrations of how TailwindUI components can be combined to create different designs and serve different use cases. The Figma kit does not include them for this reason, but it is possible to re-create them quickly using the components provided by the kit. Plus, it can be a good learning challenge for those who are new to the kit/Figma and want experience working with components.

Thanks!
