### ISSUE TITLE
Progress componet

### ISSUE THREAD

**Issue by lelelaileabc** [tailwindlabs/tailwindui-issues#685]
we need Progress componet , thanks

**Screenshots**
Provide a screenshot of your existing solution or of examples you've seen elsewhere that you think would be helpful inspiration.

**Additional context**
Add any important details you think we need to know to make sure we build something that matches what you need.

**Comment by davidluhr** [comment]
@lelelaileabc The Steps components are progress components: https://tailwindui.com/components/application-ui/navigation/steps

Hope this helps!
