### ISSUE TITLE
Loader/Loading Component

### ISSUE THREAD

**Issue by austriker27** [tailwindlabs/tailwindui-issues#69]
It would be awesome to have a simple loader component. It would be animated. I know loaders can pretty subjective design-wise so I trust your judgement on making it fit the tailwind designs. Also I have no idea how to make it customizable with tailwind css. Hmmm 🤔

## examples:
Google's: 
![tenor](https://user-images.githubusercontent.com/14855925/76181765-7632c100-617f-11ea-858d-051736f4d0ee.gif)

Old school: 
![giphy](https://user-images.githubusercontent.com/14855925/76181769-7af77500-617f-11ea-9c32-4c8173effb58.gif)

Thanks a lot!

**Comment by J05HI** [comment]
Related to #121

**Comment by simonswiss** [comment]
Nice one - consolidating with other skeleton/loading requests at https://github.com/tailwindlabs/tailwindui-issues/issues/121
