### ISSUE TITLE
More realistic tables

### ISSUE THREAD

**Issue by MarcelMalik** [tailwindlabs/tailwindui-issues#691]
The tailwind ui tables look great (https://tailwindui.com/components/application-ui/lists/tables), but there are not one-to-one usable in a realistic environment.

Problem 1: If they are more rows in the table, than place is on the screen, we lose the header, if the user scrolls down
Solution: Please provide a design with sticky headers.

Problem 2: The tables don't have horizontal scrolling. It looks like they have, but the scrolling is defined for the complete page and not only for the table.
Solution: Please provide a design with horizontal (and vertically) scrolling inside the table.

**Comment by davidluhr** [comment]
@MarcelMalik Thanks for this suggestion!

1. I've added a link to this issue to our public Tailwind UI roadmap in Trello, where the community vote for what we should add: https://trello.com/c/kwSGrxGE/160-tables-with-sticky-headers
2. The scrolling is localized to the table components. The couple layers of wrapping `<div>` elements in the component code enable the scrolling, and can be placed inside any other elements as needed. The table does not rely on the page for scrolling.
