### ISSUE TITLE
Support Ticket Chain Component

### ISSUE THREAD

**Issue by AlexWinder** [tailwindlabs/tailwindui-issues#695]
I maintain a support system which makes use of ticketing functionality. It would be a great addition to include a support ticket chain component which allows full view of replies in a clean interface.

Feeds (https://tailwindui.com/components/application-ui/lists/feeds) seem to be the closest thing to what you already have availabel but these seem to be quite limited in the amount of information which is displayed.

**Screenshots**

![image](https://user-images.githubusercontent.com/24867605/127854805-252ad53d-859e-43a4-b353-28df970034a6.png)

**Additional context**

Typical details shown on such tickets are:

- Author
- Date
- Body of ticket response
- Attachments
- Meta info such as IP address, user agent

**Comment by davidluhr** [comment]
@AlexWinder Thanks for your suggestion! I've added a link to this issue in our public Tailwind UI roadmap in Trello, where the community can vote for what we should add:

https://trello.com/c/Ct1I3Xre/163-message-reply-thread
