### ISSUE TITLE
Slide-Overs (Dialog) have no option to disable close on click outside

### ISSUE THREAD

**Issue by joshgdale** [tailwindlabs/tailwindui-issues#697]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/overlays/slide-overs
- Component name: Slide Over (HeadlessUI Dialog)

**Describe the bug**
Clicking outside the dialog (on the Dialog.Overlay) causes the slide over to dismiss. 

**Expected behavior**
Please can we have a prop such as 'dismissOnOutsideClick' or 'dismissOnOverlayClick' on the Dialog component.

**Additional context**
We really need the prop for this as all forms in our application are within slide over panels. Our end users accidentally click outside the panel, the form dismisses, they loose the form state and raise a support ticket! We've tried to hack it to achieve the same behaviour but (as per design) the components don't seem to pass the click events up so we can't prevent it.

Really appreciate your help with this! Thanks :)

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

The `Dialog` component in both React and Vue are controlled components. 
This means that you can do something like this:

```js
function Example() {
  let [open, setOpen] = useState(false)

  return <Dialog open={open} onClose={() => {
    if (formIsNotCompleteYet()) return
    // All good now
    setOpen(false)
  }} />
}
```

If we would introduce a prop like that to control it, then you would probably apply the same condition anyway:

```js
<Dialog outsideClickable={formIsComplete()} />
``` 

Does this help for your use case?

**Comment by joshgdale** [comment]
Hey Robin! Thanks for replying so quick!

I see what you're saying, thanks for the suggestion. You mentioning that has revealed the solution!

This is a screenshot of an example slide over form in our application...

![Screenshot 2021-08-05 at 13 26 11](https://user-images.githubusercontent.com/46057976/128349929-05122510-9867-4aec-b7b8-b270897ab784.png)

We've actually got dedicated `X` button that we use to manipulate the state directly. We want users to be able to close the form at any time through this `X` button by not by clicking outside as this may be accidental.

So I'm thinking... 

``` javascript
export const Example = () => {
    const [open, setOpen] = useState(false);

    return (
        <Dialog
            open={open}
            onClose={() => {}}
            >
            <button onClick={() => setOpen(!open)}>X</button>
            {/* Content */}
        </Dialog>
    )
}
```

By giving an empty function for onClose, it means that it doesn't close on Overlay click! Win!

The only downside is that it also doesn't close on `esc` but in this use case, it might be more of a feature rather than a bug as they could do that accidentally as well.

Does this sound about right to you?

Thanks so much for your help!

**Comment by RobinMalfait** [comment]
Yep that makes sense, there is another downside, if you are hiding the parent of the slideover using something like `lg:hidden`, then internally we will detect that and call the close function (otherwise the focus trap is still active). But for that reason we call the `onClose` function.

I'm going to close this for now since your problem seems to be fixed!
