### ISSUE TITLE
Footer is not aligned properly in small size.

### ISSUE THREAD

**Issue by asaf** [tailwindlabs/tailwindui-issues#699]
**What component (if applicable)**
https://tailwindui.com/components/marketing/sections/footers#component-de25869ecf8c2903fbede9b3a7602adb
- Component name:  footer(s)

**Describe the bug**
Each section should be aligned to its sibling.

**Screenshots**
<img width="310" alt="Screen Shot 2021-08-06 at 17 29 02" src="https://user-images.githubusercontent.com/14259/128526350-90d59a88-a611-403c-bc98-4f73c4e8bde0.png">

**Browser/Device (if applicable)**
- small devices

**Comment by davidluhr** [comment]
@asaf This layout is working as intended. The layout is columnar, so sections with different numbers of links will have consistent vertical spacing between sections.

If the layout was row-based, there would be large, uneven vertical gaps between sections if they contained varying numbers of links.

Hope that helps. Thank you!
