### ISSUE TITLE
"Sidebar Navigation" components do not work as expected.

### ISSUE THREAD

**Issue by faaizajaz** [tailwindlabs/tailwindui-issues#700]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/navigation/sidebar-navigation
- Component name: "Brand with icons, badges, and profile section", but may apply to others in this section

**Describe the bug**
Component does not render as expected when copying HTML or Vue code (and may apply to other formats as well). Content is rendered in a single full width column with menu items in a narrow frame at the top.

**To Reproduce**
1. Copy the code for the component
2. Open the page in your browser.

Example codepen with Tailwind 2.0 CSS imported demonstrating the issue: https://codepen.io/bozmannie/pen/WNjaXEG

**Expected behavior**
The component should render correctly as expected.

**Screenshots**
![image](https://user-images.githubusercontent.com/8207214/128546332-4aa7ebf1-b9e0-497a-adaa-8b14a348258b.png)

**Browser/Device (if applicable)**
 - OS:Ubuntu 20.04
 - Browser: Chrome
 - Version:  92.0.4515.107

**Additional context**
When using Sidebar Layout components under the Application Shells heading (https://tailwindui.com/components/application-ui/application-shells/sidebar), everything works fine. See: https://codepen.io/bozmannie/pen/wvdYYyN

**Comment by davidluhr** [comment]
@faaizajaz Thank you for reporting this! The issue was caused by `h-0` on the sidebar container, which was present to encourage overflow scrolling if the viewport is shorter than the sidebar. Changing this to `min-h-0` preserves the desired behavior, but fixes the isolated sidebar code from rendering a collapsed sidebar.

The fix should be live on the site soon!

**Comment by faaizajaz** [comment]
@davidluhr Indeed you are right! Thanks.
