### ISSUE TITLE
Home Screens > Constrained multi-column

### ISSUE THREAD

**Issue by seb-jean** [tailwindlabs/tailwindui-issues#701]
Hi,
Design of component : https://tailwindui.com/components/application-ui/page-examples/home-screens#component-d222be82dfec1951191abe8624a2a1ed has a problem.

**Comment by davidluhr** [comment]
@seb-jean I'm not seeing an issue with the component, so I'm closing this issue for now.

If you can collaborate on the issue, feel free to reply here or open a new issue with any relevant details. Thank you!
