### ISSUE TITLE
Gray bars on Component: application UI > page examples > constrained multi-column (Safari only)

### ISSUE THREAD

**Issue by RicoTrevisan** [tailwindlabs/tailwindui-issues#702]
Component: application UI > page examples > constrained multi-column
https://tailwindui.com/components/application-ui/page-examples/home-screens

**Describe the bug**
Gray bars show on sides when wide.
![2021-08-07 21 54 57](https://user-images.githubusercontent.com/2459327/128612565-13c87d18-ef09-4cb6-8ddc-e025ddfebdeb.gif)

**To Reproduce**
1. While logged out,
2. Go to page: https://tailwindui.com/components/application-ui/page-examples/home-screens
2. Scroll to the 3rd example.
3. Log in
4. Bars will appear
5. Shrink the element and bars disappear.

**Expected behavior**
No gray bars.

**Screenshots**

**Browser/Device (if applicable)**
- macOS 11.5.1
- Safari
- Version 14.1.2 (16611.3.10.1.3)

**Comment by adamwathan** [comment]
Fixed, accidentally broke this when trying to fix something else 🤦‍♂️ Thank you!
