### ISSUE TITLE
Components cannot be used in Vuejs 3

### ISSUE THREAD

**Issue by manast** [tailwindlabs/tailwindui-issues#703]
Due to an issue in @heroicons the components cannot currently be built for Vuejs3 projects. Here is the issue https://github.com/tailwindlabs/heroicons/issues/318 and here the PR waiting to be merged:
https://github.com/tailwindlabs/heroicons/pull/322

**Comment by bradlc** [comment]
Thanks for reporting. This should be fixed now in `v1.0.4` of `@heroicons/vue` 👍
