### ISSUE TITLE
Slide-Over with Branded Header Submits like a Form when closed

### ISSUE THREAD

**Issue by bithavoc** [tailwindlabs/tailwindui-issues#704]
**What component (if applicable)**
- URL for category: https://tailwindui.com/#product-application-ui-overlays
- Component name: Slide-Overs/With branded header

**Describe the bug**
Unlike the other slide-overs, the close button in this one does not specify `type="button"` so its assumed to be a `submit`which makes the page submit like a form by the default. 

**Expected behavior**
I paste the snippet in my app and by default the close button of the modal should not submit like a form.

**Comment by davidluhr** [comment]
@bithavoc Thanks for reporting this! I've updated any buttons in Tailwind UI that were missing the `type` attribute, so this should be fixed across the board now.

Thanks for helping us improve things!
