### ISSUE TITLE
Semantically incorrect HTML inside of <button> element

### ISSUE THREAD

**Issue by erier** [tailwindlabs/tailwindui-issues#705]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/ecommerce/components/product-overviews#component-13a89c2dc50a31afd66541dc28fa3c13
- Component name: With image gallery and expandable details

**Describe the bug**
I'm not claiming to be an authority here, but from reading (and from my IDE yelling at me), having more than a single `<div>` or other non-span element inside of a `<button>` is semantically incorrect and not validated via W3C.

**To Reproduce**
1. Use the following code from the component described:

```
            <button id="tabs-1-tab-1" class="relative h-24 bg-white rounded-md flex items-center justify-center text-sm font-medium uppercase text-gray-900 cursor-pointer hover:bg-gray-50 focus:outline-none focus:ring focus:ring-offset-4 focus:ring-opacity-50" aria-controls="tabs-1-panel-1" role="tab" type="button">
              <p class="sr-only">
                Angled view
              </p>
              <div class="absolute inset-0 rounded-md overflow-hidden">
                <img src="https://tailwindui.com/img/ecommerce-images/product-page-03-product-01.jpg" alt="Angled front view with bag zipped and handles upright." class="w-full h-full object-center object-cover">
              </div>
              <!-- Selected: "ring-indigo-500", Not Selected: "ring-transparent" -->
              <div class="ring-transparent absolute inset-0 rounded-md ring-2 ring-offset-2 pointer-events-none" aria-hidden="true"></div>
            </button>
```

2. Go to https://validator.w3.org/#validate_by_input+with_options
3. Paste the above
4. See validation errors

**Expected behavior**
Semantic HTML

**Comment by davidluhr** [comment]
@erier Thanks for reporting this. Not sure how this slipped through, but we appreciate you pointing it out.

You're correct that only inline elements are valid children of `<button>`. Additionally, since we have hidden (`.sr-only`) text to provide an accessible name, the image should have empty `alt=""` text.

I've fixed these up and the correct version should be live soon. Thanks again for helping us to improve things!
