### ISSUE TITLE
sub nav not showing on smaller devices

### ISSUE THREAD

**Issue by export-mike** [tailwindlabs/tailwindui-issues#706]
- URL for category: 
- Component name: 
https://tailwindui.com/components/application-ui/page-examples/settings-screens#component-de918ddc41eab4f395f5e48ce2815937

**Describe the bug**
`< settings` is shown but onclick doesn't actually do anything

**To Reproduce**
1. Go to https://tailwindui.com/components/application-ui/page-examples/settings-screens#component-de918ddc41eab4f395f5e48ce2815937
2. resize window until sidenav disappears
3. click `< settings`
4. Nothing happens, this needs styling for mobile

**Expected behaviour**
Mobile styling is expected here.

**Screenshots**
sm screen
![image](https://user-images.githubusercontent.com/2983327/129656272-29694fbc-f8f4-4cbd-8426-b03ee8e13c1d.png)

xl screen
![image](https://user-images.githubusercontent.com/2983327/129656296-b5e2edaf-89e5-41e4-91c0-203125eeaf22.png)

**Comment by davidluhr** [comment]
@export-mike Thank you for the feedback. This is actually the intended functionality. On mobile, we provide a back link that would take users to a page showing the sub-navigation options that are typically shown in multiple hierarchies on larger screens.

This is a common pattern, and you'll spot it on sites like Twitter, for example:

<img width="1257" alt="Twitter settings on desktop, showing three levels of navigation." src="https://user-images.githubusercontent.com/16038754/129762197-aef24521-25c0-44ee-8eb2-492ed4f249e2.png">

<img width="448" alt="Twitter settings on mobile, showing sidebar and main content with back link." src="https://user-images.githubusercontent.com/16038754/129762199-366ab88b-559a-4f34-97d5-5c259008446f.png">

The Tailwind UI component follows this convention for the page example. Hope that helps!
