### ISSUE TITLE
Category filters and category sample pages lack pagination

### ISSUE THREAD

**Issue by woutersamaey** [tailwindlabs/tailwindui-issues#707]
**What component (if applicable)**
Category filters components: https://tailwindui.com/components/ecommerce/components/category-filters
Sample category pages: https://tailwindui.com/components/ecommerce/page-examples/category-pages

**Describe the bug**
I got the impression that you totally forgot about pagination on category filter component and also on the category pages.

We can clearly see filters + sorting, but no pagination anywhere. Maybe it should be added? Pagination can be a bit tricky because the area above and below the product grid can be crowded if there is sorting + filters + alternative views (thumbnail vs list view - also not included, but that's not important)

**Comment by davidluhr** [comment]
@woutersamaey We do have [Category Page: With product grid and pagination](https://tailwindui.com/components/ecommerce/page-examples/category-pages#component-01e6cce6c6c0b0de6f399049b2f512cc)

Hopefully this helps demonstrate how pagination can be used in combination with the filters. Thank you for the feedback!
