### ISSUE TITLE
Enable 404 pages for Application UI

### ISSUE THREAD

**Issue by raci-aivy** [tailwindlabs/tailwindui-issues#708]
I believe that also the Application UI (besides the Marketing package) needs the 404 pages. Is it planned that they will be enabled in the future or extended as components?

**Comment by davidluhr** [comment]
@raci-aivy Thank you for the feedback. We'll likely only offer 404 Pages through the Marketing package, as the various designs are mainly intended for content-focused websites. Some of the simpler examples would work well for a web app, but there probably aren't enough variations that would justify a dedicated category in Application UI as well.

I've made note of this request with the team for future consideration. Thanks again!
