### ISSUE TITLE
Breadcrumbs vertical misalignment

### ISSUE THREAD

**Issue by andcl** [tailwindlabs/tailwindui-issues#709]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/headings/page-headings
- Component name: All components with breadcrumbs

**Describe the bug**
There is a tiny vertical misalignment in breadcrumbs 

**Additional context**
Corrected by adding a `mt-0.5` on the second and successive links.

**Comment by davidluhr** [comment]
@andcl Thank you for the feedback.

Looks like the vertical alignment is actually correct. The optical baseline of the font within it's line-height is a little weighted towards the bottom, but that varies significantly. The actual box model of the text and icons are all 20px in height and vertically centered:

<img width="395" alt="Browser inspector tool showing 20px box height of breadcrumb text and icon with vertical centering." src="https://user-images.githubusercontent.com/16038754/130266062-73850e58-c88b-483b-8d94-613673ebe5ae.png">

Closing this for now, as no change is needed on our end. Hope this helps explain things!
