### ISSUE TITLE
Navigation Steps component borders don't display bc missing `border-solid` class

### ISSUE THREAD

**Issue by xaphod** [tailwindlabs/tailwindui-issues#711]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/navigation/steps
- Component name:  Panels

**Describe the bug**
Panels: take the React source code, make it into a component. Probably same bug with HTML code too.
EXPECTED: all three types of steps have borders around them as per preview
ACTUAL: borders missing for current and upcoming types

TO FIX:

In code where border-2 is shown:
```
<span className="flex-shrink-0 w-10 h-10 flex items-center justify-center border-2 border-indigo-600 rounded-full">
```

... add the `border-solid` class.
This causes borders to show up like they should.

**Browser/Device (if applicable)**
 - OS: macOS Big Sur latest
 - Browser: Chrome latest

**Comment by davidluhr** [comment]
@xaphod I have copied the React code into a new project and the borders appear as expected. `border-solid` shouldn't be necessary, as it's part of the Tailwind CSS reset:

```css
*, ::before, ::after {
  ...
  border-style: solid;
  ...
}
```

If you are using JIT mode, it's possible that the `border-2` class hasn't been previously generated. Usually, giving the project a refresh with `border-2` somewhere in the markup resolves this.

Closing this issue for now, as the code provided by the preview is working as expect. But, please reply here and we're happy to help resolve the issue on your end.

**Comment by xaphod** [comment]
Using `border-1` or other values that we use all over our project didn't work either.
In other components we don't need to specify `border-solid` , but in this component we have to. Don't know why.
