### ISSUE TITLE
Docs pages

### ISSUE THREAD

**Issue by beerose** [tailwindlabs/tailwindui-issues#712]
It would be nice to have some simple docs page(s), e.g.: https://tailwindui.com/documentation (your own docs page 😅).

Idea: it could just be a `table of contents` component instead.

**Comment by davidluhr** [comment]
@beerose Thanks for this suggestion! I've created a card with a link to this issue in our public Tailwind UI roadmap in Trello, where the community can vote for what they would like us to add: https://trello.com/c/0niTepPx/164-documentation-page-example
