### ISSUE TITLE
Prebuilt Component Library for Vue

### ISSUE THREAD

**Issue by reidjs** [tailwindlabs/tailwindui-issues#713]
First of all, thank you, I love using tailwindui and think it's a great product. 

It would be nice if tailwindUI had a prebuilt component library,  that I could import, or partially import, instead of having to create each component individually.

As a developer, it would be nice to do something like this, without having to build my own `Button.vue` component:
```
<template>
  <Button size="lg" type="primary">Hello World</Button>
</template>
<script>
import { Button } from 'vue-tailwindui'
export default {
  components: { Button }
}
</script>
```

**Comment by davidluhr** [comment]
@reidjs Thanks for the suggestion! This is a bit out of scope for Tailwind UI, but I've made note of this with the team. Thanks again!
