### ISSUE TITLE
Request: add component id to comment for easy reference

### ISSUE THREAD

**Issue by emcoding** [tailwindlabs/tailwindui-issues#717]
I would love for the components to have its id in the comments, so I can reference them. 

I find myself copying the url of #component-id and add it to the top comment in my code, for every component I use. 

Like this:

```html
<!-- https://tailwindui.com/components/marketing/sections/header#component-2c3b25e7b9e4490edd7b6950692c0a11 -->
<!-- This example requires Tailwind CSS v2.0+ -->
<div class="bg-white">
  ...
</div>

**Comment by davidluhr** [comment]
@emcoding Thanks for this suggestion! It's definitely an interesting idea that we will consider. We appreciate the feedback!
