### ISSUE TITLE
Submit button missing on form component

### ISSUE THREAD

**Issue by itsmebennyb** [tailwindlabs/tailwindui-issues#72]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/forms/form-layouts
- Component name: Two-column in full-width cards

**Describe the bug**
A "submit" button is missing for the "two-column in full-width cards" form layout. All other form layouts include a "submit" button, except this one.

**Screenshot**

![tailwindui com_components_application-ui_forms_form-layouts](https://user-images.githubusercontent.com/23037675/76221317-e7f22580-61e6-11ea-94c5-21ef57736c26.png)

**Comment by davidluhr** [comment]
I've been going through past issues and this should now be fixed on the live site soon. Thanks for your improvement!
