### ISSUE TITLE
Ecommerce | Product list: Compact list variant

### ISSUE THREAD

**Issue by tho-masn** [tailwindlabs/tailwindui-issues#720]
Hi there,

First of all, I absolutely love your products and what you are building with Tailwind, TailwindUI and all the other stuff. For me, as a developer with just basic design and CSS skills, it makes developing beautiful, responsive UIs so much easier now.

However, what I noticed is, that all the ecommerce components are built with beautiful images as the center of the product. Not sure how high the demand is, but there are many use cases where shops are selling (unsexy) products where images don't deliver much value, or shops where there are only partially product images available. Or even worse: there are no images at all. 

Imaging restaurants selling their meals, or shops selling the same type of product with different specifications (e.g: cables), or shops with a huge amount of products, where product lists should be more compact to make scrolling through easier. These kind of things are probably more difficult to style then shops with a few products with beautiful images. 

I think something like a list-style based variant of the product list would be an approach to address this need.
Is there anything planned in this direction?

**Comment by davidluhr** [comment]
@tho-masn Thanks for the kind words! Happy to hear Tailwind UI is providing value in your work.

Thanks for the suggestion as well. I've added a link to this issue to a card in our Tailwind UI public roadmap in Trello, where the community can vote for what they'd like us to add:

https://trello.com/c/ZfFGfwqz/166-text-focused-product-list
