### ISSUE TITLE
Suggestion: Printable image of each component

### ISSUE THREAD

**Issue by wouterdorgelo** [tailwindlabs/tailwindui-issues#723]
A printable image of each component would allow developers to quickly plan their next big thing as a jigsaw puzzle. Not on a computer screen but on a table or a whiteboard.

**Comment by davidluhr** [comment]
@wouterdorgelo Thanks for the suggestion! One thing that may be helpful is viewing the site while logged out. Most components are PNG previews, which would be easier to print. You could also screenshot any component and print from there. Hope that helps!
