### ISSUE TITLE
Small bug in React code for Header (Simple links centered)

### ISSUE THREAD

**Issue by mplis-ta** [tailwindlabs/tailwindui-issues#724]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/marketing/elements/headers
- Component name: Simple links centered

**Describe the bug**
One part of the React component uses the wrong variable when creating the element `key`:

```
{resources.map((item) => (
    <a
        key={resources.name}
        href={item.href}
        className="text-base font-medium text-gray-900 hover:text-gray-700"
    >
        {item.name}
    </a>
))}
```

**Expected behavior**

Code should be:

```diff
{resources.map((item) => (
    <a
-        key={resources.name}
+        key={item.name}
        href={item.href}
        className="text-base font-medium text-gray-900 hover:text-gray-700"
    >
        {item.name}
    </a>
))}
```

**Comment by davidluhr** [comment]
@mplis-ta Thank you for reporting this! I've updated the code to ensure that the key uses the correct object name. The fixed version should be live on the site soon.
