### ISSUE TITLE
Alpine.js Support

### ISSUE THREAD

**Issue by MFFunmaker** [tailwindlabs/tailwindui-issues#725]
Hey there, I just think it would be awesome to have Alpine.js as an option. I know that is a big request and if I could somehow help, I would. I use TailwindCSS UI components with Alpine.js and it's a match made in heaven for rapid development.

**Comment by davidluhr** [comment]
@MFFunmaker Thank you for this suggestion! Currently, with [Headless UI](https://headlessui.dev/) (which powers the interactive components in Tailwind UI), we're focused on React and Vue support to meet the demand from the large majority of users. While it's possible we may expand support in the future, we have to focus on serving as many customers as possible. I've made note of this request with the team, and we appreciate the feedback!
