### ISSUE TITLE
Component Idea: Progress bars

### ISSUE THREAD

**Issue by littleluce** [tailwindlabs/tailwindui-issues#73]
I would really like to see progress bar element.

Bootstrap has some nice examples of this (https://www.w3schools.com/bootstrap/bootstrap_progressbars.asp) but I think it would be good to include a version in Tailwind UI

**Comment by stevecastaneda** [comment]
![image](https://user-images.githubusercontent.com/171488/77689416-9cbe6d80-6f6f-11ea-99db-278beafe5f5c.png)
![2020-03-26 14 39 08](https://user-images.githubusercontent.com/171488/77689423-9fb95e00-6f6f-11ea-8365-da3f54daf51b.gif)

https://react.semantic-ui.com/modules/progress/

**Comment by J05HI** [comment]
https://element.eleme.io/#/en-US/component/progress

![image](https://user-images.githubusercontent.com/16399787/82410668-9ed51200-9a70-11ea-8ad8-284ade293b03.png)

![image](https://user-images.githubusercontent.com/16399787/82410697-a72d4d00-9a70-11ea-8d54-03569312a180.png)

![image](https://user-images.githubusercontent.com/16399787/82410719-b1e7e200-9a70-11ea-8e82-7b2deeddda27.png)

![image](https://user-images.githubusercontent.com/16399787/82410751-bd3b0d80-9a70-11ea-9175-8706cc2bae21.png)

**Comment by simonswiss** [comment]
Nice one! 👍

Capturing this in our "bag of ideas" on the Trello roadmap. If it becomes a popular demand, we'll consider building it! 🎉 https://trello.com/c/qMtkbuST/81-progress-bars
