### ISSUE TITLE
UI components display broken after first installation

### ISSUE THREAD

**Issue by rkefi** [tailwindlabs/tailwindui-issues#730]
URL for category: https://tailwindui.com/components/marketing/sections/heroes
Component name: Simple Centered

Using latest NextJS and TailwindCSS

**Describe the bug**
Went through the installation guide, got all the requirements installed and all seems ok.
After running the app and trying different components, all of them have a broken display and did not get any to work.
Tried the whole setup again but got same result

I've got my code on this repo so you can reproduce the issue on your side.

Screenshot i get :

![Screen Shot 2021-09-06 at 4 11 10 PM](https://user-images.githubusercontent.com/13288543/132258256-8d6d132b-f18a-41d9-b1d6-83eb46f5ae7a.png)

**To Reproduce**
1. Clone : https://github.com/rkefi/tailwind-bug
2. cd tailwing-bug
3. npm run dev

**Expected behavior**
Components renders properly as shown in the preview of the documentation

**Browser/Device (if applicable)**
 - OS: OSX Big Sur 11.5.2
 - Browser Chrome
 - Version 92.0

**Comment by OmkarK45** [comment]
You forgot to include @tailwind directive rules in globals.css file https://tailwindcss.com/docs/guides/nextjs#include-tailwind-in-your-css

**Comment by reinink** [comment]
Yup, @OmkarK45 is exactly right. Simply update your `/styles/globals.css` to look like this, and you should be good to go.

```css
@tailwind base;
@tailwind components;
@tailwind utilities;
```
