### ISSUE TITLE
Small inconsistency in markup for "Checkboxes -- List with inline description" 

### ISSUE THREAD

**Issue by richardkmiller** [tailwindlabs/tailwindui-issues#731]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/forms/checkboxes
- Component name: List with inline description

**Describe the bug**
In the sample code, the paragraph of code for the 2nd and 3rd checkboxes are wrapped in an extra div, but the 1st item is not. This probably has no bearing on the output, but caused a moment of pause on my part. Maybe you'll want to make these consistent. 

First item:
```html
<div class="relative flex items-start">
```

Second and third item:
```html
<div>
  <div class="relative flex items-start">
```

**To Reproduce**

**Expected behavior**

**Screenshots**

**Browser/Device (if applicable)**

**Additional context**

**Comment by reinink** [comment]
Hey thanks @richardkmiller, you're right, those extra divs are pointless. I fixed this in the following three components:

- List with description
- List with inline description"
- List with checkbox on right

**Comment by richardkmiller** [comment]
Nice! I didn't notice those other two. Thank you, @reinink!
