### ISSUE TITLE
Pricing section has duplicate color classes

### ISSUE THREAD

**Issue by f3bruary** [tailwindlabs/tailwindui-issues#732]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/marketing/sections/pricing
- Component name: Three tiers on brand and feature comparison

**Describe the bug**
In the comparison table the Starter/Scale/Growth texts have duplicate color classes assigned to them. All three have an extra `text-gray-900` assigned. Lines 775, 782 and 789.

Example: `<p class="text-gray-900 text-sm font-bold text-gray-900">Growth</p>`

**Additional context**
It's not 'breaking' anything. And the colors show fine. Just something vscode likes to highlight.

**Comment by reinink** [comment]
Hey there @f3bruary, thanks so much for reporting this. I've fixed this. 👍
