### ISSUE TITLE
Typo on notifications with split buttons message

### ISSUE THREAD

**Issue by marky291** [tailwindlabs/tailwindui-issues#733]
<img width="474" alt="Screenshot 2021-09-06 at 23 10 24" src="https://user-images.githubusercontent.com/5384515/132262935-3ac8fa57-4a2e-42a6-bd96-38e61d059bc7.png">

**Comment by reinink** [comment]
Thanks for catching this @marky291. This has been fixed. 👍 

![image](https://user-images.githubusercontent.com/882133/132552368-16b1684a-ceb4-4924-8e90-d75fa219b9be.png)
