### ISSUE TITLE
Invalid Example at Staked Layouts

### ISSUE THREAD

**Issue by ahmadfikrimasyhur** [tailwindlabs/tailwindui-issues#734]
- URL for category: https://tailwindui.com/components/application-ui/application-shells/stacked#component-7022793f3a06d980f7d7f8394a057092
- Component name: Staked Layouts

**Describe the bug**
no differentiations between fisrt and second example of stacked layouts but has differents title
Light nav with bottom border >< Light nav on gray background

**Expected behavior**
must be differ from first example for the second

**Screenshots**
![image](https://user-images.githubusercontent.com/30574371/132349628-5f5241c5-0b27-4c14-aa6b-4e0b3f7f8aac.png)

**Comment by reinink** [comment]
Hey there @ahmadfikrimasyhur,

So these two components do slightly differ.

The first one (Light nav with bottom border) has a border below the header and nav, and has a white background for the body.

![image](https://user-images.githubusercontent.com/882133/132734861-18fa3e86-5927-48e3-be90-d8ac151cf20b.png)

The second one (Light nav on gray background) has a shadow below the header and nav, and has a gray background for the body.

![image](https://user-images.githubusercontent.com/882133/132734880-46f4531d-5f8c-41d1-a9fc-c4aaaa198d4d.png)

We like to offer similar components in different variations like this, where it makes sense, to help give developers a good starting point.

I agree though, on first glance, they do look very similar. 😊

**Comment by ahmadfikrimasyhur** [comment]
My false of understanding 🙏🤭
