### ISSUE TITLE
Number input fields

### ISSUE THREAD

**Issue by f3bruary** [tailwindlabs/tailwindui-issues#736]
**Screenshots**
![image](https://user-images.githubusercontent.com/5641933/132738335-acadf986-6d5b-47f1-b859-20874aa3794a.png)

**Additional context**
I noticed it was missing and nobody has requested it. It seems like a basic element to include. A lot of e-commerce platforms use number inputs for product quantity fields. The e-commerce cart examples in TailwindUI only have quantity dropdowns which isn't really the ideal input type to use here... :(
The example screenshot still shows the native step buttons. Those shouldn't be there in the actual component of course.

**Comment by reinink** [comment]
Thanks for the suggestion @f3bruary! We'll consider this for future updates. 👍
