### ISSUE TITLE
TailwindUI eCommerce - Multi level menubar for a marketplace

### ISSUE THREAD

**Issue by zbaloch** [tailwindlabs/tailwindui-issues#738]
Hi TailwindUI Team,

Most of the stores that I work with are kind of like the marketplaces hence I am looking for a navigation component that is multi-level. As of now what is provided is for a small store with two categories only (Men, Women etc). An example can be found here for what I am looking for: 

<img width="1510" alt="Screen Shot 2021-09-12 at 7 40 56 PM" src="https://user-images.githubusercontent.com/8920243/132995722-43c93ec2-1a69-4e68-884c-b72248289afa.png">

**Comment by reinink** [comment]
@zbaloch Thanks for sharing this idea. We'll certainly consider it for the future. 👍
