### ISSUE TITLE
2-section badge with key and value

### ISSUE THREAD

**Issue by bkniffler** [tailwindlabs/tailwindui-issues#74]
**Screenshots**
<img width="918" alt="Bildschirmfoto 2020-03-09 um 23 42 54" src="https://user-images.githubusercontent.com/4349324/76263715-e6b10f00-625f-11ea-9ffd-90ca7371a75e.png">

**Additional context**
Sometimes it's useful to have badges work as key/value pair like "Category: Shoes" or "Name: Max" or "Email: info@xyz.com", or the other direction around like "Shoes (Category). Semantic UI does this beautifully as shown on the image. The icons would be nice bonus, but not as important as the labels.

**Comment by simonswiss** [comment]
Those are super neat! ❤️

I have captured this suggestion in our "bag of ideas" that could be considered to built at some point - go give it an upvote at https://trello.com/c/qfiNwKwq/80-multi-section-badges 👍
