### ISSUE TITLE
Modal background + sidebar layout with search not working together nicely

### ISSUE THREAD

**Issue by patrickbergman** [tailwindlabs/tailwindui-issues#75]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/application-shells/sidebar + https://tailwindui.com/components/application-ui/overlays/modals
- Component name: Dark sidebar with light header + Simple with gray footer

**Describe the bug**
When having a modal open, the search part on the top half is not covered. Probably due to the absolute class. (Not sure, since I am no CSS hero ^_^)

**To Reproduce**
1. Add the layout to a page
2. Add the modal to the page
3. Make sure the modal is opened
4. See same kind of behavior as displayed on the screenshot

**Expected behavior**
The search/user part of the layout should also be covered by the modal dark overlay.

**Screenshots**
<img width="2560" alt="afbeelding" src="https://user-images.githubusercontent.com/17382449/76336310-1ad70f00-62f6-11ea-9470-96d7b138ab17.png">

**Comment by frankperez87** [comment]
You can change the `z-10` class to `z-0` on the div containing the search. That should take care of it 👍
