### ISSUE TITLE
Mobile Device Frames for Promotional App Landers

### ISSUE THREAD

**Issue by crock** [tailwindlabs/tailwindui-issues#76]
Ya know how every promotional landing page for a mobile app has an actual device frame with screenshots of the device on the desktop version of the site to show off the app? Let's have a layout or just a device frame component like that to whip up these common sites quickly and easily.

**Comment by evdama** [comment]
should go onto https://trello.com/b/Nh6e9w8Q/tailwind-ui-roadmap

**Comment by crock** [comment]
@evdama Looks like I don't have access to add it to the Trello backlog. I believe the public has to make the suggestions here and they are added by Adam or someone to the backlog if a decision is reached to make it.

**Comment by dillingham** [comment]
Desktop screens would be nice too
Kind of like the feature components 
But an image wrapped with an svg. 

Great idea :)

**Comment by simonswiss** [comment]
> @evdama Looks like I don't have access to add it to the Trello backlog. I believe the public has to make the suggestions here and they are added by Adam or someone to the backlog if a decision is reached to make it.

This is changing today! We're moving the component requests/suggestions to a new "ideas" column in the roadmap.

This doesn't mean that what's added will be implemented, but it gives a chance for people to upvote what they really like, and if it's there, it's in the mix of what could be built next! 👍

I've captured this specific suggestion here: https://trello.com/c/jpQXubGW/79-device-mockup-wrapper

Thanks for the request!

**Comment by simonswiss** [comment]
Already seeing an upvote on this one that I just created! 😅👏
