### ISSUE TITLE
Sortable tables

### ISSUE THREAD

**Issue by emil-nasso** [tailwindlabs/tailwindui-issues#80]
It would be great to see an addition to the tables in tailwind that adds styles for sortable columns. Something like this, but, decent looking. ;)

![image](https://user-images.githubusercontent.com/1119706/76524204-f1d78b00-6469-11ea-9a97-8aba4dd1d363.png)

**Comment by PolMrt** [comment]
Take a look to #49

**Comment by simonswiss** [comment]
Consolidating this with https://github.com/tailwindlabs/tailwindui-issues/issues/49 👍
