### ISSUE TITLE
Event Page

### ISSUE THREAD

**Issue by knorthfield** [tailwindlabs/tailwindui-issues#81]
It would be marvellous to have an event page, for either in person events like conferences or training courses. Or digital events like webinars. I'm thinking a page might include elements such as:

- Event photo
- Title
- Description
- Time and date
- Agenda
- Location. Address and map/directions
- Booking form
- Testimonials
- Bio of speaker

**Comment by simonswiss** [comment]
Nice one! 👍

Capturing this in our "bag of ideas" on the Trello roadmap. If it becomes a popular demand, we'll consider building it! 🎉

https://trello.com/c/BXtML6pN/77-event-page
