### ISSUE TITLE
Case Study Page

### ISSUE THREAD

**Issue by knorthfield** [tailwindlabs/tailwindui-issues#82]
For the marketing site section I believe a case study page example would be a good addition. Many SaaS companies use case studies to show how their software can be used in a specific industry or for a specific client.

- Client logo and company name
- Client photo and name/job title 
- Title
- Subtitle
- Text
- Call out quotes/testimonials
- CTA

**Comment by masonhensley** [comment]
This would be a great add to the marketing components.

**Comment by simonswiss** [comment]
Nice one! 👍

I am porting the component suggestions to an "ideas" column in the Trello roadmap. I'll close this issue, but you can find this request here: https://trello.com/c/tPymQEZE/76-case-study-page
