### ISSUE TITLE
Accordion sidebar

### ISSUE THREAD

**Issue by lucperkins** [tailwindlabs/tailwindui-issues#86]
I'm a bit biased because I mostly work on technical documentation sites, but I'd love to have a beautiful accordion sidebar nav for Tailwind UI as found in many admin/dashboard themes. Here are some examples (on the left side of each dashboard):

https://coderthemes.com/uplon/layouts/vertical
https://docs.d2iq.com/mesosphere/dcos/2.0/overview/what-is-dcos

**Comment by simonswiss** [comment]
By accordion, do you mean the multi-level navigation with sub-sections?

If yes, we have some of these now in the [Sidebar Navigation](https://tailwindui.com/components/application-ui/navigation/sidebar-navigation) section (see the "with expandable sections" example).

If you mean that the sidebar itself can collapse into a smaller, thin navbar with just icons (like in your first example), then that idea has been captured on our roadmap based on https://github.com/tailwindlabs/tailwindui-issues/issues/37

Thank you for suggesting this! ✨
