### ISSUE TITLE
Fixed navbar

### ISSUE THREAD

**Issue by lucperkins** [tailwindlabs/tailwindui-issues#87]
The current navbars look great but would love an example with a fixed navbar. Making one of the existing navbars fixed is easy enough (using something like `fixed w-full top-0`) but it's a bit tricky getting them to work with things like dropdowns. Would be great to have an example alongside the non-fixed navbars.

**Comment by cypris75** [comment]
This in combination with a "scroll-up-show-navbar" feature. So if you scroll down, the navbar disappears and if you start to scroll-up the navbar is shown again.

https://codepen.io/tahazsh/pen/wNOvyK

**Comment by simonswiss** [comment]
Thanks for the suggestion! 👍

I am porting the component suggestions to an "ideas" column in the Trello roadmap. I'll close this issue, but you can find this request here: https://trello.com/c/SArwxjRO/74-fixed-navbar-page-layout-example
