### ISSUE TITLE
Horizontal Scrolling Tab

### ISSUE THREAD

**Issue by cenksener** [tailwindlabs/tailwindui-issues#88]
**Screenshots**
http://prntscr.com/rgjkrx

**Additional context**
Horizontal scrolling tab would be great.There can be arrow icons in mobile screen.

**Comment by simonswiss** [comment]
This is a valid solution to simplify responsive navigation menu when you don't want to go down the hamburger menu route! 👍

Adding to our [bag of suggestions/ideas to consider](https://trello.com/c/16k7jNR4/73-horizontal-scrolling-lists) on our Trello roadmap. 

No guarantee it's going to be implemented, but hey it's in the mix! 🎉
