### ISSUE TITLE
Repeatable input groups

### ISSUE THREAD

**Issue by RobertCordes** [tailwindlabs/tailwindui-issues#89]
I'm constantly reinventing some kind of repeatable inputs/input groups. I would love to see how you guys tackle this.

**Example**
Just to show you what I mean exactly, [I found this](https://formidableforms.com/knowledgebase/repeatable-section/).

**Additional context**
Sometimes I give clients the ability to have zero _items_ and prepare an empty state for that. Othertimes at least one item is required so I remove the _delete_ button when there’s only one item left.
Oftentimes I also give the ability to reorder items.

**Comment by simonswiss** [comment]
Nice suggestion! ✨

These typically involve a lot of JavaScript to work, so I am not too sure how that would fit in the Tailwind UI angle of being mostly a collection of UI screens, layouts and components.

The request for the visual UI of such repeatable input fields is definitely valid, and I have captured this in our "bag of ideas to consider" in our Trello roadmap: https://trello.com/c/aJicQwlX/72-repeatable-form-section-ui

Thanks again for suggesting! 👍

**Comment by RobertCordes** [comment]
Yeah, I actually meant the visual aspect of it :) The JavaScript to make this work would be fairly minimal — I just built a basic version for a client with a few lines of Alpine. But as always, every project has different requirements and there were cases where I had a ton of logic for this kind of UI.
