### ISSUE TITLE
Ticket or Issue timeline UI/UX

### ISSUE THREAD

**Issue by Nness** [tailwindlabs/tailwindui-issues#90]
We are designing interface for ticketing system, the ticket's timeline is one of important piece.

Personally, I like how GitHub did it. Where the communication been split into blocks, so it has clear indication of different comment, then there is line that connected together which indicate it's time series where between comment have relationship.

As for attachment, I feels like it should be same to those event on GitHub issues. Where it should be subtle. To make sure user notice comment first. But not inside another tab, where it is hard to discover. 

It is more towards noise control. 

For attachment, currently, it can be uploaded without note. If it is submit with note, then it should be bundled together with note. 

![image](https://user-images.githubusercontent.com/1712143/76894070-4f4c5b80-68f2-11ea-9960-06ca48e85fb0.png)

The other piece that we are struggling is submit comment. `Reply`, `Flag`, `Close` those action feels too subtle. GitHub use different button at bottom for action. We use subtle tab. First its not clear whether we selected something in first place, second it feels like our typing could be disappear after change tab.  It looks like tab, it is tab, expectation on the outcome and actual outcome not line up.

The last part is left side ticket information. Where name of field is bold and dark. Which we can see in first place. Should name of field to be subtle but actual value to be pop out? What's best balance there?

e.g. Assigned  Technician is subtle where technician is bold. Then priority title is bold, but value is subtle.

**Comment by J05HI** [comment]
@Nness 
You mean messages?
The title "timeline" is a bit confusing.

**Comment by Nness** [comment]
@J05HI 
Messages is more like chat. Where this is mainly for issue or ticket. e.g. issue in GitHub, Ticket in ZenDesk.

For issue and ticket, it has timeline, where the original request or issue report, then its continue conversation plus additional material and events.

For GitHub, you will normally see messages as big blocks, then anytime change tag, change assigned etc, there are events mixed inside.

As result, you know how issue or ticket progressed through time.

It is not for chat, but similar.

**Comment by J05HI** [comment]
@Nness
What about these? They are also timelines. 
 https://dribbble.com/shots/10993769-Timeline-Design https://dribbble.com/shots/10761839-Timeline-UI-Design

**Comment by simonswiss** [comment]
Consolidating this with https://github.com/tailwindlabs/tailwindui-issues/issues/249 (Activity Feed) and https://github.com/tailwindlabs/tailwindui-issues/issues/196 (Timeline/Roadmap) 👍
