### ISSUE TITLE
Button notifications, banners and badges

### ISSUE THREAD

**Issue by JeanPaulvB** [tailwindlabs/tailwindui-issues#91]
Would love to see your take on special "effects" for buttons, like notifications ("5 new messages"), banners ("new", "premium") and badges (like icons).

**Examples**
![Imgur](https://i.imgur.com/LEssIQr.png)
**https://tailwindcomponents.com/component/button-with-counter
https://tailwindcomponents.com/component/premium-banner-around-button**

**Comment by simonswiss** [comment]
Thanks for the suggestion! 👍

I am porting the component suggestions to an "ideas" column in the Trello roadmap. I'll close this issue, but you can find this request here: https://trello.com/c/Pf0JsJYQ/71-button-badges-notifications
