### ISSUE TITLE
Dropdown select improvement

### ISSUE THREAD

**Issue by JeanPaulvB** [tailwindlabs/tailwindui-issues#93]
The current TailwindUI dropdown select items do not have any markup on the dropdown elements (the dropdown select items are the "plain" browser defaults):

![Dropdown tailwindUI example](https://i.imgur.com/h9gnz1G.png)

It would be nice if the dropdown select would have the same look as the dropdown menus:

![Dropdown menu example](https://i.imgur.com/8uEYLDp.png)

**Comment by J05HI** [comment]
Would be amazing!

**Comment by J05HI** [comment]
Related to #61

**Comment by simonswiss** [comment]
Consolidating this with https://github.com/tailwindlabs/tailwindui-issues/issues/61 👍
