### ISSUE TITLE
Breadcrumb

### ISSUE THREAD

**Issue by seb-jean** [tailwindlabs/tailwindui-issues#95]
Hi,
I would love to have a Breadcrumb component
Thanks

**Comment by simonswiss** [comment]
Thanks for the suggestion! 👍

I am porting the component suggestions to an "ideas" column in the Trello roadmap. I'll close this issue, but you can find this request here: https://trello.com/c/NnWz1bYM/69-breadcrumbs

**Comment by seb-jean** [comment]
Thanks @simonswiss
