### ISSUE TITLE
Slider

### ISSUE THREAD

**Issue by veeral-patel** [tailwindlabs/tailwindui-issues#96]
https://material.io/components/sliders/

**Comment by J05HI** [comment]
Additional examples:

https://element.eleme.io/#/en-US/component/slider#slider

![Range Slider](https://user-images.githubusercontent.com/16399787/80517403-4df85f00-8985-11ea-9202-fcef4d1b003b.png)

**Comment by simonswiss** [comment]
Moving this suggestion to https://trello.com/c/qYooawle/68-range-sliders 👍
